### ISSUE TITLE
udev: lvm logical volumes are no longer properly initialized

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#11255]
**systemd version the issue has been seen with**

v240

**Used distribution**

Debian sid
Filed as downstream bug report
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917124

Since the update of udev from 239 to 240, we had several bug reports in Debian, where LVM logical volumes are no longer properly initialized. As a result, the devices are not marked as ready and time out, leading to a failed boot.

v240
```
# udevadm info /sys/class/block/dm-2
P: /devices/virtual/block/dm-2
N: dm-2
L: 0
E: DEVPATH=/devices/virtual/block/dm-2
E: DEVNAME=/dev/dm-2
E: DEVTYPE=disk
E: MAJOR=253
E: MINOR=2
E: SUBSYSTEM=block
E: USEC_INITIALIZED=9715169
E: DM_UDEV_DISABLE_SUBSYSTEM_RULES_FLAG=1
E: DM_UDEV_DISABLE_DISK_RULES_FLAG=1
E: DM_UDEV_DISABLE_OTHER_RULES_FLAG=1
E: DM_UDEV_RULES=1
E: DM_UDEV_RULES_VSN=2
E: net.ifnames=0
E: SYSTEMD_READY=0
E: TAGS=:systemd:
```

Same device with 239
```
# udevadm info /sys/class/block/dm-2
P: /devices/virtual/block/dm-2
N: dm-2
S: disk/by-id/dm-name-vg-home
S: 
disk/by-id/dm-uuid-LVM-SiqeiwSeAj9MM50Phu717igDgDlF5NIq0N9nmHNGMYuvfy7LFfYfUQpyivO394C5
S: disk/by-label/Home
S: disk/by-uuid/39303d70-dd06-4356-b413-efcb35f8cd4c
S: mapper/vg-home
S: vg/home
E: DEVLINKS=/dev/mapper/vg-home /dev/disk/by-id/dm-name-vg-home 
/dev/disk/by-id/dm-uuid-LVM-SiqeiwSeAj9MM50Phu717igDgDlF5NIq0N9nmHNGMYuvfy7LFfYfUQpyivO394C5 
/dev/vg/home /dev/disk/by-label/Home 
/dev/disk/by-uuid/39303d70-dd06-4356-b413-efcb35f8cd4c
E: DEVNAME=/dev/dm-2
E: DEVPATH=/devices/virtual/block/dm-2
E: DEVTYPE=disk
E: DM_LV_NAME=home
E: DM_NAME=vg-home
E: DM_STATE=ACTIVE
E: DM_SUSPENDED=0
E: DM_TABLE_STATE=LIVE
E: DM_UDEV_DISABLE_LIBRARY_FALLBACK_FLAG=1
E: DM_UDEV_PRIMARY_SOURCE_FLAG=1
E: DM_UDEV_RULES=1
E: DM_UDEV_RULES_VSN=2
E: 
DM_UUID=LVM-SiqeiwSeAj9MM50Phu717igDgDlF5NIq0N9nmHNGMYuvfy7LFfYfUQpyivO394C5
E: DM_VG_NAME=vg
E: ID_FS_LABEL=Home
E: ID_FS_LABEL_ENC=Home
E: ID_FS_TYPE=ext4
E: ID_FS_USAGE=filesystem
E: ID_FS_UUID=39303d70-dd06-4356-b413-efcb35f8cd4c
E: ID_FS_UUID_ENC=39303d70-dd06-4356-b413-efcb35f8cd4c
E: ID_FS_VERSION=1.0
E: MAJOR=253
E: MINOR=2
E: SUBSYSTEM=block
E: TAGS=:systemd:
E: USEC_INITIALIZED=12329587
E: net.ifnames=0
```

lvm2 is version 2.03.01, lvmetad is enabled by default in Debian.

**Comment by wavexx** [comment]
I can confirm this issue as well (debian unstable). I downgraded just udev/libudev1 to get a bootable system.

**Comment by mbiebl** [comment]
Looks like I can reproduce the issue in a test-vm as well. Interestingly, the system boots correctly if I remove `quiet` from the kernel command line. Might be a race and the additional output slows down the system just enough to avoid it.

**Comment by mbiebl** [comment]
Actually, adding a line `ExecStart=/bin/udevadm trigger --type=devices --action=change` works better.
With
```
ExecStart=/bin/udevadm trigger --type=subsystems --action=add
ExecStart=/bin/udevadm trigger --type=devices --action=add
ExecStart=/bin/udevadm trigger --type=devices --action=change
```
the system boots without any noticeable issues.

**Comment by johnwmail** [comment]
> Actually, adding a line `ExecStart=/bin/udevadm trigger --type=devices --action=change` works better.
> With
> 
> ```
> ExecStart=/bin/udevadm trigger --type=subsystems --action=add
> ExecStart=/bin/udevadm trigger --type=devices --action=add
> ExecStart=/bin/udevadm trigger --type=devices --action=change
> ```
> 
> the system boots without any noticeable issues.

Hi, it work on my kvm/quem(quest) system, but can not work on my bare metal system.

but replace /lib/systemd/systemd-udevd with udev version 239's
(/lib/systemd/systemd-udevd), then update-initramfs -u work for my both kvm/bare metal system.

Thanks.

**Comment by xabbu** [comment]
> Actually, adding a line `ExecStart=/bin/udevadm trigger --type=devices --action=change` works better.

I can confirm this workaround. It works form me in a test vm and on my bare metal Manjaro system.

**Comment by yuwata** [comment]
I hope this is also fixed by #11244. Please test the PR.

**Comment by xabbu** [comment]
I tried PR #11244 , but it did not helped. The lvm volumes are still not activated. 

I also did a git bisect, systemd fails to activate lvm volumes with commit  feaa6db7 . There is no good version with and after this commit.

**Comment by yuwata** [comment]
Could you test #11270?

**Comment by lorenzhs** [comment]
I don't think this is limited to LVM. I'm having issues with LUKS on Debian sid. The system is still bootable, but the `/dev/mapper/*` symlinks aren't present, for example (breaking `grub-probe` and thus `update-grub`). Running `udevadm trigger --type=devices --action=change` fixes it. Or is that a different issue?

**Comment by philmmanjaro** [comment]
I've just added the provided patches to **(lib32-)systemd 240.1-6** on Manjaro Unstable branch. Feedback is highly appreciated.

**Comment by xabbu** [comment]
On my system, #11270 with #11244 fixes the problem. I can start and the lvm volumes are correctly initialized.

**Comment by yuwata** [comment]
Thank you for testing!

**Comment by philmmanjaro** [comment]
We are always keen to help. **v240.1-6** was confirmed to be working on our end.

**Comment by mbiebl** [comment]
I can confirm as well, that my test VMs (one with LVM, another one with LVM+cryptsetup) now successfully boot with #11270 applied. Thanks @yuwata!

As a follow-up, we really should add an automated test for LVM, at least a basic one.

**Comment by yuwata** [comment]
> As a follow-up, we really should add an automated test for LVM, at least a basic one.

Yeah.

**Comment by mbiebl** [comment]
> > I did not need #11244, fwiw.
> 
> It is necessary if you want to boot with debug logging.

yeah, I consider cherry-picking at least https://github.com/systemd/systemd/pull/11244/commits/2c74c0647571941681f1c829e84dc81ec5394ecb in Debian.
Or do I need the other commits as well?

That commit (or the PR) should probably mention #11258

**Comment by philmmanjaro** [comment]
@mbiebl: you are correct. If you only want to fix the issue of this thread, you only need PR #11270 applied.

**Comment by johnwmail** [comment]
> I can confirm as well, that my test VMs (one with LVM, another one with LVM+cryptsetup) now successfully boot with #11270 applied. Thanks @yuwata!
> 
> I did not need #11244, fwiw.
> 
> As a follow-up, we really should add an automated test for LVM, at least a basic one.

Hi, do plan to backport this fix to debian?
Thanks.

**Comment by panpakos** [comment]
> > I can confirm as well, that my test VMs (one with LVM, another one with LVM+cryptsetup) now successfully boot with #11270 applied. Thanks @yuwata!
> > I did not need #11244, fwiw.
> > As a follow-up, we really should add an automated test for LVM, at least a basic one.
> 
> Hi, do plan to backport this fix to debian?
> Thanks.

obviously, it's fixed in git, awaiting for upload so should be soon in repos
https://salsa.debian.org/systemd-team/systemd/commit/1bdc896a4fd6d29af847b8fe7edd4d710ec6142d

**Comment by bencaradocdavies** [comment]
Confirmed fixed for me in 240-2 on Debian sid (I am the original reporter of [Debian #917124](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917124)).

**Comment by johnwmail** [comment]
> > Actually, adding a line `ExecStart=/bin/udevadm trigger --type=devices --action=change` works better.
> > With
> > ```
> > ExecStart=/bin/udevadm trigger --type=subsystems --action=add
> > ExecStart=/bin/udevadm trigger --type=devices --action=add
> > ExecStart=/bin/udevadm trigger --type=devices --action=change
> > ```
> > the system boots without any noticeable issues.
> 
> Hi, it work on my kvm/quem(quest) system, but can not work on my bare metal system.
> 
> but replace /lib/systemd/systemd-udevd with udev version 239's
> (/lib/systemd/systemd-udevd), then update-initramfs -u work for my both kvm/bare metal system.
> 
> Thanks.

Fixed for me with 240-2 on both kvm and bare metal system, thanks.
