### ISSUE TITLE
test-mountpoint-util fails when run in a mount/pid namepace

### ISSUE THREAD

**Issue by floppym** [systemd/systemd#11505]
**systemd version the issue has been seen with**
240

**Used distribution**
Gentoo
https://bugs.gentoo.org/674458

**Summary**
Gentoo's Portage package manager runs builds in a separate pid namespace. It also creates a separate mount namespace to allow /proc to be over-mounted with a new proc instance.

When run in such an environment, `test-mountpoint-util` fails as below.
```
--- command ---
SYSTEMD_KBD_MODEL_MAP='/x/portage/sys-apps/systemd-240-r2/work/systemd-240/src/locale/kbd-model-map' SYSTEMD_LANGUAGE_FALLBACK_MAP='/x/portage/sys-apps/systemd-240-r2/work/systemd-240/src/locale/language-fallback-map' PATH='/x/portage/sys-apps/systemd-240-r2/work/systemd-240-abi_x86_64.amd64:/x/portage/sys-apps/systemd-240-r2/temp/python3.7/bin:/usr/lib/ccache/bin:/home/floppym/src/portage/bin/ebuild-helpers/xattr:/home/floppym/src/portage/bin/ebuild-helpers:/usr/lib/llvm/7/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin' /x/portage/sys-apps/systemd-240-r2/work/systemd-240-abi_x86_64.amd64/test-mountpoint-util
--- stderr ---
Found container virtualization none.
/* test_mount_propagation_flags(shared) */
/* test_mount_propagation_flags(slave) */
/* test_mount_propagation_flags(private) */
/* test_mount_propagation_flags((null)) */
/* test_mount_propagation_flags() */
/* test_mount_propagation_flags(xxxx) */
/* test_mount_propagation_flags( ) */
/* test_mnt_id */
mountinfo: / → 464
mountinfo: /sys → 465
mountinfo: /sys/fs/cgroup → 466
mountinfo: /sys/fs/cgroup/unified → 467
mountinfo: /sys/fs/cgroup/systemd → 468
mountinfo: /sys/fs/cgroup/perf_event → 469
mountinfo: /sys/fs/cgroup/pids → 470
mountinfo: /sys/fs/cgroup/cpu,cpuacct → 471
mountinfo: /sys/fs/cgroup/net_cls,net_prio → 472
mountinfo: /sys/fs/cgroup/cpuset → 473
mountinfo: /sys/fs/cgroup/blkio → 474
mountinfo: /sys/fs/cgroup/memory → 475
mountinfo: /sys/fs/cgroup/devices → 476
mountinfo: /sys/fs/cgroup/freezer → 477
mountinfo: /sys/fs/cgroup/hugetlb → 478
mountinfo: /sys/fs/bpf → 479
mountinfo: /sys/kernel/debug → 480
mountinfo: /sys/fs/fuse/connections → 481
mountinfo: /dev → 482
mountinfo: /dev/shm → 483
mountinfo: /dev/pts → 484
mountinfo: /dev/mqueue → 485
mountinfo: /dev/hugepages → 486
mountinfo: /run → 487
mountinfo: /run/user/10000 → 488
mountinfo: /run/user/0 → 489
mountinfo: /proc → 490
mountinfo: /proc/sys/fs/binfmt_misc → 491
mountinfo: /proc/sys/fs/binfmt_misc → 492
mountinfo: /tmp → 493
mountinfo: /x → 494
mountinfo: /mnt/data1 → 495
mountinfo: /var/cache/distfiles → 496
mountinfo: /home → 497
mountinfo: /home/floppym/tmp → 498
mountinfo: /var/cache/packages → 499
mountinfo: /boot → 500
mountinfo: /proc → 503
mnt ids of /run are 487, 487
mnt ids of /var/cache/packages are 499, 499
mnt ids of /boot are 500, 500
mnt ids of /sys/fs/cgroup/cpuset are 473, 473
mnt ids of /dev/shm are 483, 483
mnt ids of /run/user/0 are 489, 489
mnt ids of /proc/sys/fs/binfmt_misc are 491, 503
the other path for mnt id 503 is /proc
Assertion 'path_equal(p, t)' failed at ../systemd-240/src/test/test-mountpoint-util.c:86, function test_mnt_id(). Aborting.
```

**Comment by poettering** [comment]
so /proc is mounted twice, one on top of the other? why that?

**Comment by floppym** [comment]
We need to mount a new instance of /proc to get pids from the new namespace to show up; otherwise, /proc remains tied to the parent namespace. Is there some better way to handle this?

I suppose the alternative would be to recursively unmount /proc before mounting the new instance, but is there any benefit in doing so?

**Comment by robert-scheck** [comment]
Same issue here with systemd v244 when trying to build `systemd` on CentOS 8.1 in `mock`:

```
The output from the failed tests:

340/543 test-mountpoint-util                    FAIL     0.51 s (killed by signal 6 SIGABRT)

--- command ---
SYSTEMD_KBD_MODEL_MAP='/builddir/build/BUILD/systemd-stable-244.1/src/locale/kbd-model-map' PATH='/builddir/build/BUILD/systemd-stable-244.1/x86_64-redhat-linux-gnu:/builddir/.local/bin:/builddir/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin' SYSTEMD_LANGUAGE_FALLBACK_MAP='/builddir/build/BUILD/systemd-stable-244.1/src/locale/language-fallback-map' /builddir/build/BUILD/systemd-stable-244.1/x86_64-redhat-linux-gnu/test-mountpoint-util
--- stderr ---
Found container virtualization systemd-nspawn.
/* test_mount_propagation_flags(shared) */
/* test_mount_propagation_flags(slave) */
/* test_mount_propagation_flags(private) */
/* test_mount_propagation_flags((null)) */
/* test_mount_propagation_flags() */
/* test_mount_propagation_flags(xxxx) */
/* test_mount_propagation_flags( ) */
/* test_mnt_id */
mountinfo: / → 452
mountinfo: /var/cache/dnf → 453
mountinfo: /proc/filesystems → 454
mountinfo: /tmp → 455
mountinfo: /sys → 456
mountinfo: /sys/fs/selinux → 457
mountinfo: /dev → 458
mountinfo: /dev/shm → 459
mountinfo: /dev/pts → 460
mountinfo: /dev/console → 461
mountinfo: /run → 462
mountinfo: /run/systemd/nspawn/incoming → 463
mountinfo: /etc/resolv.conf → 464
mountinfo: /proc → 287
mountinfo: /proc/sys → 288
mountinfo: /proc/kallsyms → 289
mountinfo: /proc/kcore → 290
mountinfo: /proc/keys → 291
mountinfo: /proc/sysrq-trigger → 292
mountinfo: /proc/timer_list → 293
mountinfo: /proc/acpi → 294
mountinfo: /proc/asound → 295
mountinfo: /proc/bus → 296
mountinfo: /proc/fs → 297
mountinfo: /proc/irq → 298
mountinfo: /proc/scsi → 299
mountinfo: /sys/fs/cgroup → 300
mountinfo: /sys/fs/cgroup/pids → 302
mountinfo: /sys/fs/cgroup/blkio → 303
mountinfo: /sys/fs/cgroup/rdma → 304
mountinfo: /sys/fs/cgroup/hugetlb → 305
mountinfo: /sys/fs/cgroup/freezer → 310
mountinfo: /sys/fs/cgroup/devices → 311
mountinfo: /sys/fs/cgroup/cpu,cpuacct → 312
mountinfo: /sys/fs/cgroup/memory → 313
mountinfo: /sys/fs/cgroup/cpuset → 314
mountinfo: /sys/fs/cgroup/perf_event → 315
mountinfo: /sys/fs/cgroup/net_cls,net_prio → 316
mountinfo: /sys/fs/cgroup/systemd → 317
mountinfo: /proc/sys/kernel/random/boot_id → 318
mountinfo: /proc/sys/kernel/random/boot_id → 319
mountinfo: /proc/kmsg → 401
mnt ids of /sys/fs/cgroup/net_cls,net_prio is 316
mnt ids of /proc/filesystems are 454, 287
the other path for mnt id 287 is /proc
Assertion 'path_equal(p, t)' failed at src/test/test-mountpoint-util.c:94, function test_mnt_id(). Aborting.
```

**Comment by poettering** [comment]
At least partly addressed by af918c481864116fdf92eceb3376a014053eaf5f

**Comment by yuwata** [comment]
@floppym @robert-scheck What is the status of this issue?

**Comment by floppym** [comment]
I still get the same failure on Gentoo with Portage's pid-sandbox feature enabled. The change in af918c481864116fdf92eceb3376a014053eaf5f does not help because we do not run the tests as root.
```
================================== 479/1064 ==================================
test:         systemd / test-mountpoint-util
start time:   18:41:40
duration:     0.09s
result:       killed by signal 6 SIGABRT
command:      PATH=/x/portage/sys-apps/systemd-251.4/work/systemd-stable-251.4-abi_x86_64.amd64:/x/portage/sys-apps/systemd-251.4/temp/python3.11/bin:/usr/lib/ccache/bin:/home/floppym/src/portage/bin/ebuild-helpers/xattr:/home/floppym/src/portage/bin/ebuild-helpers:/usr/local/sbin:/usr/sbin:/sbin:/bin:/usr/local/bin:/usr/bin:/opt/bin:/usr/lib/llvm/15/bin:/usr/lib/llvm/14/bin:/usr/lib/llvm/13/bin MALLOC_PERTURB_=80 SYSTEMD_LANGUAGE_FALLBACK_MAP=/x/portage/sys-apps/systemd-251.4/work/systemd-stable-251.4/src/locale/language-fallback-map /x/portage/sys-apps/systemd-251.4/work/systemd-stable-251.4-abi_x86_64.amd64/test-mountpoint-util
----------------------------------- stderr -----------------------------------
Lacking privilege to create separate mount namespace, proceeding in originating mount namespace.
/* test_fd_is_mount_point */
/* test_path_is_mount_point */
/* test_mnt_id */
/* test_mnt_id */
mountinfo: / → 618
mountinfo: /var/lib/nfs/rpc_pipefs → 619
mountinfo: /sys → 620
mountinfo: /sys/kernel/security → 621
mountinfo: /sys/fs/cgroup → 622
mountinfo: /sys/fs/cgroup/portage → 623
mountinfo: /sys/fs/pstore → 624
mountinfo: /sys/fs/bpf → 625
mountinfo: /sys/kernel/debug → 626
mountinfo: /sys/kernel/tracing → 627
mountinfo: /sys/fs/fuse/connections → 628
mountinfo: /sys/kernel/config → 629
mountinfo: /dev → 630
mountinfo: /dev/shm → 631
mountinfo: /dev/pts → 632
mountinfo: /dev/hugepages → 633
mountinfo: /dev/mqueue → 634
mountinfo: /run → 635
mountinfo: /run/credentials/systemd-sysusers.service → 656
mountinfo: /run/user/10000 → 715
mountinfo: /proc → 716
mountinfo: /proc/sys/fs/binfmt_misc → 717
mountinfo: /proc/sys/fs/binfmt_misc → 718
mountinfo: /tmp → 719
mountinfo: /home/floppym/tmp → 720
mountinfo: /x → 721
mountinfo: /data → 722
mountinfo: /proc → 724
mnt ids of /tmp is 719
mnt ids of /sys/fs/cgroup is 622
mnt ids of /dev/mqueue is 634
mnt ids of /dev/hugepages is 633
mnt ids of /sys/kernel/security is 621
mnt ids of /run is 635
mnt ids of /data is 722
mnt ids of /sys/fs/cgroup/portage is 623
mnt ids of /run/user/10000 is 715
mnt ids of /proc/sys/fs/binfmt_misc are 718, 724
the other path for mnt id 724 is /proc
Assertion 'path_equal(p, t)' failed at src/test/test-mountpoint-util.c:105, function test_mnt_id(). Aborting.
==============================================================================
```

**Comment by yuwata** [comment]
I remembered that fedora skip the test.
https://src.fedoraproject.org/rpms/systemd/blob/rawhide/f/f58b96d3e8d1cb0dd3666bc74fa673918b586612.patch

**Comment by yuwata** [comment]
And this can be easily triggered with `$ sudo unshare --mount-proc build/test-mountpoint-util`.
