### ISSUE TITLE
sd_journal_previous called right after sd_journal_seek_tail returns 0

### ISSUE THREAD

**Issue by JonathanKang** [systemd/systemd#1152]
I use sd_journal_query_unique (priv->journal, "_BOOT_ID") and SD_JOURNAL_FOREACH_UNIQUE to access every boot. Then I use sd_journal_seek_tail and sd_journal_previous to get the realtime of the last log message for every boot.

But at a specific boot in my laptop, the sd_journal_previous call after sd_journal_seek_tail returns 0, which means it reaches the beginning of the journal. I think this is something wrong with sd_journal_previous().

The relevant codes can be found in the pictures below.﻿

![screenshot from 2015-08-30 20-07-39](https://cloud.githubusercontent.com/assets/5607743/9697847/5fe0086a-53d1-11e5-97cf-3566ff882a3b.png)
![screenshot from 2015-08-30 20-08-30](https://cloud.githubusercontent.com/assets/5607743/9697833/c61a0a5a-53d0-11e5-9a37-ebcf6e0fe463.png)

**Comment by poettering** [comment]
Could provide us with a minimal test case in C?

Which systemd version are you using? If it's not a very recent version, could you try if this issue persists with a very recent version?

Any chance you can provide us with a minimal set of .journal files that trigger this issue?

**Comment by JonathanKang** [comment]
Test case can be found [here](http://fpaste.org/264435/).

I'm using the API of systemd [here](http://www.freedesktop.org/software/systemd/man/) rather than using journalctl. So I think it's not related to a specific version of systemd. Anyway, the systemd installed on my laptop is version 219.

I found something odd. I used the test case above. If I use sd_journal_open() directly, the issue exists. But I copied those file to ~/log/, and then used sd_journal_open_directory() to open journal files in ~/log/, the issue was gone!

The .journal files can be found [here](http://pan.baidu.com/s/1mgCezR6).

**Comment by poettering** [comment]
We made quite some fixes to the journal code in newer systemd versions. Could you retry your test case on something more recent, such as v226 or so? I'd rather not spend time tracking this down if it is already fixed in current version!

**Comment by JonathanKang** [comment]
I updated the systemd version to 226 and tested again using the test case above. The problem still exists. :-(

I use journalctl -b to view the boot in which the call returns 0. I get some logs but not all from that boot and also an error saying "Failed to get journal fields: Bad message". Output of the command can be found [here](http://fpaste.org/269696/). I hope this would help. :-)

**Comment by keszybz** [comment]
Can you try again with newer systemd? In particular dc00966228ff90c554fd034e588ea55eb605ec52, which landed in systemd-230, might be relevant.

**Comment by JonathanKang** [comment]
Tested in Fedora 25 with systemd 231, the issue is gone. Thanks for the work on it.

**Comment by keszybz** [comment]
Pff, one down, 499 to go.
