### ISSUE TITLE
systemd-networkd writes to the log "Configured" each time, when it gets RA message

### ISSUE THREAD

**Issue by LetzteInstanz** [systemd/systemd#13595]
**systemd version the issue has been seen with**
> 243

**Used distribution**
 > 5.2.14-arch2-1-ARCH

**Expected behaviour you didn't see**
 > systemd-networkd should write once "Configured" to the log.

**Unexpected behaviour you saw**
 > systemd-networkd writes "Configured" each time to the log, when it gets RA message.

**Steps to reproduce the problem**

Configure a network interface with the same address and the same gateway, which the interface gets via RA:
```
[Match]
Name=wan

[Network]
DHCP=yes
Address=2a00:1838:aaaa:2037:7285:c2ff:fe25:bc62/64
IPForward=yes
IPv6AcceptRA=true

[Route]
Gateway=fe80::204:4eff:fe87:f000
PreferredSource=2a00:1838:aaaa:2037:7285:c2ff:fe25:bc62

[DHCP]
UseDNS=false
UseNTP=false
UseMTU=true

[IPv6AcceptRA]
UseDNS=false
```

The log in debug mode:
```
сен 18 13:25:19 server systemd-networkd[10705]: NDISC: Received Router Advertisement: flags none preference medium lifetime 1800 sec
сен 18 13:25:19 server systemd-networkd[10705]: NDISC: Invoking callback for 'router' event.
сен 18 13:25:19 server systemd-networkd[10705]: wan: Configuring route: dst: n/a, src: n/a, gw: fe80::204:4eff:fe87:f000, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
сен 18 13:25:19 server systemd-networkd[10705]: wan: Configuring route: dst: 2a00:1838:aaaa:2037::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
сен 18 13:25:19 server systemd-networkd[10705]: wan: Remembering updated address: 2a00:1838:aaaa:2037:7285:c2ff:fe25:bc62/64 (valid for 4w 2d)
сен 18 13:25:19 server systemd-networkd[10705]: wan: Configuring route: dst: n/a, src: n/a, gw: fe80::204:4eff:fe87:f000, prefsrc: n/a, scope: global, table: main, proto: static, type: unicast
сен 18 13:25:19 server systemd-networkd[10705]: wan: Setting routes
сен 18 13:25:19 server systemd-networkd[10705]: wan: State changed: configured -> configuring
сен 18 13:25:19 server systemd-networkd[10705]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=27 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
сен 18 13:25:19 server systemd-networkd[10705]: wan: Routes set
сен 18 13:25:19 server systemd-networkd[10705]: wan: Configured
сен 18 13:25:19 server systemd-networkd[10705]: wan: State changed: configuring -> configured
сен 18 13:25:19 server systemd-networkd[10705]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=28 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
```

**Comment by ssahani** [comment]
It's updating it cloud be same or different ? You saying it's too noisy ?

**Comment by LetzteInstanz** [comment]
I get the same network configuration via RA, what is in the static configuration except `PreferredSource`. But systemd-networkd behaviour is the same without `PreferredSource`.

I get every 200 seconds RA message and the message "Configured" is showed each time in the journal. Yes, I think, this is too noisy. It is not clear, why systemd-networkd writes "Configured", when it gets the configuration, which it has.

```
сен 18 01:28:31 server systemd[1]: Starting Network Service...
сен 18 01:28:31 server systemd-networkd[442]: /etc/systemd/network/12-lan.network:23: Found prefix 2dc0:a17b:7415:0000::/64
сен 18 01:28:31 server systemd-networkd[442]: Enumeration completed
сен 18 01:28:31 server systemd[1]: Started Network Service.
сен 18 01:28:31 server systemd-networkd[442]: wan: Interface name change detected, wan has been renamed to eth0.
сен 18 01:28:31 server systemd-networkd[442]: lan: Interface name change detected, lan has been renamed to eth1.
сен 18 01:28:31 server systemd-networkd[442]: eth0: Interface name change detected, eth0 has been renamed to wan.
сен 18 01:28:31 server systemd-networkd[442]: eth1: Interface name change detected, eth1 has been renamed to lan.
сен 18 01:28:31 server systemd-networkd[442]: wan: IPv6 successfully enabled
сен 18 01:28:31 server systemd-networkd[442]: lan: IPv6 successfully enabled
сен 18 01:28:33 server systemd-networkd[442]: wan: Gained carrier
сен 18 01:28:34 server systemd-networkd[442]: wan: Gained IPv6LL
сен 18 01:28:36 server systemd-networkd[442]: lan: Gained carrier
сен 18 01:28:37 server systemd-networkd[442]: lan: Gained IPv6LL
сен 18 01:29:01 server systemd-networkd[442]: lan: Could not set neighbor, ignoring: Connection timed out
сен 18 01:29:01 server systemd-networkd[442]: lan: Configured
сен 18 01:29:05 server systemd-networkd[442]: wan: DHCPv4 address 94.242.17.243/26 via 94.242.17.193
сен 18 01:29:05 server systemd-networkd[442]: wan: Configured
сен 18 01:29:05 server systemd-networkd[442]: tun0: Gained carrier
сен 18 01:29:05 server systemd-networkd[442]: tun0: Gained IPv6LL
сен 18 01:29:33 server systemd-networkd[442]: wan: Configured
сен 18 01:32:54 server systemd-networkd[442]: wan: Configured
сен 18 01:36:14 server systemd-networkd[442]: wan: Configured
сен 18 01:39:35 server systemd-networkd[442]: wan: Configured
сен 18 01:42:55 server systemd-networkd[442]: wan: Configured
сен 18 01:46:16 server systemd-networkd[442]: wan: Configured
сен 18 01:49:36 server systemd-networkd[442]: wan: Configured
сен 18 01:52:57 server systemd-networkd[442]: wan: Configured
сен 18 01:56:17 server systemd-networkd[442]: wan: Configured
сен 18 01:59:38 server systemd-networkd[442]: wan: Configured
сен 18 02:02:58 server systemd-networkd[442]: wan: Configured
сен 18 02:06:19 server systemd-networkd[442]: wan: Configured
сен 18 02:09:39 server systemd-networkd[442]: wan: Configured
сен 18 02:13:00 server systemd-networkd[442]: wan: Configured
сен 18 02:16:20 server systemd-networkd[442]: wan: Configured
сен 18 02:19:41 server systemd-networkd[442]: wan: Configured
сен 18 02:23:01 server systemd-networkd[442]: wan: Configured
сен 18 02:26:22 server systemd-networkd[442]: wan: Configured
сен 18 02:29:42 server systemd-networkd[442]: wan: Configured
сен 18 02:33:03 server systemd-networkd[442]: wan: Configured
сен 18 02:36:23 server systemd-networkd[442]: wan: Configured
сен 18 02:39:44 server systemd-networkd[442]: wan: Configured
сен 18 02:43:04 server systemd-networkd[442]: wan: Configured
сен 18 02:46:25 server systemd-networkd[442]: wan: Configured
сен 18 02:49:45 server systemd-networkd[442]: wan: Configured
сен 18 02:53:06 server systemd-networkd[442]: wan: Configured
сен 18 02:56:26 server systemd-networkd[442]: wan: Configured
сен 18 02:59:47 server systemd-networkd[442]: wan: Configured
сен 18 03:03:07 server systemd-networkd[442]: wan: Configured
```

**Comment by LetzteInstanz** [comment]
> It's updating it could be same or different ? You saying it's too noisy ?

I get the same network configuration via RA, what is in the static configuration except PreferredSource. But systemd-networkd behaviour is the same without PreferredSource.

My ISP sends every 200 seconds RA message and the message "Configured" is showed each time in the journal. Yes, I think, this is too noisy. It is not clear, why systemd-networkd writes "Configured", when it gets the configuration, which it has.

```
сен 18 01:28:31 server systemd[1]: Starting Network Service...
сен 18 01:28:31 server systemd-networkd[442]: /etc/systemd/network/12-lan.network:23: Found prefix 2dc0:a17b:7415:0000::/64
сен 18 01:28:31 server systemd-networkd[442]: Enumeration completed
сен 18 01:28:31 server systemd[1]: Started Network Service.
сен 18 01:28:31 server systemd-networkd[442]: wan: Interface name change detected, wan has been renamed to eth0.
сен 18 01:28:31 server systemd-networkd[442]: lan: Interface name change detected, lan has been renamed to eth1.
сен 18 01:28:31 server systemd-networkd[442]: eth0: Interface name change detected, eth0 has been renamed to wan.
сен 18 01:28:31 server systemd-networkd[442]: eth1: Interface name change detected, eth1 has been renamed to lan.
сен 18 01:28:31 server systemd-networkd[442]: wan: IPv6 successfully enabled
сен 18 01:28:31 server systemd-networkd[442]: lan: IPv6 successfully enabled
сен 18 01:28:33 server systemd-networkd[442]: wan: Gained carrier
сен 18 01:28:34 server systemd-networkd[442]: wan: Gained IPv6LL
сен 18 01:28:36 server systemd-networkd[442]: lan: Gained carrier
сен 18 01:28:37 server systemd-networkd[442]: lan: Gained IPv6LL
сен 18 01:29:01 server systemd-networkd[442]: lan: Could not set neighbor, ignoring: Connection timed out
сен 18 01:29:01 server systemd-networkd[442]: lan: Configured
сен 18 01:29:05 server systemd-networkd[442]: wan: DHCPv4 address 94.242.17.243/26 via 94.242.17.193
сен 18 01:29:05 server systemd-networkd[442]: wan: Configured
сен 18 01:29:05 server systemd-networkd[442]: tun0: Gained carrier
сен 18 01:29:05 server systemd-networkd[442]: tun0: Gained IPv6LL
сен 18 01:29:33 server systemd-networkd[442]: wan: Configured
сен 18 01:32:54 server systemd-networkd[442]: wan: Configured
сен 18 01:36:14 server systemd-networkd[442]: wan: Configured
сен 18 01:39:35 server systemd-networkd[442]: wan: Configured
сен 18 01:42:55 server systemd-networkd[442]: wan: Configured
сен 18 01:46:16 server systemd-networkd[442]: wan: Configured
сен 18 01:49:36 server systemd-networkd[442]: wan: Configured
сен 18 01:52:57 server systemd-networkd[442]: wan: Configured
сен 18 01:56:17 server systemd-networkd[442]: wan: Configured
сен 18 01:59:38 server systemd-networkd[442]: wan: Configured
сен 18 02:02:58 server systemd-networkd[442]: wan: Configured
сен 18 02:06:19 server systemd-networkd[442]: wan: Configured
сен 18 02:09:39 server systemd-networkd[442]: wan: Configured
сен 18 02:13:00 server systemd-networkd[442]: wan: Configured
сен 18 02:16:20 server systemd-networkd[442]: wan: Configured
сен 18 02:19:41 server systemd-networkd[442]: wan: Configured
сен 18 02:23:01 server systemd-networkd[442]: wan: Configured
сен 18 02:26:22 server systemd-networkd[442]: wan: Configured
сен 18 02:29:42 server systemd-networkd[442]: wan: Configured
сен 18 02:33:03 server systemd-networkd[442]: wan: Configured
сен 18 02:36:23 server systemd-networkd[442]: wan: Configured
сен 18 02:39:44 server systemd-networkd[442]: wan: Configured
сен 18 02:43:04 server systemd-networkd[442]: wan: Configured
сен 18 02:46:25 server systemd-networkd[442]: wan: Configured
сен 18 02:49:45 server systemd-networkd[442]: wan: Configured
сен 18 02:53:06 server systemd-networkd[442]: wan: Configured
сен 18 02:56:26 server systemd-networkd[442]: wan: Configured
сен 18 02:59:47 server systemd-networkd[442]: wan: Configured
сен 18 03:03:07 server systemd-networkd[442]: wan: Configured
```

**Comment by falconindy** [comment]
I was able to bisect this to 6545067aa950cf0af740a6fad88ff56d1b3fd40a. Disabling RAs in the .network file makes the spam stop.

**Comment by falconindy** [comment]
@ssahani Shouldn't networkd only log if the configured has *changed*? What's the point in logging *every* time we change some internal state tracked on the interface? In my case, my upstream router is emitting RAs on the order of every ~5 seconds, and the amount of logging is extreme, and extremely annoying.

Simply put: the logging is too noisy, and it isn't providing any useful information.

**Comment by ssahani** [comment]
Yes I agree we should fix this

**Comment by yuwata** [comment]
Does the current git master still show the message frequently?

**Comment by falconindy** [comment]
Yes. Situation seems unchanged.

```
Sep 25 11:13:20 rampage systemd-networkd[178293]: br-qemu: netdev ready
Sep 25 11:13:20 rampage systemd-networkd[178293]: br-qemu: Gained IPv6LL
Sep 25 11:13:20 rampage systemd-networkd[178293]: eth0: Gained IPv6LL
Sep 25 11:13:20 rampage systemd-networkd[178293]: Enumeration completed
Sep 25 11:13:20 rampage systemd-networkd[178293]: br-qemu: netdev exists, using existing without changing its parameters
Sep 25 11:13:20 rampage systemd-networkd[178293]: br-qemu: IPv6 successfully enabled
Sep 25 11:13:20 rampage systemd-networkd[178293]: eth0: IPv6 successfully enabled
Sep 25 11:13:22 rampage systemd-networkd[178293]: eth0: Configured
Sep 25 11:13:28 rampage systemd-networkd[178293]: eth0: Configured
Sep 25 11:13:32 rampage systemd-networkd[178293]: br-qemu: Configured
Sep 25 11:13:35 rampage systemd-networkd[178293]: eth0: Configured
Sep 25 11:13:42 rampage systemd-networkd[178293]: eth0: Configured
Sep 25 11:13:50 rampage systemd-networkd[178293]: eth0: Configured
Sep 25 11:13:58 rampage systemd-networkd[178293]: eth0: Configured
```

**Comment by ssahani** [comment]
@yuwata we can put this in debug.

**Comment by yuwata** [comment]
Thank you for the confirmation.

@ssahani Yeah, I think so.

**Comment by yuwata** [comment]
@ssahani I will prep a patch. Or are you already working on this?

**Comment by yuwata** [comment]
Fix is waiting in #13650.
