### ISSUE TITLE
Invalid systemctl warning that source configuration file changed on disk

### ISSUE THREAD

**Issue by dsahern** [systemd/systemd#13634]
**systemd version the issue has been seen with**
> v241 - debian buster, but from a source code review should be present on top of tree

**Used distribution**
 > debian buster

**Expected behaviour you didn't see**
 > Warning message should not be visible in systemctl output

**Unexpected behaviour you saw**
 > Warning message in systemctl output

The vrf package has a systemd generator that leverages systemd instances.[1] The generated unit files set SourcePath to the file from which the vrf override was created.

With debian jessie, this generator worked fine. With debian buster (systemd 241) we are seeing an error on all VRF related services running ‘systemctl status <service name>’:

Warning: The unit file, source configuration file or drop-ins of <service name> changed on disk. Run 'systemctl daemon-reload' to reload units.

In fact if you compare the mtimes of the original file, e.g., /lib/systemd/system/ssh.service, and the generated vrf override, /run/systemd/generator/ssh@.service.d/vrf.conf, the mtimes of the original file (all times really) are < the times of the vrf config file.

I added debugs and this seems to be a clear systemd bug: it is comparing the mtime of the SourcePath file to 0 which of course means the mtime is always newer so unit_need_daemon_reload returns true. Specificaally, the root cause is either the source_path not getting set when it should be or the mtime check needs to be skipped if the mtime is 0. I do not know system well enough to submit a patch, but this is what I am seeing. In load_from_path, source_path is not set:

2019-09-23T17:12:53.649611+00:00 myhost systemd[1]: load_from_path: src path <none> mtime 0 fragment /run/systemd/system/ssh@.service mtime 1569258763287765

so the mtime is 0. And then later unit_need_daemon_reload calls fragment_mtime_newer with an mtime of 0:

2019-09-23T17:12:53.666978+00:00 myhost systemd[1]: path /lib/systemd/system/ssh.service has mtime 1554717083000000; comparing to 0 (masked 0)

so of course it returns true resulting in the systemctl warning.

[1] https://github.com/CumulusNetworks/vrf/blob/master/systemd/systemd-vrf-generator

**Comment by poettering** [comment]
I am pretty sure this has been fixed already with 581fef8d56a13390a331d4d404f178d7cc188ccf and related patches. @keszybz Right?

Let's close this here. Please report back though if you manage to reproduce this with a version post the mentioned commit.

**Comment by dsahern** [comment]
I booted Ubuntu 19.10, ported 581fef8d56a13390a331d4d404f178d7cc188ccf to it. Problem still exists:
$ systemctl status ssh@mgmt
Warning: The unit file, source configuration file or drop-ins of ssh@mgmt.service changed on disk. Run 'systemctl daemon-reload' to reload units.

$ dpkg -l | grep systemd
ii  dbus-user-session                1.12.14-1ubuntu2                    amd64        simple interprocess messaging system (systemd --user integration)
ii  libnss-systemd:amd64             242-7ubuntu3.1                      amd64        nss module providing dynamic user and group name resolution
ii  libpam-systemd:amd64             242-7ubuntu3.1                      amd64        system and service manager - PAM module
ii  libsystemd0:amd64                242-7ubuntu3.1                      amd64        systemd utility library
ii  networkd-dispatcher              2.0.1-1                             all          Dispatcher service for systemd-networkd connection status changes
ii  python3-systemd                  234-3                               amd64        Python 3 bindings for systemd
ii  systemd                          242-7ubuntu3.1                      amd64        system and service manager
ii  systemd-sysv                     242-7ubuntu3.1                      amd64        system and service manager - SysV links

**Comment by dsahern** [comment]
@poettering  Looking at what the referenced commit it is not clear to me why you think it would solve the problem. As noted in the description above, the issue I raised has to do with mtimes of SourcePath being compared to 0, so it is an ordering problem.

**Comment by dsahern** [comment]
@poettering My debugging patch showing the problem: https://github.com/dsahern/systemd/commit/f4082d85316c47b4eb78516f4775caeadbc56b61

**Comment by keszybz** [comment]
The right commit is 5a1c1b534fe13e60ef9bce0dc680ad6f2a0c577f.

@dsahern if you can reproduce the issue with current master (or at least v243-stable), then we can reopen this. But I'm pretty sure it's currently fixed.

**Comment by dsahern** [comment]
@keszybz Commit 5a1c1b5 is a fix for commit e8630e695232bdfc which is dated July 2019,  a commit that is not in the debian  buster version of systemd. Anyways, I built top of tree, c488660e6edb3c1375ab62514a8df035c3d712bf, and problem still exists:

$ systemctl status ssh@mgmt
Warning: The unit file, source configuration file or drop-ins of ssh@mgmt.service changed on disk. Run 'systemctl daemon-reload' to reload units.

**Comment by SylwesterZarebski** [comment]
I have the same problem on Debian 10 when going with procedure from [Perfect Server Debian 10](https://www.howtoforge.com/perfect-server-debian-10-buster-apache-bind-dovecot-ispconfig-3-1/) with created file:
```
nano /etc/systemd/system/mysql.service.d/limits.conf
```
and then:
```
systemctl daemon-reload
systemctl restart mariadb
```
There is always message of:
```
Warning: The unit file, source configuration file or drop-ins of mariadb.service changed on disk. Run 'systemctl daemon-reload' to reload units.
```

Otherwise this is harmless, but warning is wrong, because `systemctl daemon-reload` or even `reboot` do not remove warning.

**Comment by sshedi** [comment]
Hi @poettering @keszybz this issue still exists. In PhotonOS 4.0 we have `systemd-247.11` and this particular issue happens after upgrading docker package. There is absolutely no difference between `docker.service`file in existing and updated version of docker package but still systemd complains that `docker.service` file is changed on disk.

Here are the steps to reproduce this issue on PhotonOS:
````
# tdnf downgrade -y docker --enablerepo=photon
# reboot
# tdnf update -y docker
```

After update, I see following output.

```
root@arm-ph4-sshedi:~ # tdnf update docker

Upgrading:
docker-cli                            aarch64            20.10.14-9.ph4           local               47.16M 49449718
docker-engine                         aarch64            20.10.14-9.ph4           local               60.18M 63103233
docker                                aarch64            20.10.14-9.ph4           local                   0.00b 0

Total installed size: 107.34M 112552951
Is this ok [y/N]: y

Downloading:
docker-cli                             9735593 100%
docker-engine                         14425820 100%
docker                                    7297 100%
Testing transaction
Running transaction
Installing/Updating: docker-engine-20.10.14-9.ph4.aarch64
Installing/Updating: docker-cli-20.10.14-9.ph4.aarch64
Installing/Updating: docker-20.10.14-9.ph4.aarch64
Removing: docker-20.10.14-8.ph4.aarch64
Removing: docker-cli-20.10.14-8.ph4.aarch64
Removing: docker-engine-20.10.14-8.ph4.aarch64
Warning: The unit file, source configuration file or drop-ins of docker.service changed on disk. Run 'systemctl daemon-reload' to reload units.

Complete!
```

Here is the file hash of older and latest docker.service file

````
root@arm-ph4-sshedi:~ # md5sum /lib/systemd/system/docker.service docker.service 
90c88d42e81ab02489746416f72afd08  /lib/systemd/system/docker.service
90c88d42e81ab02489746416f72afd08  docker.service
```

Tricky thing is, it doesn't happen with other service files, I tried with one other package and I don't see this issue.

Here is our docker spec:
https://github.com/vmware/photon/blob/4.0/SPECS/docker/docker-20.10.spec

And systemd spec:
https://github.com/vmware/photon/blob/4.0/SPECS/systemd/systemd.spec

And link to the issue where some folks reported that with tdnf-automatic, the issue is observed.
https://github.com/vmware/photon/issues/1244

cc: @YustasSwamp @tapakund

**Comment by sshedi** [comment]
Hi @poettering & @keszybz, any inputs on this issue? Please assist.
