### ISSUE TITLE
Add support for Lenovo Thinkpad Yoga 12 (2015)

### ISSUE THREAD

**Issue by rexcze-zz** [systemd/systemd#1440]
Hello,

on Lenovo Thinkpad Yoga 12 (2015) when I flip screen to tablet mode I can see that key is not mapped.

`atkbd serio0: Unknown key pressed (translated set 2, code 0xd8 on isa0060/serio0).`
 `atkbd serio0: Use 'setkeycodes e058 <keycode>' to make it known.`

Ant after rotating screen back to laptop mode:

`atkbd serio0: Unknown key pressed (translated set 2, code 0xd9 on isa0060/serio0).`
`atkbd serio0: Use 'setkeycodes e059 <keycode>' to make it known.`

Would it be possible to map those keys? How to find correct filter expression to add mapping to 60-keyboard.hwdb?

Thank you.

**Comment by martinpitt** [comment]
Yes, we can do that. Presumably we should map them both to `KEY_ROTATE_DISPLAY` as there are no separate codes for "laptop to tablet" and "tablet to laptop". Can you please copy&paste the output of 

```
cat /sys/class/dmi/id/modalias
```

? Thanks!

**Comment by rexcze-zz** [comment]
Thanks!

cat /sys/class/dmi/id/modalias

`dmi:bvnLENOVO:bvrJEET70WW(1.19):bd08/25/2015:svnLENOVO:pn20DK002EMC:pvrThinkPadS1Yoga12:rvnLENOVO:rn20DK002EMC:rvrSDK0E50510WIN:cvnLENOVO:ct10:cvrNone:`

**Comment by poettering** [comment]
@rexcze  Hmm, why did you close this bug? Or did @martinpitt already integrate the line?

**Comment by rexcze-zz** [comment]
Hi @poettering,
I closed it by mistake. Sorry.

**Comment by martinpitt** [comment]
@rexcze, can you please double-check that PR #1457 fixes this for you?

**Comment by rexcze-zz** [comment]
Hi I added lines from https://github.com/systemd/systemd/pull/1457, ran `udevadm hwdb --update`, restarted computer but I still can see:

atkbd serio0: Unknown key pressed (translated set 2, code 0xd8 on isa0060/serio0).
`atkbd serio0: Use 'setkeycodes e058 <keycode>' to make it known.`
`atkbd serio0: Unknown key released (translated set 2, code 0xd8 on isa0060/serio0).`
`atkbd serio0: Use 'setkeycodes e058 <keycode>' to make it known.`
`atkbd serio0: Unknown key pressed (translated set 2, code 0xd9 on isa0060/serio0).`
`atkbd serio0: Use 'setkeycodes e059 <keycode>' to make it known.`
`atkbd serio0: Unknown key released (translated set 2, code 0xd9 on isa0060/serio0).`
`atkbd serio0: Use 'setkeycodes e059 <keycode>' to make it known.`

But I am not sure if `udevadm hwdb --update` and restart is enough. 

Thanks

**Comment by poettering** [comment]
Reopening as per the last comment. @martinpitt, any idea?

**Comment by martinpitt** [comment]
`udevadm hwdb --update` ought to be enough, yes. Can you please run `udevadm info --export-db > /tmp/udev.txt` and put /tmp/udev.txt into a pastebin? Indeed #1457 did not add the 0xd8 key, but 0xd9 ought to work now.

**Comment by rexcze-zz** [comment]
Hello,
here is the output https://paste.fedoraproject.org/275903/

**Comment by martinpitt** [comment]
@rexcze: I'm honestly out of ideas what went wrong then. The DMI pattern does seem to match on your `/devices/virtual/dmi/id`, but there's clearly no `KEYBOARD_KEY_d9` on `/devices/platform/i8042/serio0/input/input3` (but its driver is atkbd). `60-keyboard.hwdb` has similar patterns for other models which seem to work. Are you sure that you put it into the right place? Could you maybe download the complete https://github.com/systemd/systemd/blob/master/hwdb/60-keyboard.hwdb and replace your current version with that, and re-run `udevadm hwdb --update`?

Also, which systemd version are you running? The format of `60-keyboard.hwdb` changed in March 2015, thus in systemd 220. If you run an older version, the `evdev:` match won't work (see commit 51c0c286).

**Comment by rexcze-zz** [comment]
I changed my 60-keyboard.hwdb by that from github, rerun `udevadm hwdb --update` and when I flip screen to tablet mode I can see in logs:

`atkbd serio0: Unknown key pressed (translated set 2, code 0xd8 on isa0060/serio0).`
`atkbd serio0: Use 'setkeycodes e058 <keycode>' to make it known.`

After switch back to laptop mode I can see:

`atkbd serio0: Unknown key pressed (translated set 2, code 0xd9 on isa0060/serio0).`
`atkbd serio0: Use 'setkeycodes e059 <keycode>' to make it known.`

**Comment by rexcze-zz** [comment]
I am running systemd-219-24.fc22.x86_64...

**Comment by martinpitt** [comment]
systemd 219? That explains it then, as I said the above patches are for >= 220. I pushed the above commit to add the missing 0xd8 key as well.

**Comment by martinpitt** [comment]
As pointed out in #1539 this indeed doesn't work yet, but for another reason. Reopening, will send PR momentarily.

**Comment by martinpitt** [comment]
PR #1558 should now fix this for good for systemd >= 220.

**Comment by martinpitt** [comment]
As discussed in #1539 these keys should _not_ be assigned to "direction" as they are merely an indication of screen rotation, not a button to _request_ screen rotation (like on other ThinkPad models). Assigning them to "reserved" also does not make the warnings disappear, so there's nothing we can/should do on the udev keymap side. I'll push a PR to remove the mapping again, which will auto-close this issue.

**Comment by d4g** [comment]
This issue still exists for me.
On my Thinkpad Yoga S1, I see the following issue:
When i flip the display back to "laptop mode", XF86RotateWindows is triggered.
But when the display is flipped into "tablet mode", this does not occur. 

But what I see is the following messages in dmesg:
    [  638.504273] atkbd serio0: Unknown key pressed (translated set 2, code 0xd8 on isa0060/serio0).
    [  638.504282] atkbd serio0: Use 'setkeycodes e058 <keycode>' to make it known.
    [  638.511214] thinkpad_acpi: unknown possible thermal alarm or keyboard event received
    [  638.511222] thinkpad_acpi: unhandled HKEY event 0x60c0

Can you please fix this?

Systemd:
systemd 227

**Comment by wlhlm** [comment]
Well, the commit that fixes this is part of systemd 228, so please update.

**Comment by ragtag** [comment]
This really needs to trigger two different events on e058 and e059.

**Comment by ragtag** [comment]
This really needs to trigger different events for e058 and e059. On the Yoga 12, the e058 is triggered when three different things happen:
- going from laptop to tent mode
- going from tent mode to tablet mode
- going from tablet mode to tent mode.

e059 is triggered when going from tent mode to laptop mode. 

I've been trying to get this laptop working the same way it does under Windows, and this issue as had me stumped. You can find my branch of the spin.py code for it here https://github.com/ragtag/spin  (still a bit hacky). 

The reason we need to differentiate the two, is that the laptop needs to enter tablet mode (disable keyboard, enable autoration etc.). when e058 is triggered, and enter laptop mode when e059 is triggered. With just one event, there is no way of telling where it goes from tent mode.

**Comment by d4g** [comment]
The issue is still appearing for me, running systemd 228:
`systemd-run --version
systemd 228`

> dmesg -w
> [56187.466149] atkbd serio0: Unknown key pressed (translated set 2, code 0xd8 on isa0060/serio0).
> [56187.466152] atkbd serio0: Use 'setkeycodes e058 <keycode>' to make it known.
> [56187.467361] thinkpad_acpi: unknown possible thermal alarm or keyboard event received
> [56187.467365] thinkpad_acpi: unhandled HKEY event 0x60c0
> [56187.467367] thinkpad_acpi: please report the conditions when this event happened to ibm-acpi-devel@lists.sourceforge.net
> [56187.482037] atkbd serio0: Unknown key released (translated set 2, code 0xd8 on isa0060/serio0).
> [56187.482040] atkbd serio0: Use 'setkeycodes e058 <keycode>' to make it known.
> [56192.205462] atkbd serio0: Unknown key pressed (translated set 2, code 0xd9 on isa0060/serio0).
> [56192.205465] atkbd serio0: Use 'setkeycodes e059 <keycode>' to make it known.
> [56192.206567] thinkpad_acpi: unknown possible thermal alarm or keyboard event received
> [56192.206575] thinkpad_acpi: unhandled HKEY event 0x60c0
> [56192.206576] thinkpad_acpi: please report the conditions when this event happened to ibm-acpi-devel@lists.sourceforge.net
> [56192.221220] atkbd serio0: Unknown key released (translated set 2, code 0xd9 on isa0060/serio0).
> [56192.221223] atkbd serio0: Use 'setkeycodes e059 <keycode>' to make it known.

So the events are still not handled and not mapped.

**Comment by d4g** [comment]
This issue is still not resolved. It's ennerving that I can't just reopen the issue.

**Comment by AlexeyGusev** [comment]
same story here on Lenovo Thinkpad Yoga, kernel version 4.10.0, systemd 229. 
```
$ cat /sys/class/dmi/id/modalias
dmi:bvnLENOVO:bvrN1FET40W(1.14):bd04/18/2016:svnLENOVO:pn20FQ004WMS:pvrThinkPadX1Yoga1st:rvnLENOVO:rn20FQ004WMS:rvrSDK0J40697WIN:cvnLENOVO:ct10:cvrNone:
```

Flip the screen and you get 
```
[  102.872282] thinkpad_acpi: unknown possible thermal alarm or keyboard event received
[  102.872286] thinkpad_acpi: unhandled HKEY event 0x60f0
[  102.872287] thinkpad_acpi: please report the conditions when this event happened to ibm-acpi-devel@lists.sourceforge.net
```

dmesg output contains complaints about unhandled HKEY events 0x60f0 and 0x60c0. Eagerly waiting for fix, can assist with testing if needed.

**Comment by alexanderavrorin** [comment]
I can confirm the issue on Thinkpad Yoga S1,  kernel 4.9.0-2, systemd version 232.
