### ISSUE TITLE
Fuzz is no longer being set from 60-evdev.hwdb

### ISSUE THREAD

**Issue by mkhpalm** [systemd/systemd#14967]
**systemd version the issue has been seen with**

`244.3`

**Used distribution**

Debian Sid: `Linux 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux`

**Expected behaviour you didn't see**

 Fuzz to be set via: https://github.com/systemd/systemd/blob/61c0ac0924d5a7bc9ce5e028538b399bc48db87c/hwdb.d/60-evdev.hwdb#L536-L540

**Unexpected behaviour you saw**

 Fuzz is not getting set anymore causing the pointer to jitter

```
evemu-describe /dev/input/event6
# EVEMU 1.3
# Kernel: 5.4.0-4-amd64
# DMI: dmi:bvnRazer:bvr3.02:bd02/22/2018:svnRazer:pnBladeStealth:pvr4.06:rvnRazer:rnBladeStealth:rvr:cvnRazer:ct9:cvr:
# Input device name: "1A586757:00 06CB:8323 Touchpad"
# Input device ID: bus 0x18 vendor 0x6cb product 0x8323 version 0x100
# Size in mm: 101x65
# Supported events:
#   Event type 0 (EV_SYN)
#     Event code 0 (SYN_REPORT)
#     Event code 1 (SYN_CONFIG)
#     Event code 2 (SYN_MT_REPORT)
#     Event code 3 (SYN_DROPPED)
#     Event code 4 ((null))
#     Event code 5 ((null))
#     Event code 6 ((null))
#     Event code 7 ((null))
#     Event code 8 ((null))
#     Event code 9 ((null))
#     Event code 10 ((null))
#     Event code 11 ((null))
#     Event code 12 ((null))
#     Event code 13 ((null))
#     Event code 14 ((null))
#     Event code 15 (SYN_MAX)
#   Event type 1 (EV_KEY)
#     Event code 272 (BTN_LEFT)
#     Event code 325 (BTN_TOOL_FINGER)
#     Event code 328 (BTN_TOOL_QUINTTAP)
#     Event code 330 (BTN_TOUCH)
#     Event code 333 (BTN_TOOL_DOUBLETAP)
#     Event code 334 (BTN_TOOL_TRIPLETAP)
#     Event code 335 (BTN_TOOL_QUADTAP)
#   Event type 3 (EV_ABS)
#     Event code 0 (ABS_X)
#       Value     1162
#       Min          0
#       Max       1220
#       Fuzz         0
#       Flat         0
#       Resolution  12
#     Event code 1 (ABS_Y)
#       Value       89
#       Min          0
#       Max        721
#       Fuzz         0
#       Flat         0
#       Resolution  11
#     Event code 47 (ABS_MT_SLOT)
#       Value        0
#       Min          0
#       Max          4
#       Fuzz         0
#       Flat         0
#       Resolution   0
#     Event code 53 (ABS_MT_POSITION_X)
#       Value        0
#       Min          0
#       Max       1220
#       Fuzz         0
#       Flat         0
#       Resolution  12
#     Event code 54 (ABS_MT_POSITION_Y)
#       Value        0
#       Min          0
#       Max        721
#       Fuzz         0
#       Flat         0
#       Resolution  11
#     Event code 57 (ABS_MT_TRACKING_ID)
#       Value        0
#       Min          0
#       Max      65535
#       Fuzz         0
#       Flat         0
#       Resolution   0
#   Event type 4 (EV_MSC)
#     Event code 5 (MSC_TIMESTAMP)
# Properties:
#   Property  type 0 (INPUT_PROP_POINTER)
#   Property  type 2 (INPUT_PROP_BUTTONPAD)
N: 1A586757:00 06CB:8323 Touchpad
I: 0018 06cb 8323 0100
P: 05 00 00 00 00 00 00 00
B: 00 0b 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 01 00 00 00 00 00
B: 01 20 e5 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 02 00 00 00 00 00 00 00 00
B: 03 03 00 00 00 00 80 60 02
B: 04 20 00 00 00 00 00 00 00
B: 05 00 00 00 00 00 00 00 00
B: 11 00 00 00 00 00 00 00 00
B: 12 00 00 00 00 00 00 00 00
B: 14 00 00 00 00 00 00 00 00
B: 15 00 00 00 00 00 00 00 00
B: 15 00 00 00 00 00 00 00 00
A: 00 0 1220 0 0 12
A: 01 0 721 0 0 11
A: 2f 0 4 0 0 0
A: 35 0 1220 0 0 12
A: 36 0 721 0 0 11
A: 39 0 65535 0 0 0
```

**Steps to reproduce the problem**

Try to set fuzz with evdev on version 244

**Comment by keszybz** [comment]
@whot ?

**Comment by whot** [comment]
Probably [this libinput bug](https://gitlab.freedesktop.org/libinput/libinput/issues/424) fixed [here](https://gitlab.freedesktop.org/libinput/libinput/commit/19898eb2b2f74b3a4b2382765f33a5ee257a9b03) and available in 1.15.2 and later.

**Comment by mkhpalm** [comment]
I've been running libinput 1.15.2

```
ii  libinput-bin                          1.15.2-1                                 amd64        input device management and event handling library - udev quirks
ii  libinput-tools                        1.15.2-1                                 amd64        input device management and event handling library - command line tools
ii  libinput10:amd64                      1.15.2-1                                 amd64        input device management and event handling library - shared library
```

But still no fuzz:
```
# EVEMU 1.3
# Kernel: 5.4.0-4-amd64
# DMI: dmi:bvnRazer:bvr3.02:bd02/22/2018:svnRazer:pnBladeStealth:pvr4.06:rvnRazer:rnBladeStealth:rvr:cvnRazer:ct9:cvr:
# Input device name: "1A586757:00 06CB:8323 Touchpad"
# Input device ID: bus 0x18 vendor 0x6cb product 0x8323 version 0x100
# Size in mm: 101x65
# Supported events:
#   Event type 0 (EV_SYN)
#     Event code 0 (SYN_REPORT)
#     Event code 1 (SYN_CONFIG)
#     Event code 2 (SYN_MT_REPORT)
#     Event code 3 (SYN_DROPPED)
#     Event code 4 ((null))
#     Event code 5 ((null))
#     Event code 6 ((null))
#     Event code 7 ((null))
#     Event code 8 ((null))
#     Event code 9 ((null))
#     Event code 10 ((null))
#     Event code 11 ((null))
#     Event code 12 ((null))
#     Event code 13 ((null))
#     Event code 14 ((null))
#     Event code 15 (SYN_MAX)
#   Event type 1 (EV_KEY)
#     Event code 272 (BTN_LEFT)
#     Event code 325 (BTN_TOOL_FINGER)
#     Event code 328 (BTN_TOOL_QUINTTAP)
#     Event code 330 (BTN_TOUCH)
#     Event code 333 (BTN_TOOL_DOUBLETAP)
#     Event code 334 (BTN_TOOL_TRIPLETAP)
#     Event code 335 (BTN_TOOL_QUADTAP)
#   Event type 3 (EV_ABS)
#     Event code 0 (ABS_X)
#       Value      890
#       Min          0
#       Max       1220
#       Fuzz         0
#       Flat         0
#       Resolution  12
#     Event code 1 (ABS_Y)
#       Value      389
#       Min          0
#       Max        721
#       Fuzz         0
#       Flat         0
#       Resolution  11
#     Event code 47 (ABS_MT_SLOT)
#       Value        0
#       Min          0
#       Max          4
#       Fuzz         0
#       Flat         0
#       Resolution   0
#     Event code 53 (ABS_MT_POSITION_X)
#       Value        0
#       Min          0
#       Max       1220
#       Fuzz         0
#       Flat         0
#       Resolution  12
#     Event code 54 (ABS_MT_POSITION_Y)
#       Value        0
#       Min          0
#       Max        721
#       Fuzz         0
#       Flat         0
#       Resolution  11
#     Event code 57 (ABS_MT_TRACKING_ID)
#       Value        0
#       Min          0
#       Max      65535
#       Fuzz         0
#       Flat         0
#       Resolution   0
#   Event type 4 (EV_MSC)
#     Event code 5 (MSC_TIMESTAMP)
# Properties:
#   Property  type 0 (INPUT_PROP_POINTER)
#   Property  type 2 (INPUT_PROP_BUTTONPAD)
N: 1A586757:00 06CB:8323 Touchpad
I: 0018 06cb 8323 0100
P: 05 00 00 00 00 00 00 00
B: 00 0b 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 01 00 00 00 00 00
B: 01 20 e5 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 02 00 00 00 00 00 00 00 00
B: 03 03 00 00 00 00 80 60 02
B: 04 20 00 00 00 00 00 00 00
B: 05 00 00 00 00 00 00 00 00
B: 11 00 00 00 00 00 00 00 00
B: 12 00 00 00 00 00 00 00 00
B: 14 00 00 00 00 00 00 00 00
B: 15 00 00 00 00 00 00 00 00
B: 15 00 00 00 00 00 00 00 00
A: 00 0 1220 0 0 12
A: 01 0 721 0 0 11
A: 2f 0 4 0 0 0
A: 35 0 1220 0 0 12
A: 36 0 721 0 0 11
A: 39 0 65535 0 0 0
```
Example from before when Fuzz was getting set by this rule: https://github.com/systemd/systemd/pull/9746

**Comment by whot** [comment]
https://github.com/systemd/systemd/pull/14839 should fix it, just had a [similar bugreport in libinput](https://gitlab.freedesktop.org/libinput/libinput/issues/442) and reproduced that so I strongly suspect yours is the same issue.

**Comment by mkhpalm** [comment]
Thanks, I replaced 60-evdev.rules on my system to test.

I still don't see fuzz with evemu-describe but I'm not getting the jitter that was previously resolved by adding it to 60-evdev.hwdb. So it seems fixed but I don't understand why. Was that udev rule affecting libinput hysteresis or something?

**Comment by whot** [comment]
right, so the whole thing is a tad complicated:
- ideally, the hardware or kernel driver set the fuzz to the correct value
- an `EVDEV_ABS` override may cause udev to change that fuzz
- a udev callout provided by libinput **reads** that fuzz and sets the `LIBINPUT_FUZZ_*` udev properties
- a different udev callout provided by libinput **sets** that fuzz to 0
- libinput uses `LIBINPUT_FUZZ_*` where available

The above only works when the order is correct and everything falls into place. Which is where the recent bugs came from.

And the sole reason for all this is that the kernel's handling of fuzz is bad so we need to set it to 0 so the kernel doesn't do any defuzzing. but libinput needs to know the fuzz value so it can do its own fuzz handling based on that value.

When everything works correctly `evemu` will always show a fuzz of zero. Use `libinput record`  instead, that shows the `LIBINPUT_FUZZ` properties as well.

**Comment by mkhpalm** [comment]
Makes sense, thanks for the explanation. I'll mark this closed with #14839 since its been working great for me.
