### ISSUE TITLE
System hangs at reboot/shutdown - Arch Linux

### ISSUE THREAD

**Issue by prescott66** [systemd/systemd#1615]
Hi.
When i try to shutdown/reboot arch linux, my system hangs to cca 90 seconds and then shutdown or reboot.
I have created bug report at arch's bugzilla, but there is no one, who can find the problem.
It looks like there is problem with systemd, because after update to v227 issue is fixed for few reboots, then is back.
PLEASE take a look at my logs in bug report. Maybe you will find problem:

https://bugs.archlinux.org/task/46709

**Comment by prescott66** [comment]
Now i get two jobs, that are waiting to stop at shutdown:
1.)Session c1 of user
2.)User manager for UID 1000

**Comment by dvdhrm** [comment]
If your session is not stopped at shutdown, it's very likely due to a program in your session being stuck. Please try logging out of your session and then check via a different user which programs are still running in that session. The systemd-cgls tool might come in handy.

**Comment by prescott66** [comment]
Here is my output of systemd-cgls command:

https://drive.google.com/file/d/0B7IVEEF2578ra2xGUFlzSDVmbkE/view?usp=sharing

**Comment by elkrejzi** [comment]
Apparently I'm not the only one with this issue. I ran into it too. See also

http://lists.freedesktop.org/archives/systemd-devel/2016-January/035619.html

Hope it gets resolved soon.

**Comment by Potomac** [comment]
I have the same bug,  a message "A stop job is running for Session c2 for user...." and a delay of 90 seconds,

 I use archlinux, systemd 229-3

**Comment by ongun-kanat** [comment]
Same as @Potomac here. Ver. 229-3

**Comment by diegoviola** [comment]
Same problem here on systemd 229 (archlinux)

**Comment by nagyf** [comment]
I have the same problem, systemd 229-3, arch linux. How can we check what program hangs?

**Comment by ongun-kanat** [comment]
@nagyf I don't think it's about a program refuses to terminate but systemd guys screwed user services things so that the user daemon of systemd fails to shutdown properly.

**Comment by ghost** [comment]
I approve, have similar problem on Arch with systemd 229-3. It's definately not connected with desktop manager but only systemd :( I'm waiting for fix couse right now almost every shutdown seems to be the weakest part of my system.

**Comment by miradozk** [comment]
I have same problem on Archlinux

**Comment by M-Tarasov** [comment]
I can also confirm the issue with systemd 229-3 on Arch Linux

**Comment by varlesh** [comment]
Confirm this

**Comment by ghost** [comment]
I have the same issue periodically (not each time). So i confirm this issue.

**Comment by manjarqo** [comment]
I confirm the issue too

**Comment by vk0novalov** [comment]
Confirm this issue too.

**Comment by lynxthecat** [comment]
Confirmed Archlinux. Something about "Session c1 of user" and hangs without shutting down properly. I can still Ctrl-Alt-F but otherwise unresponsive.

**Comment by GeorgeTG** [comment]
I have this issue too, but only on my desktop. Version 229-3 Arch Linux. Happens randomely at reboot/shutdown. "Session c2 of user" and i get a 90 sec timeout. Any way we can help or provide more info on this ?

**Comment by bunkbail** [comment]
I'm using systemd 229-3 Arch and I can confirm this. Its already continuing hanging on shutdown for about 2 weeks now. 

EDIT: A workaround here. I'm using Gnome, loging out current seesion before reboot/shutdown works for me. But it still doesn't remedy the problem.

**Comment by hexagonal-sun** [comment]
+1 on Arch Linux.

**Comment by firekage** [comment]
I can confirm it. In fact, i have this for a long time - Arch linux. What is strange, i don't have it on laptop machine and netbook machine. On all of them, i have nearly exacly the same programs, and apps but only on desktop i have conky.

BTW - this "bug" is not only true for 229-3. I had previous version with the same bug. 

Edit: after yesterday updates, my laptop and netbook machines have the same behaviour during shutdown.

**Comment by benjarobin** [comment]
I have done an analyze here https://github.com/systemd/systemd/issues/2691#issuecomment-202588915 And I think I found the root cause of the problem. The solution is not that easy, I have got an idea how to solve the problem (but I don't like it), I thing @poettering will have a better idea

**Comment by Potomac** [comment]
there is a workaround found by Ebiggers : 

just create a file "/etc/sysctl.d/50-coredump.conf" with the following contents:

kernel.core_pattern=core

then after a reboot this bug will never occur

**Comment by bakteria1** [comment]
Same issue here

**Comment by Potomac** [comment]
despite the workaround found by Ebiggers I still have the bug ( "a stop job for session C2 user" )

it's a random bug, for example it can occur after 10 reboots ( that's why I thought it was solved, we need to test with a lot of reboot/shutdown, the bug will be considered as solved only when no bug occurs after at least 10~15 reboots )

**Comment by varlesh** [comment]
Yes, random. Sometime reboot now, sometime reboot wait 90 sec. I kill plasmashell and other processes change DM (lightdm, sddm, slim) - this not solved problem.

**Comment by adeleglise** [comment]
Hi all,
I'm facing the same issue.

**Comment by molecularresearcher** [comment]
Thank you very much!
I did how Potomac described and the problem is solved.

ISamsung NC10 and Acer Aspire 7739 - and in both Arch Linux Kernel 4.4

**Comment by kyawthusoe45** [comment]
Systemd 215-17, Debian Jessie: confirm this.

**Comment by layus** [comment]
(Modified version of [an ArchLinux forum discussion](https://bbs.archlinux.org/viewtopic.php?pid=1619701#p1619701))

There appears to be two distinct issues with systemd 226-3 (and some other versions).

The first one is an issue with coredumps when killing applications, and is described at https://github.com/systemd/systemd/issues/2691.

The other is a bug with applications refusing to die, and is not an issue with systemd, but with the application itself. This is the case with conky for example.

@benjarobin has done a very good job at explaining the two failures in a series of comments.
(See https://github.com/systemd/systemd/issues/2691#issuecomment-202547898 and following).

Both cases are linked with the application reacting badly to the SIGTERM sent to to them when the system goes down.
- In the first case, the application crashes, but a bug with coredumps makes the system wait forever on the coredump service that can not start during shutdown. See https://github.com/systemd/systemd/pull/2993 for an attempt at fixing it.
- In the second case, the application ignores (or misses) the SIGTERM signal and continues running, unaware of the shutdown.
  As systemd cannot tell this situation from a service requiring more time to exit cleanly, it must wait untill the hard limit of 90s before killing the process with SIGKILL. Fixing the application is the way to go. For conky I have submitted https://github.com/brndnmtthws/conky/pull/233.

Of course, this does not explain why so many programs started to fail with systemd versions around 229-3. I think one explanation might be that systemd started to send SIGHUP on top of SIGTERM (as outlined in https://bbs.archlinux.org/viewtopic.php?pid=1617469#p1617469).

SIGHUP is often used to tell processes to reload their configuration. The processes failing to shutdown properly are probably not handling correctly a reload operation during their exit sequence (chromium ?).

For example, conky has a bug in its signal handling scheme since Nov 2005 (ironically, the commit is called "fix signal processing"), and possibly before, but this bug is only triggered by a SIGHUP cancelling a previous SIGTERM. As this issue arose only recently and for many programs at the same time, it is reasonable to think that the spurious SIGHUP comes from systemd.

**Comment by wfhu** [comment]
CentOS Linux release 7.2.1511 (Core)
3.10.0-327.4.4.el7.x86_64

systemd-sysv-219-19.el7.x86_64
systemd-libs-219-19.el7.x86_64
systemd-219-19.el7.x86_64

confirmed with this issue, I have to wait 20 minutes for xxx xxx

**Comment by Insomnium** [comment]
+1 on Arch

**Comment by evverx** [comment]
@layus

> As this issue arose only recently and for many programs at the same time, it is reasonable to think that the spurious SIGHUP comes from systemd.

I think the spurious SIGHUP comes from the kernel.

> Since the process group is orphaned when the parent terminates, and the process group contains a stopped process, POSIX.1 requires that every process in the newly orphaned process group be sent the hang-up signal (SIGHUP) followed by the continue signal (SIGCONT).

Try this:

``` c
# cat orphaned.c
#include <signal.h>
#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>

static void sig_hup(int signo) {
    printf("SIGHUP received, pid = %ld\n", (long)getpid());
}

static void sig_term(int signo) {
    printf("SIGTERM received, pid = %ld\n", (long)getpid());
}

int main(int argc, char *argv[]) {
    pid_t pid;

    pid = fork();
    if (pid < 0)
        return 1;

    if (pid > 0) {
        sleep(5);
        return 0;
    }

    signal(SIGHUP, sig_hup);
    signal(SIGTERM, sig_term);
    setpgid(0, 0);
    kill(getpid(), SIGSTOP);
    printf("Heya!\n");

        return 0;
}

# make orphaned

#  cat <<EOL >/etc/systemd/system/orphaned.service
[Service]
Type=oneshot
ExecStart=$(realpath orphaned)
EOL

# systemctl start orphaned.service

# journalctl -u orphaned -b
-- Logs begin at Mon 2016-05-16 10:54:57 UTC, end at Mon 2016-05-16 14:39:59 UTC. --
May 16 14:39:52 ubuntu-xenial systemd[1]: orphaned.service: Collecting.
May 16 14:39:54 ubuntu-xenial systemd[21305]: orphaned.service: Executing: /home/ubuntu/orphaned
May 16 14:39:54 ubuntu-xenial systemd[1]: Starting orphaned.service...
May 16 14:39:59 ubuntu-xenial orphaned[21305]: SIGHUP received, pid = 21306
May 16 14:39:59 ubuntu-xenial orphaned[21305]: Heya!
May 16 14:39:59 ubuntu-xenial systemd[1]: orphaned.service: Child 21305 belongs to orphaned.service
May 16 14:39:59 ubuntu-xenial systemd[1]: orphaned.service: Main process exited, code=exited, status=0/SUCCESS
May 16 14:39:59 ubuntu-xenial systemd[1]: orphaned.service: Changed start -> dead
May 16 14:39:59 ubuntu-xenial systemd[1]: orphaned.service: Job orphaned.service/start finished, result=done
May 16 14:39:59 ubuntu-xenial systemd[1]: Started orphaned.service.
May 16 14:39:59 ubuntu-xenial systemd[1]: orphaned.service: cgroup is empty
May 16 14:39:59 ubuntu-xenial systemd[1]: orphaned.service: Collecting.
```

**Comment by diegoviola** [comment]
Isn't this solved already? See #2691

Or it's a different issue?

**Comment by evverx** [comment]
@diegoviola , see https://github.com/systemd/systemd/issues/1615#issuecomment-209301790

**Comment by diegoviola** [comment]
@evverx Got it. I stopped seeing this issue after I switched to Firefox (from Chromium).

**Comment by layus** [comment]
@evverx Thanks for explaining this. It seems that you are right, SIGHUP is sent by the kernel, not systemd. This is quite a relief regarding my programming skills, because I could not find the offending line in systemd codebase :-).

Meanwhile, the issue remains. While we know that applications mishandling signals are the real offenders here, we do not know why it started breaking around v229 of systemd, nor if systemd is responsible for the change of behavior.
Of course, the bug is in the applications themselves (apparently conky and chromium) but the fact is that that bug never revealed itself before, so something must have changed in between. What could it be ? 

All I can think of is a change in the order in which applications are killed. Systemd is quite aggressive when killing all the processes. It sends SIGSTOP to everyone without trusting the process hierarchy to do its job. Or maybe a change in cgroups implementation by the kernel;

The strange thing is, I do not observe the "a stop job is running for..." message anymore, but systemd still indirectly waits for my running conky when trying to unmount /home, and so for 90 seconds.

**Comment by chadmiller** [comment]
If 

$ echo core |sudo tee /proc/sys/kernel/core_pattern

makes it not hang, then it's something funny. SIGHUP on chromium/chrome could cause a crash of some child, which causes systemd to run something when it's trying to shut down. I expect systemd to be more resilient, but perhaps there is some new edge case.

**Comment by diegoviola** [comment]
I can confirm `echo core |sudo tee /proc/sys/kernel/core_pattern` makes it not hang when using Chromium.

**Comment by diegoviola** [comment]
After I shutdown/reboot with /proc/sys/kernel/core_pattern being set to `|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %e` it hangs again.

**Comment by chadmiller** [comment]
@diegoviola 
I think you should fabricate some shell script that writes its parameters to a file. Then change the core pattern to "|/usr/local/bin/diegos-systemd-shutdown-test %P %u %g %s %t %c %e"
(You see what to name the script now, yes?)

Steps:
Capture the results of "ps axwww" in a file.
Reboot to get the crash info logged to another file.
Look in the shutdown test output file. Compare the process listing. Paste results here.

**Comment by benjarobin** [comment]
This bug is not already solved in git ? See https://github.com/systemd/systemd/issues/2691 ?

**Comment by diegoviola** [comment]
@chadmiller I've used this script:

``` bash
#!/bin/bash

echo $1 >> /var/tmp/systemd-core-handler
echo $2 >> /var/tmp/systemd-core-handler
echo $3 >> /var/tmp/systemd-core-handler
echo $4 >> /var/tmp/systemd-core-handler
echo $5 >> /var/tmp/systemd-core-handler
echo $6 >> /var/tmp/systemd-core-handler
echo $7 >> /var/tmp/systemd-core-handler

ps axwww >> /var/tmp/systemd-core-handler
```

And here is the output:

```
675
1000
1000
6
1463430870
18446744073709551615
D-Bus
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 /sbin/init
    2 ?        S      0:00 [kthreadd]
    3 ?        S      0:00 [ksoftirqd/0]
    4 ?        S      0:00 [kworker/0:0]
    5 ?        S<     0:00 [kworker/0:0H]
    6 ?        S      0:00 [kworker/u8:0]
    7 ?        S      0:00 [rcu_preempt]
    8 ?        S      0:00 [rcu_sched]
    9 ?        S      0:00 [rcu_bh]
   10 ?        S      0:00 [migration/0]
   11 ?        S      0:00 [watchdog/0]
   12 ?        S      0:00 [watchdog/1]
   13 ?        S      0:00 [migration/1]
   14 ?        S      0:00 [ksoftirqd/1]
   15 ?        S      0:00 [kworker/1:0]
   16 ?        S<     0:00 [kworker/1:0H]
   17 ?        S      0:00 [kdevtmpfs]
   18 ?        S<     0:00 [netns]
   19 ?        S      0:00 [khungtaskd]
   20 ?        S<     0:00 [writeback]
   21 ?        SN     0:00 [ksmd]
   22 ?        SN     0:00 [khugepaged]
   23 ?        S<     0:00 [crypto]
   24 ?        S<     0:00 [kintegrityd]
   25 ?        S<     0:00 [bioset]
   26 ?        S<     0:00 [kblockd]
   27 ?        S<     0:00 [devfreq_wq]
   28 ?        S      0:00 [kworker/0:1]
   29 ?        S      0:00 [kworker/1:1]
   30 ?        S      0:00 [kswapd0]
   31 ?        S<     0:00 [vmstat]
   40 ?        S<     0:00 [kthrotld]
   44 ?        S<     0:00 [ipv6_addrconf]
   45 ?        S<     0:00 [deferwq]
   46 ?        S      0:00 [kworker/u8:1]
   83 ?        S<     0:00 [ata_sff]
   84 ?        S      0:00 [kworker/0:2]
   85 ?        S      0:00 [scsi_eh_0]
   86 ?        S<     0:00 [scsi_tmf_0]
   87 ?        S      0:00 [scsi_eh_1]
   88 ?        S<     0:00 [scsi_tmf_1]
   89 ?        S      0:00 [kworker/u8:2]
   90 ?        S      0:00 [scsi_eh_2]
   91 ?        S<     0:00 [scsi_tmf_2]
   92 ?        S      0:00 [scsi_eh_3]
   93 ?        S<     0:00 [scsi_tmf_3]
   94 ?        S      0:00 [kworker/u8:3]
   95 ?        S      0:00 [kworker/u8:4]
   96 ?        S      0:00 [kworker/u8:5]
   97 ?        S      0:00 [kworker/1:2]
   98 ?        S      0:00 [kworker/1:3]
   99 ?        S      0:00 [kworker/1:4]
  100 ?        S<     0:00 [bioset]
  101 ?        S<     0:00 [bioset]
  103 ?        S<     0:00 [kworker/1:1H]
  104 ?        S<     0:00 [kworker/0:1H]
  125 ?        S      0:00 [jbd2/sda3-8]
  126 ?        S<     0:00 [ext4-rsv-conver]
  163 ?        Ss     0:00 /usr/lib/systemd/systemd-journald
  172 ?        S      0:00 [kworker/0:3]
  201 ?        Ss     0:00 /usr/lib/systemd/systemd-udevd
  217 ?        S<     0:00 [acpi_thermal_pm]
  224 ?        S<     0:00 [kvm-irqfd-clean]
  244 ?        Ssl    0:00 /usr/lib/systemd/systemd-timesyncd
  250 ?        Ss     0:00 /usr/lib/systemd/systemd-logind
  262 ?        S<     0:00 [cfg80211]
  265 ?        Ss     0:00 login -- diego
  341 tty1     Ds     0:00 -bash
  349 tty1     S+     0:00 /bin/sh /usr/bin/startx
  371 tty1     S+     0:00 xinit /home/diego/.xinitrc -- /etc/X11/xinit/xserverrc :0 vt1 -auth /tmp/serverauth.GHrIq7WPyC
  372 tty1     Z      0:01 [Xorg] <defunct>
  416 tty1     Z      0:00 [i3] <defunct>
  504 ?        Ds     0:00 -bash
  511 ?        Z      0:00 [weechat] <defunct>
  522 ?        Ds     0:00 -bash
  528 ?        S      0:00 su -
  530 ?        Z      0:00 [bash] <defunct>
  675 ?        Dl     0:09 /usr/lib/chromium/chromium
 1037 ?        Ds     0:00 -bash
 1356 ?        Ss     0:00 /bin/bash /usr/bin/mkinitcpio -A sd-shutdown -k none -c /dev/null -d /run/initramfs
 1361 ?        S      0:00 [kworker/0:4]
 1369 ?        S      0:00 [kworker/0:5]
 1402 ?        D      0:00 install -Dm755 /usr/lib/systemd/systemd-shutdown /run/initramfs/shutdown
 1403 ?        S      0:00 /bin/bash /root/diego-systemd-shutdown-test.sh 675 1000 1000 6 1463430870 18446744073709551615 D-Bus thread
 1404 ?        R      0:00 ps axwww
```

It doesn't hang with my script, but when `|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %e` is set to `/proc/sys/kernel/core_pattern` it hangs every time.

So maybe it's just the same bug from #2691?

**Comment by diegoviola** [comment]
@benjarobin I'm still on 229, I haven't tested git yet.

Can someone try and confirm please?

**Comment by layus** [comment]
@evverx Some aspects are still very strange to me.
i3bar has conky as a child. During the exit sequence i3bar waitpid()'s on conky. So presumably this unchecked waitpid return EINTR and does not behave as expected, right ?
Don't you also think that these poor programs receive too many signals at once ?

**Comment by evverx** [comment]
@layus 

> Don't you also think that these poor programs receive too many signals at once ?

Well, I don't know how your service works.
But you can reproduce that "many signals at once":

``` sh
-bash-4.3# systemctl cat handle-and-stop --no-pager
# /etc/systemd/system/handle-and-stop.service
[Service]
ExecStart=/bin/bash -x -c 'trap "echo CONT" CONT; trap "echo TERM" TERM; trap "echo HUP" HUP; trap "echo USR1" USR1; trap "echo USR2" USR2; while :; do kill -STOP $$$$; done'

-bash-4.3# systemctl start handle-and-stop

-bash-4.3# main_pid=$(systemctl show --property=MainPID --value handle-and-stop)

-bash-4.3# for s in TERM HUP USR1 USR2; do kill -$s $main_pid; done

-bash-4.3# grep -i sigq /proc/$main_pid/status
SigQ:   4/7959

-bash-4.3# systemctl stop handle-and-stop
...HANGS...

-bash-4.3# journalctl -u handle-and-stop -b --no-hostname
May 16 22:40:02 systemd[1]: Started handle-and-stop.service.
May 16 22:40:02 bash[104]: + trap 'echo CONT' CONT
May 16 22:40:02 bash[104]: + trap 'echo TERM' TERM
May 16 22:40:02 bash[104]: + trap 'echo HUP' HUP
May 16 22:40:02 bash[104]: + trap 'echo USR1' USR1
May 16 22:40:02 bash[104]: + trap 'echo USR2' USR2
May 16 22:40:02 bash[104]: + :
May 16 22:40:02 bash[104]: + kill -STOP 104
May 16 22:40:02 systemd[1]: handle-and-stop.service: Failed to send unit change signal for handle-and-stop.service: Connection reset by peer
May 16 22:42:28 systemd[1]: handle-and-stop.service: Trying to enqueue job handle-and-stop.service/stop/replace
May 16 22:42:28 systemd[1]: handle-and-stop.service: Installed new job handle-and-stop.service/stop as 392
May 16 22:42:28 bash[104]: ++ echo HUP
May 16 22:42:28 bash[104]: HUP
May 16 22:42:28 bash[104]: ++ echo USR1
May 16 22:42:28 bash[104]: USR1
May 16 22:42:28 bash[104]: ++ echo USR2
May 16 22:42:28 bash[104]: USR2
May 16 22:42:28 bash[104]: ++ echo TERM
May 16 22:42:28 bash[104]: TERM
May 16 22:42:28 bash[104]: ++ echo CONT
May 16 22:42:28 bash[104]: CONT
May 16 22:42:28 bash[104]: + :
May 16 22:42:28 bash[104]: + kill -STOP 104
May 16 22:42:28 systemd[1]: handle-and-stop.service: Enqueued job handle-and-stop.service/stop as 392
May 16 22:42:28 systemd[1]: handle-and-stop.service: Changed running -> stop-sigterm
May 16 22:42:28 systemd[1]: Stopping handle-and-stop.service...
May 16 22:43:58 systemd[1]: handle-and-stop.service: State 'stop-sigterm' timed out. Killing.
May 16 22:43:58 systemd[1]: handle-and-stop.service: Changed stop-sigterm -> stop-sigkill
May 16 22:43:58 systemd[1]: handle-and-stop.service: Child 104 belongs to handle-and-stop.service
May 16 22:43:58 systemd[1]: handle-and-stop.service: Main process exited, code=killed, status=9/KILL
May 16 22:43:58 systemd[1]: handle-and-stop.service: Changed stop-sigkill -> failed
May 16 22:43:58 systemd[1]: handle-and-stop.service: Job handle-and-stop.service/stop finished, result=done
May 16 22:43:58 systemd[1]: Stopped handle-and-stop.service.
May 16 22:43:58 systemd[1]: handle-and-stop.service: Unit entered failed state.
May 16 22:43:58 systemd[1]: handle-and-stop.service: Failed with result 'signal'.
May 16 22:43:58 systemd[1]: handle-and-stop.service: cgroup is empty
```

Anyway, try to reproduce your problem and file a new issue.
Also consider contacting the systemd mailing list: https://lists.freedesktop.org/mailman/listinfo/systemd-devel

@diegoviola 

> Can someone try and confirm please?

https://github.com/systemd/systemd/issues/2691#issuecomment-215924909
https://github.com/systemd/systemd/pull/3148#issuecomment-215694998

**Comment by Dawnflash** [comment]
Confirmed on Arch Linux, kernel 4.5.4., SystemD 229 with Cinnamon and Gnome DEs.
The issue is hard to track as no journal logs are made and TTYs are killed, so system is unmanageable at that point. Moreover it only occurs sporadically, reproduction at will seems impossible.
Also, the issue appears right after DBus daemon dies (not sure if relevant though).

**Comment by maher-hanna** [comment]
I hava this problem also but it apeares only in kde desktop not in gnome.
Kernel 4.5.4 , Systemd 229

**Comment by startas** [comment]
Ubuntu 16.04 also has this bug.

**Comment by egriffith** [comment]
This bug is the same as: https://github.com/systemd/systemd/issues/2691 , no? If so, this is thought to be fixed as of v230 and should be closed as well.

**Comment by diegoviola** [comment]
I'm still having this issue on Arch Linux (systemd 230-3) but I don't know if systemd-coredump is to blame or something else.

Anyone else?

**Comment by diegoviola** [comment]
I was using Firefox this time, I simply typed `poweroff` and got the 90s timeout.

**Comment by Potomac** [comment]
@diegoviola : you can try to "mask" systemd-coredump@.service with systemd 

systemctl mask systemd-coredump@.service

and then just create a file "/etc/sysctl.d/50-coredump.conf" with the following contents:

kernel.core_pattern = /tmp/core-%e-%s-%u-%g-%p-%t

tested with archlinux 64 bits with success

**Comment by diegoviola** [comment]
@Potomac Thanks, but I thought the issue was already fixed in v230?

**Comment by japhir** [comment]
I'm running 230-3 on Arch and while the above fix has some effect, the issue is not resolved for me.

It used to be a 1:30 wait for /run/user/1000 to unmount or something similar, now I get a message saying that a stop job is running for [tlp](https://wiki.archlinux.org/index.php/TLP), but this doesn't hang for the full 1:30 but just for ~10 seconds. This might have become a different issue though.

**Comment by poettering** [comment]
I'll close this bug now. The coredump issue has been fixed, and this bug was mostly about that.

of course, timeouts may be hit due to a variety of causes during shutdown. For example @japhir's issue is probably within his "tlp" service.

As it doesn't make sense to track issues with such a variety of services in a single bug I will close this now. If the issue remains with specific services, and it is clear that this is not a bug in the individual service but in systemd, then please open new, separate bugs for that.

**Comment by diegoviola** [comment]
I've just started using chromium again and I got the 90s timeout on shutdown again. Are you sure the problem with systemd-coredump is fixed? How can we debug this?

**Comment by diegoviola** [comment]
I've just started using chromium again and I got the 90s timeout again, any ideas?

**Comment by benjarobin** [comment]
@diegoviola This bug report is closed, see poettering comment... And this is highly probable that the bug is inside chromium

**Comment by diegoviola** [comment]
@benjarobin OK I've disabled "Continue running background apps when Chromium is closed" in chromium and that seems to have helped.

Sorry for mixing issues on this thread.

**Comment by diegoviola** [comment]
I can confirm that after disabling "Continue running background apps when Chromium is closed" under Chromium' System makes this issue go away.

**Comment by berndbb** [comment]
I have found no reason why my shutdown once hangs like described here and then with another session the PC is shut down in only a few seconds -
but since I don't use Cromium I can't consider this the (only) reason. Maybe someone somewhere else finds a clue ...

**Comment by diegoviola** [comment]
I've submitted this bug to chromium, if someone is interested to follow up here:

https://bugs.chromium.org/p/chromium/issues/detail?id=619418

Thanks.

**Comment by kilbith** [comment]
I didn't bother to read the whole discussion, just want to inform that I suffer from the same bug with systemd 230 on archlinux : 

```
Started generate shutdown-ramfs
A stop job is running for User Manager for UID 1000 (1min30)
```

In any case, 90s is way too long. I'm forced to brutally power-off my computer when it happens (quite oftenly the case).

**Comment by kyawthusoe45** [comment]
FYI, in my case, Debian Jessie and systemd 215, installing watchdog solved the problem.

**Comment by charleslouis** [comment]
On fresh install of ubuntu 16.04 :

I had either a "a stop job is running for session c2 of user XYZ" /1min30 or a total hang when pressing ESC on shutdown/reboot splash screen.
Several tests showed that deactivating Private Internet Access VPN avoided being stuck at shutdown splash screen.

**Comment by kyawthusoe45** [comment]
Debian Jessie with backported systemd 230-7~bpo8+2, this bug is found, again.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822996

"A STOP JOB IS RUNNING FOR AVAHI MDNS/DNS/SD STACK"

It eventually completed. It occurred intermittently.

**Comment by smcv** [comment]
> this bug is found, again

No it isn't. The (vague) title of this bug is a symptom, not a cause. If you see the same symptom for a different reason, nothing that has been said on this bug is going to help you.

In your case, the stop job that is taking a long time is Avahi, which is not the same thing as any of the other shutdown hangs discussed on this bug.

**Comment by kyawthusoe45** [comment]
@smcv It didn't not always show,  "A stop job is running for Avahi mDNS/DNS-SD Stack". It sometimes showed, "A stop job is running for session c2 of user ... (1min 30s).".

**Comment by nettlebay** [comment]
Me too with Ubuntu 16.04. Seems to be caused by systemd. I installed Watchdog for a couple of days but I'm not sure what it does. It's better but not perfect.

**Comment by ghost** [comment]
I have this problem with Mint 18.1. It's driving me crazy. I've tried all sorts of workaround and none of them - at least fully - work. For I still have the problem, at least when using ethernet as against wifi. The problem means I have to hard reset my machine, which can't be good for it. This problem takes us back to the bad old days of Linux when basically nothing worked without hacks and prayer.

EDIT: It seems no-one is assigned to this bug. Why?

**Comment by grossws** [comment]
I have similar issue on ArchLinux (linux 4.11.2-1-ARCH, systemd 232-8, plamsa-desktop 5.9.5-1, sddm 0.14.0-2). 

It seems that either `kded5` or `sddm` is an offending process. On shutdown sequence `sddm` tries to stop both X server and plasma/kde (which is run under `sddm-helper`) and X stops before `kded5` which somehow leads to latter to ignore SIGTERM.

```
May 30 00:35:05 wahnsinn sddm[687]: Display server stopping...
May 30 00:35:05 wahnsinn sddm-helper[5686]: [PAM] Starting...
May 30 00:35:05 wahnsinn sddm-helper[5686]: [PAM] Authenticating...
May 30 00:35:05 wahnsinn sddm-helper[5686]: [PAM] returning.
May 30 00:35:05 wahnsinn systemd[1]: Stopped Manage swap spaces on zram, files and partitions..
May 30 00:35:07 wahnsinn sddm[687]: Display server stopped.
May 30 00:35:07 wahnsinn sddm[687]: Running display stop script  "/usr/share/sddm/scripts/Xstop"
May 30 00:35:07 wahnsinn sddm[687]: QProcess: Destroyed while process ("/usr/lib/sddm/sddm-helper") is still running.
May 30 00:35:07 wahnsinn systemd[1]: Stopped Simple Desktop Display Manager.
May 30 00:36:32 wahnsinn systemd[1]: session-c2.scope: Stopping timed out. Killing.
May 30 00:36:32 wahnsinn systemd[1]: session-c2.scope: Killing process 1373 (kded5) with signal SIGKILL.
May 30 00:36:32 wahnsinn systemd[1]: Stopped Session c2 of user gross.
May 30 00:36:32 wahnsinn systemd[1]: session-c2.scope: Unit entered failed state.
```

See also [FS#46585 (Arch bugtracker)](https://bugs.archlinux.org/task/46585)

**Comment by osho741** [comment]
My system with Openbox/Tint2  on kernel 4.11.2-1_ARCH just freezes  when doing reboot from terminal.  If I roll back to 4.10.17 it is able to reboot fine.

**Comment by smcv** [comment]
There are many reasons why a system might hang during reboot/shutdown. It is a symptom, not a cause. If you do not have evidence that the root cause of your system hang is the same as the root cause of the system hang experienced by the initial reporter of this issue, then please do not reply to this issue.

If you see the same symptom for a different reason, then nothing that has been said on this issue report is going to help you, and anything you say on this issue report is just going to make it even more confusing to a reader.

Please contact your distribution vendor (Arch Linux, Ubuntu/Canonical, Mint, etc.) for initial support. If you have evidence that your issue is **caused by** systemd (not to be confused with a bug merely **involving** systemd) then you can report that as a **separate** bug, with a more specific description based on that evidence.

For example, the details provided by @grossws seem to indicate a bug in either kded5, sddm, or the systemd units provided with sddm. That is probably not a bug in systemd and will probably not be fixed by changing systemd, so this is the wrong place to ask for a solution.

> It seems no-one is assigned to this bug. Why?

Here are some reasons why assigning a developer to work on this issue would be counterproductive:

1. Because the issue was closed in 2016. Closed issues are not worked on. If you have evidence of a bug in systemd, please open a new issue to represent it, with a more specific title and description than this one, and do not mix it up with everything else that has been said in this thread.

2. Because there does not seem to be any particular evidence that any of the various problems that different people are experiencing are bugs in systemd, as opposed to bugs in particular services that they are running. Bugs in pieces of software outside systemd are not solved by changing systemd, they are solved by changing the other piece of software.

3. Because even if some or all of the problems reported in this comment thread were caused by bugs in systemd, no single volunteer is going to want to take responsibility for fixing a series of different bugs (some of which might be bugs in systemd, some of which are almost certainly not) that are getting mixed into this issue thread. That would be an endless task - by the time one had been solved, another would likely have been reported, because the title of this issue thread is so general that it could describe all sorts of different root causes. Again, if you have evidence of a bug in systemd, please open a new issue to represent it, and do not mix it up with everything else that has been said in this thread.

**Comment by ghost** [comment]
Dear @smcv 

- Thank you for your explanations.

- A combination of several bits of hackery seem to have solved the problem for me. If the problem recurrs I will open a new bug report.

- It seems to me that (contrary to your point 2) the number of contributions of this thread is _prima facie_ evidence of a problem - perhaps _qua_ full-blown bug, perhaps _qua_ something that is encouraging software writers to code their services wrongly - with systemd.

**Comment by audiomuze** [comment]
got the same thing happening here, every time  shut down my laptop. Running Arch 4.11.7-1-ARCH

**Comment by smcv** [comment]
@audiomuze Please contact your distribution vendor (in your case Arch Linux?) for initial support. If there is evidence that your issue is caused by systemd (and not a result of a bug in some other component), please open a separate bug report with full details of the symptoms and evidence, including relevant log messages and version numbers.

The title of this issue is a symptom, not a cause; there are many things that could be causing it (some of them would be systemd bugs, and some of them would not). If everyone whose system hangs during shutdown keeps adding comments to this closed issue report, then we are never going to be able to disentangle which bug reporter was suffering that symptom as a result of which root cause.

@poettering, perhaps it would be worthwhile to close the comments on this issue?

**Comment by poettering** [comment]
@poettering, perhaps it would be worthwhile to close the comments on this issue?

Uh, I am a bit afraid of the reddit firestorm this would likely result in...

**Comment by cxpreng** [comment]
@smcv So basically you hear hoofbeats and think zebras

**Comment by adrinjalali** [comment]
@smcv  If several people, many of whome are tech-savy enough to have installed and working with archlinux, and wait and read the message they see on their screen, and then come back and search for the issue tying to report/fix/help in that regard, are commenting on the same issue here because of the same "symptom" they observe, maybe you should open an issue for your piece of software to give a more helpful message.

**Comment by tsdh** [comment]
Same problem on a current Arch laptop (since ages, I think), i.e., it is waiting for a stop job of User Manager for UID 1000 (which is my user).  But now I had the time to debug the issue.  After my user (with uid 1000) logged out, I checked `systemd-cgls` and there's still

```
│ └─user-1000.slice
│   └─user@1000.service
│     ├─init.scope
│     │ ├─2140 /usr/lib/systemd/systemd --user
│     │ └─2141 (sd-pam)
│     └─tracker-store.service
│       └─2471 /usr/lib/tracker/tracker-store
```

So do I see it correctly that in my case, GNOME's desktop search (Tracker) is the faulty process which doesn't properly terminate when being sent a SIGTERM followed by a SIGHUP and I should report a bug for that?

**Comment by silliwretep** [comment]
This is caused by a kernel driver failing on shutdown.
The culprit can be found by methodically using modprobe -r   to remove a specific driver and then shutting down.
If removing that driver before shutdown allows the system to proceed normally, that driver is likely the culprit.

If you have custom drivers on the system, the shutdown script for that driver system should contain lines to modprobe -r  the drivers used prior to shutdown or reboot. This ensures the bad driver is unloaded before shutdown.

It may be good to somehow get test of what driver is currently being closed/called for debug purposes.  Anyone know if  that possible with kernel debugging enabled?

**Comment by kareliot** [comment]
@tsdh thanks for this. I have the exact same thing showing up when running systemd-cgls after logging out with user uid 1000.
So tracker does seem to cause the problem. Have you found out anything else?

**Comment by tsdh** [comment]
@kareliot Nope, nothing new from my side.  Didn't have the time to debug any more, and since the issue is just on one machine, it hasn't bothered me enough.

**Comment by ulises-jeremias** [comment]
I have same problem on Archlinux

**Comment by kareliot** [comment]
I have opened a bug report about the tracker.store.system issue in the gnome bug tracker:
https://bugzilla.gnome.org/show_bug.cgi?id=793027#c2
Someone has already started debugging, but I have not had time to see if I can reproduce their findings.

**Comment by CottonEaster** [comment]
I have the same problem - but on Linux Mint.

**Comment by stueja** [comment]
For me (Arch Linux, Gnome desktop) the issue resolves whenever I deactivate `Settings > Sharing > Remote Login`. Hope that helps?

**Comment by CottonEaster** [comment]
Thanks stueja, but my own workaround is to allow my Internet connection to persist after log off.

**Comment by FabianInostroza** [comment]
@kevinxucs It seems to be related to dleyna-renderer, I found the following on my shutdown log:
```
jun 02 04:34:29 debian systemd[1862]: dbus.service: State 'stop-final-sigterm' timed out. Killing.
jun 02 04:34:29 debian systemd[1862]: dbus.service: Killing process 14329 (dleyna-renderer) with signal SIGKILL.
jun 02 04:34:29 debian systemd[1862]: dbus.service: Killing process 14330 (gmain) with signal SIGKILL.
jun 02 04:34:29 debian systemd[1862]: dbus.service: Failed with result 'timeout'.
```
Also found the following bug reports: 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=868951
https://github.com/intel/dleyna-renderer/issues/164

You could try to uninstall dleyna-renderer and see if the problem goes away.

**Comment by kevinxucs** [comment]
@FabianInostroza Thanks for pointing me the bug, but I am not sure I have dleyna-render installed.

The solution for me is to switch from gdm to lightdm, so I guess something related with gdm

**Comment by chuchana** [comment]
In my case, this problem was caused by a service that was not required.

Here's how I fixed it. Maybe it can help someone:

1. Find the problem: `journalctl | grep -i shutdown`
➡︎ […] `systemd[1]: Failed to start Disable brcmfmac kernel module ` […]
2. The driver is not installed: `lsmod | grep brcmfmac` returns nothing
3. Find the service: `systemctl list-unit-files | grep brcm`
➡︎ `remove-brcmfmac.service                    enabled`
4. Disable the service: `systemctl disable remove-brcmfmac.service`
5. Find the file location: `systemctl status remove-brcmfmac.service`
➡︎ […] `Loaded: loaded (/etc/systemd/system/remove-brcmfmac.service;` […]
6. Delete the file: `sudo rm /etc/systemd/system/remove-brcmfmac.service`

**Comment by WhyNotHugo** [comment]
From what I've managed to figure out via the documentation on `DefaultTimeoutStopSec=` and `TimeoutStopSec=`, the typical cause for many seems to be that if any single application you're running does not exit on `SIGTERM`, systemd will wait for it 90 seconds before killing it.

This makes sense if you want to be conservative or know you have applications that take a while to shut down (e.g.: an application server, or a large database, and many other examples I can't think of right now). On a usual desktop environment, _nothing_ takes more than 2-3 seconds to exit cleanly. Especially if it's just a lone desktop with no network mounts or alike.

It would seem that hitting this delay is an **extremely** common scenario based on reports here, and the amount of almost-identical reports found of distribution forums and support channels. However, very few have managed to figure out what's causing the issue.

The real issue here seems that there's no clear way to debug this or gain visibility on it.  Yes, some application is misbehaving and refusing to exit, but _which_ application? How do we figure that out? (In all honesty, there probably is a way, but it's not being documented/communicated in a a way that any of the affected).

---

On my end, I've fixed this by adding this droppin `/etc/systemd/system.conf.d/kill-fast.conf`:

```ini
# By default, when a service is told to stop, systemd waits 90s before SIGTERM.
#
# This might make perfect sense for servers where a database might be slow to
# shut down, and scenarios like that. However, on a simple desktop, it's
# senseless. Anything that takes over 2s to stop is just misbehaving, my
# computer needs to turn off when told to.

[Manager]
DefaultTimeoutStopSec=3s
```

Note that if any of your applications takes more than 3s to exit cleanly, this _will_ result in data loss. You should have an idea of what you're running. Push it up to `10s` if you're not sure (though waiting 10 seconds for a system power off is still too long IMHO).

---

This workaround works, but, as an end-user of systemd, I'd appreciate a bit more clarity on how we're supposed to debug this.

Earlier on this thread it was mentioned we should go to distribution support channels -- those channels are just the community trying to help each other out, but we're all still just users of systemd, and none of us know how to debug this. This is evident by the overwhelming amount of re-reports of this same issue piling up since 2014. I've gone through dozens of them over the years, all of them unconsclusive.

```
A stop job is running for Session XXX
```

Would it be too much to ask for the actual job to be shown here? Rather than display `a job`, might it be possible to display `job <service-name>` or `job <process-name>`?

**Comment by smac89** [comment]
Just wanted to add my two-cents to this.

Firstly, it really helps to follow the guide suggested by this https://github.com/systemd/systemd/issues/1615#issuecomment-489818681.

So after I was able to finally reboot, I immediately ran the command:

```
journalctl --boot=-1 --reverse
```

And this is the output (shortened for brevity):
```
Dec 05 13:43:53 ArcoB systemd[1]: Stopping User Manager for UID 1000...
Dec 05 13:43:53 ArcoB systemd[1]: Stopping User Login Management...
Dec 05 13:43:53 ArcoB systemd[1]: Stopped Session 2 of user chigozirim.
Dec 05 13:43:53 ArcoB systemd[1]: session-2.scope: Failed with result 'timeout'.
Dec 05 13:43:53 ArcoB systemd[1]: session-2.scope: Killing process 3114 (rygel) with signal SIGKILL.
Dec 05 13:43:53 ArcoB systemd[1]: session-2.scope: Stopping timed out. Killing.
Dec 05 13:42:26 ArcoB systemd[1]: Stopped Optimus Manager Commands Daemon.
Dec 05 13:42:26 ArcoB systemd[1]: optimus-manager.service: Succeeded.
Dec 05 13:42:26 ArcoB python3[1026]: [6030535] INFO: Goodbye !
Dec 05 13:42:26 ArcoB python3[1026]: [6030535] INFO: Closing and removing the socket...
Dec 05 13:42:26 ArcoB python3[1026]: [6030535] INFO: Process stop requested
...
Dec 05 13:42:23 ArcoB systemd[1]: Stopping Session 2 of user chigozirim.
Dec 05 13:42:23 ArcoB sudo[44571]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
Dec 05 13:42:23 ArcoB sudo[44571]: chigozirim : TTY=pts/0 ; PWD=/home/chigozirim ; USER=root ; COMMAND=/usr/bin/reboot
```

Notice the difference in time between the bottom and the top entry? And right in the middle we see the reason: Some user process (`rygel`) is being started and not being stopped for some reason.

It was kinda weird because after killing this process, I restarted and tried to kill it with a simple `pkill -TERM rygel` command and that worked, so I'm not sure how systemd is trying to kill this process and not succeeding.

In retrospect, it may have been caused by my blunder because `rygel` is being auto-started as a desktop application, instead of using the systemd service that it came with. I have corrected this now and removed the auto-start file, so hopefully that fixes it. I will update this comment if this doesn't work.

---

HTH

**Comment by OneOfOne** [comment]
It's almost year 2022, the world is on fire, a deadly comet is heading towards earth and Bruce Willis joined NASA to help stop it, covid is still alive and so this bug is still triggering without any useful information in the log.

systemd 249.7, arch linux.

Arch

**Comment by JimPix1** [comment]
It sure is weird that this problem has been around for 7 years (and it's quite a large problem) and the systemd devs still haven't bothered fixing it..

**Comment by vcaputo** [comment]
After waiting the 90 seconds for a stalled shutdown to finish, on the next boot perform the aforementioned `sudo journalctl --boot=-1 --reverse`.

Personally I always find useful information about what held up the shutdown, and it's usually some non-systemd process refusing to exit despite receiving SIGTERM.

There doesn't appear to be a systemd bug here, if you're experiencing hangs on shutdown without anything in the logs on the next boot, open a new issue.
