### ISSUE TITLE
systemd-analyze blame shows different time values at every invocation

### ISSUE THREAD

**Issue by lhoenig** [systemd/systemd#16415]
**systemd version the issue has been seen with**
> 245

**Used distribution**
 > None, compilation based on LFS 9.1-systemd-rc1 instructions

**Expected behaviour you didn't see**
 > systemd-analyze blame should show the same times at every run

**Unexpected behaviour you saw**
 > different time values at each run, or more likely a different (random) offset for each run. video of behaviour: https://asciinema.org/a/dho8SUmuD3z7k3YcsLj2OvHVY

**Steps to reproduce the problem**
I'm not sure how I triggered this behaviour. I remember it working perfectly beforehand. The only thing out of the ordinary I did before I noticed the behavior was trying to run `bootctl install` to try to overwrite an old version of systemd-boot that was installed by an Arch partition running systemd 244. That could have something to do with it, maybe.

**Comment by lhoenig** [comment]
Fixed by a successful `bootctl install` from the affected partition. Still shouldn't happen.

**Comment by poettering** [comment]
This is very weird. Any chance you can still get "systemctl show -a" on the affected configuration? Or given that the "bootctl install" fixed it I figure that's not possible anymore (in which case we should just close this, as this isn't actionable anymore.

**Comment by poettering** [comment]
Two ideas what might happen: something reenqueues the initial transaction all the time, or something is wrong with the boot timestamp determination (for example with deriving the wallclock timestamp of kernel initialization from the monotonic clock or so)

**Comment by lhoenig** [comment]
Thank you for taking a look! I am unable to reproduce the behaviour at this moment. I think it was first triggered when from systemd-245, I tried to update/replace systemd-244 EFI boot binaries. It failed, because I didn't have `gnu-efi` installed. What is interesting maybe, is that when I first tried to run `bootctl install` it failed with some `File not found` error, and I got to the weird state. Now, `bootctl install` will not attempt to copy the missing files when I don't have `gnu-efi` installed.
Anyways, closing this for now. Will reopen if I find out something new or how to reproduce.
