### ISSUE TITLE
systemd-timesyncd: on DNS failure reduce poll interval

### ISSUE THREAD

**Issue by vinc17fr** [systemd/systemd#16529]
**systemd version the issue has been seen with**
> 245.6

**Used distribution**
 > Debian/unstable

**Expected behaviour you didn't see**
 > The time should be synchronized and `timedatectl timesync-status` should show a server with an IP address.

**Unexpected behaviour you saw**
 > The time is no longer synchronized (about 1-2 second difference) and `timedatectl timesync-status` is stuck at `(null) (3.debian.pool.ntp.org)`.

**Steps to reproduce the problem**
The problem seems reproducible, but I don't know the exact conditions. I've noticed it on my laptop, which is sometimes suspended and not always connected, and when it is connected, this is via the wifi hotspot of my phone.

Now, my laptop has been connected for more than 3 hours. The connection seems very good (I haven't noticed any issue with the other applications).

```
zira:~> timedatectl timesync-status
       Server: (null) (3.debian.pool.ntp.org)   
Poll interval: 34min 8s (min: 32s; max 34min 8s)
         Leap: normal                           
      Version: 4                                
      Stratum: 1                                
    Reference: NICT                             
    Precision: 1us (-20)                        
Root distance: 0 (max: 5s)                      
       Offset: +81.242ms                        
        Delay: 388.037ms                        
       Jitter: 162.461ms                        
 Packet count: 32                               
    Frequency: -18.678ppm                       

zira:~> timedatectl show-timesync
FallbackNTPServers=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org
ServerName=3.debian.pool.ntp.org
RootDistanceMaxUSec=5s
PollIntervalMinUSec=32s
PollIntervalMaxUSec=34min 8s
PollIntervalUSec=34min 8s
NTPMessage={ Leap=0, Version=4, Mode=4, Stratum=1, Precision=-20, RootDelay=0, RootDispersion=0, Reference=NICT, OriginateTimestamp=Mon 2020-07-20 00:37:54 CEST, ReceiveTimestamp=Mon 2020-07-20 00:37:55 CEST, TransmitTimestamp=Mon 2020-07-20 00:37:55 CEST, DestinationTimestamp=Mon 2020-07-20 00:37:55 CEST, Ignored=no PacketCount=32, Jitter=162.461ms }
Frequency=-1224110

zira:~> systemctl status systemd-timesyncd.service
● systemd-timesyncd.service - Network Time Synchronization
     Loaded: loaded (/lib/systemd/system/systemd-timesyncd.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2020-07-19 19:11:29 CEST; 1 day 6h ago
       Docs: man:systemd-timesyncd.service(8)
   Main PID: 682 (systemd-timesyn)
     Status: "Idle."
      Tasks: 2 (limit: 19071)
     Memory: 3.0M
     CGroup: /system.slice/systemd-timesyncd.service
             └─682 /lib/systemd/systemd-timesyncd

Jul 19 19:11:29 zira systemd[1]: Starting Network Time Synchronization...
Jul 19 19:11:29 zira systemd[1]: Started Network Time Synchronization.
Jul 19 19:14:23 zira systemd-timesyncd[682]: Initial synchronization to time server 51.158.67.116:123 (1.debian.pool.ntp.org).
Jul 19 23:30:01 zira systemd-timesyncd[682]: Initial synchronization to time server 133.243.238.163:123 (0.debian.pool.ntp.org).
```
and `3.debian.pool.ntp.org` is pingable.

**Comment by vinc17fr** [comment]
And also:
```
zira:~> timedatectl
               Local time: Tue 2020-07-21 02:15:38 CEST
           Universal time: Tue 2020-07-21 00:15:38 UTC 
                 RTC time: Tue 2020-07-21 00:15:38     
                Time zone: Europe/Paris (CEST, +0200)  
System clock synchronized: no                          
              NTP service: active                      
          RTC in local TZ: no                          
```

**Comment by keszybz** [comment]
Is this fixed with #16494?

**Comment by vinc17fr** [comment]
Without #16494, I could not reproduce this particular issue, but after testing during the past few days, I could notice a completely reproducible related issue: after suspending the laptop for a long enough period, I get
```
       Server: (null) (3.debian.pool.ntp.org)
Poll interval: 34min 8s (min: 32s; max 34min 8s)
```
for about half an hour. I suppose that the cause is the following. When resuming after more than the current poll interval, which is typically 34 min, systemd-timesyncd does another poll, but at this time, the laptop is not connected yet, hence the failure, and one needs to wait for another 34-minute delay.

I'm going to do some tests with #16494. I assume that it should fix the issue if it behaves as said in the comment: "re-arm timer with the minimum poll interval, in case the packets never arrive back".

**Comment by vinc17fr** [comment]
#16494 does not seem to solve this issue. 24 minutes after the wifi connection, I still get:
```
zira:~> timedatectl timesync-status
       Server: n/a (3.debian.pool.ntp.org)
Poll interval: 34min 8s (min: 32s; max 34min 8s)
[...]
```

**Comment by vinc17fr** [comment]
And I had to wait for 34 minutes in order to get an IP address.

**Comment by ssahani** [comment]
FIx is https://github.com/systemd/systemd/pull/17611

```
Last login: Sat Nov 14 17:32:08 2020 from 10.104.45.138
 17:36:19 up 0 min,  0 users,  load average: 0.00, 0.00, 0.00
> systemd-analyze blame
Bootup is not yet finished (org.freedesktop.systemd1.Manager.FinishTimestampMonotonic=0).
Please try again later.
Hint: Use 'systemctl list-jobs' to see active jobs
```

**Comment by bluca** [comment]
@vinc17fr does https://github.com/systemd/systemd/pull/16624 (included in v246/v247) fix the issue? A cap on the retry has been introduced.

**Comment by vinc17fr** [comment]
I have the systemd 247.1-3 Debian package (I rebooted after the upgrade). And the issue is still not fixed. Nothing changed. Here's what I did:

1. Wait for the poll interval to become the maximum, which is "34min 8s":
```
       Server: 51.15.177.17 (0.debian.pool.ntp.org)
Poll interval: 34min 8s (min: 32s; max 34min 8s)
         Leap: normal
      Version: 4
      Stratum: 3
    Reference: C39AAED1
    Precision: 1us (-22)
Root distance: 44.165ms (max: 5s)
       Offset: -3.472ms
        Delay: 10.101ms
       Jitter: 3.859ms
 Packet count: 14
    Frequency: -10.305ppm
```
2. Suspend my laptop and wait for 5 minutes.

3. Unplug the Ethernet cable.

4. Resume. After a few seconds, I got:
```
       Server: n/a (3.debian.pool.ntp.org)
Poll interval: 34min 8s (min: 32s; max 34min 8s)
         Leap: normal
      Version: 4
      Stratum: 3
    Reference: C39AAED1
    Precision: 1us (-22)
Root distance: 44.165ms (max: 5s)
       Offset: -3.472ms
        Delay: 10.101ms
       Jitter: 3.859ms
 Packet count: 14
    Frequency: -10.305ppm
```
See that the server no longer has an IP address.

5. Plug in the Ethernet cable. But for the next 34 minutes, I still had the same output, in particular `Server: n/a (3.debian.pool.ntp.org)`. After 34 minutes, it came back with
```
       Server: 51.68.44.27 (0.debian.pool.ntp.org)
Poll interval: 32s (min: 32s; max 34min 8s)
```

**Comment by vinc17fr** [comment]
I suppose that when the server becomes n/a (e.g. due to a lack of Internet connection, even temporary), the poll interval should be reduced to the minimum. This should not hurt since NTP packets will not be sent until an IP address becomes available.

**Comment by bluca** [comment]
> I suppose that when the server becomes n/a (e.g. due to a lack of Internet connection, even temporary), the poll interval should be reduced to the minimum. This should not hurt since NTP packets will not be sent until an IP address becomes available.

I think this is a very good point. IMHO it makes more sense to do this automatically, rather than adding a knob to change the interval manually - after all, we want things to "just work" in these situations, I believe

**Comment by ssahani** [comment]
What is choice for the for disputed interval. That bus why its a knob.

**Comment by ssahani** [comment]
This bug is creating a havoc . tons of complain about boot time . we need to disable timesync or replace with something else for photon.

**Comment by bluca** [comment]
When using networkd, timesyncd will immediately detect the network change and sync the time. The problem is when networkd is not used, then we can't detect that the network is back.

Given it seems many distros are enabling timesyncd but not networkd (eg: Debian), it seems like a worthwhile use case to cover, but it's going to be difficult. I do not believe we have prior art for doing anything like that, and in fact it's notoriously difficult to achieve.

Perhaps we should start by documenting the issue and suggesting a lower PollIntervalMaxSec= when networkd is not in use?

**Comment by ssahani** [comment]
No networks is enabled .

**Comment by bluca** [comment]
Not on Debian - ifupdown is used on headless clients and network-manager on desktops. Unless @vinc17fr has changed it manually?

**Comment by ssahani** [comment]
You enable networks as online code depends on it

**Comment by vinc17fr** [comment]
When I reported the bug, I was using wicd. Now I'm using NetworkManager.

Note that putting a script in the `/etc/network/if-up.d` directory seems to be a portable solution. As a workaround to this bug, I put the following script:
```
#!/bin/sh

[ "$IFACE" != "lo" ] || exit 0
[ -d /run/systemd/system ] || exit 0
[ -x /lib/systemd/systemd-timesyncd ] || exit 0

cmd="systemctl try-restart systemd-timesyncd.service"
[ -x /usr/bin/logger ] && /usr/bin/logger -t "${0#/etc/network/}" "$cmd"
$cmd || true
```

**Comment by bluca** [comment]
Yes, that sounds like something that could work when networkd is not used. Perhaps we could add a verb in timedatectl or ExecReload support to avoid a restart, which will lose all states, and instead simply get systemd-timesync to reload its config and thus check again the state of the network, and then document this somewhere?
