### ISSUE TITLE
Ability for stub to listen on ::1

### ISSUE THREAD

**Issue by SRv6d** [systemd/systemd#17434]
**Is your feature request related to a problem? Please describe.**
Systems running in IPv6 only networks may stop forwarding or simply drop any IPv4 packet.  
Since systemd's stub listener only supports IPv4 it does not work on these systems. 

**Describe the solution you'd like**
A configuration option that enables an IPv6 localhost (::1) stub listener.
For example:
```
DNSStubAddressFamily=any|inet|inet6
```

**Comment by yuwata** [comment]
We have implemented `DNSStubListenerExtra=`.

**Comment by s1lversurfer** [comment]
DNSStubListenerExtra= will only add additional listeners and the main listener in /etc/resolv.conf will still be 127.0.0.1, which means that systemd-resolved will still not work on IPv6 only systems.

**Comment by keszybz** [comment]
Well, the ask was "A configuration option that enables an IPv6 localhost (::1) stub listener." and "DNSStubListenerExtra=::1" does exactly that. If you need some additional features, please describe them.
