### ISSUE TITLE
The program runs successfully and has output, but systemd-udevd loses program's output information and the stdout event appears to be unprocessed.

### ISSUE THREAD

**Issue by hexiaowen** [systemd/systemd#18190]
**systemd version the issue has been seen with**
 > v247

**Used distribution**
 > f33

**Linux kernel version used** (`uname -a`)
 > 5.9.16

**CPU architecture issue was seen on**
 > aarch64

**Expected behaviour you didn't see**
 > Everything goes well.

**Unexpected behaviour you saw**
 > The program runs successfully and has output, but systemd-udevd loses program's output information and the stdout event appears to be unprocessed.

**Steps to reproduce the problem**
 > 
```
#!/bin/bash

function check_lvm(){
    for i in `seq 10`;do
        vgs | grep vgtest$i || exit 1
        ls /dev/vgtest$i || exit 1
        for j in `seq 10`;do
            lvs | grep lvtest${i}-${j} || exit 1
            ls /dev/vgtest${i}/lvtest${i}-${j} || exit 1
        done
    done
}

while true;do
    vgchange --refresh
    check_lvm
```
/usr/lib/udev/rules.d/11-dm-lvm.rules
```
# Use DM name and split it up into its VG/LV/layer constituents.
IMPORT{program}="/usr/sbin/dmsetup splitname --nameprefixes --noheadings --rows $env{DM_NAME}"    ####HERE, program cannot got the output ####

# DM_SUBSYSTEM_UDEV_FLAG0 is the 'NOSCAN' flag for LVM subsystem.
# This flag is used to temporarily disable selected rules to prevent any
# processing or scanning done on the LVM volume before LVM has any chance
# to zero any stale metadata found within the LV data area. Such stale
# metadata could cause false claim of the LV device, keeping it open etc.
#
# If the NOSCAN flag is present, backup selected existing flags used to
# disable rules, then set them firmly so those selected rules are surely skipped.
# Restore these flags once the NOSCAN flag is dropped (which is normally any
# uevent that follows for this LV, even an artificially generated one).
ENV{DM_SUBSYSTEM_UDEV_FLAG0}=="1", ENV{DM_NOSCAN}="1", ENV{DM_DISABLE_OTHER_RULES_FLAG_OLD}="$env{DM_UDEV_DISABLE_OTHER_RULES_FLAG}", ENV{DM_UDEV_DISABLE_OTHER_RULES_FLAG}="1"
ENV{DM_SUBSYSTEM_UDEV_FLAG0}!="1", IMPORT{db}="DM_NOSCAN", IMPORT{db}="DM_DISABLE_OTHER_RULES_FLAG_OLD"
ENV{DM_SUBSYSTEM_UDEV_FLAG0}!="1", ENV{DM_NOSCAN}=="1", ENV{DM_UDEV_DISABLE_OTHER_RULES_FLAG}="$env{DM_DISABLE_OTHER_RULES_FLAG_OLD}", \
                                   ENV{DM_DISABLE_OTHER_RULES_FLAG_OLD}="", ENV{DM_NOSCAN}=""

ENV{DM_UDEV_DISABLE_SUBSYSTEM_RULES_FLAG}=="1", GOTO="lvm_end"

# Do not create symlinks for inappropriate subdevices.
ENV{DM_LV_NAME}=="pvmove?*|?*_vorigin", GOTO="lvm_disable"
ENV{DM_LV_LAYER}=="?*", GOTO="lvm_disable"

# Create symlinks for top-level devices only.
ENV{DM_VG_NAME}=="?*", ENV{DM_LV_NAME}=="?*", SYMLINK+="$env{DM_VG_NAME}/$env{DM_LV_NAME}", GOTO="lvm_end"   ###The SYMLINK cannot be created correctly.###
```
The link cannot be created correctly because udev does not get output, but we are sure that the dmsetup has output.

**Comment by hexiaowen** [comment]
```
static int on_spawn_sigchld(sd_event_source *s, const siginfo_t *si, void *userdata) {
        Spawn *spawn = userdata;
        int ret = -EIO;

        assert(spawn);

        switch (si->si_code) {
        case CLD_EXITED:
                if (si->si_status == 0)
                        log_device_debug(spawn->device, "Process '%s' succeeded.", spawn->cmd);
                else
                        log_device_full(spawn->device, spawn->accept_failure ? LOG_DEBUG : LOG_WARNING,
                                        "Process '%s' failed with exit code %i.", spawn->cmd, si->si_status);
                ret = si->si_status;
                break;
        case CLD_KILLED:
        case CLD_DUMPED:
                log_device_error(spawn->device, "Process '%s' terminated by signal %s.", spawn->cmd, signal_to_string(si->si_status));
                break;
        default:
                log_device_error(spawn->device, "Process '%s' failed due to unknown reason.", spawn->cmd);
        }

        sd_event_exit(sd_event_source_get_event(s), ret);   //It is suspected that the I/O event is not received when the program exits signal processing. As a result, the stdout is discarded.
        return 1;
}
```

**Comment by yuwata** [comment]
Hmm??? If I understand correctly, your script always exit with `1`. That is treated us failure by udevd, which is intentional. Please return `0` on success.

**Comment by hexiaowen** [comment]
> Hmm??? If I understand correctly, your script always exits with `1`. That is treated as failure by udevd, which is intentional. Please return `0` on success.
> 
> EDIT: Not always, but sometimes.

This is intentional until the error exits, otherwise keep testing.

**Comment by hexiaowen** [comment]
Here is the log
```
Jan 09 01:14:03 localhost.localdomain root[1150]: TAGS=:systemd:
Jan 09 01:14:03 localhost.localdomain systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/dev_2ddisk_2dby_5cx2did_2ddm_5cx2dname_5cx2dvgtest3_5cx2dlvtest3_5cx2d_5cx2d6_2edevice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=2062562 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jan 09 01:14:03 localhost.localdomain root[1150]:
Jan 09 01:14:03 localhost.localdomain systemd-udevd[475943]: dm-92: Process '/usr/sbin/dmsetup splitname --nameprefixes --noheadings --rows vgtest3-lvtest3--7' succeeded.
Jan 09 01:14:03 localhost.localdomain dmsetup[476033]: DM_VG_NAME='vgtest3'
Jan 09 01:14:03 localhost.localdomain systemd-udevd[475943]: dm-92: /usr/lib/udev/rules.d/95-dm-notify.rules:12 RUN '/usr/sbin/dmsetup udevcomplete $env{DM_COOKIE}'
Jan 09 01:14:03 localhost.localdomain dmsetup[476033]: DM_LV_NAME='lvtest3-7'
Jan 09 01:14:03 localhost.localdomain systemd-udevd[475943]: dm-92: Updating old name, '/dev/disk/by-id/dm-name-vgtest3-lvtest3--7' no longer belonging to '/devices/virtual/block/dm-92'
Jan 09 01:14:03 localhost.localdomain dmsetup[476033]: DM_LV_LAYER=''
Jan 09 01:14:03 localhost.localdomain systemd-udevd[475943]: dm-92: No reference left, removing '/dev/disk/by-id/dm-name-vgtest3-lvtest3--7'
Jan 09 01:14:03 localhost.localdomain systemd-udevd[475943]: dm-92: Updating old name, '/dev/vgtest3/lvtest3-7' no longer belonging to '/devices/virtual/block/dm-92'
Jan 09 01:14:03 localhost.localdomain systemd-udevd[475943]: dm-92: No reference left, removing '/dev/vgtest3/lvtest3-7'
Jan 09 01:14:03 localhost.localdomain systemd-udevd[475943]: dm-92: Updating old name, '/dev/disk/by-id/dm-uuid-LVM-7fGWz12k8RZl1FMFCG1KP9zUYGTeL4THdvfh7OArC9oAAzieXrtPeylhdufSVcf7' no longer belonging to '/devices/virtual/block/dm-92'
Jan 09 01:14:03 localhost.localdomain systemd-udevd[475943]: dm-92: No reference left, removing '/dev/disk/by-id/dm-uuid-LVM-7fGWz12k8RZl1FMFCG1KP9zUYGTeL4THdvfh7OArC9oAAzieXrtPeylhdufSVcf7'
Jan 09 01:14:03 localhost.localdomain systemd-udevd[475943]: dm-92: Handling device node '/dev/dm-92', devnum=b253:92
Jan 09 01:14:03 localhost.localdomain systemd-udevd[475943]: dm-92: Preserve already existing symlink '/dev/block/253:92' to '../dm-92'
Jan 09 01:14:03 localhost.localdomain systemd-udevd[475943]: dm-92: Found 'b253:92' claiming '/run/udev/links/\x2fmapper\x2fvgtest3-lvtest3--7'
Jan 09 01:14:03 localhost.localdomain systemd-udevd[475943]: dm-92: Preserve already existing symlink '/dev/mapper/vgtest3-lvtest3--7' to '../dm-92'
/dm-92
```

**Comment by yuwata** [comment]
It seems the link is once created, and removed in a subsequent uevent. Could you show the full log for `dm-92`?

**Comment by yuwata** [comment]
From 11-dm-lvm.rules,
```
# "add" event is processed on coldplug only!
ACTION!="add|change", GOTO="lvm_end"
```
What happens if this line is changed to the following?
```
ACTION=="remove", GOTO="lvm_end"
```

**Comment by hexiaowen** [comment]
This is the log for filtering useless information.  Only dm-92 is abnormal.

```
Jan 09 01:14:03 localhost.localdomain systemd-udevd[475946]: dm-91: Process '/usr/sbin/dmsetup udevflags 6356549' succeeded.
Jan 09 01:14:03 localhost.localdomain systemd-udevd[475946]: dm-91: /usr/lib/udev/rules.d/10-dm.rules:135 LINK 'mapper/vgtest1-lvtest1--9'
Jan 09 01:14:03 localhost.localdomain systemd-udevd[475946]: dm-91: /usr/lib/udev/rules.d/11-dm-lvm.rules:21 Importing properties from results of '/usr/sbin/dmsetup splitname --nameprefixes --noheadings --rows vgtest1-lvtest1--9'
Jan 09 01:14:03 localhost.localdomain systemd-udevd[475946]: dm-91: Starting '/usr/sbin/dmsetup splitname --nameprefixes --noheadings --rows vgtest1-lvtest1--9'
Jan 09 01:14:03 localhost.localdomain systemd-udevd[475946]: Successfully forked off '(spawn)' as PID 476069.
Jan 09 01:14:03 localhost.localdomain dmsetup[476069]: DM_VG_NAME='vgtest1'
Jan 09 01:14:03 localhost.localdomain dmsetup[476069]: DM_LV_NAME='lvtest1-9'
Jan 09 01:14:03 localhost.localdomain systemd-udevd[475946]: dm-91: '/usr/sbin/dmsetup splitname --nameprefixes --noheadings --rows vgtest1-lvtest1--9'(out) 'DM_VG_NAME='vgtest1''
Jan 09 01:14:03 localhost.localdomain dmsetup[476069]: DM_LV_LAYER=''
Jan 09 01:14:03 localhost.localdomain systemd-udevd[475946]: dm-91: '/usr/sbin/dmsetup splitname --nameprefixes --noheadings --rows vgtest1-lvtest1--9'(out) 'DM_LV_NAME='lvtest1-9''
Jan 09 01:14:03 localhost.localdomain dmsetup[476068]: Complete cookie 0xd4dfe45 success.
Jan 09 01:14:03 localhost.localdomain systemd-udevd[475946]: dm-91: '/usr/sbin/dmsetup splitname --nameprefixes --noheadings --rows vgtest1-lvtest1--9'(out) 'DM_LV_LAYER='''
Jan 09 01:14:03 localhost.localdomain systemd-udevd[475946]: dm-91: Process '/usr/sbin/dmsetup splitname --nameprefixes --noheadings --rows vgtest1-lvtest1--9' succeeded.
```

Dm-92 is no different from other LVMs. We can see that the preceding log is displayed in the normal state, but the dm-92 does not. Especially 
```
dm-91: '/usr/sbin/dmsetup splitname --nameprefixes --noheadings --rows vgtest1-lvtest1--9'(out) 'DM_VG_NAME='vgtest1'' 
dm-91: '/usr/sbin/dmsetup splitname --nameprefixes --noheadings --rows vgtest1-lvtest1--9'(out) 'DM_LV_NAME='lvtest1-9'' 
dm-91: '/usr/sbin/dmsetup splitname --nameprefixes --noheadings --rows vgtest1-lvtest1--9'(out) 'DM_LV_LAYER='''
```

**Comment by hexiaowen** [comment]
> From 11-dm-lvm.rules,
> 
> ```
> # "add" event is processed on coldplug only!
> ACTION!="add|change", GOTO="lvm_end"
> ```
> 
> What happens if this line is changed to the following?
> 
> ```
> ACTION=="remove", GOTO="lvm_end"
> ```

It doesn't work. Nothing changes.

**Comment by yuwata** [comment]
Thanks. But your issue seems already fixed in v245 by 9f537ae3100f8372579daea53c24fff917cc3257. I have no idea why we see the issue again...

**Comment by poettering** [comment]
is it possible that the offending program has a child process that lives a bit longer than itself? so udev currently picks up the logs from the main program, and on SIGCHLD stops doing so, but the child process (i.e. the grandchild of udev) still lives on for a bit and continues to log and its stdout now goes nowhere?

**Comment by hexiaowen** [comment]
> Thanks. But your issue seems already fixed in v245 by [9f537ae](https://github.com/systemd/systemd/commit/9f537ae3100f8372579daea53c24fff917cc3257). I have no idea why we see the issue again...

I'm sure this commit [9f537ae](https://github.com/systemd/systemd/commit/9f537ae3100f8372579daea53c24fff917cc3257)  just reduces the probability and does not solve my problem.

**Comment by hexiaowen** [comment]
![20210112-140442(WeLinkPC)](https://user-images.githubusercontent.com/2988994/104276506-f03e7f80-54df-11eb-87b2-0331139eadb8.png)
![20210112-140525(WeLinkPC)](https://user-images.githubusercontent.com/2988994/104276512-f46a9d00-54df-11eb-945d-2a1555e84f49.png)

On the host where the problem is easily reproduced, the added retry rule is triggered. The log shows that the missing information is obtained for the second time. This reduces the probability of the problem.

In the first figure, the red box indicates the problem recurrence, and the green box indicates that the added workaround rule is triggered to retry.
The second figure shows the added workaround rule.

**Comment by hexiaowen** [comment]
> is it possible that the offending program has a child process that lives a bit longer than itself? so udev currently picks up the logs from the main program, and on SIGCHLD stops doing so, but the child process (i.e. the grandchild of udev) still lives on for a bit and continues to log and its stdout now goes nowhere?

It is confirmed that the dmsetup does not create subprocesses or threads when splitting the transferred DM_NAME.

**Comment by hexiaowen** [comment]
I added a print to the entry of on_spawn_io. When the problem occurred, it was confirmed that on_spawn_io was not invoked.

**Comment by hexiaowen** [comment]
Can someone help me?

**Comment by gaoyi1988** [comment]
Revert to spawn_read can fix this problem

https://github.com/systemd/systemd/pull/18330

**Comment by yuwata** [comment]
@hexiaowen and @gaoyi1988 I cannot reproduce this issue. I've introduced a test for `udev_event_spawn()` in #18331. Could you add a reproducer for this issue in the test?

**Comment by gaoyi1988** [comment]
@yuwata 
I don't know how to realize the test right away. my test in VM is as below:
1. A virtual Machine with three disks which the sizes are 20G,20G,10G
2. Use fdisk to part the disks above. Each partition has 5G sizes.
3. Create lvm devices as below, this will create 100 devices.
```
j=1
for each_disk in `fdisk -l | grep 5G | awk '{print $1}'`; do
    vgcreate vgtest${j} ${each_disk}
    for k in `seq 10`; do
        lvcreate -n lvtest${j}-${k} -L 480MVG vgtest${j}
    done
    ((j++))
done
```
4. Execute the script below.
```
#!/bin/bash

function check_lvm(){
    for i in `seq 10`;do
        vgs | grep vgtest$i || exit 1
        ls /dev/vgtest$i || exit 1
        for j in `seq 10`;do
            lvs | grep lvtest${i}-${j} || exit 1
            ls /dev/vgtest${i}/lvtest${i}-${j} || exit 1
        done
    done
}

while true;do
    vgchange --refresh
    check_lvm
done
```
Usually, this test will reproduce the problem no more than **10 hours**.
My test for "revert spawn_read" is over 18 hours.

**Comment by yuwata** [comment]
10 hours... Hmm...

**Comment by yuwata** [comment]
@hexiaowen and @gaoyi1988 Does the last commit for sd-event in #18331 fix your issue?

**Comment by gaoyi1988** [comment]
I backport the commit https://github.com/systemd/systemd/pull/18331/commits/01544d306d133c7af80fa0c6bac156b2b8030ac8, but this don't fix my problem

**Comment by yuwata** [comment]
Hmm...

**Comment by gaoyi1988** [comment]
@yuwata 
According to adding print, I find this problem is occured in follow call trace:
```
sd_event_prepare -> sd_event_wait(e, 0) --> epoll_wait
                                        |
                                        \-> process_child
```
epoll_wait will return 0 when io event is not received and then goto process child.

PR https://github.com/systemd/systemd/pull/18750 can fix this, and it just affect udev-event

**Comment by mrc0mmand** [comment]
Reopening because of #18967, so we don't forget about this.
