### ISSUE TITLE
Assertion failure in dns_query_complete()

### ISSUE THREAD

**Issue by jdz** [systemd/systemd#18232]
**systemd version the issue has been seen with**
 > 247.2
```
systemctl --version
systemd 247 (247.2-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > Linux kuro 5.10.6-arch1-1 #1 SMP PREEMPT Sat, 09 Jan 2021 18:22:35 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > No coredumps.

**Unexpected behaviour you saw**
 > Coredump.

**Steps to reproduce the problem**
 > Have no clue.

Relevant messages from journal:

```
Jan 13 14:06:55.112194 kuro systemd-resolved[490]: Assertion 'DNS_TRANSACTION_IS_LIVE(q->state)' failed at src/resolve/resolved-dns-query.c:485, function dns_query_complete(). Aborting.
Jan 13 14:06:55.122317 kuro systemd[1]: Created slice system-systemd\x2dcoredump.slice.
Jan 13 14:06:55.123528 kuro systemd[1]: Started Process Core Dump (PID 9717/UID 0).
Jan 13 14:06:55.201253 kuro systemd-coredump[9718]: [🡕] Process 490 (systemd-resolve) of user 980 dumped core.

                                                    Stack trace of thread 490:
                                                    #0  0x00007fd5ad9d6615 raise (libc.so.6 + 0x3d615)
                                                    #1  0x00007fd5ad9bf862 abort (libc.so.6 + 0x26862)
                                                    #2  0x00007fd5ae1fa07f n/a (libsystemd-shared-247.so + 0x5607f)
                                                    #3  0x0000556778be961a n/a (systemd-resolved + 0x1361a)
                                                    #4  0x0000556778be972b n/a (systemd-resolved + 0x1372b)
                                                    #5  0x00007fd5ae3595e6 n/a (libsystemd-shared-247.so + 0x1b55e6)
                                                    #6  0x00007fd5ae35997b sd_event_dispatch (libsystemd-shared-247.so + 0x1b597b)
                                                    #7  0x00007fd5ae35ad31 sd_event_run (libsystemd-shared-247.so + 0x1b6d31)
                                                    #8  0x00007fd5ae35af70 sd_event_loop (libsystemd-shared-247.so + 0x1b6f70)
                                                    #9  0x0000556778c0e369 n/a (systemd-resolved + 0x38369)
                                                    #10 0x0000556778be1126 n/a (systemd-resolved + 0xb126)
                                                    #11 0x00007fd5ad9c1152 __libc_start_main (libc.so.6 + 0x28152)
                                                    #12 0x0000556778be11ce n/a (systemd-resolved + 0xb1ce)
Jan 13 14:06:55.202691 kuro systemd[1]: systemd-coredump@0-9717-0.service: Succeeded.
Jan 13 14:06:55.203531 kuro systemd[1]: systemd-resolved.service: Main process exited, code=dumped, status=6/ABRT
Jan 13 14:06:55.203593 kuro systemd[1]: systemd-resolved.service: Failed with result 'core-dump'.
```

Excerpt from `journalctl -o short-precise -u systemd-resolved.service`:

```
Jan 13 11:10:38.780890 kuro systemd[1]: Started Network Name Resolution.
Jan 13 14:05:02.947664 kuro systemd-resolved[490]: Using degraded feature set UDP instead of UDP+EDNS0 for DNS server 9.9.9.9.
Jan 13 14:05:12.951069 kuro systemd-resolved[490]: Using degraded feature set TCP instead of UDP for DNS server 9.9.9.9.
Jan 13 14:05:33.112299 kuro systemd-resolved[490]: Using degraded feature set UDP instead of TCP for DNS server 9.9.9.9.
Jan 13 14:06:55.112194 kuro systemd-resolved[490]: Assertion 'DNS_TRANSACTION_IS_LIVE(q->state)' failed at src/resolve/resolved-dns-query.c:485, function dns_query_complete(). Aborting.
Jan 13 14:06:55.203531 kuro systemd[1]: systemd-resolved.service: Main process exited, code=dumped, status=6/ABRT
Jan 13 14:06:55.203593 kuro systemd[1]: systemd-resolved.service: Failed with result 'core-dump'.
```

**Comment by jdz** [comment]
Looking back in journal I see that a me starting `bandwhich` (which seems to be doing quite a few reverse lookups) might have contributed to the crash:

```
Jan 13 14:04:48.871776 kuro kernel: device lo entered promiscuous mode
Jan 13 14:04:48.894776 kuro kernel: device enp9s0 entered promiscuous mode
Jan 13 14:04:48.931671 kuro kernel: device vpn0 entered promiscuous mode
Jan 13 14:05:02.947664 kuro systemd-resolved[490]: Using degraded feature set UDP instead of UDP+EDNS0 for DNS server 9.9.9.9.
Jan 13 14:05:12.951069 kuro systemd-resolved[490]: Using degraded feature set TCP instead of UDP for DNS server 9.9.9.9.
Jan 13 14:05:32.808902 kuro systemd[881]: Started Application launched by gsd-media-keys.
Jan 13 14:05:32.892950 kuro io.elementary.t[1232]: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook
Jan 13 14:05:32.898115 kuro systemd[881]: Started VTE child process 9587 launched by io.elementary.terminal process 1232.
Jan 13 14:05:32.899889 kuro systemd[881]: app-gnome-io.elementary.terminal-9579.scope: Succeeded.
Jan 13 14:05:33.112299 kuro systemd-resolved[490]: Using degraded feature set UDP instead of TCP for DNS server 9.9.9.9.
Jan 13 14:05:47.388663 kuro systemd[881]: vte-spawn-ebd6d0c4-2cbb-4b34-9f3d-e96150e1db38.scope: Succeeded.
Jan 13 14:06:18.508107 kuro kernel: device lo left promiscuous mode
Jan 13 14:06:18.528107 kuro kernel: device enp9s0 left promiscuous mode
Jan 13 14:06:19.114773 kuro kernel: device vpn0 left promiscuous mode
Jan 13 14:06:19.459317 kuro systemd[881]: vte-spawn-618227ae-3977-434b-a777-a5d4083bceb5.scope: Succeeded.
Jan 13 14:06:24.476609 kuro gnome-shell[1003]: Can't update stage views actor MetaWindowGroup is on because it needs an allocation.
Jan 13 14:06:24.476628 kuro gnome-shell[1003]: Can't update stage views actor Gjs_ui_altTab_CyclerHighlight is on because it needs an allocation.
Jan 13 14:06:24.476636 kuro gnome-shell[1003]: Can't update stage views actor StWidget is on because it needs an allocation.
Jan 13 14:06:24.734920 kuro gnome-shell[1003]: Can't update stage views actor MetaWindowGroup is on because it needs an allocation.
Jan 13 14:06:24.734930 kuro gnome-shell[1003]: Can't update stage views actor Gjs_ui_altTab_CyclerHighlight is on because it needs an allocation.
Jan 13 14:06:24.734937 kuro gnome-shell[1003]: Can't update stage views actor StWidget is on because it needs an allocation.
Jan 13 14:06:55.112194 kuro systemd-resolved[490]: Assertion 'DNS_TRANSACTION_IS_LIVE(q->state)' failed at src/resolve/resolved-dns-query.c:485, function dns_query_complete(). Aborting.
```

**Comment by jdz** [comment]
Triggered it again by using `bandwhich`:

```
Jan 13 15:03:19.897776 kuro kernel: device lo entered promiscuous mode
Jan 13 15:03:19.921265 kuro kernel: device enp9s0 entered promiscuous mode
Jan 13 15:03:19.954601 kuro kernel: device vpn0 entered promiscuous mode
Jan 13 15:04:53.915724 kuro systemd[881]: Started Application launched by gsd-media-keys.
Jan 13 15:04:53.990836 kuro io.elementary.t[1232]: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook
Jan 13 15:04:53.996872 kuro systemd[881]: Started VTE child process 15131 launched by io.elementary.terminal process 1232.
Jan 13 15:04:53.998830 kuro systemd[881]: app-gnome-io.elementary.terminal-15123.scope: Succeeded.
Jan 13 15:05:17.070591 kuro systemd[881]: vte-spawn-9690ea7d-8615-44db-b554-3b803398cfe5.scope: Succeeded.
Jan 13 15:06:32.012042 kuro systemd[881]: Started Application launched by gsd-media-keys.
Jan 13 15:06:32.094817 kuro io.elementary.t[1232]: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook
Jan 13 15:06:32.100212 kuro systemd[881]: Started VTE child process 15290 launched by io.elementary.terminal process 1232.
Jan 13 15:06:32.102204 kuro systemd[881]: app-gnome-io.elementary.terminal-15279.scope: Succeeded.
Jan 13 15:07:29.704436 kuro systemd[881]: vte-spawn-17227722-1dd1-43b9-b957-6111c755abb8.scope: Succeeded.
Jan 13 15:07:31.577740 kuro kernel: device lo left promiscuous mode
Jan 13 15:07:31.581067 kuro kernel: device enp9s0 left promiscuous mode
Jan 13 15:07:31.581111 kuro kernel: device vpn0 left promiscuous mode
Jan 13 15:07:32.237586 kuro systemd[881]: vte-spawn-c2af9357-b27a-42b1-8a85-411497655376.scope: Succeeded.
Jan 13 15:09:31.612218 kuro systemd-resolved[9730]: Assertion 'DNS_TRANSACTION_IS_LIVE(q->state)' failed at src/resolve/resolved-dns-query.c:485, function dns_query_complete(). Aborting.
Jan 13 15:09:31.623273 kuro systemd[1]: Started Process Core Dump (PID 15575/UID 0).
Jan 13 15:09:31.693732 kuro systemd-coredump[15576]: [🡕] Process 9730 (systemd-resolve) of user 980 dumped core.
                                                     
                                                     Stack trace of thread 9730:
                                                     #0  0x00007f7306ede615 raise (libc.so.6 + 0x3d615)
                                                     #1  0x00007f7306ec7862 abort (libc.so.6 + 0x26862)
                                                     #2  0x00007f730770207f n/a (libsystemd-shared-247.so + 0x5607f)
                                                     #3  0x00005629b3f2261a n/a (systemd-resolved + 0x1361a)
                                                     #4  0x00005629b3f2272b n/a (systemd-resolved + 0x1372b)
                                                     #5  0x00007f73078615e6 n/a (libsystemd-shared-247.so + 0x1b55e6)
                                                     #6  0x00007f730786197b sd_event_dispatch (libsystemd-shared-247.so + 0x1b597b)
                                                     #7  0x00007f7307862d31 sd_event_run (libsystemd-shared-247.so + 0x1b6d31)
                                                     #8  0x00007f7307862f70 sd_event_loop (libsystemd-shared-247.so + 0x1b6f70)
                                                     #9  0x00005629b3f47369 n/a (systemd-resolved + 0x38369)
                                                     #10 0x00005629b3f1a126 n/a (systemd-resolved + 0xb126)
                                                     #11 0x00007f7306ec9152 __libc_start_main (libc.so.6 + 0x28152)
                                                     #12 0x00005629b3f1a1ce n/a (systemd-resolved + 0xb1ce)
Jan 13 15:09:31.695098 kuro systemd[1]: systemd-coredump@1-15575-0.service: Succeeded.
Jan 13 15:09:31.695944 kuro systemd[1]: systemd-resolved.service: Main process exited, code=dumped, status=6/ABRT
Jan 13 15:09:31.696006 kuro systemd[1]: systemd-resolved.service: Failed with result 'core-dump'.
Jan 13 15:09:31.696518 kuro systemd[1]: systemd-resolved.service: Scheduled restart job, restart counter is at 2.
```

**Comment by jdz** [comment]
This morning I noticed that connecting to VPN (openconnect) takes longer than expected, and offline imap was syncing slowly, so I suspected `systemd-resolved` is acting up (I've had this before, restarting the daemon solves issues).  Pretty sure `systemd-resolve` gets into weird states, but I started `bandwhich` to maybe notice anything weird.  Did not notice anything weird, except `systemd-reslved` crashed with assertion error, but this time while the interface was still in promiscuous mode (and not after quitting `bandwhich`).

What's weird is that shortly afterwards (`bandwhich` still running) `systemd-resolve` exited because of SIGSEGV, not an assertion error.

Kernel now is `5.10.7-arch1-1 #1 SMP PREEMPT Wed, 13 Jan 2021 12:02:01 +0000 x86_64 GNU/Linux`.

```
Jan 18 09:18:07.850081 kuro systemd[879]: Started Application launched by gsd-media-keys.
Jan 18 09:18:07.926453 kuro io.elementary.t[1233]: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook
Jan 18 09:18:07.931317 kuro systemd[879]: Started VTE child process 96295 launched by io.elementary.terminal process 1233.
Jan 18 09:18:07.933257 kuro systemd[879]: app-gnome-io.elementary.terminal-96287.scope: Succeeded.
Jan 18 09:18:10.351328 kuro kernel: device lo entered promiscuous mode
Jan 18 09:18:10.371323 kuro kernel: device enp9s0 entered promiscuous mode
Jan 18 09:18:10.391324 kuro kernel: device vpn0 entered promiscuous mode
Jan 18 09:18:12.131467 kuro /usr/lib/gdm-x-session[929]: (EE) event3  - Logitech G9x Laser Mouse: client bug: event processing lagging behind by 11ms, your system is too slow
Jan 18 09:18:25.982743 kuro /usr/lib/gdm-x-session[929]: (EE) event3  - Logitech G9x Laser Mouse: client bug: event processing lagging behind by 12ms, your system is too slow
Jan 18 09:18:40.422112 kuro systemd-resolved[468]: Using degraded feature set UDP instead of TCP for DNS server 9.9.9.9.
Jan 18 09:18:45.320427 kuro systemd[879]: Started Application launched by gsd-media-keys.
Jan 18 09:18:45.393071 kuro io.elementary.t[1233]: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook
Jan 18 09:18:45.398001 kuro systemd[879]: Started VTE child process 96349 launched by io.elementary.terminal process 1233.
Jan 18 09:18:45.399508 kuro systemd[879]: app-gnome-io.elementary.terminal-96341.scope: Succeeded.
Jan 18 09:18:45.533408 kuro syncthing[895]: [XXXXX] INFO: Established secure connection to XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX at xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/tcp-client/TLS1.3-TLS_AES_128_GCM_SHA256
Jan 18 09:18:45.533408 kuro syncthing[895]: [XXXXX] INFO: Device XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX client is "syncthing v1.10.0" named "xxxxxxxx" at xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/tcp-client/TLS1.3-TLS_AES_128_GCM_SHA256
Jan 18 09:18:46.412794 kuro systemd-resolved[468]: Using degraded feature set TCP instead of UDP for DNS server 9.9.9.9.
Jan 18 09:18:49.417878 kuro /usr/lib/gdm-x-session[929]: (EE) event3  - Logitech G9x Laser Mouse: client bug: event processing lagging behind by 11ms, your system is too slow
Jan 18 09:18:51.401227 kuro /usr/lib/gdm-x-session[929]: (EE) event3  - Logitech G9x Laser Mouse: client bug: event processing lagging behind by 12ms, your system is too slow
Jan 18 09:18:51.401628 kuro /usr/lib/gdm-x-session[929]: (EE) event3  - Logitech G9x Laser Mouse: WARNING: log rate limit exceeded (5 msgs per 60min). Discarding future messages.
Jan 18 09:19:06.449437 kuro systemd-resolved[468]: Using degraded feature set UDP instead of TCP for DNS server 9.9.9.9.
Jan 18 09:19:21.699367 kuro systemd-resolved[468]: Using degraded feature set TCP instead of UDP for DNS server 9.9.9.9.
Jan 18 09:19:47.449428 kuro systemd-resolved[468]: Using degraded feature set UDP instead of TCP for DNS server 9.9.9.9.
Jan 18 09:19:57.949344 kuro systemd-resolved[468]: Using degraded feature set TCP instead of UDP for DNS server 9.9.9.9.
Jan 18 09:20:20.425067 kuro systemd-resolved[468]: Assertion 'DNS_TRANSACTION_IS_LIVE(q->state)' failed at src/resolve/resolved-dns-query.c:485, function dns_query_complete(). Aborting.
Jan 18 09:20:20.433934 kuro systemd[1]: Started Process Core Dump (PID 96403/UID 0).
Jan 18 09:20:20.501359 kuro systemd-coredump[96404]: [🡕] Process 468 (systemd-resolve) of user 980 dumped core.
                                                     
                                                     Stack trace of thread 468:
                                                     #0  0x00007f9b63b08615 raise (libc.so.6 + 0x3d615)
                                                     #1  0x00007f9b63af1862 abort (libc.so.6 + 0x26862)
                                                     #2  0x00007f9b6432c07f n/a (libsystemd-shared-247.so + 0x5607f)
                                                     #3  0x0000556d8a09f61a n/a (systemd-resolved + 0x1361a)
                                                     #4  0x0000556d8a09f72b n/a (systemd-resolved + 0x1372b)
                                                     #5  0x00007f9b6448b5e6 n/a (libsystemd-shared-247.so + 0x1b55e6)
                                                     #6  0x00007f9b6448b97b sd_event_dispatch (libsystemd-shared-247.so + 0x1b597b)
                                                     #7  0x00007f9b6448cd31 sd_event_run (libsystemd-shared-247.so + 0x1b6d31)
                                                     #8  0x00007f9b6448cf70 sd_event_loop (libsystemd-shared-247.so + 0x1b6f70)
                                                     #9  0x0000556d8a0c4369 n/a (systemd-resolved + 0x38369)
                                                     #10 0x0000556d8a097126 n/a (systemd-resolved + 0xb126)
                                                     #11 0x00007f9b63af3152 __libc_start_main (libc.so.6 + 0x28152)
                                                     #12 0x0000556d8a0971ce n/a (systemd-resolved + 0xb1ce)
Jan 18 09:20:20.502619 kuro systemd[1]: systemd-coredump@2-96403-0.service: Succeeded.
Jan 18 09:20:20.503651 kuro systemd[1]: systemd-resolved.service: Main process exited, code=dumped, status=6/ABRT
Jan 18 09:20:20.503721 kuro systemd[1]: systemd-resolved.service: Failed with result 'core-dump'.
Jan 18 09:20:20.504363 kuro systemd[1]: systemd-resolved.service: Scheduled restart job, restart counter is at 1.
Jan 18 09:20:20.504489 kuro systemd[1]: Stopped Network Name Resolution.
Jan 18 09:20:20.505680 kuro systemd[1]: Starting Network Name Resolution...
Jan 18 09:20:20.565404 kuro systemd-resolved[96412]: Positive Trust Anchors:
Jan 18 09:20:20.565414 kuro systemd-resolved[96412]: . IN DS 20326 8 2 e06d44b80b8f1d39a95c0b0d7c65d08458e880409bbc683457104237c7f8ec8d
Jan 18 09:20:20.565443 kuro systemd-resolved[96412]: Negative trust anchors: 10.in-addr.arpa 16.172.in-addr.arpa 17.172.in-addr.arpa 18.172.in-addr.arpa 19.172.in-addr.arpa 20.172.in-addr.arpa 21.172.in-addr.arpa 22.172.in-addr.arpa 23.172.in-addr.arpa 24.172.in-addr.arpa 25.172.in-addr.arpa 26.172.in-addr.arpa 27.172.in-addr.arpa 28.172.in-addr.arpa 29.172.in-addr.arpa 30.172.in-addr.arpa 31.172.in-addr.arpa 168.192.in-addr.arpa d.f.ip6.arpa corp home internal intranet lan local private test
Jan 18 09:20:20.572161 kuro systemd-resolved[96412]: Using system hostname 'kuro'.
Jan 18 09:20:20.572554 kuro systemd-resolved[96412]: LLMNR-IPv4(TCP): There appears to be another LLMNR responder running, or previously systemd-resolved crashed with some outstanding transfers.
Jan 18 09:20:20.573345 kuro systemd[1]: Started Network Name Resolution.
Jan 18 09:20:38.431326 kuro rtkit-daemon[679]: Supervising 12 threads of 8 processes of 1 users.
Jan 18 09:20:38.431723 kuro rtkit-daemon[679]: Supervising 12 threads of 8 processes of 1 users.
Jan 18 09:20:38.432507 kuro rtkit-daemon[679]: Supervising 12 threads of 8 processes of 1 users.
Jan 18 09:20:38.432861 kuro rtkit-daemon[679]: Supervising 12 threads of 8 processes of 1 users.
Jan 18 09:20:38.435495 kuro rtkit-daemon[679]: Successfully made thread 96432 of process 1465 owned by '1000' RT at priority 10.
Jan 18 09:20:38.435514 kuro rtkit-daemon[679]: Supervising 13 threads of 9 processes of 1 users.
Jan 18 09:23:20.767154 kuro pipewire-pulse[893]: pulse-server 0x5617f31a1e60: [Firefox] UNDERFLOW channel:0 offset:62341120
Jan 18 09:23:26.213347 kuro /usr/lib/gdm-x-session[929]: (EE) client bug: timer event3 debounce short: scheduled expiry is in the past (-3ms), your system is too slow
Jan 18 09:23:38.835474 kuro rtkit-daemon[679]: Supervising 13 threads of 9 processes of 1 users.
Jan 18 09:23:38.835792 kuro rtkit-daemon[679]: Supervising 13 threads of 9 processes of 1 users.
Jan 18 09:27:15.482253 kuro rtkit-daemon[679]: Successfully made thread 96703 of process 96703 owned by '1000' high priority at nice level -11.
Jan 18 09:27:15.482271 kuro rtkit-daemon[679]: Supervising 14 threads of 10 processes of 1 users.
Jan 18 09:27:15.482745 kuro rtkit-daemon[679]: Supervising 14 threads of 10 processes of 1 users.
Jan 18 09:27:15.483206 kuro rtkit-daemon[679]: Supervising 14 threads of 10 processes of 1 users.
Jan 18 09:27:15.485741 kuro rtkit-daemon[679]: Successfully made thread 96718 of process 96703 owned by '1000' RT at priority 20.
Jan 18 09:27:15.485759 kuro rtkit-daemon[679]: Supervising 15 threads of 10 processes of 1 users.
Jan 18 09:28:24.451253 kuro kernel: systemd-resolve[96412]: segfault at 56355f9523b0 ip 000056355f9523b0 sp 00007ffc2918db98 error 15
Jan 18 09:28:24.451435 kuro kernel: Code: 00 00 21 00 00 00 00 00 00 00 41 38 32 37 34 33 32 38 37 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 61 00 00 00 00 00 00 00 <52> f9 55 63 05 00 00 00 61 2e 37 2e 61 2e 37 2e 66 2e 31 2e 38 2e
Jan 18 09:28:24.460197 kuro systemd[1]: Started Process Core Dump (PID 96749/UID 0).
Jan 18 09:28:24.529321 kuro systemd-coredump[96750]: [🡕] Process 96412 (systemd-resolve) of user 980 dumped core.
                                                     
                                                     Stack trace of thread 96412:
                                                     #0  0x000056355f9523b0 n/a (n/a + 0x0)
Jan 18 09:28:24.530536 kuro systemd[1]: systemd-coredump@3-96749-0.service: Succeeded.
Jan 18 09:28:24.531222 kuro systemd[1]: systemd-resolved.service: Main process exited, code=dumped, status=11/SEGV
Jan 18 09:28:24.531287 kuro systemd[1]: systemd-resolved.service: Failed with result 'core-dump'.
Jan 18 09:28:24.531802 kuro systemd[1]: systemd-resolved.service: Scheduled restart job, restart counter is at 2.
Jan 18 09:28:24.531901 kuro systemd[1]: Stopped Network Name Resolution.
Jan 18 09:28:24.532844 kuro systemd[1]: Starting Network Name Resolution...
Jan 18 09:28:24.600799 kuro systemd-resolved[96761]: Positive Trust Anchors:
Jan 18 09:28:24.600812 kuro systemd-resolved[96761]: . IN DS 20326 8 2 e06d44b80b8f1d39a95c0b0d7c65d08458e880409bbc683457104237c7f8ec8d
Jan 18 09:28:24.600841 kuro systemd-resolved[96761]: Negative trust anchors: 10.in-addr.arpa 16.172.in-addr.arpa 17.172.in-addr.arpa 18.172.in-addr.arpa 19.172.in-addr.arpa 20.172.in-addr.arpa 21.172.in-addr.arpa 22.172.in-addr.arpa 23.172.in-addr.arpa 24.172.in-addr.arpa 25.172.in-addr.arpa 26.172.in-addr.arpa 27.172.in-addr.arpa 28.172.in-addr.arpa 29.172.in-addr.arpa 30.172.in-addr.arpa 31.172.in-addr.arpa 168.192.in-addr.arpa d.f.ip6.arpa corp home internal intranet lan local private test
Jan 18 09:28:24.607808 kuro systemd-resolved[96761]: Using system hostname 'kuro'.
Jan 18 09:28:24.609065 kuro systemd[1]: Started Network Name Resolution.
Jan 18 09:28:27.444597 kuro kernel: device enp9s0 left promiscuous mode
Jan 18 09:28:27.564585 kuro kernel: device lo left promiscuous mode
Jan 18 09:28:27.634596 kuro kernel: device vpn0 left promiscuous mode
```

**Comment by topimiettinen** [comment]
Do you use nss-resolve? If so, can you check if #18248 fixes this?

**Comment by jdz** [comment]
> Do you use nss-resolve?

I don't think so.  But how do I check?  Is that a command, a library, a configuration option?

**Comment by topimiettinen** [comment]
It's enabled in `/etc/nsswitch.conf` by adding `resolve` to hosts line with something like below:
```
hosts:          files resolve [!UNAVAIL=return] dns
```

**Comment by jdz** [comment]
Yes, I have this line:

```
hosts: files mymachines myhostname resolve [!UNAVAIL=return] dns
```

Compiling my own systemd will have to wait, though.

**Comment by poettering** [comment]
Please provide a proper backtrace with debug symbols

**Comment by poettering** [comment]
Probably a duplicate of #16168.

**Comment by topimiettinen** [comment]
Now that #18328 was merged (which replaced #18248), there's a chance that this was also fixed.

**Comment by keszybz** [comment]
Please test #18407.

**Comment by poettering** [comment]
Pretty sure this is fixed with #18407. Pleas test, and report back if issue persists, we can reopen then.

**Comment by omexlu** [comment]
I have similiar problem, please see:
https://github.com/eventure/hide.client.linux/issues/11#issuecomment-839600038

Is there anyway to fix that, or need to wait an official fix in distro update?

**Comment by jdz** [comment]
Still getting these, also after leaving promiscuous mode when running `bandwhich` (with reverse lookups enabled).

```
$ systemctl --version
systemd 249 (249.3-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

```
Aug 20 21:34:15.512223 kernel: device enp4s0 left promiscuous mode
Aug 20 21:34:15.514224 kernel: device lo left promiscuous mode
Aug 20 21:34:18.123690 systemd[577]: vte-spawn-71535fd6-b6e5-48e3-ab60-88b8eacdc934.scope: Consumed 17.570s CPU time.
Aug 20 21:36:14.992308 systemd-resolved[546]: Assertion 'DNS_TRANSACTION_IS_LIVE(q->state)' failed at src/resolve/resolved-dns-query.c:579, function dns_query_complete(). Aborting.
Aug 20 21:36:15.022371 systemd[1]: Started Process Core Dump (PID 499031/UID 0).
Aug 20 21:36:15.065030 systemd-coredump[499032]: [🡕] Process 546 (systemd-resolve) of user 980 dumped core.

                                                 Found module linux-vdso.so.1 with build-id: 27d9b8c0c25b172c86a29351e47701c1d0676035
                                                 Found module libunistring.so.2 with build-id: 015ac6d6bcb60b7d8bea31a80d1941b06e8636ab
                                                 Found module libidn2.so.0 with build-id: 1ce2b50ad9f9821c2c629b521cf5a3c99593d332
                                                 Found module libcap-ng.so.0 with build-id: 345acbd3f1a251a101cd25c90bf0b3adb9f5c70e
                                                 Found module libaudit.so.1 with build-id: ebf0a40919d7bb093d2f3ddfd08bdfe35f2e9f18
                                                 Found module libffi.so.7 with build-id: de60e99f39569d11d09160bbdcd486cedc87d2b6
                                                 Found module libz.so.1 with build-id: 81bf6e728a6d6f5b105b0f8b25f6c614ce10452a
                                                 Found module ld-linux-x86-64.so.2 with build-id: 040cc3dd10461562f177df39e3be2f3704258c3c
                                                 Found module liblzma.so.5 with build-id: f8d607153b2b315f1aaa1c8e12553d544e661f2d
                                                 Found module libzstd.so.1 with build-id: 4b10444c1560ebc574af4d5f488b7408b22d450e
                                                 Found module libseccomp.so.2 with build-id: c6205d9cd777f122457120e4245fd802980696bb
                                                 Found module librt.so.1 with build-id: 75484da2d6f1515189eefa076e0a40328834cd16
                                                 Found module libpam.so.0 with build-id: cc094abc5e6bb62f5156ed1ff5d828957cebe46c
                                                 Found module libp11-kit.so.0 with build-id: 5314ec746546ada6f442b6fdfae15eab9f6d3cdc
                                                 Found module libmount.so.1 with build-id: 04aad53a9b4ef6947c8b39712736813b59d30256
                                                 Found module liblz4.so.1 with build-id: e63600ab23b2f6997f42fac2fa56e1f02ce159a1
                                                 Found module libkmod.so.2 with build-id: e72a955105b636f6f6fce520fe2dcf6d6c3ee1b4
                                                 Found module libip4tc.so.2 with build-id: 614c189c0dad12cfff3dd96e3ffdd698bf209fb8
                                                 Found module libdl.so.2 with build-id: 5abc547e7b0949f89f3c0e21ab0c8331a7440a8a
                                                 Found module libcrypt.so.2 with build-id: 3743451bdaf36f951f926927633fd964813025d0
                                                 Found module libcap.so.2 with build-id: d3d0ddf2f54f554fb280d7eb41a06dd39173009e
                                                 Found module libblkid.so.1 with build-id: 15cc4bc7ca545819c3f35013f9056723b24eb774
                                                 Found module libacl.so.1 with build-id: 35319ea4baa70564deddffb113c0961002bc394c
                                                 Found module libc.so.6 with build-id: 4b406737057708c0e4c642345a703c47a61c73dc
                                                 Found module libpthread.so.0 with build-id: 07c8f95b4f3251d08550217ad8a1f31066229996
                                                 Found module libgcrypt.so.20 with build-id: 4a114f6a371dee16ad6e01023b0b3c654b8582a3
                                                 Found module libcrypto.so.1.1 with build-id: 81b77a8e0b6e1c0db19644a5f120890f02762021
                                                 Found module libssl.so.1.1 with build-id: 99394a6653d9c107f2e9b730bbbfd18ed43ae3b9
                                                 Found module libm.so.6 with build-id: 2b8fd1f869ecab4e0b55e92f2f151897f6818acf
                                                 Found module libgpg-error.so.0 with build-id: ba85170c2d9343ea05eea8fa2048c212ff4ef552
                                                 Found module libsystemd-shared-249.so with build-id: 1d2f8e98fa483de825253b3c5bee49d2d6bf3d57
                                                 Found module systemd-resolved with build-id: 6d7f7a6138f9781a2403f4f9a586f7de81c76fa9
                                                 Stack trace of thread 546:
                                                 #0  0x00007f7a614ced22 raise (libc.so.6 + 0x3cd22)
                                                 #1  0x00007f7a614b8862 abort (libc.so.6 + 0x26862)
                                                 #2  0x00007f7a61d25068 n/a (libsystemd-shared-249.so + 0x5c068)
                                                 #3  0x000056136e67c23b n/a (systemd-resolved + 0xf23b)
                                                 #4  0x00007f7a61ebd2d4 n/a (libsystemd-shared-249.so + 0x1f42d4)
                                                 #5  0x00007f7a61ebd60e sd_event_dispatch (libsystemd-shared-249.so + 0x1f460e)
                                                 #6  0x00007f7a61ebec39 sd_event_run (libsystemd-shared-249.so + 0x1f5c39)
                                                 #7  0x00007f7a61ebee60 sd_event_loop (libsystemd-shared-249.so + 0x1f5e60)
                                                 #8  0x000056136e6ad7c5 n/a (systemd-resolved + 0x407c5)
                                                 #9  0x000056136e678126 n/a (systemd-resolved + 0xb126)
                                                 #10 0x00007f7a614b9b25 __libc_start_main (libc.so.6 + 0x27b25)
                                                 #11 0x000056136e6781ce n/a (systemd-resolved + 0xb1ce)
Aug 20 21:36:15.065881 systemd[1]: systemd-coredump@1-499031-0.service: Deactivated successfully.
Aug 20 21:36:15.079030 systemd[1]: systemd-resolved.service: Main process exited, code=dumped, status=6/ABRT
Aug 20 21:36:15.079085 systemd[1]: systemd-resolved.service: Failed with result 'core-dump'.
Aug 20 21:36:15.079221 systemd[1]: systemd-resolved.service: Consumed 14.246s CPU time.
Aug 20 21:36:15.079431 systemd[1]: systemd-resolved.service: Scheduled restart job, restart counter is at 1.
Aug 20 21:36:15.079496 systemd[1]: Stopped Network Name Resolution.
```

**Comment by fbriere** [comment]
I've been seeing this pop up sporadically ever since I started using resolved over a year ago.  However, due to the Debian freeze, I was usually stuck two releases behind, and thus couldn't comment on this issue, until today when (mis)fortune struck while running version 249.5-2.

See the [attached backtrace](https://github.com/systemd/systemd/files/7531155/18232.log) with debug info.  Here's also the contents of the `DnsQuery *q` argument to `dns_query_complete()`:

```c
{manager = 0x55caaed875b8, question_idna = 0x55cff1f5d010, question_utf8 = 0x55cff225f040, question_bypass = 0x0, flags = 94351609432928, ifindex = 2, auxiliary_result = 0, 
  auxiliary_for = 0x0, auxiliary_queries = 0xffffffff00000000, candidates = 0x16b2c, timeout_event_source = 0x0, answer = 0x0, answer_rcode = 0, answer_dnssec_result = DNSSEC_VALIDATED, 
  answer_query_flags = 0, answer_protocol = DNS_PROTOCOL_DNS, answer_family = 0, answer_full_packet = 0x0, answer_search_domain = 0x0, state = -1, answer_errno = -1, 
  block_ready = 4047168016, n_auxiliary_queries = 207 '\317', n_cname_redirects = 85 'U', previous_redirect_unauthenticated = false, previous_redirect_non_confidential = false, 
  previous_redirect_non_synthetic = false, request_address_valid = false, bus_request = 0x16775770640, varlink_request = 0x3d090, request_family = 0, request_address = {in = {s_addr = 0}, 
    in6 = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, bytes = '\000' <repeats 15 times>}, 
  block_all_complete = 0, request_address_string = 0x0, request_packet = 0x0, request_stream = 0x0, reply_answer = 0x0, reply_authoritative = 0x0, reply_additional = 0x0, 
  stub_listener_extra = 0x0, complete = 0x0, bus_track = 0x0, queries_next = 0x0, queries_prev = 0x0, auxiliary_queries_next = 0x0, auxiliary_queries_prev = 0x0}
```

Notice `state = -1`, which fails `assert(DNS_TRANSACTION_IS_LIVE)`.

Unfortunately, unlike @jdz, this is not something I can reproduce at will; it simply happens (seemingly) at random, sometimes several times a day, sometimes not at all over a month.

**Comment by poettering** [comment]
I tried really hard to try to reproduce this issue with current git (even installd bandwich), and couldn't. I have the suspicion this is already fixed by 97935302283729c9206b84f5e00b1aff0f78ad19, but that is already included in 249, and @fbriere suggests they saw the issue with 249 still, hence I am puzzled.

If anyone sees this issue frequently enough to make the effort worth it, it would be good to get a backtrace with full debug symbols with current systemd 249 (even better: current git main), in combination with the debug output when this happens, i.e. change systemd-resolved.service to include:

```c
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

(you can add this with `systemctl edit systemd-resolved` easily, and then restart the service).

With that data there's a good chance I can figure things out, but without it I don#t see any chance.

(to make this clear: backtraces without debug symbols are not interesting)

**Comment by poettering** [comment]
(Dropped from the v250 since not actionable for now, and hence shouldn't delay the release)

**Comment by fbriere** [comment]
(For the record, this is still present in 250.3.)

According to Valgrind, all these crashes follow from `on_query_timeout()` being called with a bad pointer, typically (though not always, I think) one that has already been freed.  Since the target of the pointer is now garbage, the circumstances of each crash may vary, but it can always be traced back to `on_query_timeout()`.

(The real question is probably who put that pointer in the event queue in the first place, but I'm not smart enough to figure that one out.)

I've now managed to reliably trigger this by running `bandwhich` (thanks @jdz!) along with 1-2 threads that constantly do reverse lookups on random IP addresses¹.  This will make `resolved` crash every ~125 seconds.  (The delay is sometimes longer, but it is surprisingly stable for what one would expect to be random behavior.)

I'm attaching a few logs (warning: over 1 MiB each) illustrating this, including Valgrind's output.  The first three ([1](https://github.com/systemd/systemd/files/8189837/1.log), [2](https://github.com/systemd/systemd/files/8189838/2.log), [3](https://github.com/systemd/systemd/files/8189839/3.log)) are consecutive crashes and represent the most common behavior.  The [next one](https://github.com/systemd/systemd/files/8189840/b.log) shows a somewhat common instance where the bogus pointer was not a previously freed `DnsQuery *` (since the size doesn't match), and the [last one](https://github.com/systemd/systemd/files/8189841/c.log) could not be traced to a freed pointer in the first place, which was more unusual.

Please let me know it there's anything further I can do to help.

¹ Something like this:
```shell
perl -le 'print join "." => map int(rand(256)) => 0..3 while 1' \
    | while read ADDR; do dig +noall -x $ADDR; done
```

**Comment by fbriere** [comment]
> (For the record, this is still present in 250.3.)

Funnily enough, I can't seem to reproduce it with `main`.  I'll look deeper to confirm if it's indeed been resolved.

**Comment by fbriere** [comment]
This was indeed fixed in 73bfd7be (which is rather obvious on hindsight).  Many thanks to @yuwata.  I assume this issue can now be closed.

**Comment by yuwata** [comment]
If this is fixed by the commit, the issue will be fixed in the next point release of v250, as the commit is backported: https://github.com/systemd/systemd-stable/commit/d82bd80cf4e7659906a502735b20a45964b55a88

**Comment by yuwata** [comment]
Indeed, from 1.log:
```
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411== Invalid read of size 4
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    at 0x118C62: UnknownInlinedFun (resolved-dns-query.c:579)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x118C62: on_query_timeout (resolved-dns-query.c:597)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x4A6403B: source_dispatch (sd-event.c:3606)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x4A6437C: UnknownInlinedFun (sd-event.c:3758)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x4A6437C: sd_event_dispatch (sd-event.c:4176)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x4A659AF: sd_event_run (sd-event.c:4244)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x4A65BC6: sd_event_loop (sd-event.c:4265)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x149F29: run (resolved.c:92)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x114C65: main (resolved.c:99)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==  Address 0x6699570 is 128 bytes inside a block of size 288 free'd
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    at 0x484217B: free (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x129C1C: UnknownInlinedFun (resolved-dns-query.c:381)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x129C1C: UnknownInlinedFun (resolved-dns-stub.c:870)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x129C1C: dns_stub_stream_complete.lto_priv.0 (resolved-dns-stub.c:858)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x128FFB: dns_stream_complete (resolved-dns-stream.c:81)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x12995F: on_stream_io (resolved-dns-stream.c:406)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x4A6407F: source_dispatch (sd-event.c:3598)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x4A6437C: UnknownInlinedFun (sd-event.c:3758)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x4A6437C: sd_event_dispatch (sd-event.c:4176)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x4A659AF: sd_event_run (sd-event.c:4244)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x4A65BC6: sd_event_loop (sd-event.c:4265)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x149F29: run (resolved.c:92)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x114C65: main (resolved.c:99)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==  Block was alloc'd at
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    at 0x483F7B5: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x11E260: UnknownInlinedFun (alloc-util.h:103)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x11E260: dns_query_new (resolved-dns-query.c:504)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x12BC31: dns_stub_process_query.lto_priv.0 (resolved-dns-stub.c:973)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x12BE93: on_dns_stub_stream_packet.lto_priv.0 (resolved-dns-stub.c:1058)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x129728: on_stream_io (resolved-dns-stream.c:417)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x4A6407F: source_dispatch (sd-event.c:3598)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x4A6437C: UnknownInlinedFun (sd-event.c:3758)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x4A6437C: sd_event_dispatch (sd-event.c:4176)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x4A659AF: sd_event_run (sd-event.c:4244)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x4A65BC6: sd_event_loop (sd-event.c:4265)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x149F29: run (resolved.c:92)
Mar 04 17:32:49 rydia valgrind[807411]: ==00:00:02:04.972 807411==    by 0x114C65: main (resolved.c:99)
```
This suggests that `on_query_timeout()` is called after the relevant query object was freed. And it should be fixed by 73bfd7be042cc63e7649242b377ad494bf74ea4b (#22430). Closing.
