### ISSUE TITLE
systemd-homed: Cannot set up authentication with a FIDO2

### ISSUE THREAD

**Issue by gibeom-gwon** [systemd/systemd#19183]
**systemd version the issue has been seen with**
 > 248

**Used distribution**
 > archlinux

**Linux kernel version used** (`uname -a`)

 > `5.11.11`-arch1-1

**CPU architecture issue was seen on**
 > AMD64

**Expected behaviour you didn't see**
 > Set up authentication with a FIDO2 key for systemd-homed based user.

**Unexpected behaviour you saw**
 > Failed to set up authentication with a FIDO2 key.

**Steps to reproduce the problem**

```
# homectl create test --storage=directory
🔐 Please enter new password for user test: ****                    
🔐 Please enter new password for user test (repeat): ****  
# homectl update test --fido2-device=auto
Initializing FIDO2 credential on security token.
👆 (Hint: This might require verification of user presence on security token.)
Generating secret key on FIDO2 security token.
Updating home directory.
Security token not inserted, refusing.
```

**Additional program output to the terminal or log subsystem illustrating the issue**

```
…
Apr 02 23:02:27 archlaptop systemd-homed[16071]: Sending to worker: {"userName":"test","disposition":"regular","perMachine":[{"storage":"directory","matchMachineId":"abcdefghijkl..."}],"fido2HmacCredential":["touM8unF3k0HmM70+Z/by/wQezQ1fwTOZKlxEftfSyg>
Apr 02 23:02:27 archlaptop systemd-homed[16071]: Successfully forked off '(sd-homework)' as PID 25966.
Apr 02 23:02:27 archlaptop systemd-homed[16071]: test: changing state inactive → updating
Apr 02 23:02:27 archlaptop systemd-homework[25966]: User record has no recovery keys, plaintext passwords not tested against it.
Apr 02 23:02:27 archlaptop systemd-homework[25966]: None of the supplied plaintext passwords unlock the user record's hashed passwords.
Apr 02 23:02:27 archlaptop systemd-homed[16071]: Worker reported error code EBADSLT.
Apr 02 23:02:27 archlaptop systemd-homed[16071]: Change operation failed: Invalid slot
Apr 02 23:02:27 archlaptop systemd-homed[16071]: Sent message type=error sender=n/a destination=:1.260 path=n/a interface=n/a member=n/a cookie=66 reply_cookie=3 signature=s error-name=org.freedesktop.home1.BadPasswordAndNoToken error-message=Password for home test is >
Apr 02 23:02:27 archlaptop systemd-homed[16071]: test: changing state updating → inactive
…
```

**Comment by poettering** [comment]
hmm, what kind of fido2 device is this?

**Comment by gibeom-gwon** [comment]
@poettering I used Solokeys. As indicated in the first line of the log, FIDO2 hmac-secret operation was successful.

**Comment by Drugantibus** [comment]
Can confirm, this also happens to me on both a Yubikey 5 NFC and Yubikey 5C. Same distro, architecture, and versions.

**Comment by poettering** [comment]
I am pretty sure this was fixed with cde2f8605e0c3842f9a87785dd758f955f2d04ba and related calls. Closing.

**Comment by gibeom-gwon** [comment]
I tested with 249, still not working.

```
# homectl update test --fido2-device=auto
Requested to lock with PIN, but FIDO2 device /dev/hidraw5 does not support it, disabling.
Initializing FIDO2 credential on security token.
👆 (Hint: This might require confirmation of user presence on security token.)
Generating secret key on FIDO2 security token.
👆 In order to allow secret key generation, please confirm presence on security token.
Updating home directory.
👆 Please confirm presence on security token.
Security token not inserted, refusing.
```
```
# homectl create test --storage=directory --fido2-device=auto
Requested to lock with PIN, but FIDO2 device /dev/hidraw5 does not support it, disabling.
Initializing FIDO2 credential on security token.
👆 (Hint: This might require confirmation of user presence on security token.)
Generating secret key on FIDO2 security token.
👆 In order to allow secret key generation, please confirm presence on security token.
🔐 Please enter new password for user test: ****                    
🔐 Please enter new password for user test (repeat): ****                    
👆 Please confirm presence on security token.
Operation on home test failed: Failed to execute operation: Resource temporarily unavailable
```
Process immediately fails after `Please confirm presence on security token.` shown.
