### ISSUE TITLE
systemd-journal-upload dies due to watchdog

### ISSUE THREAD

**Issue by DSpeichert** [systemd/systemd#2010]
It seems like systemd-journal-upload is not properly notifying watchdog, which is configured in `/lib/systemd/system/systemd-journal-upload.service`:

```
WatchdogSec=3min
```

```
Nov 23 21:58:48 goweb1 systemd[1]: Started Journal Remote Upload Service.
Nov 23 22:01:48 goweb1 systemd[1]: systemd-journal-upload.service: Watchdog timeout (limit 3min)!
Nov 23 22:01:48 goweb1 systemd[1]: systemd-journal-upload.service: Main process exited, code=dumped, status=6/ABRT
Nov 23 22:01:48 goweb1 systemd[1]: systemd-journal-upload.service: Unit entered failed state.
Nov 23 22:01:48 goweb1 systemd[1]: systemd-journal-upload.service: Failed with result 'core-dump'.
Nov 23 22:57:35 goweb1 systemd[1]: Started Journal Remote Upload Service.
Nov 23 23:00:35 goweb1 systemd[1]: systemd-journal-upload.service: Watchdog timeout (limit 3min)!
Nov 23 23:00:35 goweb1 systemd[1]: systemd-journal-upload.service: Main process exited, code=dumped, status=6/ABRT
Nov 23 23:00:35 goweb1 systemd[1]: systemd-journal-upload.service: Unit entered failed state.
Nov 23 23:00:35 goweb1 systemd[1]: systemd-journal-upload.service: Failed with result 'core-dump'.
```

```
[root@goweb1 ~]# /lib/systemd/systemd-journal-upload --version
systemd 227
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD +IDN
```

**Comment by evverx** [comment]
@DSpeichert , could you attach the result of `strace -s500 -p` on the `systemd-journal-upload` pid?

**Comment by evverx** [comment]
Looks like a starvation of the watchdog timer.
Are there any timeouts [here](https://github.com/systemd/systemd/blob/master/src/journal-remote/journal-upload.c#L499)?

**Comment by heftig** [comment]
Sounds like journal-upload should be ported to `curl_multi_perform` in order to do non-blocking uploads. Or perhaps use `curl_easy_*` from another thread.

**Comment by DSpeichert** [comment]
@evverx Emailed you the link to strace log.

**Comment by evverx** [comment]
@DSpeichert , thanks.

`poll`, `write`, `poll`, `write`, ..., `poll`, `write`, `+++ killed by SIGABRT (core dumped) +++`
It's a `Curl_poll`.
So, you have a [starvation of the watchdog timer](https://github.com/systemd/systemd/issues/2010#issuecomment-159528952).

A temporary solution: increase your `WatchdogSec` (or remove it).

**Comment by DSpeichert** [comment]
Same thing happens to systemd-journal-remote.service

**Comment by chaloulo** [comment]
PR https://github.com/systemd/systemd/pull/2923 should solve this issue.

**Comment by poettering** [comment]
Closing this as #2968 has been merged now.

**Comment by kaihendry** [comment]
This is still a problem for me on v230 
http://s.natalian.org.s3.amazonaws.com/2016-06-28/systemd-journal-remote.export
