### ISSUE TITLE
systemd-networkd failes send IPv6 Router Solicitation after restart

### ISSUE THREAD

**Issue by RoadRunnr** [systemd/systemd#2365]
On a multi homed system, networkd from git HEAD (7a92163974) fails to send Router Solicitations after it has been restarted.

From the debug log:

```
NDisc CLIENT: Error sending Router Solicitation
NDisc CLIENT: Error sending Router Solicitation
```

Reproduce with:

```
systemctl stop systemd-networkd
SYSTEMD_LOG_LEVEL=debug ./systemd-networkd
```

**Comment by poettering** [comment]
@teg?

**Comment by vindicatorr** [comment]
+1 on this I think.
I was playing around with IPv6 and was noticing that sometimes I would get it from my ISP and sometimes not.
I found that when I reboot my system, I will get the DHCPv6 (and v4) address assigned, but if I restart systemd-networkd, I am left with only v4 (and v6 link-local).

Using Archlinux systemd 228

EDIT:
Forgot to mention that I follow RoadRunnr's step and am seeing that very same response along with

```
DHCPv6 CLIENT: Next retransmission in 1s
```

**Comment by vindicatorr** [comment]
And in 229
I just compiled and installed it, rebooted and:

```
$ systemctl status systemd-networkd
● systemd-networkd.service - Network Service
   Loaded: loaded (/usr/lib/systemd/system/systemd-networkd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2016-02-12 23:45:37 CST; 1min 32s ago
     Docs: man:systemd-networkd.service(8)
 Main PID: 2120 (systemd-network)
   Status: "Processing requests..."
   CGroup: /system.slice/systemd-networkd.service
           └─2120 /usr/lib/systemd/systemd-networkd

Feb 12 23:46:40 computer systemd-networkd[2120]: br0: Starting DHCPv6 client on NDisc request failed: Invalid argument
Feb 12 23:46:43 computer systemd-networkd[2120]: br0: Starting DHCPv6 client on NDisc request failed: Invalid argument
Feb 12 23:46:47 computer systemd-networkd[2120]: br0: Starting DHCPv6 client on NDisc request failed: Invalid argument
Feb 12 23:46:50 computer systemd-networkd[2120]: br0: Starting DHCPv6 client on NDisc request failed: Invalid argument
Feb 12 23:46:53 computer systemd-networkd[2120]: br0: Starting DHCPv6 client on NDisc request failed: Invalid argument
Feb 12 23:46:56 computer systemd-networkd[2120]: br0: Starting DHCPv6 client on NDisc request failed: Invalid argument
Feb 12 23:46:59 computer systemd-networkd[2120]: br0: Starting DHCPv6 client on NDisc request failed: Invalid argument
Feb 12 23:47:03 computer systemd-networkd[2120]: br0: Starting DHCPv6 client on NDisc request failed: Invalid argument
Feb 12 23:47:06 computer systemd-networkd[2120]: br0: Starting DHCPv6 client on NDisc request failed: Invalid argument
Feb 12 23:47:09 computer systemd-networkd[2120]: br0: Starting DHCPv6 client on NDisc request failed: Invalid argument
$ systemctl --version
systemd 229
+PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
$ cat /etc/systemd/network/40-bridge.netdev 
[NetDev]
Description="Bridge Network Device"
Name=br0
Kind=bridge
$ cat /etc/systemd/network/45-bridge.network 
[Match]
Name=br0
[Network]
Description="br0 - Bridge Network"
Address=192.168.1.1/24
```

I'll build and install tag v227 and see what happens.

**Comment by cvmiller** [comment]
+1 on this. I think this may be the root cause of [#2912](https://github.com/systemd/systemd/issues/2912). If no Router Solicitation is sent out upon link up, then no RA will be sent, and IPv6 will remain unconfigured until the next RA is received.

**Comment by ssahani** [comment]
@RoadRunnr  Can you still reproduce this issue with current code?

**Comment by cvmiller** [comment]
I am traveling, and won't be able to retest until after 23 May. I will retest after I return. Thanks for looking into this.

**Comment by tomty89** [comment]
systemd v229:

case 1:

```
[tom@localhost ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.110/24 brd 192.168.1.255 scope global dynamic enp3s0
       valid_lft 86373sec preferred_lft 86373sec
    inet6 2404:c805:e00:5500:ae22:bff:fe29:e60c/64 scope global mngtmpaddr noprefixroute dynamic 
       valid_lft 1621sec preferred_lft 1621sec
    inet6 fe80::ae22:bff:fe29:e60c/64 scope link 
       valid_lft forever preferred_lft forever

[tom@localhost ~]$ sudo ip a flush enp3s0

[tom@localhost ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff

[tom@localhost ~]$ journalctl -b -f -u systemd-networkd
-- Logs begin at Wed 2016-05-04 14:49:19 HKT. --
May 15 13:20:34 localhost systemd[1]: Starting Network Service...
May 15 13:20:34 localhost systemd-networkd[222]: Enumeration completed
May 15 13:20:34 localhost systemd[1]: Started Network Service.
May 15 13:20:34 localhost systemd-networkd[222]: eth0: Renamed to enp3s0
May 15 13:20:37 localhost systemd-networkd[222]: enp3s0: Gained carrier
May 15 13:20:37 localhost systemd-networkd[222]: enp3s0: DHCPv4 address 192.168.1.110/24 via 192.168.1.1
May 15 13:20:39 localhost systemd-networkd[222]: enp3s0: Gained IPv6LL
May 15 13:20:40 localhost systemd-networkd[222]: enp3s0: Configured
^C

[tom@localhost ~]$ sudo systemctl restart systemd-networkd

[tom@localhost ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.110/24 brd 192.168.1.255 scope global dynamic enp3s0
       valid_lft 86396sec preferred_lft 86396sec

[tom@localhost ~]$ journalctl -b -f -u systemd-networkd
-- Logs begin at Wed 2016-05-04 14:49:19 HKT. --
May 15 13:20:37 localhost systemd-networkd[222]: enp3s0: DHCPv4 address 192.168.1.110/24 via 192.168.1.1
May 15 13:20:39 localhost systemd-networkd[222]: enp3s0: Gained IPv6LL
May 15 13:20:40 localhost systemd-networkd[222]: enp3s0: Configured
May 15 13:21:32 localhost systemd[1]: Stopping Network Service...
May 15 13:21:32 localhost systemd[1]: Stopped Network Service.
May 15 13:21:32 localhost systemd[1]: Starting Network Service...
May 15 13:21:32 localhost systemd-networkd[417]: Enumeration completed
May 15 13:21:32 localhost systemd[1]: Started Network Service.
May 15 13:21:32 localhost systemd-networkd[417]: enp3s0: Could not drop address: No such process
May 15 13:21:32 localhost systemd-networkd[417]: enp3s0: DHCPv4 address 192.168.1.110/24 via 192.168.1.1
^C

[tom@localhost ~]$ sudo systemctl restart systemd-networkd

[tom@localhost ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.110/24 brd 192.168.1.255 scope global dynamic enp3s0
       valid_lft 86399sec preferred_lft 86399sec

[tom@localhost ~]$ journalctl -b -f -u systemd-networkd
-- Logs begin at Wed 2016-05-04 14:49:19 HKT. --
May 15 13:21:32 localhost systemd-networkd[417]: enp3s0: DHCPv4 address 192.168.1.110/24 via 192.168.1.1
May 15 13:21:46 localhost systemd[1]: Stopping Network Service...
May 15 13:21:46 localhost systemd[1]: Stopped Network Service.
May 15 13:21:46 localhost systemd[1]: Starting Network Service...
May 15 13:21:46 localhost systemd-networkd[431]: Enumeration completed
May 15 13:21:46 localhost systemd[1]: Started Network Service.
May 15 13:21:46 localhost systemd-networkd[431]: enp3s0: Could not drop address: No such process
May 15 13:21:46 localhost systemd-networkd[431]: enp3s0: Could not drop address: No such process
May 15 13:21:46 localhost systemd-networkd[431]: enp3s0: Could not drop address: No such process
May 15 13:21:46 localhost systemd-networkd[431]: enp3s0: DHCPv4 address 192.168.1.110/24 via 192.168.1.1
^C
```

case 2:

```
[tom@localhost ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.110/24 brd 192.168.1.255 scope global dynamic enp3s0
       valid_lft 86390sec preferred_lft 86390sec
    inet6 2404:c805:e00:5500:ae22:bff:fe29:e60c/64 scope global mngtmpaddr noprefixroute dynamic 
       valid_lft 900sec preferred_lft 900sec
    inet6 fe80::ae22:bff:fe29:e60c/64 scope link 
       valid_lft forever preferred_lft forever

[tom@localhost ~]$ sudo ip l set enp3s0 down

[tom@localhost ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp3s0: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff

[tom@localhost ~]$ journalctl -b -f -u systemd-networkd
-- Logs begin at Wed 2016-05-04 14:49:19 HKT. --
May 15 13:32:51 localhost systemd-networkd[218]: Enumeration completed
May 15 13:32:51 localhost systemd[1]: Started Network Service.
May 15 13:32:51 localhost systemd-networkd[218]: eth0: Renamed to enp3s0
May 15 13:32:54 localhost systemd-networkd[218]: enp3s0: Gained carrier
May 15 13:32:54 localhost systemd-networkd[218]: enp3s0: DHCPv4 address 192.168.1.110/24 via 192.168.1.1
May 15 13:32:56 localhost systemd-networkd[218]: enp3s0: Gained IPv6LL
May 15 13:32:57 localhost systemd-networkd[218]: enp3s0: Configured
May 15 13:33:09 localhost systemd-networkd[218]: enp3s0: Lost carrier
May 15 13:33:09 localhost systemd-networkd[218]: enp3s0: DHCP lease lost
May 15 13:33:09 localhost systemd-networkd[218]: enp3s0: DHCPv6 lease lost
^C

[tom@localhost ~]$ sudo ip l set enp3s0 up

[tom@localhost ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.110/24 brd 192.168.1.255 scope global dynamic enp3s0
       valid_lft 86391sec preferred_lft 86391sec
    inet6 fe80::ae22:bff:fe29:e60c/64 scope link 
       valid_lft forever preferred_lft forever

[tom@localhost ~]$ journalctl -b -f -u systemd-networkd
-- Logs begin at Wed 2016-05-04 14:49:19 HKT. --
May 15 13:32:54 localhost systemd-networkd[218]: enp3s0: DHCPv4 address 192.168.1.110/24 via 192.168.1.1
May 15 13:32:56 localhost systemd-networkd[218]: enp3s0: Gained IPv6LL
May 15 13:32:57 localhost systemd-networkd[218]: enp3s0: Configured
May 15 13:33:09 localhost systemd-networkd[218]: enp3s0: Lost carrier
May 15 13:33:09 localhost systemd-networkd[218]: enp3s0: DHCP lease lost
May 15 13:33:09 localhost systemd-networkd[218]: enp3s0: DHCPv6 lease lost
May 15 13:33:26 localhost systemd-networkd[218]: enp3s0: Gained carrier
May 15 13:33:26 localhost systemd-networkd[218]: enp3s0: Lost carrier
May 15 13:33:29 localhost systemd-networkd[218]: enp3s0: Gained carrier
May 15 13:33:29 localhost systemd-networkd[218]: enp3s0: DHCPv4 address 192.168.1.110/24 via 192.168.1.1
^C
```

while this works:

```
[tom@localhost ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.110/24 brd 192.168.1.255 scope global dynamic enp3s0
       valid_lft 86392sec preferred_lft 86392sec
    inet6 2404:c805:e00:5500:ae22:bff:fe29:e60c/64 scope global mngtmpaddr noprefixroute dynamic 
       valid_lft 1569sec preferred_lft 1569sec
    inet6 fe80::ae22:bff:fe29:e60c/64 scope link 
       valid_lft forever preferred_lft forever

[tom@localhost ~]$ sudo ip l set enp3s0 down

[tom@localhost ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp3s0: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff

[tom@localhost ~]$ journalctl -b -f -u systemd-networkd
-- Logs begin at Wed 2016-05-04 14:49:19 HKT. --
May 15 13:36:44 localhost systemd-networkd[247]: enp3s0: Renamed to eth0
May 15 13:36:44 localhost systemd-networkd[247]: eth0: Renamed to enp3s0
May 15 13:36:44 localhost systemd[1]: Started Network Service.
May 15 13:36:47 localhost systemd-networkd[247]: enp3s0: Gained carrier
May 15 13:36:47 localhost systemd-networkd[247]: enp3s0: DHCPv4 address 192.168.1.110/24 via 192.168.1.1
May 15 13:36:48 localhost systemd-networkd[247]: enp3s0: Gained IPv6LL
May 15 13:36:50 localhost systemd-networkd[247]: enp3s0: Configured
May 15 13:37:00 localhost systemd-networkd[247]: enp3s0: Lost carrier
May 15 13:37:00 localhost systemd-networkd[247]: enp3s0: DHCP lease lost
May 15 13:37:00 localhost systemd-networkd[247]: enp3s0: DHCPv6 lease lost
^C

[tom@localhost ~]$ sudo systemctl restart systemd-networkd

[tom@localhost ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.110/24 brd 192.168.1.255 scope global dynamic enp3s0
       valid_lft 86395sec preferred_lft 86395sec
    inet6 2404:c805:e00:5500:ae22:bff:fe29:e60c/64 scope global mngtmpaddr noprefixroute dynamic 
       valid_lft 1539sec preferred_lft 1539sec
    inet6 fe80::ae22:bff:fe29:e60c/64 scope link 
       valid_lft forever preferred_lft forever

[tom@localhost ~]$ journalctl -b -f -u systemd-networkd
-- Logs begin at Wed 2016-05-04 14:49:19 HKT. --
May 15 13:37:17 localhost systemd[1]: Stopped Network Service.
May 15 13:37:18 localhost systemd[1]: Starting Network Service...
May 15 13:37:18 localhost systemd-networkd[391]: Enumeration completed
May 15 13:37:18 localhost systemd[1]: Started Network Service.
May 15 13:37:18 localhost systemd-networkd[391]: enp3s0: Gained carrier
May 15 13:37:18 localhost systemd-networkd[391]: enp3s0: Lost carrier
May 15 13:37:21 localhost systemd-networkd[391]: enp3s0: Gained carrier
May 15 13:37:21 localhost systemd-networkd[391]: enp3s0: DHCPv4 address 192.168.1.110/24 via 192.168.1.1
May 15 13:37:22 localhost systemd-networkd[391]: enp3s0: Gained IPv6LL
May 15 13:37:24 localhost systemd-networkd[391]: enp3s0: Configured
^C
```

**Comment by tomty89** [comment]
Interestingly, a down/up cycle works fine on setting up both the global and the link-local IPv6 address when systemd-networkd is not used at all:

```
[tom@localhost ~]$ systemctl status systemd-networkd
● systemd-networkd.service - Network Service
   Loaded: loaded (/usr/lib/systemd/system/systemd-networkd.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:systemd-networkd.service(8)

[tom@localhost ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp3s0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff

[tom@localhost ~]$ sudo ip l set enp3s0 up

[tom@localhost ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff
    inet6 2404:c805:e00:5500:ae22:bff:fe29:e60c/64 scope global mngtmpaddr dynamic 
       valid_lft 1543sec preferred_lft 1543sec
    inet6 fe80::ae22:bff:fe29:e60c/64 scope link 
       valid_lft forever preferred_lft forever

[tom@localhost ~]$ sudo ip l set enp3s0 down

[tom@localhost ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp3s0: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff

[tom@localhost ~]$ sudo ip l set enp3s0 up

[tom@localhost ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff
    inet6 2404:c805:e00:5500:ae22:bff:fe29:e60c/64 scope global mngtmpaddr dynamic 
       valid_lft 1520sec preferred_lft 1520sec
    inet6 fe80::ae22:bff:fe29:e60c/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by cvmiller** [comment]
Sending of RS after link up appears fixed in version 231. See issue #2912

**Comment by vindicatorr** [comment]
I don't know why it worked for you, but it still doesn't for me.

```
$ pacman -Ss systemd
...
core/systemd 231-4 [installed]
...
```

```
$ ip addr show eth0
inet <sanitized external ipv4 address>
inet6 <sanitized external ipv6 address>
inet6 <sanitized local ipv6 address>
$ sudo ip link set eth0 down
$ sudo ip link set eth0 up
$ ip addr show eth0
inet <sanitized external ipv4 address>
inet6 <sanitized local ipv6 address>
```

reboot

```
$ ip addr show eth0
inet <sanitized external ipv4 address>
inet6 <sanitized external ipv6 address>
inet6 <sanitized local ipv6 address>
$ sudo systemctl stop systemd-networkd
$ sudo SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/systemd-networkd
br0 stuff
wlan0 stuff
eth1 stuff
eth0 stuff
lo stuff
//now the important stuff
DHCPv6 CLIENT: Started in Information request mode
eth0: Acquiring DHCPv6 lease
eth0: Discovering IPv6 routers
NDISC: Started IPv6 Router Solicitation client
Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=19 reply_cookie=0 error=n/a
Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=20 reply_cookie=0 error=n/a
Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=21 reply_cookie=0 error=n/a
NDISC: Error sending Router Solicitation: Network is unreachable
NDISC: Stopping IPv6 Router Solicitation client
DHCP CLIENT (<sanitized hex?>): DISCOVER
DHCPv6 CLIENT: Next retransmission in 1s
DHCPv6 CLIENT: Next retransmission in ...<repeating>
```

**Comment by cvmiller** [comment]
I stand corrected. When I was testing, I saw the GUAs return to the interface and I could ping. However, I have now run tcpdump while bouncing the link, and I see **no** RS being sent by the host upon link up. And if I run multiple times, there are times when the GUAs are not on the interface, and ping is unsuccessful.

What I was seeing was the RA just happened to come in after link up. No RS is being sent upon link up. This is _still_ an issue. Thanks vindicatorr for catching this.

**Comment by ssahani** [comment]
@cvmiller  I can reproduce this 

> And  if I run multiple times, there are times when the GUAs are not on the interface, and ping is unsuccessful'
> 

sudo ip link set dev enp0s8 down
```
np0s8: Flags change: -UP -LOWER_UP -RUNNING
Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=63 reply_cookie=0 error=n/a
LLDP: Stopping LLDP client
enp0s8: Stopped LLDP.
enp0s8: Lost carrier
DHCP CLIENT (0x53d57973): STOPPED
enp0s8: DHCP lease lost
NDISC: Stopping IPv6 Router Solicitation client
enp0s8: State is configured, dropping config
enp0s8: Removing address: 2001:db8:1:0:a00:27ff:fe40:aadb/64 (valid for 23h 59min 45s)
enp0s8: Removing address: fe80::a00:27ff:fe40:aadb/64 (valid forever)
enp0s8: Removing address: 10.65.193.46/23 (valid for 23h 57min 43s)
```
sudo ip link set dev enp0s8 up
```
enp0s8: Flags change: +UP +LOWER_UP +RUNNING
Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=64 reply_cookie=0 error=n/a
LLDP: Started LLDP client
enp0s8: Started LLDP.
enp0s8: Gained carrier
enp0s8: Acquiring DHCPv4 lease
DHCP CLIENT (0x2854759a): STARTED on ifindex 3
Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=65 reply_cookie=0 error=n/a
Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=66 reply_cookie=0 error=n/a
DHCP CLIENT (0x2854759a): REQUEST (init-reboot)
DHCP CLIENT (0x2854759a): ACK
DHCP CLIENT (0x2854759a): lease expires in 23h 59min 57s
DHCP CLIENT (0x2854759a): T2 expires in 20h 59min 57s
DHCP CLIENT (0x2854759a): T1 expires in 11h 59min 59s
enp0s8: DHCPv4 address 10.65.193.46/23 via 10.65.193.254
enp0s8: Updating address: 10.65.193.46/23 (valid for 1d)
Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=67 reply_cookie=0 error=n/a
enp0s8: Adding address: fe80::a00:27ff:fe40:aadb/64 (valid forever)
enp0s8: Gained IPv6LL
enp0s8: Configured
Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=68 reply_cookie=0 error=n/a
enp0s8: Discovering IPv6 routers
NDISC: Started IPv6 Router Solicitation client
NDISC: Invoking callback for 't'.

***Delay is here  ***

NDISC: Received Router Advertisement: flags none preference medium lifetime 120 sec
NDISC: Invoking callback for 'r'.
NDISC: Received Router Advertisement: flags none preference medium lifetime 120 sec
NDISC: Invoking callback for 'r'.
enp0s3: Updating address: 2001:db8:1:0:a00:27ff:fe42:66ed/64 (valid for 1d)
enp0s8: Updating address: 2001:db8:1:0:a00:27ff:fe40:aadb/64 (valid for 23h 59min 58s)
```
I guess the delay is because of the the RA is received after a certain time.
`NDISC: Received Router Advertisement` and your ping goes unsuccessful.

**Comment by martyg77** [comment]
+1 here on Arch running 233.75
Easily duplicated on laptop with IPv6 over WiFi, toggle keyboard WiFi key to turn link on/off.
Here is a debug log from systemd-networkd showing coming out of suspend.
Note 5 minutes elapsed between IPv4 and IPv6 addresses being assigned.


[log.txt](https://github.com/systemd/systemd/files/1150745/log.txt)

**Comment by mvduin** [comment]
I'm still seeing this in systemd 234:

```
eth0: Gained carrier
eth0: Acquiring DHCPv4 lease
Joining mDNS multicast group on interface eth0.IPv4 with address 10.0.31.27.
DHCP CLIENT (0x8c206b4c): STARTED on ifindex 2
New relevant interface eth0.IPv4 for mDNS.
eth0: Discovering IPv6 routers
Registering new address record for 10.0.31.27 on eth0.IPv4.
NDISC: Started IPv6 Router Solicitation client
Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=28 reply_cookie=0 error=n/a
Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=29 reply_cookie=0 error=n/a
Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=30 reply_cookie=0 error=n/a
NDISC: Error sending Router Solicitation: Network is unreachable
NDISC: Stopping IPv6 Router Solicitation client
```

This is really annoying, especially since I've also seen this state get triggered by a change in network connectivity and I haven't found any way to recover from this state other than rebooting.

**Comment by ssahani** [comment]
@mvduin this is another issue please open a new Issue for this . I think you intended that ndisc client should not stop and keep on trying.  This means  sendmsg fails . does ping works ? Is there some conf error please elaborate.

**Comment by mvduin** [comment]
Uhh, why should I open a new issue when this one is still open and appears to be identical to the one I experienced?

After reboot SLAAC works fine:
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 6c:ec:eb:b9:e2:10 brd ff:ff:ff:ff:ff:ff
    inet 10.0.31.47/24 brd 10.0.31.255 scope global dynamic eth0
       valid_lft 863960sec preferred_lft 863960sec
    inet6 2001:981:5f7c:1:6eec:ebff:feb9:e210/64 scope global mngtmpaddr noprefixroute dynamic 
       valid_lft 7160sec preferred_lft 3560sec
    inet6 fe80::6eec:ebff:feb9:e210/64 scope link 
       valid_lft forever preferred_lft forever
```

then, after doing `systemctl restart systemd-networkd`, SLAAC fails:
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 6c:ec:eb:b9:e2:10 brd ff:ff:ff:ff:ff:ff
    inet 10.0.31.47/24 brd 10.0.31.255 scope global dynamic eth0
       valid_lft 863991sec preferred_lft 863991sec
    inet6 fe80::6eec:ebff:feb9:e210/64 scope link 
       valid_lft forever preferred_lft forever
```

Running networkd with debug output reveals the error shown in my previous post, indicating that networkd was unable to send an RS.

My config:
```
[Match]
Name=eth0

[Network]
DHCP=ipv4
IPv6PrivacyExtensions=no
IPv6DuplicateAddressDetection=0
LLMNR=on

[DHCP]
UseDomains=yes
```

**Comment by WGH-** [comment]
Having this on systemd 238 on Gentoo. For some weird reason, at this moment, this occurs only with wired connection, and it works fine with the wireless one. 

I've compared straces, but couldn't figure out the problem.

Wired connection:
```
socket(AF_INET6, SOCK_RAW|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_ICMPV6) = 19
setsockopt(19, SOL_ICMPV6, 1, "\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\277\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377", 32) = 0
setsockopt(19, SOL_IPV6, IPV6_ADD_MEMBERSHIP, {inet_pton(AF_INET6, "ff02::1", &ipv6mr_multiaddr), ipv6mr_interface=if_nametoindex("enp0s25")}, 20) = 0
setsockopt(19, SOL_IPV6, IPV6_MULTICAST_IF, [2], 4) = 0
setsockopt(19, SOL_IPV6, IPV6_MULTICAST_LOOP, [0], 4) = 0
setsockopt(19, SOL_IPV6, IPV6_MULTICAST_HOPS, [255], 4) = 0
setsockopt(19, SOL_IPV6, IPV6_UNICAST_HOPS, [255], 4) = 0
setsockopt(19, SOL_IPV6, IPV6_RECVHOPLIMIT, [1], 4) = 0
setsockopt(19, SOL_SOCKET, SO_TIMESTAMP, [1], 4) = 0
setsockopt(19, SOL_SOCKET, SO_BINDTODEVICE, "enp0s25", 7) = 0

sendmsg(19, {msg_name={sa_family=AF_INET6, sin6_port=htons(0), inet_pton(AF_INET6, "ff02::2", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, msg_namelen=28, msg_iov=[{iov_base="\205\0\0\0\0\0\0\0\1\1(\322Dm\365\243", iov_len=16}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = -1 ENETUNREACH (Network is unreachable)
```

Wireless connection:
```
socket(AF_INET6, SOCK_RAW|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_ICMPV6) = 21
setsockopt(21, SOL_ICMPV6, 1, "\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\277\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377", 32) = 0
setsockopt(21, SOL_IPV6, IPV6_ADD_MEMBERSHIP, {inet_pton(AF_INET6, "ff02::1", &ipv6mr_multiaddr), ipv6mr_interface=if_nametoindex("wlp3s0")}, 20) = 0
setsockopt(21, SOL_IPV6, IPV6_MULTICAST_IF, [4], 4) = 0
setsockopt(21, SOL_IPV6, IPV6_MULTICAST_LOOP, [0], 4) = 0
setsockopt(21, SOL_IPV6, IPV6_MULTICAST_HOPS, [255], 4) = 0
setsockopt(21, SOL_IPV6, IPV6_UNICAST_HOPS, [255], 4) = 0
setsockopt(21, SOL_IPV6, IPV6_RECVHOPLIMIT, [1], 4) = 0
setsockopt(21, SOL_SOCKET, SO_TIMESTAMP, [1], 4) = 0
setsockopt(21, SOL_SOCKET, SO_BINDTODEVICE, "wlp3s0", 6) = 0

sendmsg(21, {msg_name={sa_family=AF_INET6, sin6_port=htons(0), inet_pton(AF_INET6, "ff02::2", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, msg_namelen=28, msg_iov=[{iov_base="\205\0\0\0\0\0\0\0\1\1|z\221u\230~", iov_len=16}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 16
```

**Comment by WGH-** [comment]
Interesting, I can also reproduce this with plain ping:
```
$ ping ff02::2%wlp3s0 
PING ff02::2%wlp3s0(ff02::2%wlp3s0) 56 data bytes
64 bytes from fe80::YYYY:YYYY:YYYY:YYYY%wlp3s0: icmp_seq=1 ttl=64 time=20.8 ms
^C

$ ping ff02::2%enp0s25
connect: Network is unreachable

$  ip -6 route
2a02:XXXX:XXXX:XXXX::/64 dev wlp3s0 proto ra metric 2048 pref medium
fe80::/64 dev enp0s25 proto kernel metric 256 pref medium
fe80::/64 dev wlp3s0 proto kernel metric 256 pref medium
ff00::/8 dev wlp3s0 metric 256 pref medium
default via fe80::YYYY:YYYY:YYYY:YYYY dev wlp3s0 proto ra metric 2048 pref medium
```

**Comment by WGH-** [comment]
If you add `ff00::/8` route manually (`sudo ip route add ff00::/8 dev enp0s25`), multicast pings will work again. However, each time `systemd-networkd` restarts, the route disappears for some reason...

From what I've figured out it's the kernel that is responsible for both generating link-local address and adding "default multicast route". Why it doesn't do so with my wired ethernet interface is still beyond me.

**Comment by delacroix0815** [comment]
I had almost the same problem, systemd-networkd lost its ipv6 addresses after a resume from suspend. I can confirm that after recompiling the kernel with WGH's options mentioned above, systemd-networkd successfully starts the IPv6 Router Solicitation client and obtains an ipv6 address after resuming from suspend.

**Comment by eugene-bright** [comment]
I was slowly enabling kernel options to watch their effect.
The last two options which changed behaviour were:
```
CONFIG_IPV6_MULTIPLE_TABLES
CONFIG_IPV6_MROUTE_MULTIPLE_TABLES
```

Does someone know if `systemd-networkd` process RA packets by itself or it's entirely kernel work?
What behaviour is expected? Is it actually a kernel bug?

**Comment by wonderfly** [comment]
On systemd-232, `CONFIG_IPV6_MULTIPLE_TABLES=y` alone fixed the problem: I can restart `systemd-networkd` countless times and my IPV6 address sticks.

**Comment by DRiKE** [comment]
> On systemd-232, `CONFIG_IPV6_MULTIPLE_TABLES=y` alone fixed the problem: I can restart `systemd-networkd` countless times and my IPV6 address sticks.

@wonderfly, thank you: this has fixed the problem for me on two different machines. Originally, I noticed my laptop did not get an IPv6 address after resuming from suspend. Restarting systemd-networkd gave the exact same problem. CONFIG_IPV6_MULTIPLE_TABLES fixes all of that.

**Comment by ssahani** [comment]
Is this still a there or we can close this ?

**Comment by eugene-bright** [comment]
> Is this still a there or we can close this ?

The cause must be investigated further.
Ideally the issue should not be closed before [root cause analysis](https://en.m.wikipedia.org/wiki/Root_cause_analysis) is done.

**Comment by ekohl** [comment]
I can confirm it disappeared for me when I enabled `CONFIG_IPV6_MULTIPLE_TABLES` in my kernel.

**Comment by eugene-bright** [comment]
> I can confirm it disappeared for me when I enabled `CONFIG_IPV6_MULTIPLE_TABLES` in my kernel.

We found it experimentally. I personally do not know what behaviour is actually expected. I do not completely understand kernel/networkd responsibilities in the IPv6 addresses assignment process (IPv6 RA). The consultation is needed.

**Comment by cvmiller** [comment]
I too would like to see a clearer demarcation between systemd functionality and the kernel. We know that systemd is doing things that the kernel used to do (such as sending an RS when bringing an interface up). But it is unclear where systemd draws that line, since it is clearly hooked into the kernel API telling the kernel that it will handle certain functions.

In the case specifically on this issue, sending an RS after systemd-networkd restart, I would like to see an RS. A restart of systemd-networkd means it has forgotten everything, and needs to rebuild network context. Getting a timely RA (by sending an RS) is part of that rebuilding context.

**Comment by yuwata** [comment]
I think this is fixed by bd7d6cec331a00fed29d00c2498f04e83d70b19c (included in v243). If not fixed yet, please let us know. Closing.
