### ISSUE TITLE
kernel-install fails with: Error: command 'add' requires a kernel image

### ISSUE THREAD

**Issue by tgurr** [systemd/systemd#23681]
kernel-install regressed again from systemd-stable 251.1 which was/is working, into running into an error with 251.2.

**systemd version the issue has been seen with**
 > 251.2

**Used distribution**
 > Exherbo

**Linux kernel version used** (`uname -a`)

 > `Linux hostname 5.18.3 #1 SMP PREEMPT_DYNAMIC Thu Jun 9 12:23:46 CEST 2022 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
After downgrading back to systemd-stable 251.1 things work as expected:
 
```
# make && make modules_install && make install
  CALL    scripts/checksyscalls.sh
  CALL    scripts/atomic/check-atomics.sh
  DESCEND objtool
  CHK     include/generated/compile.h
Kernel: arch/x86/boot/bzImage is ready  (#1)
  DEPMOD  /lib/modules/5.18.3
sh ./arch/x86/boot/install.sh 5.18.3 \
        arch/x86/boot/bzImage System.map "/boot"
```

**Unexpected behaviour you saw**
With systemd-stable 251.2 not:
 
```
# make && make modules_install && make install
  CALL    scripts/checksyscalls.sh
  CALL    scripts/atomic/check-atomics.sh
  DESCEND objtool
  CHK     include/generated/compile.h
Kernel: arch/x86/boot/bzImage is ready  (#1)
  DEPMOD  /lib/modules/5.18.3
sh ./arch/x86/boot/install.sh 5.18.3 \
        arch/x86/boot/bzImage System.map "/boot"
Error: command 'add' requires a kernel image
make: *** [arch/x86/Makefile:274: install] Error 1
```

**Steps to reproduce the problem**
 
1. Download kernel source tarball, copy over .config and alter the /usr/src/linux symlink
2. run # make && make modules_install && make install
3. observe error message stated above

**Comment by medhefgo** [comment]
I'm pretty sure this is already fixed in -stable by https://github.com/systemd/systemd-stable/commit/c6dd6afe027209f4f9025671e0814d1acd277c69

**Comment by tgurr** [comment]
> I'm pretty sure this is already fixed in -stable by [systemd/systemd-stable@c6dd6af](https://github.com/systemd/systemd-stable/commit/c6dd6afe027209f4f9025671e0814d1acd277c69)

As I'm experiencing the issue with 251.2 which ships with the commit https://github.com/systemd/systemd-stable/commit/c6dd6afe027209f4f9025671e0814d1acd277c69 you've mentioned it's apprently not fixed?
