### ISSUE TITLE
journalctl --vacuum-* --directory… does not remove anything in remote journal storage

### ISSUE THREAD

**Issue by mbunkus** [systemd/systemd#2376]
I'm running systemd-journal-remote and let it write to the default location, `/var/log/journal/remote`. There are currently 589 files in that directory occupying ~17.6 GB:

```
[0 root@belgarath /var/log/journal/remote] ls | tail
remote-belgarath@ff20107109a142fd886d3a7c8c475e99-0000000000ac95b5-0005281c99bd5dab.journal
remote-belgarath@ff20107109a142fd886d3a7c8c475e99-0000000000ad6fd5-000527de525eda3f.journal
remote-belgarath@ff20107109a142fd886d3a7c8c475e99-0000000000ae247d-00052810e90ba858.journal
remote-belgarath@ff20107109a142fd886d3a7c8c475e99-0000000000ae49db-00052822978bb591.journal
remote-belgarath@ff20107109a142fd886d3a7c8c475e99-0000000000ae522e-00052822b1f39c2d.journal
remote-belgarath@ff20107109a142fd886d3a7c8c475e99-0000000000ae5d6d-0005281c99bd5dab.journal
remote-belgarath@ff20107109a142fd886d3a7c8c475e99-0000000000b03901-000528b8640a16c4.journal
remote-belgarath@ff20107109a142fd886d3a7c8c475e99-0000000000b0fa3b-000528f7b0b38f00.journal
remote-belgarath@ff20107109a142fd886d3a7c8c475e99-0000000000b310c5-000529ab4ae84568.journal
remote-belgarath.journal
[0 root@belgarath /var/log/journal/remote] journalctl --directory=/var/log/journal/remote --disk-usage
Archived and active journals take up 17.6G on disk.
[0 root@belgarath /var/log/journal/remote]
```

I would very much like to use the various `--vacuum-*` options to `journalctl` but they don't do anything at all with those files:

```
[0 root@belgarath /var/log/journal/remote] journalctl --directory=/var/log/journal/remote --vacuum-size=1G
[0 root@belgarath /var/log/journal/remote] ls | wc -l
589
[0 root@belgarath /var/log/journal/remote] journalctl --directory=/var/log/journal/remote --disk-usage
Archived and active journals take up 17.6G on disk.
[0 root@belgarath /var/log/journal/remote] journalctl --directory=/var/log/journal/remote --vacuum-time='1 day'
[0 root@belgarath /var/log/journal/remote] journalctl --directory=/var/log/journal/remote --disk-usage
Archived and active journals take up 17.6G on disk.
[0 root@belgarath /var/log/journal/remote]
```

I can see `journalctl` accessing all those archived files if I `strace` it, so it does seem to work on the right directory at least:

```
[0 root@belgarath /var/log/journal/remote] strace -e trace=open journalctl --directory=/var/log/journal/remote --vacuum-size=1G |& tail
open("/var/log/journal/remote/remote-belgarath@ff20107109a142fd886d3a7c8c475e99-0000000000ad6fd5-000527de525eda3f.journal", O_RDONLY|O_CLOEXEC) = 584
open("/var/log/journal/remote/remote-belgarath@ff20107109a142fd886d3a7c8c475e99-0000000000ae247d-00052810e90ba858.journal", O_RDONLY|O_CLOEXEC) = 585
open("/var/log/journal/remote/remote-belgarath@ff20107109a142fd886d3a7c8c475e99-0000000000ae49db-00052822978bb591.journal", O_RDONLY|O_CLOEXEC) = 586
open("/var/log/journal/remote/remote-belgarath@ff20107109a142fd886d3a7c8c475e99-0000000000ae522e-00052822b1f39c2d.journal", O_RDONLY|O_CLOEXEC) = 587
open("/var/log/journal/remote/remote-belgarath@ff20107109a142fd886d3a7c8c475e99-0000000000ae5d6d-0005281c99bd5dab.journal", O_RDONLY|O_CLOEXEC) = 588
open("/var/log/journal/remote/remote-belgarath@ff20107109a142fd886d3a7c8c475e99-0000000000b03901-000528b8640a16c4.journal", O_RDONLY|O_CLOEXEC) = 589
open("/var/log/journal/remote/remote-belgarath@ff20107109a142fd886d3a7c8c475e99-0000000000b0fa3b-000528f7b0b38f00.journal", O_RDONLY|O_CLOEXEC) = 590
open("/var/log/journal/remote/remote-belgarath@ff20107109a142fd886d3a7c8c475e99-0000000000b310c5-000529ab4ae84568.journal", O_RDONLY|O_CLOEXEC) = 591
open("/var/log/journal/remote/remote-belgarath.journal", O_RDONLY|O_CLOEXEC) = 592
+++ exited with 0 +++
[0 root@belgarath /var/log/journal/remote]
```

Is this supposed to work? Is the only way to actually remove entries from a remote journal storage the manual `rm remote-belgarath@*.journal` or something like that?

Thanks.

**Comment by poettering** [comment]
The vacuuming doesn't take --directory= into account, but it probably indeed should.

**Comment by MeanderingCode** [comment]
I am guessing that "RFE" is "Request for Enhancement".

I think this might be a candidate for a bug, since journald is responsible for the local logs being sent into systemd-journal-remote.

Additionally, is there information as to whether the local storage quota is respected?

**Comment by amenzhinsky** [comment]
Seems like it's fixed already, at least it works with v232

```
$ journalctl -D ../journal2 --vacuum-size 50M                                                                      
Journal file ../journal2/a8377aabed5f878cc25b515753270e90/system@ef3df322a24d47a683e46fd9f7271dfd-00000000151e7e8d-00054bbc85a33919.journal is truncated, igno
ring file.
Deleted archived journal ../journal2/a8377aabed5f878cc25b515753270e90/system@ef3df322a24d47a683e46fd9f7271dfd-00000000151e7e8d-00054bbc85a33919.journal (6.7M)
.
Deleted archived journal ../journal2/a8377aabed5f878cc25b515753270e90/system@ef3df322a24d47a683e46fd9f7271dfd-00000000151ff1e2-00054bbcc817cfce.journal (80.4M
).
Deleted archived journal ../journal2/a8377aabed5f878cc25b515753270e90/system@ef3df322a24d47a683e46fd9f7271dfd-0000000015216333-00054bbd070d6200.journal (80.4M
).
Vacuuming done, freed 167.5M of archived journals from ../journal2/a8377aabed5f878cc25b515753270e90.
```

**Comment by poettering** [comment]
OK, if this is already fixed, then let's close this.

**Comment by mbunkus** [comment]
For me the problem persists, and I'm using v232, too.

Current directory content and size:

```
[0 root@belgarath ~] ls -lrt /var/log/journal/remote|head -n 3
total 2334816
-rw-r-----+ 1 systemd-journal-remote systemd-journal-remote 100663296 Jan 28 08:41 remote@7ac14b77a52c4fe192636906460f5ea1-0000000000403c3f-00054711b7700914.journal
-rw-r-----+ 1 systemd-journal-remote systemd-journal-remote 109051904 Jan 29 15:32 remote@7ac14b77a52c4fe192636906460f5ea1-00000000004174ea-00054722b686bf85.journal
[0 root@belgarath ~] du -sh /var/log/journal/remote
2,3G    /var/log/journal/remote
[0 root@belgarath ~] ls /var/log/journal/remote|wc -l
24
```

Vacuuming by time doesn't work:

```
[0 root@belgarath ~] journalctl -D /var/log/journal/remote --vacuum-time='30 days'
[0 root@belgarath ~] du -sh /var/log/journal/remote
2,3G    /var/log/journal/remote
[0 root@belgarath ~] ls /var/log/journal/remote|wc -l
24
```

Vacuuming by size doesn't work either:

```
[0 root@belgarath ~] journalctl -D /var/log/journal/remote --vacuum-size='1G'
[0 root@belgarath ~] du -sh /var/log/journal/remote
2,3G    /var/log/journal/remote
[0 root@belgarath ~] ls /var/log/journal/remote|wc -l
24
```

**Comment by poettering** [comment]
ok, reopening

(please always verify these things on the most recently released version though, please, which is 233 by now)

**Comment by amenzhinsky** [comment]
```
$ journalctl -D /var/log/journal/remote --disk-usage
Archived and active journals take up 418.0M in the file system.
$ sudo journalctl -D /var/log/journal/remote --vacuum-size 100M
Deleted archived journal /var/log/journal/remote/a8377aabed5f878cc25b515753270e90/system@ef3df322a24d47a683e46fd9f7271dfd-0000000017e1d904-00054bf27ca5eec3.journal (80.4M).
Deleted archived journal /var/log/journal/remote/a8377aabed5f878cc25b515753270e90/system@ef3df322a24d47a683e46fd9f7271dfd-0000000017e352b6-00054bf28bd2d5ca.journal (80.4M).
Deleted archived journal /var/log/journal/remote/a8377aabed5f878cc25b515753270e90/system@ef3df322a24d47a683e46fd9f7271dfd-0000000017e4c6a9-00054bf29c3a7359.journal (80.4M).
Deleted archived journal /var/log/journal/remote/a8377aabed5f878cc25b515753270e90/system@ef3df322a24d47a683e46fd9f7271dfd-0000000017e64011-00054bf2ac172656.journal (80.4M).
Vacuuming done, freed 321.6M of archived journals from /var/log/journal/remote/a8377aabed5f878cc25b515753270e90.
$ journalctl -D /var/log/journal/remote --disk-usage
Archived and active journals take up 96.4M in the file system.
```
```
$ journalctl --version
systemd 232
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

**Comment by poettering** [comment]
@mbunkus coudl you please check with "strace" what journalctl is doing for you, if this doesn't work? does it show unlink/unlinkat calls that fail?

**Comment by mbunkus** [comment]
Sure! [Here it is.](https://gist.github.com/mbunkus/9510ac95deb81222b843c062a6c1015f) No `unlink`/`unlinkat` calls at all.

In the meantime I've tried several other things without any success:

* On two different Arch Linux installations with v232, nothing happens.
* On one Ubuntu 16.10 installation with v231 nothing happens.
* Copying the directory somewhere else doesn't work either.
* Stopping `systemd-journal-remote.service` and `systemd-journal-remote.socket` before running `journalctl` doesn't make a difference either.

**Comment by amenzhinsky** [comment]
Using `SYSTEMD_LOG_LEVEL=debug` on one of my affected machines `journalctl` gives me the following output:

```
...
Failed to open journal file /var/log/journal/remote/remote-138.201.34.149@d0493c52174f443bb4f4a2e0a4780438-00000000149616c9-00054bc41e6a60d3.journal: Protocol not supported
Journal file /var/log/journal/remote/remote-138.201.34.149@d0493c52174f443bb4f4a2e0a4780438-000000001307ef42-00054b9aa0e09752.journal uses incompatible flag xz-compressed disabled at compilation time.
Failed to open journal file /var/log/journal/remote/remote-138.201.34.149@d0493c52174f443bb4f4a2e0a4780438-000000001307ef42-00054b9aa0e09752.journal: Protocol not supported
Journal file /var/log/journal/remote/remote-138.201.34.149@d0493c52174f443bb4f4a2e0a4780438-0000000016aa2e7b-00054bed4994e9cc.journal uses an unsupported feature, ignoring file.
...
```

But that's most likely because of journal-remote and journalctl versions difference.

**Comment by mbunkus** [comment]
Ah, I didn't know about that flag. Here's some output from my server:

```
[0 root@belgarath ~] SYSTEMD_LOG_LEVEL=debug journalctl -D /var/log/journal/remote --vacuum-size=1G
Root directory /var/log/journal/remote added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-00000000004e69b9-0005489cea8f31aa.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-000000000051671c-0005490d19df5ac6.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-000000000042fe2e-0005473c92b0199e.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-000000000052f221-000549454e6496c6.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-00000000004b7ac2-0005481a7befe5b0.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-000000000058fe7b-00054a367674066c.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-00000000005a7dda-00054a6d87f26a88.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-0000000000403c3f-00054711b7700914.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-0000000000609027-00054b65aa2413f8.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-000000000049b7db-000547f438d405aa.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-000000000044c7fb-0005476ca4ab99f3.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-0000000000577901-000549fd9437b819.journal added.
File /var/log/journal/remote/remote.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-00000000005471a5-0005497f68e74c71.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-00000000004cf0f5-0005485f30c9faf2.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-000000000055f7b7-000549c0d72d4498.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-0000000000468c10-0005479560316e96.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-00000000004174ea-00054722b686bf85.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-00000000004fed20-000548d815eed029.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-0000000000621dcc-00054b9d2c712e10.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-00000000005f0c58-00054b265a20f921.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-00000000005d83fd-00054ae3078e75be.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-00000000005c050e-00054aae60af4729.journal added.
File /var/log/journal/remote/remote@7ac14b77a52c4fe192636906460f5ea1-000000000048185e-000547caa4cf8d90.journal added.
Root directory /var/log/journal/remote removed.
mmap cache statistics: 0 hit, 24 miss
```

I can read the content of those journal files just fine with `journalctl -D /var/log/journal/remote`, BTW.

**Comment by dontdieych** [comment]
Arch
systemd-239.2

exact same problem.

```
a@a ~> du -sh /var/log/journal/remote
985M    /var/log/journal/remote

a@a ~> journalctl -D /var/log/journal/remote --disk-usage
Archived and active journals take up 984.0M in the file system.

a@a ~> journalctl -D /var/log/journal/remote --vacuum-size=100M

a@a ~> du -sh /var/log/journal/remote
985M    /var/log/journal/remote

a@a ~> journalctl -D /var/log/journal/remote --disk-usage
Archived and active journals take up 984.0M in the file system.

a@a ~> env SYSTEMD_LOG_LEVEL=debug journalctl -D /var/log/journal/remote --vacuum-size=100M
Considering root directory '/var/log/journal/remote'.
Root directory /var/log/journal/remote added.
Journal effective settings seal=no compress=no compress_threshold_bytes=8B
File /var/log/journal/remote/remote-192.168.2.1@3638afa9e239421bb4a722bb33d3ee33-00000000000488ee-00056be0e90172e5.journal added.
Journal effective settings seal=no compress=no compress_threshold_bytes=8B
File /var/log/journal/remote/remote-192.168.2.1.journal added.
Journal effective settings seal=no compress=no compress_threshold_bytes=8B
File /var/log/journal/remote/remote-192.168.2.1@3638afa9e239421bb4a722bb33d3ee33-00000000000e12b1-000578b91d841e21.journal added.
Journal effective settings seal=no compress=no compress_threshold_bytes=8B
File /var/log/journal/remote/remote-192.168.2.1@3638afa9e239421bb4a722bb33d3ee33-0000000000089166-00057228c4fca621.journal added.
Journal effective settings seal=no compress=no compress_threshold_bytes=8B
File /var/log/journal/remote/remote-192.168.2.1@3638afa9e239421bb4a722bb33d3ee33-000000000009476e-000574c021d4683d.journal added.
Journal effective settings seal=no compress=no compress_threshold_bytes=8B
File /var/log/journal/remote/remote-192.168.2.1@3638afa9e239421bb4a722bb33d3ee33-00000000000247b9-00056be0427801e2.journal added.
Journal effective settings seal=no compress=no compress_threshold_bytes=8B
File /var/log/journal/remote/remote-192.168.2.1@3638afa9e239421bb4a722bb33d3ee33-000000000007daa6-00056f6c0d95b393.journal added.
Journal effective settings seal=no compress=no compress_threshold_bytes=8B
File /var/log/journal/remote/remote-192.168.2.1@3638afa9e239421bb4a722bb33d3ee33-00000000000cf176-00056be0735547f1.journal added.
Journal effective settings seal=no compress=no compress_threshold_bytes=8B
File /var/log/journal/remote/remote-192.168.2.1@3638afa9e239421bb4a722bb33d3ee33-000000000006c844-00056be178593d61.journal added.
Journal effective settings seal=no compress=no compress_threshold_bytes=8B
File /var/log/journal/remote/remote-192.168.2.1@3638afa9e239421bb4a722bb33d3ee33-00000000000aaf51-00056bdfcdffc4fd.journal added.
Journal effective settings seal=no compress=no compress_threshold_bytes=8B
File /var/log/journal/remote/remote-192.168.2.1@3638afa9e239421bb4a722bb33d3ee33-0000000000000001-00056bdc7ea9e237.journal added.
Root directory /var/log/journal/remote removed.
mmap cache statistics: 0 hit, 11 miss
a@a ~>

**Comment by dontdieych** [comment]
I've found some messages from log. Those msgs are relevant?

```
Nov 03 12:05:24 a systemd[1]: Started Journal Remote Sink Service.
Nov 03 12:07:17 a systemd-journal-remote[28254]: /var/log/journal/remote//remote-192.168.2.1.journal: Journal header limits reached or header out-of-date, rotating
Nov 03 12:14:16 a systemd-journal-remote[28254]: /var/log/journal/remote//remote-192.168.2.1.journal: Journal header limits reached or header out-of-date, rotating
Nov 03 12:15:40 a systemd-journal-remote[28254]: /var/log/journal/remote//remote-192.168.2.1.journal: Journal header limits reached or header out-of-date, rotating

**Comment by ikelos** [comment]
This issue hasn't been reopened as suggested on March 30 2017.  Could someone please reopen it?  It still affects CentOS 7.5, and the journal does not adhere to limits (#5242), so this is a reasonable issue to still have present.

**Comment by poettering** [comment]
I wonder if this is just another instance of #1017, and hence now fixed by #10525?

**Comment by disaster123** [comment]
Has anybody found a solution or workaround for this? On Debian Stretch this doesn't work either and my remote folder is exploding.

```
...
Archived and active journals take up 291.2G in the file system.
Root directory /var/log/journal/remote removed.
mmap cache statistics: 0 hit, 3934 miss
```

**Comment by mbunkus** [comment]
Yeah, this issue isn't resolved at all, even though it's been closed for a while now. The problem persists with systemd 240. @poettering can you please re-open the issue? It seems clear to me from the reports from multiple users that the issue hasn't been fixed. Thanks.

> Can I just delete the older files manually in the remote directory or what would be the best workaround for this?

That's the workaround I've been using since reporting this issue; a simple

```
/usr/bin/find /var/log/journal/remote -type f -mtime +60 -delete
```

is what I do for deleting files older than 60 days.

**Comment by ikelos** [comment]
So the logic for opening a directory in journalctl uses `sd_journal_open_directory` which then (likely) calls `add_root_directory` which typically sets `d->is_root` to true.

The comment in `add_root_directory` is that `is_root` seems to be used for inotify, rather than being the *root* directory (`/`).

```
        /* Adds a root directory to our set of directories to use. If the root directory is already in the set, we
         * update the inotify logic, and renumerate the directory entries. This call may hence be called to initially
         * populate the set, as well as to update it later. */
```

It's therefore unclear why this check would be here (is vacuuming an inotify-root directory bad?), or what it was intended to prevent?  It's also about the only use of `is_root` outside of `sd-journal.c`, which struck me as a little odd, but it's been there since 2014...

@poettering Could you please re-open this issue, and maybe look at whether this logic is necessary/working appropriately?

**Comment by saez0pub** [comment]
@poettering It seems you forgot to reopen this issue, I confirm this is still present on version 239.

```
root:~# journalctl --version
systemd 239
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
root:~# date
Wed May 22 13:02:56 UTC 2019
root:~# du -hs /var/log/journal/remote/
120G	/var/log/journal/remote/
root:~# journalctl -D /var/log/journal/remote/ --disk-usage
Archived and active journals take up 119.6G in the file system.
root:~# journalctl -D /var/log/journal/remote/ | head -1
-- Logs begin at Tue 2019-04-30 15:50:55 UTC, end at Wed 2019-05-22 13:02:56 UTC. --
root:~# journalctl -D /var/log/journal/remote/ --vacuum-time="1h"
root:~# du -hs /var/log/journal/remote/
120G	/var/log/journal/remote/
root:~# journalctl -D /var/log/journal/remote/ --disk-usage
Archived and active journals take up 119.6G in the file system.
root:~# journalctl -D /var/log/journal/remote/ | head -1
-- Logs begin at Tue 2019-04-30 15:50:55 UTC, end at Wed 2019-05-22 13:02:56 UTC. --
```

Is deleting archived files by another method like rm is safe ?

**Comment by mbiebl** [comment]
Re-opening, given the feedback. @mbunkus, @ikelos : would be great if you can test with the latest upstream version, just to confirm this is still unfixed.

**Comment by mbunkus** [comment]
I'm not using `systemd-journal-remote` anymore, so I cannot reproduce the exact setup I had before, That being said, a quick test with a copy of my `/var/log/journal` shows vacuuming by size with a custom directory working fine now:

```
[0 root@sweet-chili ~] du -sh test-storage/
4,0G    test-storage/
[0 root@sweet-chili ~] journalctl --directory=$HOME/test-storage --vacuum-size=2G
Vacuuming done, freed 0B of archived journals from /root/test-storage.
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/system@fcd7d8a97c23439cb9969965a4c8a162-00000000024358d3-00059d68d79e65f6.journal (24.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/user-1000@52f5ad249cfa4e6cb1dc058966f4e9f5-000000000245dd54-00059d71c6d4daef.journal (128.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/system@fcd7d8a97c23439cb9969965a4c8a162-000000000245de72-00059d71c784ce9f.journal (24.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/user-1000@52f5ad249cfa4e6cb1dc058966f4e9f5-0000000002487731-00059d7bbe30629a.journal (128.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/system@fcd7d8a97c23439cb9969965a4c8a162-0000000002487762-00059d7bbe34ee35.journal (24.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/user-1000@52f5ad249cfa4e6cb1dc058966f4e9f5-00000000024b14bf-00059d86a28ebfc5.journal (128.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/system@fcd7d8a97c23439cb9969965a4c8a162-00000000024b1c72-00059d86a29ebca1.journal (24.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/user-1000@52f5ad249cfa4e6cb1dc058966f4e9f5-00000000024da392-00059d8fe30f074f.journal (128.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/system@fcd7d8a97c23439cb9969965a4c8a162-00000000024db506-00059d8fe36e95dc.journal (24.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/user-1000@52f5ad249cfa4e6cb1dc058966f4e9f5-0000000002503f6f-00059d99f560c9d6.journal (128.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/system@fcd7d8a97c23439cb9969965a4c8a162-0000000002503fc2-00059d99f56ba1cc.journal (32.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/user-1000@52f5ad249cfa4e6cb1dc058966f4e9f5-00000000025311c5-00059da838917b2f.journal (128.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/system@fcd7d8a97c23439cb9969965a4c8a162-000000000253152f-00059da838ac32e5.journal (24.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/user-1000@52f5ad249cfa4e6cb1dc058966f4e9f5-000000000255a97f-00059db31d7d016b.journal (128.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/system@fcd7d8a97c23439cb9969965a4c8a162-000000000255b199-00059db31d81497d.journal (24.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/user-1000@52f5ad249cfa4e6cb1dc058966f4e9f5-00000000025849fb-00059dbdf8416064.journal (128.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/system@fcd7d8a97c23439cb9969965a4c8a162-00000000025849fd-00059dbdf84cb22d.journal (24.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/user-1000@52f5ad249cfa4e6cb1dc058966f4e9f5-00000000025ada98-00059dc7c567e4d6.journal (128.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/system@fcd7d8a97c23439cb9969965a4c8a162-00000000025adaa2-00059dc7c7a52fee.journal (24.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/user-1000@52f5ad249cfa4e6cb1dc058966f4e9f5-00000000025d79e2-00059dd2f3c817dd.journal (128.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/system@fcd7d8a97c23439cb9969965a4c8a162-00000000025d83a5-00059dd2f3d9f35f.journal (24.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/user-1000@52f5ad249cfa4e6cb1dc058966f4e9f5-00000000026001c7-00059ddc220c30b2.journal (128.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/system@fcd7d8a97c23439cb9969965a4c8a162-00000000026001f9-00059ddc221485b7.journal (24.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/user-1000@52f5ad249cfa4e6cb1dc058966f4e9f5-00000000026297a4-00059de63a113a31.journal (128.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/system@fcd7d8a97c23439cb9969965a4c8a162-0000000002629d02-00059de63a311d4e.journal (24.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/user-1000@52f5ad249cfa4e6cb1dc058966f4e9f5-000000000265255a-00059df03ffe1b7a.journal (128.0M).
Vacuuming done, freed 1.9G of archived journals from /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d.
[0 root@sweet-chili ~] du -sh test-storage/
2,1G    test-storage/
[0 root@sweet-chili ~] journalctl --directory=$HOME/test-storage/ac44a214c6aa464fa67f0f7548d48d1d --vacuum-size=1G
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/system@fcd7d8a97c23439cb9969965a4c8a162-00000000026534bc-00059df040e763e3.journal (24.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/user-1000@52f5ad249cfa4e6cb1dc058966f4e9f5-000000000267b691-00059df983152c6e.journal (128.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/system@fcd7d8a97c23439cb9969965a4c8a162-000000000267bd22-00059df983c7a7b3.journal (24.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/user-1000@52f5ad249cfa4e6cb1dc058966f4e9f5-00000000026a41fc-00059e035d5019bf.journal (128.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/system@fcd7d8a97c23439cb9969965a4c8a162-00000000026a42b5-00059e03600c3b36.journal (24.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/user-1000@52f5ad249cfa4e6cb1dc058966f4e9f5-00000000026cd671-00059e0cc66ba10c.journal (128.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/system@fcd7d8a97c23439cb9969965a4c8a162-00000000026ce2ee-00059e0cc693ec4e.journal (24.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/user-1000@52f5ad249cfa4e6cb1dc058966f4e9f5-00000000026f6061-00059e160370f817.journal (128.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/system@fcd7d8a97c23439cb9969965a4c8a162-00000000026f64a9-00059e16038b43f4.journal (24.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/user-1000@52f5ad249cfa4e6cb1dc058966f4e9f5-000000000271f664-00059e20118cb5cc.journal (128.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/system@fcd7d8a97c23439cb9969965a4c8a162-000000000271fe48-00059e2011a3acf5.journal (24.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/user-1000@52f5ad249cfa4e6cb1dc058966f4e9f5-0000000002748956-00059e29a73bd898.journal (128.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/system@fcd7d8a97c23439cb9969965a4c8a162-00000000027489af-00059e29aa631181.journal (24.0M).
Deleted archived journal /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d/user-1000@52f5ad249cfa4e6cb1dc058966f4e9f5-0000000002771b02-00059e334aea93b8.journal (128.0M).
Vacuuming done, freed 1.0G of archived journals from /root/test-storage/ac44a214c6aa464fa67f0f7548d48d1d.
[0 root@sweet-chili ~] du -sh test-storage/
992M    test-storage/
```

This is:

```
[0 root@sweet-chili ~] systemctl --version
systemd 244 (244.2-2-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

So it looks like this was fixed some time between v239 and v244. Nice!

**Comment by mbiebl** [comment]
Thanks for reporting back. Closing the bug report as per your feedback.
