### ISSUE TITLE
Make possible to disable shutdown wall messages

### ISSUE THREAD

**Issue by Diamondemon** [systemd/systemd#23769]
**Is your feature request related to a problem? Please describe.**
It seems that since [this commit](https://github.com/systemd/systemd/commit/adefc8789b63225662e50ceaa282f9553b5c64eb) at version 251, systemd always displays a wall message when shutting down. 
I know this is intentional, but this is actually getting annoying. I (and other users on r/Archlinux) liked the silent shutdown that I had before.

**Describe the solution you'd like**
Would it be possible to have a config file (or line of a config file) to enable/disable the wall message ?

**Describe alternatives you've considered**
Apart from ignoring it, I don't think there is much for me to do. But ignoring wall messages on shutdown would mean ignoring errors that sometime happen on shutdown.

**The systemd version you checked that didn't have the feature you are asking for**
v251

**Comment by yuwata** [comment]
Already fixed by #23574.

**Comment by adastx** [comment]
> Already fixed by #23574.

I am using systemd 251 (251.2-1-arch), and I still get these messages on shutdown/reboot.

I thought this was fixed?
