### ISSUE TITLE
switch-root only works onto mount points, not regular dirs, hence make them bind mount automatically if needed

### ISSUE THREAD

**Issue by safinaskar** [systemd/systemd#23807]
My system is debian sid (last time I did dist-upgrade is 2022-01-10) running inside qemu. systemd version is 251. I type this command to create temporary debian rootfs (today, i. e. 2022-06-22):
```bash
sudo debootstrap sid /debian
```
Then I do this:
```bash
sudo systemctl switch-root /debian /bin/bash
```
This command kills everything and leaves /bin/bash running in /dev/console. But prompt looks strange: `root@throw:/debian`. Then I type `ls` and `ls /` and it is clear from the output that root switching actually did not happen. I. e. `/debian` file system was not moved to `/`.

Note that /debian is on same file system as /. If this is not allowed, then systemctrl should simply print error message, but it did not.

**systemd version the issue has been seen with**
 > 251

**Used distribution**
 > Debian

**Linux kernel version used** (`uname -a`)
 > `Linux throw 5.15.0-2-amd64 #1 SMP Debian 5.15.5-2 (2021-12-18) x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Prompt should be `root@throw:/`, new file system should be mounted on /

**Unexpected behaviour you saw**
 > Prompt is `root@throw:/debian`, old root file system mounted on /

**Comment by yuwata** [comment]
Could you call systemctl with `SYSTEMD_LOG_LEVEL=debug`?

**Comment by yuwata** [comment]
It seems that currently we do not support switching root on the same fs.
Changing the label from bug to RFE.

**Comment by poettering** [comment]
Does it work if you make /debian a bind mount onto itself first?

**Comment by safinaskar** [comment]
> Does it work if you make /debian a bind mount onto itself first?

Yes.

Also, I don't need switch-root working on same fs. I just need proper error handling. Just print error message instead of killing everything, please

**Comment by poettering** [comment]
I'd rather just make this work tbh. should be easy to implicitly make a bind mount if it isn't one yet.

**Comment by poettering** [comment]
fixed by f717d7a40a696b351415976f22a4f498c401de41

**Comment by safinaskar** [comment]
@poettering . The bug is still reproducible in f717d7a40a696b351415976f22a4f498c401de41 using same instructions. I created fresh debian sid system, then I built systemd from f717d7a40a696b351415976f22a4f498c401de41 and installed. And was able to reproduce the bug

**Comment by poettering** [comment]
did you rebuild your initrd? you need to, as this affects the originating systemd (i.e. the one in the initrd) not the target initrd (i.e. the one on the host). i am really surprised that this supposedly isn't fixed...

**Comment by safinaskar** [comment]
@poettering

> did you rebuild your initrd?

No. But now I did my experiment again, this time rebuilding initramfs. The result is same. (In Debian initramfs is not systemd-based, it uses custom shell script as PID 1.)

This bug report is not about transitioning from initramfs to main system. It is about transitioning from fully running system to another chroot. (If this use case is not supported, then, okay, sorry for the noise. But then it would be nice simply to exit with error "this is not initramfs" instead of attempting transition)

**Comment by poettering** [comment]
Hmm, I am very much puzzled by this. Any chance you can get me an strace of PID1 over the transition? (strace will be killed though during hte transition, you have to block SIGTERM on it, which you can do via `env`)

Regarding your usecase, it appears to me you actually want to use the soft reboot logic that'll be part of the upcoming release, see #27435

**Comment by safinaskar** [comment]
I used `switch-root` in the past. Now I don't use it, I don't need this functionality. But of course I will try to help you fix this bug, if you think it is worth fixing.

It seems `switch-root` is for switching from initramfs only, so I suggest using some heuristics to ensure we are on initramfs (and simply fail if we are not). Here is code from busybox's switch_root, which checks this: https://github.com/mirror/busybox/blob/2d4a3d9e6c1493a9520b907e07a41aca90cdfd94/util-linux/switch_root.c#L224-L249

Let me describe again absolutely exact steps for reproducing this bug. I installed Debian sid to fresh qemu VM. Then I run this bash script in VM:
```bash
#!/bin/bash
set -e

cd /

# OLD and NEW to be sure which is which
# add command to .bash_history to make reproducing easy
echo deb http://deb.debian.org/debian sid main > /etc/apt/sources.list && apt-get update && apt-get install -y debootstrap && debootstrap sid /debian http://deb.debian.org/debian && : > /OLD && : > /debian/NEW && echo systemctl switch-root /debian /bin/bash > /root/.bash_history && apt-get install -y systemd
apt-get install -y git build-essential
echo deb-src http://deb.debian.org/debian sid main >> /etc/apt/sources.list
apt-get update && apt-get build-dep -y systemd
git clone https://github.com/systemd/systemd
# f717d7a40a696b351415976f22a4f498c401de41 - reproducible
( cd /systemd && git checkout f717d7a40a696b351415976f22a4f498c401de41 && meson setup build -Dmode=release && ninja -C build )

# we need to remove prerm (or we cannot remove systemd)
:> /var/lib/dpkg/info/systemd.prerm

# removing systemd will install sysvinit
apt-get purge -y systemd systemd-sysv && cd /systemd && make install
```

Then I rebooted and typed `systemctl switch-root /debian /bin/bash`. Then I saw that `Failed to move /debian to /` message. Then I typed `ls /` and I saw `OLD`, i. e. I see that transition did not happen.

And yes, I will try to collect strace

**Comment by poettering** [comment]
what's the precise error message from switch-root?

note that switch-root actually tries two distinct things: for the first switch root after the kernel initialized we cannot use pivot_root(), for subsequent ones we can. Typically pivot_root() is preferable though, hence we always use that first, but it will fail the first time. Which is not a total loss, since we'll immediately use MS_MOVE instead.

Hence I am asking for the precise log message. we generate a debug message in case pivot_root() doesn't work. In which case MS_MOVE should still have worked, and the message is kinda expected. hence, what precisely does the messsage say?

**Comment by safinaskar** [comment]
(Sorry for very late response.)

I just tried recent commit 1925f829ab17cee7d65cc8c350d8281f8f41588e and I see that the bug is not reproducible. So all is okay now. (The bug existed in f717d7a40a696b351415976f22a4f498c401de41 mentioned here: https://github.com/systemd/systemd/issues/23807#issuecomment-1580827178 ). If you want, I can do git bisect to determine why the bug magically disappeared. Also if you want I can send logs, try some printf-debugging, etc

**Comment by YHNdnzj** [comment]
I'm pretty sure that 2159662608a00232f94302bd5942d07830c279b4 is the commit that properly fixed this. Anyways, the issue is gone, thus closing.
