### ISSUE TITLE
Cannot run sysupdate if system extension images are in use

### ISSUE THREAD

**Issue by mcassaniti** [systemd/systemd#24562]
### systemd version the issue has been seen with

251

### Used distribution

Ubuntu Kinetic

### Linux kernel version used

5.15.0-27-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-sysext, other

### Expected behaviour you didn't see

If a system extension image is mounted then a command like `systemd-sysupdate list` should still work.

### Unexpected behaviour you saw

An error message as shown further below.

### Steps to reproduce the problem

1. Run `systemd-sysupdate list` without any system extension images to confirm proper configuration.
2. Mount a system extension image using `systemd-sysext merge`.
3. Run  `systemd-sysupdate list` again.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# /usr/lib/systemd/systemd-sysupdate list
Failed to find whole disk device for partition backing file system: No such device

# mount | grep /usr
/dev/sda4 on /usr type ext4 (rw,relatime)
sysext on /usr type overlay (ro,relatime,lowerdir=/run/systemd/sysext/meta/usr:/run/systemd/sysext/extensions/SysExt_0/usr:/usr)

```

**Comment by mcassaniti** [comment]
A quick search over the code suggests that the overlay mount is causing `get_block_device_harder_fd()` defined under `src/shared/blockdev-util.c` to fail to find the backing block device.

**Comment by mcassaniti** [comment]
@DaanDeMeyer @poettering This one is still an outstanding issue. Any update?

**Comment by AdrianVovk** [comment]
For GNOME OS we're working on integrating sysupdate with sysexts better, and we haven't run into this?

Are you able to reproduce this still? Or was it something that got fixed at some point and the issue just remained open?

**Comment by mcassaniti** [comment]
Sorry it has taken me this long to get back to you. It's still an issue under Ubuntu 24.04 (systemd v255.4).

**Comment by hundeboll** [comment]
I've hit this issue too.

@AdrianVovk Does GNOME OS happen to use a volatile root? I can work around the issue by creating `/run/systemd/volatile-root` as a symlink that points to the real device behind `/usr`.

**Comment by sorenisanerd** [comment]
This issue is biting me right now. No volatile root. Here is an strace snippet:

```
newfstatat(AT_FDCWD, "/run/systemd/volatile-root", 0x7ffd5cc8fe20, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFDIR|0755, st_size=60, st_dev=makedev(0, 0x3b), ...}) = 0
openat(AT_FDCWD, "/proc/self/fd/3", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_CLOEXEC) = 4
openat(AT_FDCWD, "/proc/self/fd/4", O_RDONLY|O_NOCTTY|O_CLOEXEC|O_PATH) = 5
fstatfs(5, {f_type=OVERLAYFS_SUPER_MAGIC, f_bsize=4096, f_blocks=980493, f_bfree=980491, f_bavail=980491, f_files=980493, f_ffree=980483, f_fsid={val=[0, 0]}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_RDONLY|ST_NODEV|ST_RELATIME}) = 0
close(5)                          = 0
close(4)                          = 0
close(3)                          = 0
ioctl(1, TCGETS, {c_iflag=ICRNL|IXON|IXANY|IMAXBEL|IUTF8, c_oflag=NL0|CR0|TAB0|BS0|VT0|FF0|OPOST|ONLCR, c_cflag=B38400|CS8|CREAD, c_lflag=ISIG|ICANON|ECHO|ECHOE|ECHOK|IEXTEN|ECHOCTL|ECHOKE|PENDIN, ...}) = 0
ioctl(2, TCGETS, {c_iflag=ICRNL|IXON|IXANY|IMAXBEL|IUTF8, c_oflag=NL0|CR0|TAB0|BS0|VT0|FF0|OPOST|ONLCR, c_cflag=B38400|CS8|CREAD, c_lflag=ISIG|ICANON|ECHO|ECHOE|ECHOK|IEXTEN|ECHOCTL|ECHOKE|PENDIN, ...}) = 0
ioctl(2, TCGETS, {c_iflag=ICRNL|IXON|IXANY|IMAXBEL|IUTF8, c_oflag=NL0|CR0|TAB0|BS0|VT0|FF0|OPOST|ONLCR, c_cflag=B38400|CS8|CREAD, c_lflag=ISIG|ICANON|ECHO|ECHOE|ECHOK|IEXTEN|ECHOCTL|ECHOKE|PENDIN, ...}) = 0 
writev(2, [{iov_base="\33[0;1;31m", iov_len=9}, {iov_base="Failed to find whole disk device"..., iov_len=82}, {iov_base="\33[0m", iov_len=4}, {iov_base="\r\n", iov_len=2}], 4) = 97
exit_group(1)                     = ?
```

That corresponds to:

https://github.com/systemd/systemd/blob/b45730389ba025489ec8d445bc91534fef515c28/src/sysupdate/sysupdate-resource.c#L586-L589

In my case `/usr` is part of my `/` which is an erofs. I have a sysext merged, so `/usr` is an overlayfs.

This is a somewhat customized Ubuntu 24.10 system with systemd 256.5.

**Comment by sorenisanerd** [comment]
`bootctl -R` has the right idea:

```
root@localhost:~# /usr/lib/systemd/systemd-sysupdate
Failed to find whole disk device for partition backing file system: No such device
root@localhost:~# bootctl -R
/dev/nvme0n1p7
root@localhost:~#
```

Could they be made to use the same logic?

**Comment by mcassaniti** [comment]
If nothing else that code from `src/sysupdate/sysupdate-resource.c` looks to be somewhat duplicated with https://github.com/systemd/systemd/blob/0d879453acdc86b0d742c5854420c116d0f23ba4/src/shared/blockdev-util.c#L867-L876 but the shared code also looks for whatever backs `/`. I've seen a mix:

* cryptenroll searches for `/var` and has a documented justification for `/var` which makes a lot of sense
* repart searches for `/` and `/usr`
* bootctl and gpt-auto-generator rely on `blockdev_get_root()` which is what is shown above

I'm sure there are other code snippets around that also look for the backing device of root. My quick search suggests that some refactoring might be needed.

**Comment by poettering** [comment]
Here's my proposed fix: #36617 ptal.
