### ISSUE TITLE
network: handle RTM_NEWROUTE request timeouts gracefully

### ISSUE THREAD

**Issue by rkolchmeyer** [systemd/systemd#25441]
### systemd version the issue has been seen with

252 and 249

### Used distribution

debian testing and Google's Container-Optimized OS

### Linux kernel version used

6.0.0-4-cloud-amd64 and 5.15.65+

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Unexpected behaviour you saw

When an RTM_NEWROUTE timeout occurs, the associated link enters a failed state, and manual intervention is required to recover networking functionality.

In our environment, the network sends router advertisements every 30 seconds. systemd-networkd sends an RTM_NEWROUTE request to the kernel for each router advertisement. If systemd-networkd fails to process the RTM_NEWROUTE acknowledgement within 25 seconds, networkd will put the link in a failed state. When combined with `ManageForeignRoutes=true`, any routes configured through router advertisements will promptly be deleted, resulting in broken networking.

Ideally, RTM_NEWROUTE timeouts shouldn't be fatal.

### Steps to reproduce the problem

We've observed this issue "in the wild" on an extremely highly utilized system (lots of OOM kills, very high CPU utilization, etc). systemd-networkd would periodically not receive any CPU cycles for >30 seconds (not long enough to trigger the 3min watchdog). With RTM_NEWROUTE requests being sent every 30 seconds in response to router advertisements, it was a matter of time until systemd-networkd didn't receive any CPU for >30 seconds while an RTM_NEWROUTE request was in-flight. As a result, the RTM_NEWROUTE request timed out, the link was put in a failed state, and the network became unreachable.

We've artificially reproduced the problem with the following patch to libsystemd. The patch unconditionally times out rtnetlink requests if /var/lib/trigger exists. When we create the trigger file before a periodic router advertisement occurs, we see the exact type of network failure that we saw on the real system.

```
--- a/src/libsystemd/sd-netlink/sd-netlink.c.orig       2022-11-08 13:59:01.000000000 +0000
+++ b/src/libsystemd/sd-netlink/sd-netlink.c    2022-11-18 01:37:21.643950026 +0000
@@ -1,6 +1,7 @@
 /* SPDX-License-Identifier: LGPL-2.1-or-later */

 #include <poll.h>
+#include <sys/stat.h>

 #include "sd-netlink.h"

@@ -238,6 +239,7 @@
         sd_netlink_slot *slot;
         usec_t n;
         int r;
+       struct stat buf;

         assert(nl);

@@ -246,7 +248,7 @@
                 return 0;

         n = now(CLOCK_MONOTONIC);
-        if (c->timeout > n)
+        if ((stat("/var/lib/trigger", &buf) != 0) && c->timeout > n)
                 return 0;

         r = message_new_synthetic_error(nl, -ETIMEDOUT, c->serial, &m);
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
On the production system, we do not have debug logging enabled, so we only have the following logs:

Oct 31 09:39:44 [REDACTED] systemd-networkd[1522]: eth0: Could not set route: Connection timed out
Oct 31 09:39:44 [REDACTED] systemd-networkd[1522]: eth0: Failed

With the artificial reproducer:

Nov 18 04:30:50 [REDACTED] systemd-networkd[639]: ens4: NDISC: Received Router Advertisement: flags MANAGED preference medium lifetime 0 sec
Nov 18 04:30:50 [REDACTED] systemd-networkd[639]: ens4: NDISC: Invoking callback for 'router' event.
Nov 18 04:30:50 [REDACTED] systemd-networkd[639]: ens4: Acquiring DHCPv6 lease on NDisc request
Nov 18 04:30:50 [REDACTED] systemd-networkd[639]: ens4: Requesting NDisc route (configuring,configured): dst: 2001:4860:8040::/42, src: n/a, gw: fe80::4001:aff:fe7f:1, prefsrc: n/>
Nov 18 04:30:50 [REDACTED] systemd-networkd[639]: ens4: Setting SLAAC addresses and router.
Nov 18 04:30:50 [REDACTED] systemd-networkd[639]: ens4: State changed: configured -> configuring
Nov 18 04:30:50 [REDACTED] systemd-networkd[639]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Proper>
Nov 18 04:30:50 [REDACTED] systemd-networkd[639]: ens4: link_check_ready(): IPv4LL:no DHCPv4:yes DHCPv6:yes DHCP-PD:no NDisc:no
Nov 18 04:30:50 [REDACTED] systemd-networkd[639]: ens4: State changed: configuring -> configured
Nov 18 04:30:50 [REDACTED] systemd-networkd[639]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Proper>
Nov 18 04:30:50 [REDACTED] systemd-networkd[639]: ens4: Configuring NDisc route (requesting,configuring,configured): dst: 2001:4860:8040::/42, src: n/a, gw: fe80::4001:aff:fe7f:1,>
Nov 18 04:30:50 [REDACTED] systemd-networkd[639]: ens4: SLAAC addresses and routes set.
Nov 18 04:31:20 [REDACTED] systemd[1]: systemd-networkd.service: Got notification message from PID 639 (WATCHDOG=1)
Nov 18 04:31:20 [REDACTED] systemd-networkd[639]: ens4: NDISC: Received Router Advertisement: flags MANAGED preference medium lifetime 0 sec
Nov 18 04:31:20 [REDACTED] systemd-networkd[639]: ens4: NDISC: Invoking callback for 'router' event.
Nov 18 04:31:20 [REDACTED] systemd-networkd[639]: ens4: Acquiring DHCPv6 lease on NDisc request
Nov 18 04:31:20 [REDACTED] systemd-networkd[639]: ens4: Requesting NDisc route (configuring,configured): dst: 2001:4860:8040::/42, src: n/a, gw: fe80::4001:aff:fe7f:1, prefsrc: n/>
Nov 18 04:31:20 [REDACTED] systemd-networkd[639]: ens4: Setting SLAAC addresses and router.
Nov 18 04:31:20 [REDACTED] systemd-networkd[639]: ens4: State changed: configured -> configuring
Nov 18 04:31:20 [REDACTED] systemd-networkd[639]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Proper>
Nov 18 04:31:20 [REDACTED] systemd-networkd[639]: ens4: link_check_ready(): IPv4LL:no DHCPv4:yes DHCPv6:yes DHCP-PD:no NDisc:no
Nov 18 04:31:20 [REDACTED] systemd-networkd[639]: ens4: State changed: configuring -> configured
Nov 18 04:31:20 [REDACTED] systemd-networkd[639]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Proper>
Nov 18 04:31:20 [REDACTED] systemd-networkd[639]: ens4: Configuring NDisc route (requesting,configuring,configured): dst: 2001:4860:8040::/42, src: n/a, gw: fe80::4001:aff:fe7f:1,>
Nov 18 04:31:20 [REDACTED] systemd-networkd[639]: ens4: Could not set route: Connection timed out
Nov 18 04:31:20 [REDACTED] systemd-networkd[639]: ens4: Failed
Nov 18 04:31:20 [REDACTED] systemd-networkd[639]: ens4: State changed: configured -> failed
Nov 18 04:31:20 [REDACTED] systemd-networkd[639]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Proper>
Nov 18 04:31:20 [REDACTED] systemd-networkd[639]: ens4: DHCPv4 client: STOPPED
Nov 18 04:31:20 [REDACTED] systemd-networkd[639]: ens4: LLDP Rx: Stopping LLDP client
Nov 18 04:31:20 [REDACTED] systemd-networkd[639]: ens4: DHCPv6 client: State changed: bound -> stopped
Nov 18 04:31:20 [REDACTED] systemd-networkd[639]: ens4: NDISC: Stopping IPv6 Router Solicitation client
Nov 18 04:33:12 [REDACTED] systemd-networkd[639]: ens4: Removed NDisc route (configuring): dst: 2001:4860:8040::/42, src: n/a, gw: fe80::4001:aff:fe7f:1, prefsrc: n/a, scope: glob>
Nov 18 04:33:12 [REDACTED] systemd[1]: systemd-networkd.service: Got notification message from PID 639 (WATCHDOG=1)
Nov 18 04:34:48 [REDACTED] systemd[1]: systemd-networkd.service: Got notification message from PID 639 (WATCHDOG=1)
Nov 18 04:36:48 [REDACTED] systemd[1]: systemd-networkd.service: Got notification message from PID 639 (WATCHDOG=1)
```

**Comment by heliochronix** [comment]
I think this is an issue that's been plaguing me since I started some Kubernetes testing recently. Is there a potential work around in the meantime? I'm constantly having to restart networkd because whole nodes will just drop off periodically with their interfaces being effectively disabled.

**Comment by mohag** [comment]
I have this as a workaround:

/usr/local/sbin/systemd-networkd-check-and-fix.sh
```shell
#!/bin/sh

if  systemctl is-active systemd-networkd.service > /dev/null && ! ip route list | grep -q .; then
    echo "$(date) systemd-networkd is running but the routes are broken. Restarting systemd-networkd.service"
    systemctl restart systemd-networkd.service
fi
```

/etc/systemd/system/systemd-networkd-check-and-fix.service
```
[Unit]
Description=Check if systemd-networkd has broken the network and fix

[Service]
Type=oneshot
# This needs to be root for the service restart to work
User=root
Group=root
ExecStart=/usr/local/sbin/systemd-networkd-check-and-fix.sh

Requisite=systemd-networkd.service
```

/etc/systemd/system/systemd-networkd-check-and-fix.timer
```
[Unit]
Description=Check if systemd-networkd has broken the network and fix

[Timer]
OnCalendar=minutely

[Install]
WantedBy=timers.target
```

```
systemctl daemon-reload
systemctl enable systemd-networkd-check-and-fix.timer
```

**Comment by raggi** [comment]
I've also seen this with DHCPv4 setting, and wrote it up here: https://gist.github.com/raggi/1f8d0b9f45c5b62e7131b03e6e2ffe68. I've seen it repro on a NUC, but also on AWS VM's. A search around seems to suggest it comes up relatively often on shared CPU VMs.

**Comment by raggi** [comment]
I just realized that this is also reliant on code using `CLOCK_MONOTONIC` for timeouts, but on supported kernels that should now be `CLOCK_MONOTONIC_RAW` to avoid being tripped by adjtime modifications.

**Comment by TonyHoyle** [comment]
I've been absolutely plagued by this.. a fairly lightly loaded server the containers will start dropping their addresses and the logs are similar to above.. the machiine gets an SLAAC update, then for some reason times out setting the route (note that it does this *1 second* later, not 30).

Then, for some insane reason, it also decides to stop the dhcpv4 client, which should be completely unrelated.  The machine goes offline shortly afterwards (about an hour later in this example) as DHCP is no longer being renewed.

This is systemd 252

Sep 04 22:02:06 plex systemd-networkd[55]: eth0: Requesting NDisc address (configuring,configured): 2001:8b0:178:1:8419:c5ff:fe75:fe7f/64 (valid for 4w 1d 23h 36min 58s, preferred for 6d 23h 37min), flags: manage-temporary-address,no-prefixroute, scope: global
Sep 04 22:02:06 plex systemd-networkd[55]: eth0: Setting SLAAC addresses and router.
Sep 04 22:02:07 plex systemd-networkd[55]: eth0: Could not set route: Connection timed out
Sep 04 22:02:08 plex systemd-networkd[55]: eth0: Failed
Sep 04 22:02:08 plex systemd-networkd[55]: eth0: State changed: configured -> failed
Sep 04 22:02:09 plex systemd-networkd[55]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=13 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sep 04 22:02:09 plex systemd-networkd[55]: eth0: DHCPv4 client: STOPPED
Sep 04 22:02:09 plex systemd-networkd[55]: eth0: LLDP Rx: Stopping LLDP client
Sep 04 22:02:09 plex systemd-networkd[55]: eth0: NDISC: Stopping IPv6 Router Solicitation client
Sep 04 22:02:12 plex systemd-networkd[55]: eth0: Received updated NDisc address (requesting,configured): 2001:8b0:178:1:8419:c5ff:fe75:fe7f/64 (valid for 4w 1d 23h 48min 29s, preferred for 6d 23h 48min 29s), flags: manage-temporary-address,no-prefixroute, scope: global
Sep 04 22:02:51 plex systemd-networkd[55]: eth0: Removed NDisc route (requesting,configuring): dst: n/a, src: n/a, gw: fe80::2ec8:1bff:feff:b134, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
Sep 04 23:50:58 plex systemd-networkd-wait-online[326298]: Timeout occurred while waiting for network connectivity.
Sep 04 23:50:58 plex apt-helper[326294]: E: Sub-process /lib/systemd/systemd-networkd-wait-online returned an error code (1)
Sep 05 06:34:42 plex systemd-networkd-wait-online[335441]: Timeout occurred while waiting for network connectivity.

**Comment by chenglongtang1** [comment]
Will someone help work on this issue?

**Comment by raggi** [comment]
I think this issue is miss-labelled, as the root issue is a bug that results in loss of network connectivity for hosts using systemd-networkd under normal conditions.

**Comment by yuwata** [comment]
> I just realized that this is also reliant on code using `CLOCK_MONOTONIC` for timeouts, but on supported kernels that should now be `CLOCK_MONOTONIC_RAW` to avoid being tripped by adjtime modifications.

Interesting. Though, I am not familiar about that.

> I think this issue is miss-labelled, as the root issue is a bug that results in loss of network connectivity for hosts using systemd-networkd under normal conditions. cc @yuwata

Done.

**Comment by yuwata** [comment]
'Fix' is waiting in #29390. Please apply the patches, and set `SYSTEMD_NETLINK_DEFAULT_TIMEOUT=1day` or even `infinity`.

**Comment by raggi** [comment]
@yuwata this issue is really still not yet fixed. The problem is that there is no way to guarantee the amount of time that the kernel will take to process a netlink message, if the machine is under undue stress or for example is a VM under suspend or migration. The bad behavior is that a _perceived timeout_ leads to a "fatal state" - networkd re-establishes netlink and then tears down all routes from the interface - completely offlining nodes. The bug would be fixed from a UX standpoint if this behavior of completely breaking network connectivity under these conditions goes away.

**Comment by rajibade** [comment]
@raggi @yuwata Is there any path forward beyond the aforementioned timeout change?

**Comment by raggi** [comment]
The change I recommend here is that a timeout in configuration should not transition the state machine into behavior that aggressively deconfigures all the covered interfaces. That reaction to a timeout is almost always harmful, and it's novel among peer systems that perform network configuration/policy application.

**Comment by raggi** [comment]
@poettering I'm sorry to tag you on this bug, but this issue has been going on for several years. I think there's a communication issue around it, and perhaps you have higher bandwidth / better communication channels necessary to help.

The issue here is that under various conditions that are fairly common particularly in cloud environments or more heavily loaded hosts, a host kernel may be very slow to respond to a netlink message. In the networkd configuration path a timeout is set on the netlink operation. The reaction to a timeout in the netlink operation is to mark the interface as failed, which implies then an action is taken to de-configure the interface entirely - for most hosts this means "knocking them off the internet". Common examples of causes of this are: memory pressure causing kernel stalls while the reclaimer/oomkiller do their thing, CPUs slowed due to VM migrations, temporary locks in network interfaces (such as in drivers). There are many other possible causes. The typical root trigger of this behavior is the DHCP refresh code path, which performs some netlink operations in steady state, and when coincident with one of these events that cause a delayed response from the kernel and then the undesirable/spurious deconfiguration occurs. Incremental changes to the timeout have been made which slightly reduce the chance of this condition, but the condition remains and continues to have severe consequences for affected hosts (they spuriously go offline).

Some additional links to prior reports are collected here: https://gist.github.com/raggi/1f8d0b9f45c5b62e7131b03e6e2ffe68

In one of my production environments we have deployed a daemon which actively watches for this state and restarts networkd if it occurs, so that networkd will then reconfigure the interface. I hope you'll agree this seems like an absurd outcome.

**Comment by yuwata** [comment]
First of all, if this is caused by the kernel stall of memory pressure or so. Then I think networkd is not a good place to workaround the issue. You should find what consumes so many memory and fix it or kill it.

This is why I introduced the configuration `$SYSTEMD_NETLINK_DEFAULT_TIMEOUT` not in the first class configuration (networkd.conf or foo.network files), but through environment variable.

Also, still `SYSTEMD_NETLINK_DEFAULT_TIMEOUT=infinity` should work fine, I believe.
If that does not work, then the issue is not in netlink, and there should be another reason that the transition of an interface into the failed state. Please provide another debugging logs of networkd and open a new issue.

**Comment by raggi** [comment]
> First of all, if this is caused by the kernel stall of memory pressure or so. Then I think networkd is not a good place to workaround the issue. You should find what consumes so many memory and fix it or kill it.

I want to clarify that this statement is equivalent to: you should never have a bug in another piece of software on the system, or systemd-networkd is free to kill your network connectivity.

I don't think this is the right stance. This isn't something "being done" to systemd-networkd, the timeout is the root cause of the problem.

Perhaps flip this around: netlink is local, why is there a timeout on netlink here?

An additional question: why when one netlink operation fails is the remedial action to then _use netlink to remove all configuration from the interface_? If the judgement is "netlink has failed", then stop and do nothing. If the netlink failure is transient then retry the operation. It doesn't make sense from a user perspective for the reaction to this state to be to deconfigure the interface over netlink. The ability to do so should clearly indicate a failure in judgement as to the state machine transition.

Please also note again, this is not solely caused by memory pressure - that is just one way in which a kernel might take an unusually long (clock) time to respond to a request. Other ways include CPU/VM throttling (e.g. VM migrations), lock contention, cpu contention, and many other ways.

Logs from todays instance:

```
2025-07-09 18:49:40.750+00:00 Under memory pressure, flushing caches.
2025-07-09 18:49:40.795+00:00 Flushed all caches.
2025-07-09 18:50:58.404+00:00 ens5: Could not set DHCPv6 address: Connection timed out
2025-07-09 18:50:58.715+00:00 ens5: Failed
```

Existing open bugs for the same issue:

- https://github.com/systemd/systemd/issues/33288 
- https://github.com/systemd/systemd/issues/32045

As noted in my earlier posts I have links to many such bugs/instances of this problem users are hitting, earlier link: https://gist.github.com/raggi/1f8d0b9f45c5b62e7131b03e6e2ffe68.

**Comment by rajibade** [comment]
Logs from when I had previously ran into this issue.
```
Apr 04 00:43:49 localhost systemd-networkd[1983]: Enumeration completed
Apr 04 00:43:49 localhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-networkd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Apr 04 00:43:49 localhost systemd[1]: Started systemd-networkd.service - Network Configuration.
Apr 04 00:43:49 localhost systemd-networkd[1983]: enX0: Configuring with /usr/lib/systemd/network/80-ec2.network.
Apr 04 00:43:49 localhost systemd-networkd[1983]: enX0: Link UP
Apr 04 00:43:49 localhost systemd-networkd[1983]: enX0: Gained carrier
Apr 04 00:43:49 localhost systemd[1]: Starting systemd-networkd-wait-online.service - Wait for Network to be Configured...
Apr 04 00:43:49 localhost systemd-networkd[1983]: enX0: DHCPv4 address 172.31.43.20/20, gateway 172.31.32.1 acquired from 172.31.32.1
Apr 04 00:43:50 localhost systemd-networkd[1983]: enX0: Gained IPv6LL
Apr 04 00:43:50 localhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-networkd-wait-online comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Apr 04 00:43:50 localhost systemd[1]: Finished systemd-networkd-wait-online.service - Wait for Network to be Configured.
Apr 04 00:43:51 localhost systemd-networkd[1983]: enX0: Reconfiguring with /run/systemd/network/70-enX0.network.
Apr 04 00:43:51 localhost systemd-networkd[1983]: enX0: DHCP lease lost
Apr 04 00:43:51 localhost systemd-networkd[1983]: enX0: DHCPv6 lease lost
Apr 04 00:43:51 localhost systemd-networkd[1983]: enX0: DHCPv4 address 172.31.43.20/20, gateway 172.31.32.1 acquired from 172.31.32.1
Apr 04 03:21:00 ip-172-31-43-20.us-west-2.compute.internal systemd-networkd[1983]: enX0: Could not set DHCPv4 address: Connection timed out
Apr 04 03:21:00 ip-172-31-43-20.us-west-2.compute.internal systemd-networkd[1983]: enX0: Failed
Apr 04 04:22:06 ip-172-31-43-20.us-west-2.compute.internal systemd[1]: systemd-networkd-wait-online.service: Deactivated successfully.
Apr 04 04:22:06 ip-172-31-43-20.us-west-2.compute.internal systemd[1]: Stopped systemd-networkd-wait-online.service - Wait for Network to be Configured.
Apr 04 04:22:06 ip-172-31-43-20.us-west-2.compute.internal systemd[1]: Stopping systemd-networkd.service - Network Configuration...
Apr 04 04:22:06 ip-172-31-43-20.us-west-2.compute.internal systemd[1]: systemd-networkd.service: Deactivated successfully.
Apr 04 04:22:06 ip-172-31-43-20.us-west-2.compute.internal systemd[1]: Stopped systemd-networkd.service - Network Configuration.
Apr 04 04:22:06 ip-172-31-43-20.us-west-2.compute.internal systemd[1]: systemd-networkd.service: Consumed 1min 43.578s CPU time.
```
