### ISSUE TITLE
networkctl doesn't add new Wireguard peers

### ISSUE THREAD

**Issue by Ambr051us** [systemd/systemd#25547]
### systemd version the issue has been seen with

249

### Used distribution

Ubuntu 22.04.1 LTS

### Linux kernel version used

5.15.0-53-generic

### CPU architectures issue was seen on

x86_64

### Component

networkctl

### Expected behaviour you didn't see

Wireguard supports adding new peers without interrupting the tunnel, so it's logical to expect that adding a new peer to a `.netdev` and issuing `networkctl reload && networkctl reconfigure` would enable the new peer to connect.

### Unexpected behaviour you saw

New peers cannot connect to systemd-managed WireGuard tunnels until `systemd-networkd` is fully restarted, which causes a brief but complete network interruption

### Steps to reproduce the problem

1. Add a new `[WireGuardPeer]` section to an existing `.netdev` unit file that describes an already working WG tunnel, let's say it's `wg0`
2. Issue `networkctl reload && networkctl reconfigure wg0`
3. Issue `wg show wg0` and look for the newly added peer in the output

**Comment by AInteriorB** [comment]
> New peers cannot connect to systemd-managed WireGuard tunnels until `systemd-networkd` is fully restarted, which causes a brief but complete network interruption

Also ran into this problem today. I didn't find out another way to reload a wireguard .netdev systemd configuration without dropping existing connections.

**Comment by serge-name** [comment]
It is being reproduced in 252.4 too.

The ugly workaround is

```shell
ip l d wg-foo; networkctl reload
```

But it would be much better if networkctl able to add new peers (and remove old ones) according to a current `.netdev` peer list.

**Comment by seblu** [comment]
Reproduced on
```
systemd 253 (253.3-3-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

**Comment by mjt0k** [comment]
running debian bookworm here, systemd 252.6. Even after restart of systemd-networkd, the peer list on the actual interface is not synced with the ,netdev file anymore.  Instead, it prints:

  wg0: netdev exists, using existing without changing its parameters

I had to manually add peer using `wg set wg0 peer "$pubkey" allowed-ips $peerip`. An alternative is to stop systemd-networkd, remove wg0 interface, and start systemd-networkd.

Moved wireguard config to using wg tools now. It seems to be broken on systemd-networkd at the moment.

**Comment by mjt0k** [comment]
This is not RFE, it is a bug: even restarting networkd does help anymore, - there's no way to reconfigure the peers with systemd.

**Comment by peigongdsd** [comment]
This is clearly a bug, for that at least we can remove and recreate the interface on reconfiguring if netdev configuration change for wireguard interface is detected.

**Comment by lrusak** [comment]
I'm running into this also
```
$ systemctl --version                                                                                                                                                                                                                                                                                                                                         130 ↵  
systemd 255 (255.4-1.fc40)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP -GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```

**Comment by apt-install-coffee** [comment]
I am also running into this
```$ systemctl --version
systemd 255 (255.4-1ubuntu8.4)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified```

**Comment by edorgeville** [comment]
This issue will be affected by this recently merged PR: https://github.com/systemd/systemd/issues/25547
Will test with v257 when it releases and report the results here.

**Comment by minus7** [comment]
I can confirm reloading adds/removes peers with systemd v257. Note that it works by completely replacing peers. This means stats on unchanged peers are reset and manually added peers are removed.

**Comment by chronically-late** [comment]
@mjt0k Thanks, manually adding the peer worked.
`wg set $IF peer "$PUBKEY" preshared-key "$PATH_TO_PSK" allowed-ips $IP` solved it until I was able to restart the system.

**Comment by andsens** [comment]
I suppose this can be closed as fixed in v257 then?

**Comment by ruuda** [comment]
I am still experiencing this problem on 257 on Flatcar 4593.2.5. Pinging a peer that is defined in the `.netdev` file fails with `sendmsg: Required key not available`, and `wg show` does not show the peer, even after `networkctl reload` and `systemctl restart systemd-networkd`. Bringing the `wg0` link down and up again also did not help. There are other existing peers, that were present already before I added a peer to the `.netdev` file, and those are functioning correctly.

After `ip link delete dev wg0` and `systemctl restart systemd-networkd`, the peer is reachable and the network works as expected.

I wonder why it behaved this way, if the bug was supposedly fixed in v257. There is one hint in the journal that might be related. Networkd initially warned that the key file had too relaxed permissions, I then changed the permissions incorrectly and on the next run networkd logged `ignoring network device: Permission denied`. After I set the correct file permission, it logged `Failed to create netdev: File exsits`, though existing peers worked fine.

<details>
<summary>Full networkd journal</summary>

```
Aug 13 17:05:32 systemd[1]: Starting systemd-networkd.service - Network Configuration...
Aug 13 17:05:32 systemd-networkd[1308]: /etc/systemd/network/wg0.key has 0644 mode that is too permissive, please adjust the ownership and access mode.
Aug 13 17:05:32 systemd-networkd[1308]: lo: Link UP
Aug 13 17:05:32 systemd-networkd[1308]: lo: Gained carrier
Aug 13 17:05:32 systemd[1]: Started systemd-networkd.service - Network Configuration.
Aug 13 17:05:32 systemd-networkd[1308]: wg0: netdev ready
Aug 13 17:05:32 systemd-networkd[1308]: eth0: Found matching .network file, based on potentially unpredictable interface name: /usr/lib/systemd/network/zz-default.network
Aug 13 17:05:32 systemd-networkd[1308]: eth0: Configuring with /usr/lib/systemd/network/zz-default.network.
Aug 13 17:05:32 systemd-networkd[1308]: eth0: Link UP
Aug 13 17:05:32 systemd-networkd[1308]: eth0: Gained carrier
Aug 13 17:05:32 systemd-networkd[1308]: eth0: Found matching .network file, based on potentially unpredictable interface name: /usr/lib/systemd/network/zz-default.network
Aug 13 17:05:32 systemd-networkd[1308]: eth0: DHCPv4 address XXX.XXX.117.2/23, gateway XXX.XXX.116.1 acquired from XXX.XXX.116.1
Aug 13 17:05:33 systemd-networkd[1308]: wg0: Configuring with /etc/systemd/network/wg0.network.
Aug 13 17:05:33 systemd-networkd[1308]: wg0: Link UP
Aug 13 17:05:33 systemd-networkd[1308]: wg0: Gained carrier
Aug 13 17:05:34 systemd-networkd[1308]: eth0: Gained IPv6LL
Aug 14 21:58:52 systemd-networkd[1308]: /etc/systemd/network/wg0.key has 0644 mode that is too permissive, please adjust the ownership and access mode.
Aug 14 21:58:52 systemd-networkd[1308]: wg0: netdev ready
Aug 14 21:58:52 systemd-networkd[1308]: eth0: Found matching .network file, based on potentially unpredictable interface name: /usr/lib/systemd/network/zz-default.network
Aug 14 21:58:52 systemd-networkd[1308]: wg0: Reconfiguring with /etc/systemd/network/wg0.network.
Aug 14 22:30:56 systemd-networkd[1308]: /etc/systemd/network/wg0.key has 0644 mode that is too permissive, please adjust the ownership and access mode.
Aug 14 22:30:56 systemd-networkd[1308]: wg0: netdev ready
Aug 14 22:30:56 systemd-networkd[1308]: eth0: Found matching .network file, based on potentially unpredictable interface name: /usr/lib/systemd/network/zz-default.network
Aug 14 22:30:56 systemd-networkd[1308]: wg0: Reconfiguring with /etc/systemd/network/wg0.network.
Aug 15 17:58:17 systemd-networkd[1308]: wg0: Failed to read private key from '/etc/systemd/network/wg0.key', ignoring network device: Permission denied
Aug 15 17:58:17 systemd-networkd[1308]: eth0: Found matching .network file, based on potentially unpredictable interface name: /usr/lib/systemd/network/zz-default.network
Aug 15 17:58:17 systemd-networkd[1308]: wg0: Reconfiguring with /etc/systemd/network/wg0.network.
Aug 15 17:59:30 systemd-networkd[1308]: eth0: Found matching .network file, based on potentially unpredictable interface name: /usr/lib/systemd/network/zz-default.network
Aug 15 17:59:30 systemd-networkd[1308]: wg0: Failed to create netdev: File exists
Aug 15 18:01:42 systemd-networkd[1308]: eth0: Found matching .network file, based on potentially unpredictable interface name: /usr/lib/systemd/network/zz-default.network
Aug 15 19:17:27 systemd-networkd[1308]: wg0: Link DOWN
Aug 15 19:17:27 systemd-networkd[1308]: wg0: Lost carrier
Aug 15 19:17:30 systemd-networkd[1308]: wg0: Link UP
Aug 15 19:17:30 systemd-networkd[1308]: wg0: Gained carrier
Aug 15 19:23:57 systemd[1]: Reloading systemd-networkd.service - Network Configuration...
Aug 15 19:23:57 systemd[1]: Reloaded systemd-networkd.service - Network Configuration.
Aug 15 19:23:57 systemd-networkd[1308]: eth0: Found matching .network file, based on potentially unpredictable interface name: /usr/lib/systemd/network/zz-default.network
Aug 15 19:47:09 systemd-networkd[1308]: eth0: Found matching .network file, based on potentially unpredictable interface name: /usr/lib/systemd/network/zz-default.network
Aug 15 19:51:33 systemd-networkd[1308]: wg0: Reconfiguring with /etc/systemd/network/wg0.network.
Aug 15 19:58:54 systemd-networkd[1308]: wg0: Link DOWN
Aug 15 19:58:54 systemd-networkd[1308]: wg0: Lost carrier
Aug 15 19:59:02 systemd[1]: Stopping systemd-networkd.service - Network Configuration...
Aug 15 19:59:02 systemd[1]: systemd-networkd.service: Deactivated successfully.
Aug 15 19:59:02 systemd[1]: Stopped systemd-networkd.service - Network Configuration.
Aug 15 19:59:02 systemd[1]: Starting systemd-networkd.service - Network Configuration...
Aug 15 19:59:02 systemd-networkd[7251]: lo: Link UP
Aug 15 19:59:02 systemd-networkd[7251]: lo: Gained carrier
Aug 15 19:59:02 systemd-networkd[7251]: eth0: Link UP
Aug 15 19:59:02 systemd-networkd[7251]: eth0: Gained carrier
Aug 15 19:59:02 systemd-networkd[7251]: eth0: Gained IPv6LL
Aug 15 19:59:02 systemd[1]: Started systemd-networkd.service - Network Configuration.
Aug 15 19:59:02 systemd-networkd[7251]: eth0: Found matching .network file, based on potentially unpredictable interface name: /usr/lib/systemd/network/zz-default.network
Aug 15 19:59:02 systemd-networkd[7251]: eth0: Configuring with /usr/lib/systemd/network/zz-default.network.
Aug 15 19:59:02 systemd-networkd[7251]: wg0: netdev ready
Aug 15 19:59:02 systemd-networkd[7251]: eth0: DHCPv4 address XXX.XXX.117.2/23, gateway XXX.XXX.116.1 acquired from XXX.XXX.116.1
Aug 15 19:59:02 systemd-networkd[7251]: wg0: Configuring with /etc/systemd/network/wg0.network.
Aug 15 19:59:02 systemd-networkd[7251]: wg0: Link UP
Aug 15 19:59:02 systemd-networkd[7251]: wg0: Gained carrier
```

</details>

```
systemd 257 (257.9)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +IPE +SMACK +SECCOMP -GCRYPT -GNUTLS +OPENSSL -ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBCRYPTSETUP_PLUGINS +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -BTF -XKBCOMMON +UTMP -SYSVINIT +LIBARCHIVE
```
