### ISSUE TITLE
two disks with the same id

### ISSUE THREAD

**Issue by ralphee** [systemd/systemd#2677]
https://imgur.com/6wS7Ftr

**Comment by poettering** [comment]
For some reason you have two disks with the same WWN.

We probably should downgrade the log message again.

**Comment by ralphee** [comment]
also noticed home partiton does not get un-mounted when shutting down

**Comment by WallanceLee** [comment]
I don't have two disk on my machine but I do have the problem. The error information is caused by src/core/device.c in function device_setup_unit. It displays that the device appears twice with different sysfs path. 
I have four NTFS partition and the error messages run on these partition. But whenever I restart my computer, the conflict just run to another partition.
For example, at one time, it displays the /dev/sda6 and /dev/sda{3,4,5} appear diffrent sysfs path with  same device. And another time, it displays the /dev/sda5 and /dev/sda{3,4,6} appear different sysfs path with same device.
So, I think this is not log level that caused this problem. It is concurrent problem. At some place, the race condition caused this problem. But this is not critical. I cannot find where caused the problem now. And the above is my guess.

**Comment by tomty89** [comment]
Apparently this commit:
https://github.com/systemd/systemd/commit/ac9d396b2abbae4e7ab84f7b556f70681b66236b
(unintentionally?) reverted this commit:
https://github.com/systemd/systemd/commit/5259bcf6a638d8d489db1ddefd55327aa15f3e51

**Comment by WallanceLee** [comment]
I just have a workaround on my machine. I run gdisk on my machine which uses GPT. 
I just modify my four NTFS partitions' name(delete the white space).
Now it works fine. @poettering 
But I want to know why it happen like that?

**Comment by poettering** [comment]
Fixed by 071e0b8b3a698e73bcaecba09ffccab5553d2365.

**Comment by Raboo** [comment]
@poettering it is not fixed. It is still a fact that there is no guideline or rule against having multiple disks that have the same partition label. The behavior isn't fixed, it just masked under another log level. Besides journald defaults to log debug to syslog.
