### ISSUE TITLE
ukify: Assertion hit when building UKI

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#27004]
### systemd version the issue has been seen with

main

### Used distribution

Ubuntu Jammy

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

We're seeing an assertion in ukify in mkosi CI (see https://github.com/systemd/mkosi/actions/runs/4530864308/jobs/7980348772?pr=1410)

cc @med

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
‣  Generating combined kernel + initrd boot file…
Kernel version not specified, starting autodetection 😖.
Found uname version: 5.14.0-289.el9.x86_64
Traceback (most recent call last):
  File "/usr/bin/ukify", line 801, in <module>
    main()
  File "/usr/bin/ukify", line 797, in main
    make_uki(opts)
  File "/usr/bin/ukify", line 602, in make_uki
    pe_add_sections(uki, output)
  File "/usr/bin/ukify", line 452, in pe_add_sections
    assert len(pe.__data__) % pe.OPTIONAL_HEADER.FileAlignment == 0
AssertionError
```

**Comment by medhefgo** [comment]
I believe this is caused by the symbol table being present. Looking at the distro list, any that fail probably don't have 4c0a83a434aa707d4fe43f4c5eedcd2269a14ef2 backported.

I would prefer that being backported to the distros as it will also remove those pesky sbsign warnings…

**Comment by DaanDeMeyer** [comment]
I'd prefer not to break more than half of the supported distros in mkosi until distributions backport that commit. I don't have time to chase them all down.

**Comment by keszybz** [comment]
Yeah, if it works OK, we shouldn't fail hard. A warning is better.

**Comment by yuwata** [comment]
Fixed by #27009.

**Comment by DaanDeMeyer** [comment]
This isn't actually fixed so reopening

@medhefgo So I played around some more, and there's actually two issues. On CentOS 8, https://github.com/systemd/systemd/commit/4c0a83a434aa707d4fe43f4c5eedcd2269a14ef2 is not backported, which means the symbol table is still present and its position/size are not file aligned. All the sections themselves are aligned though.

On the other hand, if I pipe a stub from current main (with aligned values) through the objcopy command from https://github.com/systemd/systemd/commit/4c0a83a434aa707d4fe43f4c5eedcd2269a14ef2, the values are not aligned anymore. So I think https://github.com/systemd/systemd/commit/4c0a83a434aa707d4fe43f4c5eedcd2269a14ef2 might be partially causing this issue.

**Comment by DaanDeMeyer** [comment]
I added workarounds for both issues in https://github.com/systemd/systemd/pull/27035
