### ISSUE TITLE
IPv6 Compliance RFC4861: Router Advertisement Processing, Cur Hop Limit [v6LC.2.2.13 Part B]

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [systemd/systemd#28437]
### systemd version the issue has been seen with

250

### Used distribution

Embedded Linux - Debian-based

### Linux kernel version used

5.15.71-rt51+gc36e774d0d9a

### CPU architectures issue was seen on

aarch64

### Component

systemd-networkd

### Expected behaviour you didn't see

**Purpose**: Verify that a node properly processes the Cur Hop Limit field of a Router Advertisement.

#### Reference
[RFC4861](https://www.rfc-editor.org/rfc/rfc4861.txt) Neighbor Discovery – Sections 4.2 and 6.3.4

From section 4.2. Router Advertisement Message Format:
```
Cur Hop Limit        8-bit unsigned integer.  The default value that
                     should be placed in the Hop Count field of the IP
                     header for outgoing IP packets.  A value of zero
                     means unspecified (by this router).
```

From section 6.3.4. Processing Received Router Advertisements:
```
If the received Cur Hop Limit value is non-zero, the host SHOULD set
its CurHopLimit variable to the received value.
```

### Unexpected behaviour you saw

networkd ignores the RA's CurHopLimit parameter.

For comparison, stopping `networkd` and configuring the interface via `/etc/network/interfaces` results in a successful protocol exchange.

### Steps to reproduce the problem

The attached zip file has a `legacy` folder, where the network was configured via `/etc/network/interfaces` and a `networkd` folder, where the network was managed by `networkd`. The PCAP in the `legacy` folder demonstrates the expected protocol exchange, whereas the PCAP in the `networkd` folder demonstrates the failure.

Specifically, in the file `v6LC_2_2_13b-Net0-20230707042202-filtered.pcapng`, packet 11 shows the RA setting `Cur hop limit: 100`. The ping reply in packet 13 shows networkd has not used the `Cur hop limit` from the RA and instead uses the value 64.

[2_2_13b - Router Advertisement Processing, Cur Hop Limit.zip](https://github.com/systemd/systemd/files/12075238/2_2_13b.-.Router.Advertisement.Processing.Cur.Hop.Limit.zip)

### Additional program output to the terminal or log subsystem illustrating the issue

Reference: [IPv6 Core Conformance Specification](https://www.ipv6ready.org/docs/Core_Conformance.pdf), Test v6LC.2.2.13, part B.

**Comment by ssahani** [comment]
By default the current hop limit is set to 64 

```
❯ sudo cat /proc/sys/net/ipv6/conf/ens33/hop_limit 
64
```
The `hop_limit` is never used .  Could you please test with https://github.com/systemd/systemd/pull/28446

**Comment by LiveFreeAndRoam** [comment]
@ssahani, this patch is not working with systemd v254.  I've further instrumented the patch with a few extra `printf` statements, and the code is clearly seeing the RA hop_limit.  However, it is not being updated to the IPv6 header in the next reply.

```
[Y:rmc] mfw30:.../workspace/sources/systemd (devtool)$ git diff src/network/networkd-ndisc.c
diff --git a/src/network/networkd-ndisc.c b/src/network/networkd-ndisc.c
index 7ec9a2da62..73c1643953 100644
--- a/src/network/networkd-ndisc.c
+++ b/src/network/networkd-ndisc.c
@@ -189,8 +189,10 @@ static int ndisc_request_route(Route *in, Link *link, sd_ndisc_router *rt) {
                         return log_link_warning_errno(link, r, "Failed to get default router MTU from RA: %m");
         }
 
+        log_link_debug(link, "IPv6 Logo: ra_use_hop_limit:%d", link->network->ipv6_accept_ra_use_hop_limit);
        if (link->network->ipv6_accept_ra_use_hop_limit) {
                 r = sd_ndisc_router_get_hop_limit(rt, &hop_limit);
+                log_link_warning_errno(link, r, "IPv6 Logo: hop_limit route:%u RA:%d", route->hop_limit, hop_limit);
                 if (r < 0 && r != -ENODATA)
                         return log_link_warning_errno(link, r, "Failed to get default router hop limit from RA: %m");
         }
```

After enabling systemd-networkd debug, I see the following in journalctl:

```
Sep 08 04:10:45 sph-614-rmc systemd-networkd[4028]: eno0: IPv6 Logo: hop_limit route:0 RA:64
Sep 08 04:10:45 sph-614-rmc systemd-networkd[4028]: eno0: IPv6 Logo: hop_limit route:0 RA:64
:
Sep 08 04:10:49 sph-614-rmc ntpd[4968]: new interface(s) found: waking up resolver
Sep 08 04:10:53 sph-614-rmc systemd-networkd[4028]: eno0: IPv6 Logo: hop_limit route:0 RA:100
Sep 08 04:10:53 sph-614-rmc systemd-networkd[4028]: eno0: IPv6 Logo: hop_limit route:0 RA:100
:
Sep 08 04:11:06 sph-614-rmc systemd-networkd[4028]: eno0: IPv6 Logo: hop_limit route:0 RA:64
Sep 08 04:11:06 sph-614-rmc systemd-networkd[4028]: eno0: IPv6 Logo: hop_limit route:0 RA:64
```

As you can see, the code is seeing the RA's hop_limit, but that is not being sent in the IP header.

Which code change is meant to cause the hop_limit from the RA to be written to the IP header on the next response?

**Comment by LiveFreeAndRoam** [comment]
@ssahani @yuwata @keszybz this issue may need to be re-opened.

**Comment by ssahani** [comment]
I see we need to use `link_set_ipv6_hop_limit` that should fix it. So this https://github.com/systemd/systemd/pull/28446#issuecomment-1641305930 you tested fixed it ?

**Comment by ssahani** [comment]
> @ssahani @yuwata @keszybz this issue may need to be re-opened.

Please test with https://github.com/systemd/systemd/pull/29126

**Comment by LiveFreeAndRoam** [comment]
>  So this https://github.com/systemd/systemd/pull/28446#issuecomment-1641305930 you tested fixed it ?

That result confused me too. I can only presume my machine was running with networkd stopped when I reran the test. Sorry, for the confusion.

**Comment by LiveFreeAndRoam** [comment]
Thanks for the quick turn around. I will apply this patch and retest on Monday.

**Comment by LiveFreeAndRoam** [comment]
@ssahani @yuwata @keszybz 

Thank you! I have verified this is fixed by https://github.com/systemd/systemd/pull/29126.

**Comment by evverx** [comment]
I don't think it's fixed. systemd-networkd appears to have started spamming the journal in containers with
```sh
Sep 30 21:40:16 C systemd-networkd[54]: host0: Cannot set IPv6 hop limit for interface, ignoring: Invalid argument
Sep 30 21:40:16 C systemd-networkd[54]: host0: Cannot set IPv6 hop limit for interface, ignoring: Invalid argument
Sep 30 21:40:16 C systemd[1]: systemd-resolved.service: Got notification message from PID 57 (WATCHDOG=1)
Sep 30 21:40:30 C systemd-networkd[54]: host0: Cannot set IPv6 hop limit for interface, ignoring: Invalid argument
Sep 30 21:40:37 C systemd-networkd[54]: host0: Cannot set IPv6 hop limit for interface, ignoring: Invalid argument
Sep 30 21:40:51 C systemd-networkd[54]: host0: Cannot set IPv6 hop limit for interface, ignoring: Invalid argument
```
It apparently tries to set the hop limit to 0
```sh
read(10</proc/sys/net/ipv6/conf/host0/hop_limit>, "64\n", 3) = 3
lseek(10</proc/sys/net/ipv6/conf/host0/hop_limit>, 0, SEEK_SET) = 0
write(10</proc/sys/net/ipv6/conf/host0/hop_limit>, "0\n", 2) = -1 EINVAL (Invalid argument)
```
when it receives RAs sent by another instance of systemd-networkd running on the host
```
Internet Control Message Protocol v6
    Type: Router Advertisement (134)
    Code: 0
    Checksum: 0xf9b8 [correct]
    [Checksum Status: Good]
    Cur hop limit: 0
    Flags: 0x00, Prf (Default Router Preference): Medium
        0... .... = Managed address configuration: Not set
        .0.. .... = Other configuration: Not set
        ..0. .... = Home Agent: Not set
        ...0 0... = Prf (Default Router Preference): Medium (0)
        .... .0.. = Proxy: Not set
        .... ..0. = Reserved: 0
    Router lifetime (s): 1800
    Reachable time (ms): 0
    Retrans timer (ms): 0
    ICMPv6 Option (Source link-layer address : 76:1a:af:88:19:10)
        Type: Source link-layer address (1)
        Length: 1 (8 bytes)
        Link-layer address: 76:1a:af:88:19:10 (76:1a:af:88:19:10)
```

**Comment by yuwata** [comment]
0ba8374bb8a7032ca13ba98d10e8d7c3378ca9c6 will be reverted. See #29873.

**Comment by yuwata** [comment]
Note, as commented in #29873, the issue is caused by the hash and compare functions for Route object (again).

**Comment by yuwata** [comment]
Fix is waiting in #31173.

**Comment by LiveFreeAndRoam** [comment]
I merged your changes into my branch, and unfortunately the IPv6 Conformance test (2.2.13b) still fails.

I'll need a bit of time to analyze the results to see why it's not working as you might have hoped.

**Comment by LiveFreeAndRoam** [comment]
2.2.13b failure signature shows:

* FAIL: No Echo Reply transmitted with a Hop Limit that matches the first Reply

I'll dig in deeper to get more details.

**Comment by LiveFreeAndRoam** [comment]
@yuwata, it's a very simple protocol exchange...

This is the summary of the exchange and why it fails... Consider three nodes with a private IPv6 network between them.  The nodes are: TR1 (Test Router 1), TN1 (test node 1) and NUT (Node Under Test).

```
     TR1 ----+
             |
             +---- NUT
             |
     TN1 ----+
```

I've attached the PCAP and debug log in the zip file.  Below, the values in square brackets match the packets in the PCAP.

1. TN1 sends ping request and observes the NUT's ping reply with `HopLimit=64` (the default) [Pkt 7 & 10]
2. TR1 sends RA with `CurHopLimit=100` [Pkt 11]
3. TN1 sends ping request and observes the NUT's ping reply with `HopLimit=64` FAIL! Should be 100. [Pkt 12 & 13]

The test fails, because the ping reply in step 3, ought to have a `HopLimit=100`.

[v6LC_2_2_13b.zip](https://github.com/systemd/systemd/files/14161745/v6LC_2_2_13b.zip)

**Comment by LiveFreeAndRoam** [comment]
As I examine the code, I do not see a function to process the RA's `Current Hop Limit`.  Do you agree? If that's the issue, then I can add this function or did you want to do it?

**Comment by yuwata** [comment]
In `ndisc_request_route()`, `sd_ndisc_router_get_hop_limit()` is called and the value is set to the Route object. So I thought the PR fixes the issue.

BTW, I am still waiting for debugging log of networkd during the test suite running. That's much helpful when debugging issues like this.

**Comment by yuwata** [comment]
Oh, I did not know that. Thanks. I will take a look.

**Comment by LiveFreeAndRoam** [comment]
From watching updates to the routing table, it's still not clear to me why networkd's `ping reply` uses the default hop limit, rather than the current hop limit that is set by the RA. The routing table for networkd looks ok, despite small differences between `native` and `networkd`.  If you have any suggestions, I'll gladly follow up.

I have compared the routing table between the native configuration (accept_ra=2) and the networkd configuration (accept_ra=0).

NOTE: The conformance test passes with the native configuration and fails with the networkd configuration.

I've annotated 4-stages of the test:

| State | Native (accept_ra=2) | Networkd (accept_ra=0) | Comments |
|--------|--------|--------|--------|
| 1. Initial | - | - | same starting state |
| 2. Receive RA w/ prefix | prefix route metric 256 proto kernel, default metric 1024 | prefix route metric 1024 proto RA, default metric 1024| Difference in prefix route's metric value |
| 3. Receive RA hoplimit = 100 | Applied to default route only| Applied to both prefix and default routes | Difference in prefix route |
| 4. RA clear prefix | - | - | same ending state| 

> The output below is an extract from this one-liner:
> 
> ```
> while :; do date +"%F %T.%N:%n""`ip -6 r | grep enp0s9`%n"; sleep 0.2; done
> ```
> 

## Native
```
# Initial state
2024-02-06 11:41:04.081594120:
fe80::/64 dev enp0s9 proto kernel metric 256 pref medium

# First RA sets the prefix
2024-02-06 11:41:04.292339468:
2001:2:0:1000::/64 dev enp0s9 proto kernel metric 256 expires 65534sec pref medium
fe80::/64 dev enp0s9 proto kernel metric 256 pref medium
default via fe80::200:10ff:fe10:1060 dev enp0s9 proto ra metric 1024 expires 8999sec hoplimit 64 pref medium
   :
   :
# Second RA sets hoplimit=100
2024-02-06 11:41:12.676067793:
2001:2:0:1000::/64 dev enp0s9 proto kernel metric 256 expires 65534sec pref medium
fe80::/64 dev enp0s9 proto kernel metric 256 pref medium
default via fe80::200:10ff:fe10:1060 dev enp0s9 proto ra metric 1024 expires 8999sec hoplimit 100 pref medium
   :
   :
# Third RA clears the prefix
2024-02-06 11:41:13.745247932:
fe80::/64 dev enp0s9 proto kernel metric 256 pref medium
```

## Systemd-Networkd
```
# Initial state
2024-02-06 11:54:33.090725216:
fe80::/64 dev enp0s9 proto kernel metric 256 pref medium

# First RA sets the prefix
2024-02-06 11:54:33.309374056:
2001:2:0:1000::/64 dev enp0s9 proto ra metric 1024 expires 65534sec mtu 1500 hoplimit 64 pref medium
fe80::/64 dev enp0s9 proto kernel metric 256 pref medium
default via fe80::200:10ff:fe10:1060 dev enp0s9 proto ra metric 1024 expires 8999sec mtu 1500 hoplimit 64 pref medium
   :
   :
# Second RA sets hoplimit=100
2024-02-06 11:54:41.496782656:
2001:2:0:1000::/64 dev enp0s9 proto ra metric 1024 expires 65534sec hoplimit 100 pref medium
fe80::/64 dev enp0s9 proto kernel metric 256 pref medium
default via fe80::200:10ff:fe10:1060 dev enp0s9 proto ra metric 1024 expires 8999sec hoplimit 100 pref medium
   :
   :
# Third RA clears the prefix
2024-02-06 11:54:54.612748044:
fe80::/64 dev enp0s9 proto kernel metric 256 pref medium
```

**Comment by LiveFreeAndRoam** [comment]
I'm going to pursue this further with the owners of the IPv6 Conformance Test Suite. 

I found that if I interrupt the test before it clears the prefix, and manually create the IPv6 address `2001:2:0:1000:200:10ff:fe10:1080`, then I am able to ping6 the remote and it responds with an echo reply that has `hoplimit=100`, as expected.

**Comment by yuwata** [comment]
Could you also check syactl value change during the test?

**Comment by LiveFreeAndRoam** [comment]
Yes, I verify that when networkd is running, `net.ipv6.conf.enp0s9.accept_ra=0`.

**Comment by yuwata** [comment]
How about hop limit in sysctl? IIRC, there is a related setting. (Sorry, today I am off, and cannot access my laptop, so I am not sure)

**Comment by LiveFreeAndRoam** [comment]
I'm still collecting more information, and may have discovered something worthwhile...

When the ping request targets the LLA, the returned hoplimit=64.  When the ping request targets the GA, the returned hoplimit=100.

Evidently, your code changes properly configure the hoplimit in the route for the GA, however they do not affect the hoplimit for the LLA.

Glad to hear your thoughts on this.

**Comment by LiveFreeAndRoam** [comment]
> How about hop limit in sysctl? IIRC, there is a related setting. (Sorry, today I am off, and cannot access my laptop, so I am not sure)

That's it!

`net.ipv6.conf.enp0s9.hop_limit = 64`

Changing this to match the route will make it all work. I then checked the native configuration and sure enough, it also changes the sysctl hop_limit value to match that in the RA.

**Comment by LiveFreeAndRoam** [comment]
I have verified a patch for this.  I added the following function to src/network/networkd-ndisc.c

```
static int ndisc_router_process_hop_limit(Link *link, sd_ndisc_router *rt) {
        uint8_t hop_limit;
        int r;

        assert(link);
        assert(link->network);
        assert(rt);

        if (!link->network->ipv6_accept_ra_use_retransmission_time)
                return 0;

        r = sd_ndisc_router_get_hop_limit(rt, &hop_limit);
        if (r < 0) {
                log_link_debug_errno(link, r, "Failed to get hop_limit from RA, ignoring: %m");
                return 0;
        }

        if (hop_limit == 0)
                return 0;

        /* Set the hop_limit for this interface. */
        r = sysctl_write_ip_property_uint32(AF_INET6, link->ifname, "hop_limit", (uint32_t) hop_limit);
        if (r < 0)
                log_link_warning_errno(
                        link, r, "Failed to apply hop_limit (%d), ignoring: %m", hop_limit);

        return 0;
}
```
I call it from `ndisc_router_handler()`:

```
        r = ndisc_router_process_hop_limit(link, rt);
        if (r < 0)
                return r;
```

After retesting with the conformance test suite, the test now passes.

I'd be grateful if you can add this patch to #31173, which would save me from creating a PR.

**Comment by yuwata** [comment]
@LiveFreeAndRoam Thanks. Your patch is added to #31173. PTAL.
