### ISSUE TITLE
Virtual Console Setup Hung Indefinitely at boot after updating to v254

### ISSUE THREAD

**Issue by clueo8** [systemd/systemd#28677]
### systemd version the issue has been seen with

254

### Used distribution

Arch Linux

### Linux kernel version used

6.1.39-3-lts

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

Could no longer boot into my system after updating systemd to 254, it was hung up on:

A start job is running for Virtual Console Setup

### Steps to reproduce the problem

Update systemd to 254 on archlinux, reboot.

**Comment by prg318** [comment]
I can reproduce this issue on a variety of hardware (a few different laptops with both nvidia and intel graphics)

To temporarily workaround the issue (without downgrading systemd), you can patch the systemd-vconsole-setup service to not run the systemd-vconsole-setup binary that hangs the boot process and never times out:

    sed -i 's|ExecStart=/usr/lib/systemd/systemd-vconsole-setup|ExecStart=/usr/bin/true|' /usr/lib/systemd/system/systemd-vconsole-setup.service

**Comment by clueo8** [comment]
Confirmed workaround.

If /etc/vconsole.conf does not contain anything, is running systemd-vconsole-setup at boot even nessisary?

**Comment by mrc0mmand** [comment]
Can you grab a debug log from a boot where the `systemd-vconsole-setup` service gets stuck? Or, if none of the tty's working, maybe adding `systemd.log_level=debug systemd.log_target=console systemd.default_standard_output=journal+console` to the kernel cmdline should dump the info to the console so you can see what's going on.

**Comment by clueo8** [comment]
As requested:
[boot.zip](https://github.com/systemd/systemd/files/12280173/boot.zip)

**Comment by mrc0mmand** [comment]
> As requested: [boot.zip](https://github.com/systemd/systemd/files/12280173/boot.zip)

Ah, so you're able to get the journal - in that case please drop the `systemd.log_target=console` and boot only with `systemd.log_level=debug systemd.default_standard_output=journal+console`.

**Comment by dolcini** [comment]
Is this error, related? 

Happening with latest OE-core, seems also reported here https://bugs.archlinux.org/task/79287 

```
x systemd-vconsole-setup.service - Virtual Console Setup
     Loaded: loaded (/lib/systemd/system/systemd-vconsole-setup.service; static)
     Active: failed (Result: exit-code) since Mon 2023-08-07 15:34:29 UTC; 8min ago
       Docs: man:systemd-vconsole-setup.service(8)
             man:vconsole.conf(5)
    Process: 765 ExecStart=/lib/systemd/systemd-vconsole-setup (code=exited, status=1/FAILURE)
   Main PID: 765 (code=exited, status=1/FAILURE)
Aug 07 15:34:29 localhost systemd[1]: Starting Virtual Console Setup...
Aug 07 15:34:29 localhost systemd-vconsole-setup[765]: /bin/loadkeys failed with exit status 1.
Aug 07 15:34:29 localhost systemd[1]: systemd-vconsole-setup.service: Main process exited, code=exited, status=1/FAILURE
Aug 07 15:34:29 localhost systemd[1]: systemd-vconsole-setup.service: Failed with result 'exit-code'.
Aug 07 15:34:29 localhost systemd[1]: Failed to start Virtual Console Setup.
```

**Comment by mrc0mmand** [comment]
This is strange. Going through the log, the `systemd-vconsole-setup` binary forks off `loadkeys`:

```
Aug 07 11:14:54 archlinux systemd-vconsole-setup[502]: Sysfs UTF-8 flag enabled
Aug 07 11:14:54 archlinux systemd-vconsole-setup[502]: UTF-8 kbdmode enabled on /dev/tty1
Aug 07 11:14:54 archlinux systemd-vconsole-setup[502]: Executing "/usr/bin/loadkeys -q -C /dev/tty1 -u us"...
Aug 07 11:14:54 archlinux systemd-vconsole-setup[502]: Successfully forked off '(loadkeys)' as PID 523.
```

which then, for some reason, triggers an automount for `/mnt/mycloud`:
```
Aug 07 11:14:54 archlinux systemd[1]: mnt-mycloud.automount: Got automount request for /mnt/mycloud, triggered by 523 (loadkeys)
Aug 07 11:14:54 archlinux systemd[1]: mnt-mycloud.mount: Trying to enqueue job mnt-mycloud.mount/start/replace
``` 

which then waits for the `network-online.target`:
```
Aug 07 11:14:54 archlinux systemd[1]: mnt-mycloud.mount: starting held back, waiting for: network-online.target
```

and if we follow the deps one after another we get to:
```
Aug 07 11:14:54 archlinux systemd[1]: network-online.target: starting held back, waiting for: NetworkManager-wait-online.service
Aug 07 11:14:54 archlinux systemd[1]: NetworkManager-wait-online.service: starting held back, waiting for: sysinit.target
Aug 07 11:14:54 archlinux systemd[1]: sysinit.target: starting held back, waiting for: systemd-vconsole-setup.service
```

which leads up to a dependency cycle, but in this case it's unfortunately "hidden" from systemd, since the automount unit is triggered indirectly by `loadkeys`.

So the main question is: why `loadkeys` trigger the automount in the first place?

**Comment by clueo8** [comment]
fstab for that storage contains a few systemd flags:
`192.168.1.XXX:/mnt/HD/HD_a2 /mnt/mycloud nfs auto,nolock,x-systemd.automount,x-systemd.device-timeout=10,timeo=14 0 0`

**Comment by mrc0mmand** [comment]
> fstab for that storage contains a few systemd flags: `192.168.1.XXX:/mnt/HD/HD_a2 /mnt/mycloud nfs auto,nolock,x-systemd.automount,x-systemd.device-timeout=10,timeo=14 0 0`

I can't reproduce the issue even with the same mount arguments, strange. Could you, temporarily, comment out the nfs mounts in `/etc/fstab`, boot into the system (hopefully successfully this time) and run `strace -s 500 -y -v -f /usr/bin/loadkeys -q -C /dev/tty1 -u us`? I'm really curious what exactly triggers the automount.

**Comment by yuwata** [comment]
> which leads up to a dependency cycle, but in this case it's unfortunately "hidden" from systemd, since the automount unit is triggered indirectly by `loadkeys`.

Hmm... I think PID1 should handle such dependency cycle gracefully.

**Comment by yuwata** [comment]
> fstab for that storage contains a few systemd flags: `192.168.1.XXX:/mnt/HD/HD_a2 /mnt/mycloud nfs auto,nolock,x-systemd.automount,x-systemd.device-timeout=10,timeo=14 0 0`

Are there any symlink under /usr or so to /mnt/myclound ?

**Comment by clueo8** [comment]
> Are there any symlink under /usr or so to /mnt/myclound ?

Yes, I have a handful of symlinks which point to directories within this path.

**Comment by poettering** [comment]
> Yes, I have a handful of symlinks which point to directories within this path.

/usr/ must be self-contained, i.e. the inodes accessible through it must be available in early boot, everything else is not supported. Thus if you put symlinks there that are backed by autofs, you are voiding your warranty since earl-boot disk accesses will deadlock on your mount that might need later stuff.

Sorry, but this is not supported, if you do it anyway you get to keep the pieces.

**Comment by clueo8** [comment]
The symlinks are not under /usr, they are on the root /.

**Comment by poettering** [comment]
then plese provide the requested strace of loadkeys

**Comment by clueo8** [comment]
[strace.zip](https://github.com/systemd/systemd/files/12291915/strace.zip)

**Comment by poettering** [comment]
.zip? seriously? is this 1990s windows? just use https://gist.github.com/ please. let's not make this harder than necessary.

**Comment by clueo8** [comment]
[https://gist.github.com/clueo8/9f9f51e8df6b7b57d9ab7d93b0c5367c](url)

**Comment by poettering** [comment]
uh, loadkeys seems to look in the cwd for a keymap. wtf. that's a security issue

**Comment by poettering** [comment]
(same behaviour here btw, except i have no automounts there)

**Comment by legionus** [comment]
> A work-around might be to just do `WorkingDirectory=/usr/lib/kbd`
> which is a dir that kbd installs and should have nothing bad in it we'd want to avoid.
> But honestly i'd really prefer if kdb would fix this rather than us work around.

You need this workaround anyway for old kbd versions.

**Comment by mrc0mmand** [comment]
I wonder what exactly changed, since as far as I understand this, the issue appeared after upgrading to systemd v254. So I assume things worked fine prior to that with the exact same setup?

**Comment by mrc0mmand** [comment]
Maybe a6f3a7eb8acb457e2d0a9974a03662870bdf0de0 could be the relevant change here.

**Comment by poettering** [comment]
Fixed in https://github.com/legionus/kbd/commit/a770f39f79e6a5fdf8f352d8b26d6a50c6b137ff upstream. (kbd-2.6.2)

I am tempted to just close this here now, given I'd claim this is a corner case (i.e. early autofs in root fs), and the fix is trivial for all distros to backport.

**Comment by yuwata** [comment]
Yeah, this is not our bug, and occurs specific setup. Closing.

**Comment by prgreadonly** [comment]
> Fixed in [legionus/kbd@a770f39](https://github.com/legionus/kbd/commit/a770f39f79e6a5fdf8f352d8b26d6a50c6b137ff) upstream. (kbd-2.6.2)
> 
> I am tempted to just close this here now, given I'd claim this is a corner case (i.e. early autofs in root fs), and the fix is trivial for all distros to backport.

FYI - this is still reproducible with systemd 254.2 and kbd 2.6.2

**Comment by legionus** [comment]
This is because setfont also needs to be fixed.

**Comment by uffejakobsen** [comment]
@legionus 
> This is because setfont also needs to be fixed.
It seems from the `kbd` commit log that `setfont` was fixed for kbd-2.6.3 release ?

**Comment by legionus** [comment]
> It seems from the `kbd` commit log that `setfont` was fixed for kbd-2.6.3 release ?

@uffejakobsen Yes. I fixed it almost as soon as I found it.

**Comment by uffejakobsen** [comment]
I still see this problem - even with systemd-254.5 and kbd-2.6.3 (on ArchLinux)

**Comment by solson** [comment]
This is still a problem for me with systemd-254.3 and kbd-2.6.3 on NixOS. Which versions are supposed to fix the problem?
