### ISSUE TITLE
Unclear message: "Failed to dissect: Structure needs cleaning"

### ISSUE THREAD

**Issue by UltimateByte** [systemd/systemd#31799]
### Component

systemd-gpt-auto-generator

### Is your feature request related to a problem? Please describe

Receiving this error once a day in syslog/journalctl on my OpenMediaVault machine:

```
Mar 15 08:35:17 nas.lrob.net systemd[1]: Reloading.
Mar 15 08:35:18 nas.lrob.net systemd-gpt-auto-generator[196408]: Failed to dissect: Structure needs cleaning
Mar 15 08:35:18 nas.lrob.net (sd-execut[196398]: /usr/lib/systemd/system-generators/systemd-gpt-auto-generator failed with exit status 1.
```

Might be since update from OpenMediaVault 6 to 7 (Debian 11 to 12), or maybe before. I noticed during the upgrade. I also had a MD RAID 5 with one disk starting failing, so I thought this was the cause but replacing the drive still shows this error at least once a day during a cron, at least for now while rebuilding (takes a long time since it's 16TB drives, it'll be over in 5 hours and I'll see tomorrow if it helps).

Problem with this error : With around 20 years of experience with Linux, I still can't figure out what this message means. Either I'm deeply stupid, either this message is actually unclear. I like to think that's more of the second option.

Failed to dissect what? Structure of what needs cleaning?

Of course I found this doc/man:
https://manpages.debian.org/bullseye/systemd/systemd-gpt-auto-generator.8.en.html
So I guess it's trying to discover some system partitions, but no info about "dissecting" anything or about what needs cleaning. But didn't see clear documentation about this message whatsoever.

Only thing found is issues here with a quite different message (like https://github.com/systemd/systemd/issues/5806 or https://github.com/systemd/systemd/issues/19377 or https://github.com/systemd/systemd/issues/25494 and of course some topics on Arch forums https://bbs.archlinux.org/viewtopic.php?id=229412). But that doesn't help understanding anything in my case as error messages are different.

### Describe the solution you'd like

I'd like to see more verbosity with these messages with specific info about which errors it found.

As well as some documentation anywhere about what these messages mean.

Ultimately if anybody knows a way to diagnose what is going on I'll take it.

### Describe alternatives you've considered

I'm considering reinstalling the OS as I noticed this after upgrading from Debian 11 to 12 (OMV 6 to 7) and noticing at the same time one drive of my MD RAID 5 starting to fail, and currently changed for a new one and rebuilding, but the error still shows. Though in my book, reinstalling without understanding an issue is a fail.

Thanks anyone for helping with this issue/bug/feature enhancement and understanding.

### The systemd version you checked that didn't have the feature you are asking for

252.22-1~deb12u1 amd64

**Comment by UltimateByte** [comment]
For info and googlers, it would seem that in my case, this issue was caused by the swap partition not having an UUID. Resolved with `swapoff -a`, then `mkswap` on the actual swap partition, then update fstab with UUID and reboot (or remount everything). However I don't know how to manually trigger this event, so I'll only be able to make sure of this tomorrow, unless someone can tell how to trigger it.

Initial request still stands.

**Comment by ikolesnikes** [comment]
I had the same case with uninitialized swap partition.
The event was triggering when I did installation of a package.
apt install <any package>
and I saw the new message in the journal.

**Comment by jult** [comment]
This bug is still there. With a clean netinstall (minimal) of debian bookworm/12. I'd say this is a pretty bad one. Like the TS; tried reinstalling, did everything according to defaults essentially, on a new nvme, and it still appeared! Also, I do wonder what actual current system still really needs swap partitions, as DDR4 prices are quite low, and I doubt a swap partition makes sense these days. Installer should prompt the user to skip creating swap i.m.o.

**Comment by afredzhou** [comment]
I am facing the same issue with connect wifi

**Comment by UltimateByte** [comment]
> I am facing the same issue with connect wifi

I doubt Wifi is related to this.

**Comment by davidschaper** [comment]
I had the same issue on Debian 12 (Bookworm), disabling swap and mkswap-ing the swap partition fixed it.
