### ISSUE TITLE
systemd unexpectedly(?) terminates units with `Unexpected error response from GetNameOwner(): Connection terminated` during a "mount storm"

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#32381]
We have an internal customer that started experiencing unexpected restarts of certain units on their OpenShift clusters. After analyzing logs the symptoms looked very similar to [this issue](https://github.com/systemd/systemd/issues/15316), since the affected units reported `Unexpected error response from GetNameOwner(): Connection terminated` just before getting restarted. However, we already have patches for that in RHEL.

Another candidate was https://github.com/systemd/systemd/issues/30573, but I failed to reproduce that issue on multiple machines with several reproducers I could come up with. However, after putting these reproducers together with a couple of other hints from customer's logs, I was able to _conjure_ a slightly different (and _spiced up_) reproducer, that appears to reproduce the issue the customer is facing not only on RHELs, but also on Fedora Rawhide, and the latest systemd upstream (af46138f39acb55f1faefcb48ebc3316efac87b4 ATTOW, also on Rawhide). In all cases `dbus-broker` was used as the dbus... broker.

Reproducer:
```bash
#/bin/bash
set -eux
set -o pipefail

NMOUNTS=800
MPOINT="$(findmnt --mountpoint / --noheading -o SOURCE)"
TS="$(date +"%s.%N")"

systemctl mask --now --runtime systemd-oomd.{socket,service}
id testuser || useradd testuser
systemctl stop "tmp-mnt*.mount" || :
systemctl log-level debug

for i in {0..100}; do
        echo "=== $i ==="
        for i in $(seq 0 $NMOUNTS); do
                mkdir -p "/tmp/mnt$i"
                systemd-mount "$MPOINT" "/tmp/mnt$i" &
        done
        wait
        for i in $(seq 0 $NMOUNTS); do
                systemd-umount "/tmp/mnt$i" &
        done
        wait

        busctl status --user --machine=testuser@ --no-pager
        systemctl stop user@4711.service
        (! journalctl --since="@$TS" --grep "Connection terminated")
done
```

With this reproducer I get following output in a couple of iterations (really depends on the machine you run this on and your luck):
```
# systemctl --version
systemd 256~devel (256~devel-gaf46138)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP -GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBCRYPTSETUP_PLUGINS +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT -LIBARCHIVE
# ./repro.sh
...
++ systemctl stop user@4711.service
++ journalctl --since=@1713626172.951606857 --grep 'Connection terminated'
-- No entries --
++ for i in {0..100}
++ echo '=== 1 ==='
=== 1 ===
+++ seq 0 800
...
Failed to stop automount unit: Connection timed out
Failed to stop automount unit: Connection timed out
Failed to stop automount unit: Connection timed out
++ busctl status --user --machine=testuser@ --no-pager
BusAddress=unixexec:path=systemd-run,argv1=-M.host,argv2=-PGq,argv3=--wait,argv4=-pUser%3dtestuser,argv5=-pPAMName%3dlogin,argv6=systemd-stdio-bridge,argv7=-punix:path%3d%24%7bXDG_RUNTIME_DIR%7d/bus
BusID=db15434bb5619733c1ee88f5c4c006b1
PID=8351
PIDFD=yes
EUID=0
EGID=0
SupplementaryGIDs=0
Label=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
++ systemctl stop user@4711.service
++ journalctl --since=@1713626172.951606857 --grep 'Connection terminated'
Apr 20 11:25:30 xxx systemd[1]: systemd-homed.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 20 11:25:30 xxx systemd[1]: systemd-hostnamed.service: Unexpected error response from GetNameOwner(): Connection terminat>
Apr 20 11:25:30 xxx systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 20 11:25:30 xxx systemd[1]: NetworkManager.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 20 11:25:30 xxx systemd[1]: avahi-daemon.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 20 11:25:30 xxx systemd[1]: systemd-resolved.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 20 11:25:30 xxx systemd[1]: systemd-networkd.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 20 11:25:30 xxx systemd[1]: udisks2.service: Unexpected error response from GetNameOwner(): Connection terminated
...
```

More details from the journal:
```
...
[  747.889938] systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/tmp_2dmnt199_2emount interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=8 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[  747.889987] systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/tmp_2dmnt199_2emount interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=9 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[  747.890050] systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/tmp_2dmnt199_2emount interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=470 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[  747.890101] systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/tmp_2dmnt199_2emount interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=471 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[  747.890152] systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/tmp_2dmnt199_2emount interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=314 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[  747.890199] systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/tmp_2dmnt199_2emount interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=315 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[  764.600613] systemd[1]: systemd-homed.service: Unexpected error response from GetNameOwner(): Connection terminated
[  764.687538] systemd[1]: systemd-homed.service: Deactivated successfully.
[  764.687805] audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-homed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  764.736119] systemd[1]: systemd-hostnamed.service: Unexpected error response from GetNameOwner(): Connection terminated
[  764.736517] audit: BPF prog-id=49 op=UNLOAD
[  764.737643] systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
[  764.738216] systemd[1]: NetworkManager.service: Unexpected error response from GetNameOwner(): Connection terminated
[  764.738638] NetworkManager[768]: <info>  [1713626730.6956] caught SIGTERM, shutting down normally.
[  764.739340] NetworkManager[768]: <info>  [1713626730.6963] dhcp4 (eth0): canceled DHCP transaction
[  764.739428] NetworkManager[768]: <info>  [1713626730.6963] dhcp4 (eth0): activation: beginning transaction (timeout in 45 seconds)
[  764.739488] NetworkManager[768]: <info>  [1713626730.6963] dhcp4 (eth0): state changed no lease
[  764.739568] NetworkManager[768]: <info>  [1713626730.6965] manager: NetworkManager state is now CONNECTED_SITE
[  764.741702] NetworkManager[768]: <info>  [1713626730.6988] exiting (success)
[  764.785825] audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=NetworkManager comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  764.785993] systemd[1]: NetworkManager.service: Deactivated successfully.
[  764.834007] systemd[1]: avahi-daemon.service: Unexpected error response from GetNameOwner(): Connection terminated
[  764.834605] avahi-daemon[744]: Got SIGTERM, quitting.
[  764.835133] avahi-daemon[744]: Leaving mDNS multicast group on interface eth0.IPv6 with address 2620:52:0:bb:f816:3eff:fe67:3519.
[  764.835201] avahi-daemon[744]: Leaving mDNS multicast group on interface eth0.IPv4 with address 10.0.187.174.
[  764.835251] avahi-daemon[744]: Leaving mDNS multicast group on interface lo.IPv6 with address ::1.
[  764.835321] avahi-daemon[744]: Leaving mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
[  764.835399] avahi-daemon[744]: avahi-daemon 0.8 exiting.
[  764.881474] systemd[1]: avahi-daemon.service: Deactivated successfully.
[  764.881747] audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=avahi-daemon comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  764.968329] systemd[1]: systemd-resolved.service: Unexpected error response from GetNameOwner(): Connection terminated
[  764.969842] systemd[1]: systemd-networkd.service: Unexpected error response from GetNameOwner(): Connection terminated
[  764.970411] systemd[1]: udisks2.service: Unexpected error response from GetNameOwner(): Connection terminated
[  764.970969] systemd[1]: systemd-timesyncd.service: Unexpected error response from GetNameOwner(): Connection terminated
...
```

The most problematic part is the unexpected NetworkManager restart (as that's how the customer noticed the issue in the first place). However, the system itself seems to be fine after this _incident_:

```
# systemctl status
● xxx
    State: running
    Units: 397 loaded (incl. loaded aliases)
     Jobs: 0 queued
   Failed: 0 units
    Since: Sat 2024-04-20 11:12:47 EDT; 18min ago
  systemd: 256~devel-gaf46138
   CGroup: /
...
```

And now for the big questions - is this our issue or somebody else's (dbus-broker?)? And can we do anything about it?

/cc @msekletar @rmetrich

**Comment by mrc0mmand** [comment]
> In all cases dbus-broker was used as the dbus... broker.

Just out of curiosity, I replaced `dbus-broker` with `dbus-daemon` on the Rawhide test machine and the results are the same.

**Comment by mrc0mmand** [comment]
Here's one interesting data point: I let the reproducer run on two machines again overnight (and for the most of Sunday, so 16+ hours on each machne) after the first "crash", and it is still running - no crashes whatsoever. But if I reboot either of those machines and start the reproducer again, it crashes in just a couple of iterations again (and then continues without any further crashes).

So it looks like the "crash" happens once (or twice in a quick succession, to be more precise), and from there it seems fine no matter how hard I hammer the machine, until the next reboot.

That is, this is the full "double crash" that happens initially (latest main on Rawhide):
```
[ 3207.675737] systemd[1]: Mounted tmp-mnt98.mount.
[ 3207.678658] systemd[1]: Mounted tmp-mnt99.mount.
[ 3235.286101] systemd[1]: udisks2.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 3235.287100] systemd[1]: avahi-daemon.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 3235.287478] avahi-daemon[736]: Got SIGTERM, quitting.
[ 3235.287958] avahi-daemon[736]: Leaving mDNS multicast group on interface eth0.IPv6 with address 2620:52:0:bb:f816:3eff:fe40:9445.
[ 3235.288031] avahi-daemon[736]: Leaving mDNS multicast group on interface eth0.IPv4 with address 10.0.185.167.
[ 3235.288085] avahi-daemon[736]: Leaving mDNS multicast group on interface lo.IPv6 with address ::1.
[ 3235.288143] avahi-daemon[736]: Leaving mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
[ 3235.292155] avahi-daemon[736]: avahi-daemon 0.8 exiting.
[ 3235.340082] systemd[1]: avahi-daemon.service: Deactivated successfully.
[ 3235.340576] audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=avahi-daemon comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 3235.438624] systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 3235.439286] systemd[1]: systemd-homed.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 3235.550745] systemd[1]: systemd-homed.service: Deactivated successfully.
[ 3235.551125] audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-homed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 3235.615132] audit: BPF prog-id=65 op=UNLOAD
[ 3235.615330] systemd[1]: systemd-networkd.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 3235.615933] systemd[1]: systemd-resolved.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 3235.616641] systemd[1]: systemd-hostnamed.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 3235.617218] systemd[1]: systemd-timesyncd.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 3235.617991] systemd[1]: NetworkManager.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 3235.618489] NetworkManager[760]: <info>  [1713649856.4647] caught SIGTERM, shutting down normally.
[ 3235.619803] NetworkManager[760]: <info>  [1713649856.4662] dhcp4 (eth0): canceled DHCP transaction
[ 3235.619989] NetworkManager[760]: <info>  [1713649856.4662] dhcp4 (eth0): activation: beginning transaction (timeout in 45 seconds)
[ 3235.620112] NetworkManager[760]: <info>  [1713649856.4663] dhcp4 (eth0): state changed no lease
[ 3235.620417] NetworkManager[760]: <info>  [1713649856.4668] manager: NetworkManager state is now CONNECTED_SITE
[ 3235.624064] NetworkManager[760]: <info>  [1713649856.4705] exiting (success)
[ 3235.673354] systemd[1]: NetworkManager.service: Deactivated successfully.
[ 3235.673875] audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=NetworkManager comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
...
[ 3363.909334] systemd[1]: Unmounted tmp-mnt99.mount.
[ 3364.013839] systemd[1]: user-runtime-dir@1001.service: Deactivated successfully.
[ 3364.014048] systemd[1]: Stopped user-runtime-dir@1001.service.
[ 3364.036622] audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=user-runtime-dir@1001 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 3369.808828] systemd[1]: udisks2.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 3369.809489] systemd[1]: avahi-daemon.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 3369.809588] systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 3369.809672] systemd[1]: systemd-homed.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 3369.809770] systemd[1]: systemd-networkd.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 3369.809856] systemd[1]: systemd-resolved.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 3369.809937] systemd[1]: systemd-hostnamed.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 3369.810031] systemd[1]: systemd-timesyncd.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 3369.810123] systemd[1]: NetworkManager.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 3369.812073] systemd[1]: Removed slice user-1001.slice.
[ 3369.830819] systemd[1]: Started run-u65.service.
```

And from now on there doesn't seem to be any similar "crashes" until the machine is rebooted.

**Comment by poettering** [comment]
Looks to me as if the broker kicks us off the bus. Maybe we hit some message limit, because of the many PropertiesChanged signals we generate or so?

if you turn of debug logging in the broker, does it show anything interesting?

**Comment by mrc0mmand** [comment]
This might be a slightly difficult (which is an issue in itself), but in the meantime the dbus-daemon logs show this just ~5 seconds before systems starts throwing errors:

```
[  974.472229] systemd[1]: Mounted tmp-mnt404.mount.
[  974.500563] systemd[1]: Mounted tmp-mnt405.mount.
[  974.523083] dbus-daemon[744]: [system] Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)
[  974.527767] systemd[1]: Mounted tmp-mnt406.mount.
[  974.555652] systemd[1]: Mounted tmp-mnt407.mount.
```

**Comment by mrc0mmand** [comment]
Yeah, there's a bunch of timeouts before the _kicking_ happens:

```
]# journalctl -b --no-pager --no-hostname -o short-monotonic -p info _SYSTEMD_UNIT=dbus-daemon.service 
[    4.395420] dbus-daemon[737]: [system] SELinux support is enabled
[    6.449341] dbus-daemon[737]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.6' (uid=0 pid=759 comm="/usr/sbin/NetworkManager --no-daemon" label="system_u:system_r:NetworkManager_t:s0")
[    6.585767] dbus-daemon[737]: [system] Successfully activated service 'org.freedesktop.hostname1'
[    6.617726] dbus-daemon[737]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service' requested by ':1.6' (uid=0 pid=759 comm="/usr/sbin/NetworkManager --no-daemon" label="system_u:system_r:NetworkManager_t:s0")
[    6.673848] dbus-daemon[737]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
[ 1462.284100] dbus-daemon[737]: [system] Rejected send message, 2 matched rules; type="method_call", sender=":1.21" (uid=1001 pid=4611 comm="(sd-pam)" label="system_u:system_r:init_t:s0") interface="org.freedesktop.login1.Manager" member="ReleaseSession" error name="(unset)" requested_reply="0" destination="org.freedesktop.login1" (uid=0 pid=741 comm="/usr/lib/systemd/systemd-logind" label="system_u:system_r:systemd_logind_t:s0")
[ 1579.480912] dbus-daemon[737]: [system] Rejected send message, 2 matched rules; type="method_call", sender=":1.22" (uid=1001 pid=4602 comm="(sd-pam)" label="system_u:system_r:init_t:s0") interface="org.freedesktop.login1.Manager" member="ReleaseSession" error name="(unset)" requested_reply="0" destination="org.freedesktop.login1" (uid=0 pid=741 comm="/usr/lib/systemd/systemd-logind" label="system_u:system_r:systemd_logind_t:s0")
[ 1583.573093] dbus-daemon[737]: [system] Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)
[ 1588.615026] dbus-daemon[737]: [system] Connection has not authenticated soon enough, closing it (auth_timeout=30000ms, elapsed: 30002ms)
[ 1608.576630] dbus-daemon[737]: [system] Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)
[ 1633.586669] dbus-daemon[737]: [system] Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)
[ 1658.599699] dbus-daemon[737]: [system] Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)
[ 1665.374225] dbus-daemon[737]: [system] Activating systemd to hand-off: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service' requested by ':1.6' (uid=0 pid=759 comm="/usr/sbin/NetworkManager --no-daemon" label="system_u:system_r:NetworkManager_t:s0")
[ 1683.618633] dbus-daemon[737]: [system] Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)
[ 1690.377194] dbus-daemon[737]: [system] Failed to activate service 'org.freedesktop.nm_dispatcher': timed out (service_start_timeout=25000ms)
[ 1717.011329] dbus-daemon[737]: [system] Connection has not authenticated soon enough, closing it (auth_timeout=30000ms, elapsed: 30009ms)
[ 1818.515350] dbus-daemon[737]: [system] Successfully activated service 'org.freedesktop.systemd1'
[ 1818.622638] dbus-daemon[737]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.27' (uid=0 pid=8208 comm="(systemd)" label="system_u:system_r:init_t:s0")
[ 1818.686025] dbus-daemon[737]: [system] Successfully activated service 'org.freedesktop.home1'
[ 1819.007295] dbus-daemon[737]: [system] Rejected send message, 2 matched rules; type="method_call", sender=":1.31" (uid=1001 pid=8221 comm="(sd-pam)" label="system_u:system_r:init_t:s0") interface="org.freedesktop.login1.Manager" member="ReleaseSession" error name="(unset)" requested_reply="0" destination="org.freedesktop.login1" (uid=0 pid=741 comm="/usr/lib/systemd/systemd-logind" label="system_u:system_r:systemd_logind_t:s0")
```

**Comment by yuwata** [comment]
Does #32398 help this issue?

**Comment by msekletar** [comment]
@poettering this is just a theory but could it be that we cause the timeout to ourselves. What I mean is that NameOwnerChange signal subscription is done via async method call so we queue or maybe even send the subscription request (depending on bus write queue size) and then because mount storm causes a ton of signals (UnitNew, JobNew, PropertiesChanged) we are essentially busy looping on signal generation and we don't process method_reply from NameOwnerChnaged subscription in time.

**Comment by poettering** [comment]
It seems everything else gets kicked off the bus too, including avahi and so on. Before we start wild guessing, let's have a look at what dbus broker actually does here, i.e. enable logs on that and see why it might decide to let eveywhere hang.

**Comment by mrc0mmand** [comment]
I don't think it kicks of anyone else than us, see the dbus-daemon log above:

```
[ 1583.573093] dbus-daemon[737]: [system] Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)
[ 1588.615026] dbus-daemon[737]: [system] Connection has not authenticated soon enough, closing it (auth_timeout=30000ms, elapsed: 30002ms)
[ 1608.576630] dbus-daemon[737]: [system] Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)
```

All the units that are affected are of type `dbus`, so it looks like systemd is responsible for the killing once we get kicked off the bus?

**Comment by msekletar** [comment]
> It seems everything else gets kicked off the bus too, including avahi and so on. Before we start wild guessing, let's have a look at what dbus broker actually does here, i.e. enable logs on that and see why it might decide to let eveywhere hang.

I actually did exactly that. Recompiled dbus broker with extra log statements and I can confirm that no service is actually kicked from the bus.

Instead what it seems to happen is NameOwnerChange signal subscription failure. Creating subscription involves GetNameOwner change method call and we timeout on that async method call. Because of that we decide to transition bus to closing state and we nuke all Type=dbus services together with the bus.

**Comment by poettering** [comment]
hmm, so you are saying the issue is entirely limited to pid1 and its communication with the bus?

**Comment by poettering** [comment]
hmm, so in "process_running()" in sd-dbus.c we'll keep processing the wqueue preferably, and only process the rqueue if the wqueue is empty.

This indeed means that if we overload the wqueue with messages that it will drown out the rqueue.

the question is if that's a bug, or if the bug is that we create so many outbound messages?

we probably could change process_running() so that on every 2nd call it dispatches the rq first, and the wq 2nd, so that both qeuues keep running.

i.e. something like:

```c
        r = process_timeout(bus);
        if (r != 0)
                goto null_message;

        /* Toggle which queue we process preferably in this iteration, the rq or the wq */  
        bus->queue_toggle = !bus->queue_toggle; 

        if (bus->queue_toggle) { /* wqueue preferably */
                r = dispatch_wqueue(bus);
                if (r != 0)
                        goto null_message;
        }

        r = dispatch_track(bus);
        if (r != 0)
                goto null_message;

        r = dispatch_rqueue(bus, &m);
        if (r < 0)
                return r;
        if (r == 0 && !bus->queue_toggle) {
                /* Nothing happened on the rq, and we didn't check the wq in this iteration, hence do that now. */
                r = dispatch_wqueue(bus);
                goto null_message; 
        } 
        if (!m)
                goto null_message;

        r = process_message(bus, m);
        if (r != 0)
                goto null_message;

        if (ret) {
                … 
        }

        if (m->header->type == SD_BUS_MESSAGE_METHOD_CALL) {
               …
        }

        return 1;
        …
```

**Comment by msekletar** [comment]
> Anyone wants to play around with this, if this helps?

I will give it a shot.

**Comment by msekletar** [comment]
@mrc0mmand so here is patch  https://github.com/msekletar/systemd/commit/9b5670832c4486d98d809dfb03809bbeba7f59a3 It is mostly verbatim copy of proposed patch from @poettering. Feel free to give it a spin.

**Comment by msekletar** [comment]
I am already testing it locally but it would help if you could run it overnight on a bunch of machines.

**Comment by mrc0mmand** [comment]
> @mrc0mmand so here is patch [msekletar@9b56708](https://github.com/msekletar/systemd/commit/9b5670832c4486d98d809dfb03809bbeba7f59a3) It is mostly verbatim copy of proposed patch from @poettering. Feel free to give it a spin.

I gave it a spin and manage to hit the issue again a couple of iterations. But maybe I f-ed something up, so I'll try again tomorrow (as I'm waiting for another test machine anyway).

**Comment by msekletar** [comment]
I am running the reproducer (on Rawhide) for couple hours already and it is still going on while previously it used to crash after 5 minutes or so.

**Comment by mrc0mmand** [comment]
> I am running the reproducer (on Rawhide) for couple hours already and it is still going on while previously it used to crash after 5 minutes or so.

Did you reboot the machine before running the reproducer? As I said in https://github.com/systemd/systemd/issues/32381#issuecomment-2068135138 it seems to happen only once per reboot:

```
# git log -1 --oneline
78fd385e02 (HEAD -> pr) sd-bus: alternate between dispatch order of internal queues
# systemctl --version
systemd 256~devel (256~devel-g78fd385)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP -GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBCRYPTSETUP_PLUGINS +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT -LIBARCHIVE
# ./repro.sh 
...
Failed to stop automount unit: Connection timed out
Failed to stop automount unit: Connection timed out
Failed to stop automount unit: Connection timed out
Failed to stop automount unit: Connection timed out
Failed to stop automount unit: Connection timed out
Failed to stop automount unit: Connection timed out
Failed to stop automount unit: Connection timed out
Failed to stop automount unit: Connection timed out
Apr 25 05:36:52 xxx.redhat.com systemd[1]: NetworkManager.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 25 05:36:52 xxx.redhat.com systemd[1]: avahi-daemon.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 25 05:36:52 xxx.redhat.com systemd[1]: systemd-homed.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 25 05:36:52 xxx.redhat.com systemd[1]: systemd-networkd.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 25 05:36:52 xxx.redhat.com systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 25 05:36:52 xxx.redhat.com systemd[1]: udisks2.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 25 05:36:52 xxx.redhat.com systemd[1]: systemd-hostnamed.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 25 05:36:52 xxx.redhat.com systemd[1]: systemd-resolved.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 25 05:36:52 xxx.redhat.com systemd[1]: systemd-timesyncd.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 25 05:39:04 xxx.redhat.com systemd[1]: NetworkManager.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 25 05:39:04 xxx.redhat.com systemd[1]: avahi-daemon.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 25 05:39:04 xxx.redhat.com systemd[1]: systemd-homed.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 25 05:39:04 xxx.redhat.com systemd[1]: systemd-networkd.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 25 05:39:04 xxx.redhat.com systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 25 05:39:04 xxx.redhat.com systemd[1]: udisks2.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 25 05:39:04 xxx.redhat.com systemd[1]: systemd-hostnamed.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 25 05:39:04 xxx.redhat.com systemd[1]: systemd-resolved.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 25 05:39:04 xxx.redhat.com systemd[1]: systemd-timesyncd.service: Unexpected error response from GetNameOwner(): Connection terminated
```

**Comment by mrc0mmand** [comment]
I added a log message that shows the state of the queues if either of them has any jobs, and it looks like the issue is might not be an overloaded rqueue:

```
# journalctl --no-hostname -o short-monotonic -b -p warning _PID=1
...
[   33.804923] systemd[1]: systemd-oomd.service: Got notification message from PID 704, but reception is disabled
[   33.805050] systemd[1]: systemd-oomd.service: Got notification message from PID 704, but reception is disabled
[  384.848408] systemd[1]: process_running: wqueue size: 0; rqueue size: 2
[  384.848936] systemd[1]: process_running: wqueue size: 0; rqueue size: 1
[  384.901772] systemd[1]: process_running: wqueue size: 0; rqueue size: 1
[  384.905494] systemd[1]: process_running: wqueue size: 0; rqueue size: 1
[  384.909864] systemd[1]: process_running: wqueue size: 0; rqueue size: 1
[  611.876364] systemd[1]: avahi-daemon.service: Unexpected error response from GetNameOwner(): Connection terminated
[  612.015579] systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
[  612.016197] systemd[1]: udisks2.service: Unexpected error response from GetNameOwner(): Connection terminated
[  612.016805] systemd[1]: systemd-resolved.service: Unexpected error response from GetNameOwner(): Connection terminated
[  612.017438] systemd[1]: systemd-timesyncd.service: Unexpected error response from GetNameOwner(): Connection terminated
[  612.019127] systemd[1]: systemd-networkd.service: Unexpected error response from GetNameOwner(): Connection terminated
[  612.019701] systemd[1]: systemd-hostnamed.service: Unexpected error response from GetNameOwner(): Connection terminated
[  612.020286] systemd[1]: NetworkManager.service: Unexpected error response from GetNameOwner(): Connection terminated
[  612.124789] systemd[1]: systemd-homed.service: Unexpected error response from GetNameOwner(): Connection terminated
[  753.242169] systemd[1]: avahi-daemon.service: Unexpected error response from GetNameOwner(): Connection terminated
[  753.243199] systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
[  753.243450] systemd[1]: udisks2.service: Unexpected error response from GetNameOwner(): Connection terminated
[  753.243607] systemd[1]: systemd-resolved.service: Unexpected error response from GetNameOwner(): Connection terminated
[  753.243792] systemd[1]: systemd-timesyncd.service: Unexpected error response from GetNameOwner(): Connection terminated
[  753.243958] systemd[1]: systemd-networkd.service: Unexpected error response from GetNameOwner(): Connection terminated
[  753.244189] systemd[1]: systemd-hostnamed.service: Unexpected error response from GetNameOwner(): Connection terminated
[  753.244409] systemd[1]: NetworkManager.service: Unexpected error response from GetNameOwner(): Connection terminated
[  753.244583] systemd[1]: systemd-homed.service: Unexpected error response from GetNameOwner(): Connection terminated
[  753.252802] systemd[1]: process_running: wqueue size: 22; rqueue size: 0
[  753.256604] systemd[1]: process_running: wqueue size: 0; rqueue size: 5
[  753.256974] systemd[1]: process_running: wqueue size: 0; rqueue size: 4
[  753.257206] systemd[1]: process_running: wqueue size: 0; rqueue size: 3
[  753.257399] systemd[1]: process_running: wqueue size: 0; rqueue size: 2
[  753.257570] systemd[1]: process_running: wqueue size: 0; rqueue size: 1
[  753.261854] systemd[1]: process_running: wqueue size: 0; rqueue size: 2
[  753.262183] systemd[1]: process_running: wqueue size: 0; rqueue size: 1
[  753.310483] systemd[1]: process_running: wqueue size: 0; rqueue size: 1
[  753.317432] systemd[1]: process_running: wqueue size: 0; rqueue size: 1
[  753.321147] systemd[1]: process_running: wqueue size: 0; rqueue size: 1
[  753.390846] systemd[1]: process_running: wqueue size: 0; rqueue size: 1
```

**Comment by msekletar** [comment]
@mrc0mmand at which point you print the queue size? Right after entering process_running?

**Comment by msekletar** [comment]
Hmm, so it seems my initial gut feeling was correct (we flood bus with writes and don't get to reading stuff in time)  but actually the root cause is different than what @poettering hinted at. 

Every `systemd-mount` establishes a private bus connection with systemd. In `manager_dispatch_dbus_queue()` we send out dbus signals (unit changed, job changed) and we also try to do "budget accounting" to limit amount of messages we send out in single loop iteration. However, we don't propagate budget variable to `bus_unit_sent_changed_signal()` and in there we send out unit change events unconditionally for all private buses (there are 100s of them) but decrement budget only by 1 in `manager_dispatch_dbus_queue()`. We essentially have `O(U * B)` time complexity here, where `U` is number of mount units which changed and `B` is number of private buses.

**Comment by msekletar** [comment]
I think that idea of budget and threshold implemented in `manager_dispatch_dbus_queue()` doesn't take into consideration private buses. In every iteration they don't have anything in write queue so every write is actually send out immediately making write queue empty hence next write is also send out immediately.

**Comment by msekletar** [comment]
Hi @mrc0mmand,

I've updated my branch where I am trying to fix the issue, https://github.com/msekletar/systemd/commits/issue-32381/. I'd appreciate if you could test it. Thanks!

**Comment by mrc0mmand** [comment]
> Hi @mrc0mmand,
> 
> I've updated my branch where I am trying to fix the issue, https://github.com/msekletar/systemd/commits/issue-32381/. I'd appreciate if you could test it. Thanks!

Unfortunately, I can still reproduce the issue, although now with more errors:
```
# git log -2 --oneline
acd77dae9d (HEAD -> issue-32381, msekletar/issue-32381) bus: actually decrease the budget for every generated message
9b5670832c sd-bus: alternate between dispatch order of internal queues
# systemctl --version
systemd 256~devel (256~devel-gacd77da)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP -GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBCRYPTSETUP_PLUGINS +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT -LIBARCHIVE
# journalctl -b --no-pager -o short-monotonic --no-hostname --grep "Connection terminated"
[ 1158.688234] systemd[1]: Failed to process message type=error sender=org.freedesktop.DBus destination=n/a path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=1 signature=s error-name=org.freedesktop.DBus.Error.NoReply error-message=Connection terminated: Connection timed out
[ 1158.688277] systemd[1]: Unable to add match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.NetworkManager', failing connection: Connection terminated
[ 1158.688322] systemd[1]: NetworkManager.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 1158.823677] systemd[1]: Unable to add match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.home1', failing connection: Connection terminated
[ 1158.823940] systemd[1]: systemd-homed.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 1159.063048] systemd[1]: Unable to add match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.hostname1', failing connection: Connection terminated
[ 1159.063700] systemd[1]: systemd-hostnamed.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 1159.064230] systemd[1]: Unable to add match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.resolve1', failing connection: Connection terminated
[ 1159.064738] systemd[1]: systemd-resolved.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 1159.066915] systemd[1]: Unable to add match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.network1', failing connection: Connection terminated
[ 1159.067416] systemd[1]: systemd-networkd.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 1159.067916] systemd[1]: Unable to add match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.timesync1', failing connection: Connection terminated
[ 1159.068421] systemd[1]: systemd-timesyncd.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 1159.068920] systemd[1]: Unable to add match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.UDisks2', failing connection: Connection terminated
[ 1159.069420] systemd[1]: udisks2.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 1159.069922] systemd[1]: Unable to add match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.login1', failing connection: Connection terminated
[ 1159.070420] systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 1159.070923] systemd[1]: Unable to add match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.systemd1.Activator',member='ActivationRequest', failing connection: Connection terminated
[ 1159.071434] systemd[1]: Unable to request name, failing connection: Connection terminated
[ 1159.071935] systemd[1]: Unable to add match type='method_call',interface='org.freedesktop.MemoryAllocation1',path='/org/freedesktop/MemoryAllocation1',destination='org.freedesktop.systemd1',member='GetMallocInfo', failing connection: Connection terminated
[ 1395.400492] systemd[1]: NetworkManager.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 1395.400776] systemd[1]: systemd-homed.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 1395.400920] systemd[1]: systemd-hostnamed.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 1395.401060] systemd[1]: systemd-resolved.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 1395.401161] systemd[1]: systemd-networkd.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 1395.401274] systemd[1]: systemd-timesyncd.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 1395.401374] systemd[1]: udisks2.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 1395.401476] systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
```

**Comment by msekletar** [comment]
Hi @mrc0mmand, so here is yet another attempt to fix (avoid) the issue. Feel free to give it a spin.

https://github.com/msekletar/systemd/commit/8d0c8b908e75f8841821f8ede27a60b881010a12

**Comment by poettering** [comment]
@msekletar so we actually have this dbus method Subscribe() that clients are supposed to call before we send out any signals. It currently has an effect only for the "API" bus connection, not on the direct connections.

I guess we could change that, and strictly require this for direct connections too. This wouldn't be an API break, since direct connections are private anyway.

implementation idea: maybe maintain two sets of private busses. The ones that called "Subscribe" and the ones that didn't. make sure that new direct connections are added to the latter, and move them over once they call Subscribe.

That way, we could trivially suppress all those messages on direct connections.

**Comment by mrc0mmand** [comment]
> Hi @mrc0mmand, so here is yet another attempt to fix (avoid) the issue. Feel free to give it a spin.
> 
> [msekletar@8d0c8b9](https://github.com/msekletar/systemd/commit/8d0c8b908e75f8841821f8ede27a60b881010a12)

This _looked_ promising and after running the reproducer for an hour I couldn't reproduce the issue anymore. So I decided to step up the game a bit and use 1600 mounts instead of _just_ 800, and with that the issue seems to be, unfortunately, back:

```
# journalctl --since="-15min" -b -o short-monotonic --no-hostname -p info
...
 4125.682261] systemd[1]: Unmounted tmp-mnt998.mount.
[ 4125.708647] systemd[1]: tmp-mnt999.mount: Deactivated successfully.
[ 4125.708981] systemd[1]: Unmounted tmp-mnt999.mount.
[ 4125.736105] systemd[1]: user-runtime-dir@1001.service: Deactivated successfully.
[ 4125.736427] systemd[1]: Stopped user-runtime-dir@1001.service.
[ 4145.719502] systemd-journald[587]: [🡕] Suppressed 661931 messages from init.scope
[ 4168.229210] systemd[1]: udisks2.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 4168.229268] systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 4168.229317] systemd[1]: systemd-homed.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 4168.229364] systemd[1]: avahi-daemon.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 4168.229431] systemd[1]: systemd-networkd.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 4168.229483] systemd[1]: systemd-timesyncd.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 4168.229535] systemd[1]: NetworkManager.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 4168.229591] systemd[1]: systemd-resolved.service: Unexpected error response from GetNameOwner(): Connection terminated
[ 4168.229638] systemd[1]: systemd-hostnamed.service: Unexpected error response from GetNameOwner(): Connection terminated
```

**Comment by poettering** [comment]
yeah something like that.

**Comment by msekletar** [comment]
@poettering PTAL at #35152

**Comment by mrc0mmand** [comment]
We got some internal pressure regarding this issue again and I was wondering if it's still reproducible with an upstream build (as several commits already attempted to address this) - and it, unfortunately, looks like it is still reproducible (with the reproducer from the issue description), the only change is a slightly reworded error message:

```
# cat /etc/fedora-release 
Fedora release 43 (Rawhide)
# systemctl --version
systemd 258 (258~devel)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +IPE +SMACK +SECCOMP -GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBCRYPTSETUP_PLUGINS +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -BTF +XKBCOMMON +UTMP +SYSVINIT +LIBARCHIVE
# git describe
v257-3367-g0425fc5eb7
```
```
# ./repro.sh
...
Failed to stop automount unit: Connection timed out
Failed to stop automount unit: Connection timed out
Failed to stop automount unit: Connection timed out
Failed to stop automount unit: Connection timed out
Failed to stop automount unit: Connection timed out
++ busctl status --user --machine=testuser@ --no-pager
BusAddress=unixexec:path=systemd-run,argv1=-M.host,argv2=-PGq,argv3=--wait,argv4=-pUser%3dtestuser,argv5=-pPAMName%3dlogin,argv6=systemd-stdio-bridge,argv7=-punix:path%3d%24%7bXDG_RUNTIME_DIR%7d/bus
Failed to start transient service unit: Remote peer disconnected
Failed to get credentials: Transport endpoint is not connected
```
```
# journalctl -o short-monotonic --no-hostname -b
...
[  661.859709] systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitRemoved cookie=369 reply_cookie=0 signature=so error->
[  661.859761] systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitRemoved cookie=300 reply_cookie=0 signature=so error->
[  661.859811] systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitRemoved cookie=327 reply_cookie=0 signature=so error->
[  669.467915] chronyd[825]: Source 45.83.234.123 replaced with 2602:2eb:2:95:1234:5678:9abc:def0 (2.fedora.pool.ntp.org)
[  674.278431] systemd[1]: NetworkManager.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  674.279096] NetworkManager[847]: <info>  [1747057679.8676] caught SIGTERM, shutting down normally.
[  674.280721] NetworkManager[847]: <info>  [1747057679.8696] dhcp4 (eth0): canceled DHCP transaction
[  674.280741] NetworkManager[847]: <info>  [1747057679.8696] dhcp4 (eth0): activation: beginning transaction (timeout in 45 seconds)
[  674.280753] NetworkManager[847]: <info>  [1747057679.8696] dhcp4 (eth0): state changed no lease
[  674.280952] NetworkManager[847]: <info>  [1747057679.8698] manager: NetworkManager state is now CONNECTED_SITE
[  674.284212] NetworkManager[847]: <info>  [1747057679.8730] exiting (success)
[  674.331247] systemd[1]: NetworkManager.service: Deactivated successfully.
[  674.330096] audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=NetworkManager comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  674.386872] systemd[1]: systemd-logind.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  674.387482] systemd[1]: polkit.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  674.387812] systemd[1]: systemd-timesyncd.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  674.388099] systemd[1]: systemd-hostnamed.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  674.389886] systemd[1]: udisks2.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  674.390324] systemd[1]: systemd-importd.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  674.390643] systemd[1]: systemd-resolved.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  674.390900] systemd[1]: systemd-networkd.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  674.391168] systemd[1]: systemd-machined.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  674.391418] systemd[1]: avahi-daemon.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  674.391756] avahi-daemon[808]: Got SIGTERM, quitting.
...
[  674.394103] avahi-daemon[808]: avahi-daemon 0.8 exiting.
[  674.449646] systemd[1]: avahi-daemon.service: Deactivated successfully.
[  674.448096] audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=avahi-daemon comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  674.590366] systemd[1]: Got disconnect on API bus.
...
[  821.866752] systemd[1]: Unmounted tmp-mnt97.mount.
[  822.004771] systemd[1]: tmp-mnt98.mount: Deactivated successfully.
[  822.005232] systemd[1]: Unmounted tmp-mnt98.mount.
[  822.145568] systemd[1]: tmp-mnt99.mount: Deactivated successfully.
[  822.145986] systemd[1]: Unmounted tmp-mnt99.mount.
[  822.267916] systemd[1]: user-runtime-dir@1001.service: Deactivated successfully.
[  822.268266] systemd[1]: Stopped user-runtime-dir@1001.service.
[  822.292096] audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=user-runtime-dir@1001 comm="systemd" exe="/usr/l>
[  828.091187] systemd[1]: NetworkManager.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  828.091253] systemd[1]: systemd-logind.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  828.091298] systemd[1]: polkit.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  828.091343] systemd[1]: systemd-timesyncd.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  828.091391] systemd[1]: systemd-hostnamed.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  828.091435] systemd[1]: udisks2.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  828.091471] systemd[1]: systemd-importd.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  828.091503] systemd[1]: systemd-resolved.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  828.091537] systemd[1]: systemd-networkd.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  828.091590] systemd[1]: systemd-machined.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  828.091622] systemd[1]: avahi-daemon.service: Unexpected error response on installing NameOwnerChanged signal match: Connection terminated
[  828.091838] systemd[1]: Got disconnect on API bus.
[  828.096643] systemd[1]: Removed slice user-1001.slice.
[  880.816197] systemd-journald[654]: [🡕] Suppressed 210472 messages from init.scope
```

/cc @msekletar

**Comment by msekletar** [comment]
@mrc0mmand thank you for retesting, unfortunately my suspicion is now confirmed, i.e. looking for fix upstream is pointless and we need to figure out what to do.

**Comment by poettering** [comment]
i.e. did anyone ever try to get some useful info out of dbus-broker? i.e. what does it say about pid1's connection when this happens?

**Comment by msekletar** [comment]
@poettering My understanding of the problem right now is that `rqueue` and `wqueue` are per bus and we don't have any particular queue overloaded but we have so many concurrent private buses on which we are sending unneeded signals that while doing all that busy work we hit timeout on system bus.

**Comment by msekletar** [comment]
> i.e. did anyone ever try to get some useful info out of dbus-broker? i.e. what does it say about pid1's connection when this happens?

We did and here is a gist of the discussion,
https://github.com/bus1/dbus-broker/issues/361#issuecomment-2098153620

But FWIW, I still think we need better traceability of disconnects from system bus, due to any reason not just timeouts so I've filled,
https://github.com/bus1/dbus-broker/issues/396

**Comment by poettering** [comment]
> [@poettering](https://github.com/poettering) My understanding of the problem right now is that `rqueue` and `wqueue` are per bus and we don't have any particular queue overloaded but we have so many concurrent private buses on which we are sending unneeded signals that while doing all that busy work we hit timeout on system bus.

how come there are so many private busses? that seems weird? it's root-only stuff? who's on the other side of those private busses?

**Comment by poettering** [comment]
> We did and here is a gist of the discussion,
> [bus1/dbus-broker#361 (comment)](https://github.com/bus1/dbus-broker/issues/361#issuecomment-2098153620)

uh, but the error is "Connection terminated", not some form of timeout. It apperas really weird to me that if our own code is triggering this that we'd generate that kind of error. Did you verify that it indeed is a disconnect issued by pid1?

**Comment by msekletar** [comment]
I think this is because when we disconnect but there are some async method calls they will be cancelled and error will be connection terminated. So we get one timeout and due to that bunch of connection terminated messages.

**Comment by msekletar** [comment]
> how come there are so many private busses? that seems weird? it's root-only stuff? who's on the other side of those private busses?

Here, in the reproducer, we do a ton of systemd-mounts in parallel but I am not sure what is triggering this in production environments.

**Comment by poettering** [comment]
(btw, one cheap trick might be to just set the GetNameOwner method call timeout to infinity, if that's the fundamental issue. we do that call async anywy, and will cancel it when we don't need it anymore anyway)

**Comment by msekletar** [comment]
I mean I am all for cheap tricks at this point...Anyway, I will try to patch systemd and rerun the reproducer and see how it goes.

**Comment by poettering** [comment]
> I mean I am all for cheap tricks at this point...Anyway, I will try to patch systemd and rerun the reproducer and see how it goes.

Well, i wrote "might be", because as I see it noone conclusively tracked down what's going on here. There are claims that PID1 disconnects the connections, but afaiu that's just a guess...

I'd really suggest to first check what is actually happening when this is reproduced, i.e. what is happening inside PID1, and how it happens that the connection ends up being terminated.

**Comment by rpigott** [comment]
> (btw, one cheap trick might be to just set the GetNameOwner method call timeout to infinity, if that's the fundamental issue. we do that call async anywy, and will cancel it when we don't need it anymore anyway)

This was one of the things I tried originally in https://github.com/systemd/systemd/pull/35450/commits. However I am also not convinced of the prevailing explanation of cause. I made some clumsy attempts with bpftrace to observe the latency of systemd in servicing messages sent by dbus, and the length of the rqueue, and I wasn't able to observe them grow to values that could cause a timeout.

That doesn't mean it doesn't happen, but idk I wish there was a clearer explanation of the problem.

**Comment by msekletar** [comment]
I've triggered crash once the error condition is reached and here is backtrace,

```
#0  __internal_syscall_cancel (a1=<optimized out>, a2=<optimized out>, a3=<optimized out>, a4=<optimized out>, a5=a5@entry=0, a6=a6@entry=0, nr=247) at cancellation.c:44
#1  0x00007fd55247d4e4 in __syscall_cancel (a1=<optimized out>, a2=<optimized out>, a3=<optimized out>, a4=<optimized out>, a5=a5@entry=0, a6=a6@entry=0, nr=247) at cancellation.c:75
#2  0x00007fd5524ec9e3 in __waitid (idtype=<optimized out>, id=<optimized out>, infop=<optimized out>, options=<optimized out>) at ../sysdeps/unix/sysv/linux/waitid.c:29
#3  0x00007fd5520a629a in freeze () at ../systemd/src/basic/process-util.c:2038
#4  0x0000000000418f95 in freeze_or_exit_or_reboot () at ../systemd/src/core/crash-handler.c:52
#5  0x0000000000419ac0 in crash (sig=6, siginfo=0x7ffcb91997b0, context=0x7ffcb9199680) at ../systemd/src/core/crash-handler.c:177
#6  <signal handler called>
#7  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#8  0x00007fd552482cf3 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:89
#9  0x00007fd552428abe in __GI_raise (sig=6) at ../sysdeps/posix/raise.c:26
#10 0x00007fd5527b4781 in signal_name_owner_changed_install_handler (message=0x3e857610, userdata=0x3e6e0790, error=0x7ffcb919ad20) at ../systemd/src/core/unit.c:3504
#11 0x00007fd55219351d in add_match_callback (m=0x3e857610, userdata=0x4943de90, ret_error=0x7ffcb919ad20) at ../systemd/src/libsystemd/sd-bus/sd-bus.c:3542
#12 0x00007fd55219230c in process_closing_reply_callback (bus=0x3e85a510, c=0x4a9c6a68) at ../systemd/src/libsystemd/sd-bus/sd-bus.c:3186
#13 0x00007fd55219247d in process_closing (bus=0x3e85a510, ret=0x0) at ../systemd/src/libsystemd/sd-bus/sd-bus.c:3212
#14 0x00007fd552192910 in bus_process_internal (bus=0x3e85a510, ret=0x0) at ../systemd/src/libsystemd/sd-bus/sd-bus.c:3317
#15 0x00007fd5521929c1 in sd_bus_process (bus=0x3e85a510, ret=0x0) at ../systemd/src/libsystemd/sd-bus/sd-bus.c:3336
#16 0x00007fd552193bc2 in time_callback (s=0x494b3700, usec=0, userdata=0x3e85a510) at ../systemd/src/libsystemd/sd-bus/sd-bus.c:3690
#17 0x00007fd5521417f2 in source_dispatch (s=0x494b3700) at ../systemd/src/libsystemd/sd-event/sd-event.c:4189
#18 0x00007fd552143a14 in sd_event_dispatch (e=0x3e63a260) at ../systemd/src/libsystemd/sd-event/sd-event.c:4800
#19 0x00007fd552143f31 in sd_event_run (e=0x3e63a260, timeout=18446744073709551615) at ../systemd/src/libsystemd/sd-event/sd-event.c:4861
#20 0x00007fd5526fa484 in manager_loop (m=0x3e6394c0) at ../systemd/src/core/manager.c:3251
#21 0x0000000000413e2c in invoke_main_loop (m=0x3e6394c0, saved_rlimit_nofile=0x7ffcb919b250, saved_rlimit_memlock=0x7ffcb919b260, ret_retval=0x7ffcb919b184, ret_fds=0x7ffcb919b1e0,
    ret_switch_root_dir=0x7ffcb919b1b8, ret_switch_root_init=0x7ffcb919b1c0, ret_error_message=0x7ffcb919b1c8) at ../systemd/src/core/main.c:2171
#22 0x0000000000418686 in main (argc=4, argv=0x7ffcb919b428) at ../systemd/src/core/main.c:3391
```

So it is indeed timeout, but in `process_closing_reply_callback()` we actually create synthetic error message `SD_BUS_ERROR_NO_REPLY`, hence the message `"Connection terminated"` that @poettering was wondering about.

**Comment by rpigott** [comment]
This still doesn't tell why the bus-api-socket connection has closed, right? The stack trace is in an asynchronous callback and shows the normal event loop. When the bus connection closes, systemd generates the connection terminated error response for all outstanding method calls, as they would otherwise hang. Maybe I just haven't sufficient inference, but this doesn't explain to me why the connection was closed. I think we knew that much already.

In fact, since the traceback includes time_callback, it seems like we can conclude that the connection was _already_ in the closing state at the time the timeout in this stack trace was triggered. Wouldn't that suggest a cause other than the timeout itself?

I think the traceback would need to be captured at the invocation of bus_enter_closing(bus), when bus refers to the api bus.

**Comment by rpigott** [comment]
That's good info.

To be clear I'm not disputing that the dbus signal work is a problem, and I agree that [processing the timeout later per-loop is a good change](https://github.com/systemd/systemd/pull/35152#issuecomment-2531042044). I think you have strong evidence that this problem is related or a direct cause of the disconnection.

But I still don't understand why it causes the disconnect, if it isn't a direct result of the timeout. Or if it is a direct result of the timeout, I don't understand the code, as I believe this hypothesis should have been address by 37ce3fd2b7dd. Since disconnection here is an "[unthinkable](https://github.com/systemd/systemd/pull/35406#issuecomment-2536459012)" error, it would be great to know exactly what steps in systemd/dbus cause the disconnect so we can ensure it is avoided in all cases.

**Comment by poettering** [comment]
> We spend a lot of time generating useless signals and sending them to private buses from multiple places, e.g. mount unit state transitions, mount sigchld handling, mount units start and stop job handling. Most of that work is absolutely pointless and completely side-steps our budget and threshold logic in `mount_dispatch_dbus_queue()` because those signals are generated and sent immediately and hence `wqueue_size` of any particular private bus is 0 after signal is sent.

I asked this before: but how come this system even has so many private busses open? I understand this is in your artificial testcase so, but why would this happen in the original issue?

**Comment by poettering** [comment]
All but one way why we decide to shut down the connection (i.e. enter CLOSING state) go through bus_enter_closing(). Would be good to go through all call sites and add a log message for each, and see which one it is that triggers entering of CLOSING state right before this happens

**Comment by poettering** [comment]
Ah, this is very good. Yeah, it seems the bus (or the connection to it) is stalled enough to not process our match installation requests and after 25s we hence think it's broken. Which I guess is somewhat sensible behaviour.

So we understand now where the disconnect comes from. We also verified that in this case the rqueue/wqueue are not actually particularly crowded (i.e. that's what https://github.com/systemd/systemd/issues/32381#issuecomment-2078039344 suggested).

The whole add match logic only is applied if we talk to the bus (not to direct connections). And thus I am very much puzzled: how come the broker doesn't respond quickly to our match requests?

**Comment by poettering** [comment]
(i guess i'd be fine with prolonging the default timeout for AddMatch() btw. It's after all not a "Primary" operation clients call, but a secondary one, and for things like the name tracker it doesn't really matter if we get immediate replies, as long as we catch up eventually)

**Comment by rpigott** [comment]
It sure seems like it has replied though, if simply deferring the processing of the timeout is helpful that indicates to me that the intended reply is already present on the rqueue.

AFAICT, that would mean the entire event loop is stalled for 25+ seconds, such that we never process messages on the bus connection.
