### ISSUE TITLE
systemd-run has inconsistent behaviour on memory accounting

### ISSUE THREAD

**Issue by HeRaNO** [systemd/systemd#33191]
### systemd version the issue has been seen with

systemd v255 (255.4-1ubuntu8.2)

### Used distribution

Ubuntu 24.04

### Linux kernel version used

6.8.0-31-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-run

### Expected behaviour you didn't see

Every time `systemd-run --wait` is executed, memory accounting should be present.

### Unexpected behaviour you saw

```plain
$ python3 check.py 1000
1000 iterations
runtime failed: 0
cpu time failed: 0
memory peak failed: 205
memory swap peak failed: 205
```

In some passes of running, memory accounting isn't present.

### Steps to reproduce the problem

Make a simple program, and run it by `systemd-run`.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
// a.c: compiled with gcc -o a a.c
int main() {}
```

```python
# check.py: count memory accounting value missing
from subprocess import (PIPE, STDOUT, run)
from sys import argv
cmd = ['systemd-run', '--user', '--unit', 'test', '--wait', './a']

N = int(argv[1])
run_time_failed = 0
cpu_time_failed = 0
mem_peak_failed = 0
swp_peak_failed = 0

for _ in range(N):
	out = run(cmd, encoding='utf-8', stdout=PIPE, stderr=STDOUT, check=True).stdout
	if 'Service runtime' not in out:
		run_time_failed += 1
	if 'CPU time consumed' not in out:
		cpu_time_failed += 1
	if 'Memory peak' not in out:
		mem_peak_failed += 1
	if 'Memory swap peak' not in out:
		swp_peak_failed += 1

print(f'{N} iterations')
print(f'runtime failed: {run_time_failed}')
print(f'cpu time failed: {cpu_time_failed}')
print(f'memory peak failed: {mem_peak_failed}')
print(f'memory swap peak failed: {swp_peak_failed}')
```

UPD: Maybe it's a similar issue as #33149

**Comment by HeRaNO** [comment]
When I'm digging in the service file, I found that:

```
/run/user/1000/systemd/transient$ cat test.service 
# This is a transient unit file, created programmatically via the systemd API. Do not edit.
[Unit]
Description=/home/yhr/ptime/./a

[Service]
RemainAfterExit=yes
ExecStart=
ExecStart=@/home/yhr/ptime/a "/home/yhr/ptime/./a"
```

the `ExecStart` appears twice. Is it an expected behavior?

**Comment by yuwata** [comment]
> the `ExecStart` appears twice. Is it an expected behavior?

Yes.

**Comment by YHNdnzj** [comment]
This should already be fixed by https://github.com/systemd/systemd/pull/30399, i.e. v256. But in v256 the whole accounting data cache is broken due to https://github.com/systemd/systemd/issues/33149...

**Comment by HeRaNO** [comment]
> This should already be fixed by #30399, i.e. v256. But in v256 the whole accounting data cache is broken due to #33149...

OK so let's wait for #33149

**Comment by HeRaNO** [comment]
Now I updated to `systemd v255 (255.4-1ubuntu8.2)`. I found that memory accounting value was still missing in ~20% possibility (205/1000). The patch should be backport to systemd but the same issue still appears.

**Comment by yuwata** [comment]
@YHNdnzj Is it possible to fix the issue for v255 by backporting some commits in #30399 and #33258 ? Or, already necessary commits are backported?

@HeRaNO You uses slightly old stable release. We already released v255.11 today.

**Comment by YHNdnzj** [comment]
> @YHNdnzj Is it possible to fix the issue for v255 by backporting some commits in #30399 and #33258 ? Or, already necessary commits are backported?

I think https://github.com/systemd/systemd/commit/ad009380e1cbee8cf6e965f1a9b5671bd74ac146 should help. Not sure if it's already backported to v255 though.

**Comment by yuwata** [comment]
> > @YHNdnzj Is it possible to fix the issue for v255 by backporting some commits in #30399 and #33258 ? Or, already necessary commits are backported?
> 
> I think [ad00938](https://github.com/systemd/systemd/commit/ad009380e1cbee8cf6e965f1a9b5671bd74ac146) should help. Not sure if it's already backported to v255 though.

Thanks. The commit is not backported to v255 yet.
