### ISSUE TITLE
Regression in terminal underline handling

### ISSUE THREAD

**Issue by Toolybird** [systemd/systemd#33449]
### systemd version the issue has been seen with

256.1

### Used distribution

Arch

### Linux kernel version used

6.9.5-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

Usual output of `$ systemctl` with underlined lines of text not blinking.

### Unexpected behaviour you saw

Undesirable output of `$ systemctl` with underlined lines of text blinking away (only happens on specific terminals - see below).

### Steps to reproduce the problem

The problem only occurs on a few different terminals. So far I have reproduced the problem on `rxvt-unicode`, `xterm` and `foot`. The first 2 in particular have been around for quite a long time.. which makes me think this is a `systemd` issue (although, of course those terminals might just be buggy?).

To reproduce:

- install / run one of the aforementioned terminal applications
- inside that terminal, run `systemctl`

Bisection (unsurprisingly) points to:
```
$ git bisect bad
891abc9cf1d3d7afd7b740b4077551dcfb5f8e16 is the first bad commit
commit 891abc9cf1d3d7afd7b740b4077551dcfb5f8e16 (HEAD)
Author: Lennart Poettering <lennart@poettering.net>
Date:   Mon Nov 20 12:06:44 2023 +0100

    systemctl: port to the new underline cell attribute
    
    And be more careful when adding color to log lines:
    
    1. Apply color derived from load state only to load state (and in
       special cases to the circle at the beginning of the line)
    
    2. Apply color derived from active/sub states only to active/sub states
       (and in special cases to the circle at the beginning of the line)
    
    3. Special case the "exited" state of services, i.e. make the substate
       grey, as in this case the service is active, yet consumes no
       resources.
    
    4. Cover the "inactive" state properly, by greying it our too
    
    5. Downgrade the load state of "not-found" from red to yellow, since
       it's not really a case one needs to be come active on.

 src/systemctl/systemctl-list-units.c | 69 +++++++++++++++++++++++++++++++++++++++++++++------------------------
 1 file changed, 45 insertions(+), 24 deletions(-)
```
Thanks for your help.

**Comment by zeha** [comment]
Please reference Debian bug #1074073 when fixing this, so it gets also applied there.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1074073

**Comment by yuwata** [comment]
Hopefully fixed by #33456.

**Comment by dnkl** [comment]
#33456 will not fix the issue correctly.

The issue is that systemd uses broken 38/48/58 SGR sequences, consisting of multiple SGR parameters, instead of sub-parameters.

For example, see https://github.com/systemd/systemd/blob/59a7019fee57b36a3deb470af09c0573de6f4a47/src/basic/terminal-util.h#L64

All VT conformant terminal emulators will ignore unrecognized/unimplemented SGR parameters, and **continue** parsing the next one. In other words; terminals that don't implement colored underlines will ignore `58`, and then apply `5` (see actual sequence in the link above). `5` means **blink**.

The correct way to emit 38/48/58 SGRs is to use sub-parameters: `CSI 58:5:<n>`. I.e. use colons instead of semicolons. This applies not only to SGR 58, but to SGR 38 and SGR 48 as well. That way, terminals see a single SGR parameter, and all of it is skipped when it isn't recognized by the terminal.

**Comment by Toolybird** [comment]
> Hopefully fixed by https://github.com/systemd/systemd/pull/33456.

Thanks for your work! Seems fixed for `rxvt-unicode` and `xterm` (Xorg).

But unfortunately not fixed for `foot` (Wayland) :(

**Comment by dnkl** [comment]
> But unfortunately not fixed for foot (Wayland) :(

Expected, since it's 24-bit capable, but does not (yet) implement colored underlines.

**Comment by yuwata** [comment]
@dnkl Thank you for the suggestion. The PR is updated, and now colon is used.
