### ISSUE TITLE
hangtask in reboot when dm device has been suspended

### ISSUE THREAD

**Issue by foolstrong** [systemd/systemd#35061]
### systemd version the issue has been seen with

255

### Used distribution

Fedora 39

### Linux kernel version used

kernel-6.6.0-136.x86_64

### CPU architectures issue was seen on

None

### Component

systemd

### Expected behaviour you didn't see

reboot success

### Unexpected behaviour you saw

systemd-shutdow hangtask

### Steps to reproduce the problem

1. create dm-snapshot
```
pvcreate /dev/sdb
vgcreate vg /dev/sdb
lvcreate -L 1G -n lv vg
lvcreate -L 1G -s -n lv_snap vg/lv
```
2. run test.sh as follow
```
remove() {
	while true
	do
		dmsetup remove vg-lv_snap
	done
}

fresh() {
	while true
	do
		vgchange --refresh vg
	done
}

remove &
fresh &
```
3. reboot

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

vgchange suspend snapshot/real/cow/origin device, and then systemd-shutdown send ioctl to remove snapshot,
destroy dm-snapshot until md->holders dec to 0, but vgchange run table_load will inc md->holders and
issue io to cow, unfortunately cow has been suspended lead to hangtask during shutdown.
```

```
crash> bt 1
PID: 1        TASK: ffff951f80214180  CPU: 0    COMMAND: "systemd-shutdow"
 #0 [ffffb3eec0013bd0] __schedule at ffffffffa330eb8b
 #1 [ffffb3eec0013c60] schedule at ffffffffa330f13a
 #2 [ffffb3eec0013c78] schedule_timeout at ffffffffa33125ca
 #3 [ffffb3eec0013d18] msleep at ffffffffa298eb9a
 #4 [ffffb3eec0013d28] __dm_destroy at ffffffffc03feaa2 [dm_mod]
 #5 [ffffb3eec0013d50] dev_remove at ffffffffc0405b80 [dm_mod]
 #6 [ffffb3eec0013d78] ctl_ioctl at ffffffffc04056b9 [dm_mod]
 #7 [ffffb3eec0013f08] dm_ctl_ioctl at ffffffffc04057ba [dm_mod]
 #8 [ffffb3eec0013f10] __se_sys_ioctl at ffffffffa2bc6ce5
 #9 [ffffb3eec0013f40] do_syscall_64 at ffffffffa33018d3
#10 [ffffb3eec0013f50] entry_SYSCALL_64_after_hwframe at ffffffffa340011f
    RIP: 00007fdced171c0b  RSP: 00007ffea55865e8  RFLAGS: 00000246
    RAX: ffffffffffffffda  RBX: 00000000ffffffff  RCX: 00007fdced171c0b
    RDX: 00007ffea55867a0  RSI: 00000000c138fd04  RDI: 0000000000000004
    RBP: 0000000000000002   R8: 0000000000000000   R9: 00007ffea55859d0
    R10: 0000000000000000  R11: 0000000000000246  R12: 0000556f0ea4dc50
    R13: 0000556f0ea4dbf0  R14: 0000000000000004  R15: 0000000000000000
    ORIG_RAX: 0000000000000010  CS: 0033  SS: 002b

crash> bt 18350
PID: 18350    TASK: ffff951ee9a20000  CPU: 3    COMMAND: "vgchange"
 #0 [ffffb3eec192b8f8] __schedule at ffffffffa330eb8b
 #1 [ffffb3eec192b988] schedule at ffffffffa330f13a
 #2 [ffffb3eec192b9a0] schedule_timeout at ffffffffa331266d
 #3 [ffffb3eec192ba40] wait_for_common at ffffffffa330fd2d
 #4 [ffffb3eec192baa0] flush_workqueue at ffffffffa29028bd
 #5 [ffffb3eec192bb20] chunk_io at ffffffffc08496f6 [dm_snapshot]
 #6 [ffffb3eec192bc00] read_header at ffffffffc0849e9e [dm_snapshot]
 #7 [ffffb3eec192bc40] persistent_read_metadata at ffffffffc084a047 [dm_snapshot]
 #8 [ffffb3eec192bc78] snapshot_ctr at ffffffffc08470a1 [dm_snapshot]
 #9 [ffffb3eec192bcd8] dm_table_add_target at ffffffffc04012d7 [dm_mod]
#10 [ffffb3eec192bd28] table_load at ffffffffc040681b [dm_mod]
#11 [ffffb3eec192bd78] ctl_ioctl at ffffffffc04056b9 [dm_mod]
#12 [ffffb3eec192bf08] dm_ctl_ioctl at ffffffffc04057ba [dm_mod]
#13 [ffffb3eec192bf10] __se_sys_ioctl at ffffffffa2bc6ce5
#14 [ffffb3eec192bf40] do_syscall_64 at ffffffffa33018d3
#15 [ffffb3eec192bf50] entry_SYSCALL_64_after_hwframe at ffffffffa340011f
    RIP: 00007fe15a6bcc0b  RSP: 00007ffe95d18128  RFLAGS: 00000206
    RAX: ffffffffffffffda  RBX: 0000560b679eb9e0  RCX: 00007fe15a6bcc0b
    RDX: 0000560b68ef1750  RSI: 00000000c138fd09  RDI: 0000000000000004
    RBP: 0000560b67aa214e   R8: 0000560b67b1c810   R9: 00007ffe95d17f80
    R10: 0000000000000004  R11: 0000000000000206  R12: 0000560b68fd9ee0
    R13: 0000560b68ef1780  R14: 0000000000000000  R15: 0000560b68ef1750
    ORIG_RAX: 0000000000000010  CS: 0033  SS: 002b

crash> bt 238
PID: 238      TASK: ffff951e8112a0c0  CPU: 3    COMMAND: "kworker/3:3"
 #0 [ffffb3eec0287bd8] __schedule at ffffffffa330eb8b
 #1 [ffffb3eec0287c68] schedule at ffffffffa330f13a
 #2 [ffffb3eec0287c80] schedule_timeout at ffffffffa331266d
 #3 [ffffb3eec0287d20] io_schedule_timeout at ffffffffa330e89c
 #4 [ffffb3eec0287d38] wait_for_common_io.constprop.0 at ffffffffa330ff35
 #5 [ffffb3eec0287d80] sync_io at ffffffffc04073be [dm_mod]
 #6 [ffffb3eec0287df8] dm_io at ffffffffc040764f [dm_mod]
 #7 [ffffb3eec0287e88] do_metadata at ffffffffc08495ed [dm_snapshot]
 #8 [ffffb3eec0287e98] process_one_work at ffffffffa2905135
 #9 [ffffb3eec0287ed8] worker_thread at ffffffffa2905699
#10 [ffffb3eec0287f10] kthread at ffffffffa290acce
#11 [ffffb3eec0287f50] ret_from_fork at ffffffffa2802302
```

**Comment by foolstrong** [comment]
#34283
this issue discuss dm device without table，we have some way to solve device which has been suspended?

**Comment by poettering** [comment]
b4b66b26620bfaf5818c95d5cffafd85207694e7 should address this case too I guess. At some point this is really a DM issue though.

Anyway, closing, assuming this is addressed from our side, and you used a much too old version.

**Comment by yuwata** [comment]
I set the 'backport' tag to #34330.

**Comment by foolstrong** [comment]
it's sure, this patch alredy commit to master, but it fix dm device without table, hangtask still exist when dm device has been suspended. @yuwata @poettering

**Comment by yuwata** [comment]
Not sure, but reopening, at least tentatively.
