### ISSUE TITLE
systemd-resolved fails to respond to mdns

### ISSUE THREAD

**Issue by rpigott** [systemd/systemd#36315]
systemd-resolved doesn't appear to respond to mdnsv4 queries anymore?

```
$ pacman -Q systemd linux-lts
systemd 257.2-2
linux-lts 6.12.12-1
$ uname -r
6.12.12-1-lts
```

sd-resolved has mdns enabled:
```
$ resolvectl status enp7s0
Link 2 (enp7s0)
    Current Scopes: DNS mDNS/IPv4 mDNS/IPv6
         Protocols: +DefaultRoute -LLMNR +mDNS -DNSOverTLS DNSSEC=yes/supported
Current DNS Server: 10.3.0.254
       DNS Servers: 10.3.0.254
        DNS Domain: abra.home
     Default Route: yes
```

sd-resolved is the only listener on mdns port:
```
$ sudo ss -lup sport eq mdns
State    Recv-Q   Send-Q     Local Address:Port     Peer Address:Port   Process                                       
UNCONN   0        0                0.0.0.0:mdns          0.0.0.0:*       users:(("systemd-resolve",pid=6729,fd=11))   
UNCONN   0        0                   [::]:mdns             [::]:*       users:(("systemd-resolve",pid=6729,fd=13))   
```

host is a member of the mdns ipv4 multicast group at first, but I find that this membership drops after a few minutes (?):
```
$ ip -4 maddr show dev enp7s0
2:	enp7s0
	inet  224.0.0.251
	inet  224.0.0.1
```
... and the output later when membership is dropped but we're still listening:
```
$ ip -4 maddr show dev enp7s0
2:	enp7s0
	inet  224.0.0.1
$ sudo ss -lup sport eq mdns
State    Recv-Q   Send-Q     Local Address:Port     Peer Address:Port   Process                                       
UNCONN   0        0                0.0.0.0:mdns          0.0.0.0:*       users:(("systemd-resolve",pid=8955,fd=11))   
UNCONN   0        0                   [::]:mdns             [::]:*       users:(("systemd-resolve",pid=8955,fd=13))   
```
I don't see any mdns response either way. It rejoins whenever I restart sd-resolved, and sometimes I see "Stale file handle" in the journal:
```
Feb 07 12:38:08 rdtw systemd-resolved[5460]: Using system hostname 'rdtw'.
Feb 07 12:38:08 rdtw systemd[1]: Started Network Name Resolution.
Feb 07 12:42:31 rdtw systemd[1]: Stopping Network Name Resolution...
Feb 07 12:42:31 rdtw systemd-resolved[5460]: mDNS-IPv4: Failed to create event source: Stale file handle
Feb 07 12:42:31 rdtw systemd-resolved[5460]: mDNS-IPv6: Failed to create event source: Stale file handle
Feb 07 12:42:31 rdtw systemd[1]: systemd-resolved.service: Deactivated successfully.
``` 

If I attempt `ping rdtw.local` from my laptop (also running sd-resolved) shortly after starting sd-resolved while we still belong to the mdnsv4 mcast group, I can see the queries in the debug log:
```
Feb 07 13:05:53 rdtw systemd-resolved[8955]: Received mdns UDP packet of size 28, ifindex=2, ttl=255, fragsize=0, sender=10.3.0.120, destination=224.0.0.251
Feb 07 13:05:53 rdtw systemd-resolved[8955]: Got mDNS query packet for id 0
Feb 07 13:05:53 rdtw systemd-resolved[8955]: Sending response packet with id 0 on interface 2/AF_INET of size 38.
Feb 07 13:05:53 rdtw systemd-resolved[8955]: Received mdns UDP packet of size 38, ifindex=2, ttl=255, fragsize=0, sender=10.3.0.5, destination=224.0.0.251
```
No response is seen by tcpdump or the remote host:
```
$ tshark -nl -i enp7s0 ip and port mdns
Capturing on 'enp7s0'
    1 0.000000000     10.3.0.5 → 224.0.0.251  MDNS 70 Standard query 0x0000 A rxps.local, "QM" question
    2 1.071981650     10.3.0.5 → 224.0.0.251  MDNS 70 Standard query 0x0000 A rxps.local, "QM" question
    3 3.321981906     10.3.0.5 → 224.0.0.251  MDNS 70 Standard query 0x0000 A rxps.local, "QM" question
3 packets captured
```
But it seems like sd-resolved at least tries to send a response, at least for the duration it is able to recieve the queries:
```
$ sudo strace -s128 -e fd=11 -p `pgrep systemd-resolve`
strace: Process 20043 attached
recvfrom(11, NULL, 0, MSG_PEEK|MSG_TRUNC, NULL, NULL) = 28
recvmsg(11, {msg_name={sa_family=AF_INET, sin_port=htons(5353), sin_addr=inet_addr("10.3.0.120")}, msg_namelen=128 => 16, msg_iov=[{iov_base="\0\0\0\0\0\1\0\0\0\0\0\0\4rdtw\5local\0\0\1\0\1", iov_len=3920}], msg_iovlen=1, msg_control=[{cmsg_len=28, cmsg_level=SOL_IP, cmsg_type=IP_PKTINFO, cmsg_data={ipi_ifindex=if_nametoindex("enp7s0"), ipi_spec_dst=inet_addr("10.3.0.5"), ipi_addr=inet_addr("224.0.0.251")}}, {cmsg_len=20, cmsg_level=SOL_IP, cmsg_type=IP_TTL, cmsg_data=[255]}], msg_controllen=56, msg_flags=0}, 0) = 28
sendmsg(11, {msg_name={sa_family=AF_INET, sin_port=htons(5353), sin_addr=inet_addr("224.0.0.251")}, msg_namelen=16, msg_iov=[{iov_base="\0\0\204\0\0\0\0\1\0\0\0\0\4rdtw\5local\0\0\1\200\1\0\0\0x\0\4\n\3\0\5", iov_len=38}], msg_iovlen=1, msg_control=[{cmsg_len=28, cmsg_level=SOL_IP, cmsg_type=IP_PKTINFO, cmsg_data={ipi_ifindex=if_nametoindex("enp7s0"), ipi_spec_dst=inet_addr("0.0.0.0"), ipi_addr=inet_addr("0.0.0.0")}}], msg_controllen=32, msg_flags=0}, 0) = 38
recvfrom(11, NULL, 0, MSG_PEEK|MSG_TRUNC, NULL, NULL) = 38
recvmsg(11, {msg_name={sa_family=AF_INET, sin_port=htons(5353), sin_addr=inet_addr("10.3.0.5")}, msg_namelen=128 => 16, msg_iov=[{iov_base="\0\0\204\0\0\0\0\1\0\0\0\0\4rdtw\5local\0\0\1\200\1\0\0\0x\0\4\n\3\0\5", iov_len=3920}], msg_iovlen=1, msg_control=[{cmsg_len=28, cmsg_level=SOL_IP, cmsg_type=IP_PKTINFO, cmsg_data={ipi_ifindex=if_nametoindex("enp7s0"), ipi_spec_dst=inet_addr("10.3.0.5"), ipi_addr=inet_addr("224.0.0.251")}}, {cmsg_len=20, cmsg_level=SOL_IP, cmsg_type=IP_TTL, cmsg_data=[255]}], msg_controllen=56, msg_flags=0}, 0) = 38
[...]
```
No firewall is active:
```
$ sudo nft list ruleset
<empty>
```
<details><summary>sd-networkd info</summary>

```
$ networkctl -n0 status enp7s0
● 2: enp7s0
                   Link File: /usr/lib/systemd/network/99-default.link
                Network File: /etc/systemd/network/10-wired.network
                       State: routable (configured)
                Online state: online                                                  
                        Type: ether
                        Path: pci-0000:07:00.0
                      Driver: r8169
                      Vendor: Realtek Semiconductor Co., Ltd.
                       Model: Killer E3000 2.5GbE Controller
           Alternative Names: enx7486e2244f96
            Hardware Address: 74:86:e2:24:4f:96 (Dell Inc.)
                         MTU: 1500 (min: 68, max: 9194)
                       QDisc: fq_codel
IPv6 Address Generation Mode: eui64
    Number of Queues (Tx/Rx): 1/1
            Auto negotiation: yes
                       Speed: 1Gbps
                      Duplex: full
                        Port: tp
                     Address: 10.3.0.5 (DHCPv4 via 10.3.0.254)
                              [... ipv6 addrs ...]
                              fe80::7686:e2ff:fe24:4f96
                     Gateway: 10.3.0.254
                              fe80::daec:5eff:fede:cd3c
                         DNS: 10.3.0.254
              Search Domains: abra.home
                         NTP: 10.3.0.254
           Activation Policy: up
         Required For Online: yes
              Captive Portal: urn:ietf:params:capport:unrestricted                    
            DHCPv4 Client ID: IAID:0x7b31fe60/DUID
          DHCPv6 Client DUID: DUID-EN/Vendor:0000ab1176675fdb85f2cfdb
```
```
$ cat /etc/systemd/network/10-wired.network
[Match]
Type=ether

[Network]
MulticastDNS=yes
DHCP=yes

[Route]
Gateway=fe80::daec:5eff:fede:cd3c
GatewayOnLink=yes
Metric=256

[DHCPv4]
UseDomains=yes
RouteMetric=256
RoutesToDNS=no

[IPv6AcceptRA]
Token=prefixstable
RouteMetric=256
```
</details>

**Comment by bluca** [comment]
can you check the v257-stable branch? it should be fixed there

**Comment by rpigott** [comment]
I built sd-resolved from 257-stable (cb7cce72becd) and the behavior seems the same.

Do you have a commit in mind that fixed this issue? I couldn't find a related issue and tbh I'm still not sure what goes wrong.

**Comment by bluca** [comment]
I was thinking about https://github.com/systemd/systemd/commit/7addd42c2e01a6b94c9c9dccece74387c9f18344

**Comment by freswa** [comment]
Maybe related to https://github.com/systemd/systemd/issues/35654 ?

**Comment by rpigott** [comment]
The strace shows an apparently successful sendmsg though, so I don't understand where/how these pkts are getting dropped before tcpdump sees them if there is no nftables ruleset present on the host...

**Comment by rpigott** [comment]
Ah, my laptop I used for testing the query was also running v257.2. I downgraded the laptop to v256 and this time running v257-stable on my desktop allows mdns to work. So I think this has been resolved.
