### ISSUE TITLE
nspawn doesn't clean up cgroups after the container stops, preventing further restart

### ISSUE THREAD

**Issue by gentoo-root** [systemd/systemd#37938]
### systemd version the issue has been seen with

257.6 (with patches cherry-picked from upstream)

### Used distribution

Arch Linux

### Linux kernel version used

6.15.2-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-nspawn

### Expected behaviour you didn't see

I should be able to restart the container under the same name, after it's been terminated with a triple press on Ctrl-].

### Unexpected behaviour you saw

After the container is terminated (with a triple press on Ctrl-]), its scope remains present under `/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/machine.slice/`. The next restart will therefore fail, if the machine uses the same name:

```
systemd[2236]: android-build.scope: Couldn't move process 260903 to requested cgroup '/user.slice/user-1000.slice/user@1000.service/machine.slice/android-build.scope': Device or resource busy
android-build.scope: Failed to add PIDs to scope's control group: Device or resource busy
android-build.scope: Failed with result 'resources'.
Failed to start Container android-build.
```

### Steps to reproduce the problem

I wrote a script that assembles the image suitable for systemd-nspawn running in unprivileged mode:

```
#!/usr/bin/env bash

set -eu
cd $(dirname "$0")

HASH=$(docker build -q .)
NAME=$(docker create "$HASH" true)
trap 'docker rm "$NAME" > /dev/null' EXIT
fallocate -l 8G rootfs.img
docker export "$NAME" | mkfs.ext4 -d - rootfs.img
docker rm "$NAME"
trap '' EXIT

veritysetup format rootfs.img rootfs.verity --root-hash-file rootfs.hash
openssl smime -sign -binary \
	-in rootfs.hash \
	-signer rootfs.crt \
	-inkey rootfs.key \
	-outform DER \
	-out rootfs.hash.p7

rm -f disk.img
fallocate -l 8270M disk.img
sgdisk -n 1:2048:+8G disk.img
sgdisk -t 1:8304 disk.img
sgdisk -n 2:0:+65M disk.img
sgdisk -t 2:830C disk.img
sgdisk -n 3:0:+1M disk.img
sgdisk -t 3:8370 disk.img

cat > rootfs.sig << EOF
{"rootHash": "$(cat rootfs.hash)", "signature": "$(base64 -w0 rootfs.hash.p7)"}
EOF

dd if=rootfs.img of=disk.img seek=2048 conv=notrunc
dd if=rootfs.verity of=disk.img seek=16779264 conv=notrunc
dd if=rootfs.sig of=disk.img seek=16912384 conv=notrunc
```

Dockerfile can be as simple as `FROM debian:12`.

0. Build systemd 257.6 with these patches cherry-picked (otherwise it will fail due to other bugs, that are fixed in upstream): https://github.com/systemd/systemd/commit/ee6fd7ef82522d538dd513e8aabf6d29ece4dc92, https://github.com/systemd/systemd/commit/790f5162174cc9813f67a01f5b8a0f960f5386f8, https://github.com/systemd/systemd/commit/273d14f5ddf5971cb89efb006ffd799a0d267214 (the last one is not only useful for tun, but also for veth).
1. As a normal user, run `openssl req -new -x509 -key rootfs.key -out rootfs.crt -days 3650 -subj "/CN=verity-signing"` to generate verity keys.
2. As root, place the generated `rootfs.crt` under `/etc/verity.d/`.
3. As a normal user, run the script above to generate the image.
4. As a normal user, run `systemd-nspawn --boot --ephemeral --image disk.img --network-veth --register no --machine android-build`.
5. Kill it with a triple press on Ctrl-].
6. Try step 4 again. It will fail if it uses the same `--machine android-build` parameter. It will succeed if the parameter is dropped, or the name is changed, but the cgroups under `/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/machine.slice/` will be leaked in any case.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
systemd[2236]: android-build.scope: Couldn't move process 260903 to requested cgroup '/user.slice/user-1000.slice/user@1000.service/machine.slice/android-build.scope': Device or resource busy
android-build.scope: Failed to add PIDs to scope's control group: Device or resource busy
android-build.scope: Failed with result 'resources'.
Failed to start Container android-build.
```

**Comment by poettering** [comment]
Already fixed by: 51a70c887570121588cbdf7cdf97ac4cec4f5bda

**Comment by gentoo-root** [comment]
> Already fixed by: https://github.com/systemd/systemd/commit/51a70c887570121588cbdf7cdf97ac4cec4f5bda

I cherry-picked this commit as well, but the bug still reproduces.

**Comment by poettering** [comment]
You need a bunch of preparatory commits too, the one i linked is just the final one that makes it all work. It's not sufficient to just cherry pick that one.
