### ISSUE TITLE
systemd-boot uses wrong id for boot entries when boot counting is enabled

### ISSUE THREAD

**Issue by danyspin97** [systemd/systemd#38813]
### systemd version the issue has been seen with

257.7

### Used distribution

openSUSE MicroOS

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

Expected behavior: systemd-boot removes the boot counting from the id when handling boot entries. I.e. boot entry `/boot/efi//loader/entries/opensuse-microos-6.16.3-1-default-4+3.conf` should have `opensuse-microos-6.16.3-1-default-4.conf` as `id` (as shown by `bootctl list`) instead of `opensuse-microos-6.16.3-1-default-4+3.conf`). This issue invalidates the reported boot entries (in EFI var `LoaderEntries`); in addition, the default entry and the selected entry don't work as intended, as bootctl and systemd-boot ids differs.

The id is generated [here](https://github.com/systemd/systemd/blob/67573e8b8ba2ef7df8640553c16beb8b60684c1d/src/boot/boot.c#L1398), where the file is used as is and the boot counting is not removed.

### Steps to reproduce the problem

- Enable Automatic Boot Assessment: `echo "3" > /etc/kernel/tries`
- Create a new entry with the boot count enabled
- Reboot to enter systemd-boot
- Boot into a different entry to keep the boot counting enabled

In addition, set the default entry (`bootctl set-default`) to the id shown by `bootctl list`, i.e. without the boot count in it, then reboot into systemd-boot, where there won't be any default.

If needed I can give detailed steps to reproduce it on MicroOS.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# bootctl list
         type: Boot Loader Specification Type #1 (.conf)
        title: openSUSE MicroOS 20250901 (4@6.16.3-1-default) (default) (not reported/new)
           id: opensuse-microos-6.16.3-1-default-4.conf
       source: /boot/efi//loader/entries/opensuse-microos-6.16.3-1-default-4+3.conf (on the EFI System Partition)
        tries: 3 left
     sort-key: opensuse-microos
      version: 4@6.16.3-1-default
        linux: /boot/efi//opensuse-microos/6.16.3-1-default/linux-69aad88811b8e5f86cfd942dd2209d5f0f5a831d
       initrd: /boot/efi//opensuse-microos/6.16.3-1-default/initrd-4c420909fedb54d346d458bde5d17ea8e4c7b252
      options: quiet systemd.show_status=yes console=ttyS0,115200 console=tty0 ignition.platform.id=qemu security=selinux sel>

         type: Reported by Boot Loader
        title: opensuse-microos-6.16.3-1-default-4+3.conf (reported/absent)
           id: opensuse-microos-6.16.3-1-default-4+3.conf
       source: /sys/firmware/efi/efivars/LoaderEntries-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f (on the EFI System Partition)
## Content of /sys/firmware/efi/efivars/LoaderEntries-*
opensuse-microos-6.16.3-1-default-5.conf
opensuse-microos-6.16.3-1-default-4+3.conf
opensuse-microos-6.16.3-1-default-3.conf
opensuse-microos-6.16.3-1-default-2.conf
opensuse-microos-6.16.3-1-default-1.conf
auto-efi-default
auto-reboot-to-firmware-setup
```

**Comment by aplanas** [comment]
To rephrase: `bootctl` seems to generate the `id` from the filename of the boot entry, removing the boot counter (`+n`), so `entry-1.conf`, `entry-1+3.conf`, `entry-1+2-1.conf` all three have the same `id`: `entry-1.conf`

But `systemd-boot` generates the `id` from the same filename, but this time it does not remove the boot counter, making for the previous example three different `id`s.

The issues of this different `id` is that the communication between `bootctl` and `systemd-boot` (specified by BLI) is now broken.  For example:

1. `bootctl set-default entry-1.conf` will write `entry-1.conf` in the `LoaderEntryDefault` EFI variable, but `systemd-boot` does not recognize this `id` as the filename is `entry-1+3.conf`, and so the generated `id` is `entry-1+3.conf`
2. Pressing 'D' in `systemd-boot` menu will make the selected entry the new default, writing the `id` in the same EFI variable, but this time includes the `+3` suffix, and `bootctl list` will not recognize the entry as default

**Comment by yuwata** [comment]
Is it reproducible with v258-rcX? I am not sure, but maybe already fixed by #37375. Could you try the RC release?

**Comment by aplanas** [comment]
Based on the code changes I would say that #37375 does not fix the issue (that will be tested, tho).

The most evident issue is that the `LoaderEntryDefault` EFI variable will contain one `id` or another depending on the actor, and this PR is not touching that part.

**Comment by danyspin97** [comment]
> Is it reproducible with v258-rcX?

Yes, it is reproducible with a build from today (commit 28edbbdc1).
