### ISSUE TITLE
bootctl does not create an EFI boot entry when running in arch-chroot

### ISSUE THREAD

**Issue by nl6720** [systemd/systemd#39002]
### systemd version the issue has been seen with

systemd 258 (258-1-arch)

### Used distribution

Arch Linux

### Linux kernel version used

6.16.7-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

bootctl

### Expected behaviour you didn't see

```sh
# bootctl --variables=yes install
Created "/boot/EFI/systemd".
Created "/boot/EFI/BOOT".
Created "/boot/loader".
Created "/boot/loader/keys".
Created "/boot/loader/entries".
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/systemd/systemd-bootx64.efi".
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/BOOT/BOOTX64.EFI".
Random seed file /boot/loader/random-seed successfully written (32 bytes).
Created EFI boot entry "Linux Boot Manager".
```

### Unexpected behaviour you saw

```sh
# bootctl --variables=yes install
Created "/boot/EFI/systemd".
Created "/boot/EFI/BOOT".
Created "/boot/loader".
Created "/boot/loader/keys".
Created "/boot/loader/entries".
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/systemd/systemd-bootx64.efi".
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/BOOT/BOOTX64.EFI".
Random seed file /boot/loader/random-seed successfully written (32 bytes).
Failed to determine current boot order: Operation not supported
```

### Steps to reproduce the problem

Run `bootctl --variables=yes install` inside [arch-chroot](https://man.archlinux.org/man/arch-chroot.8). E.g., a simple way to test from a booted system is to run:
```sh
arch-chroot / 
```
Once inside the chroot, run:
```sh
bootctl --variables=yes install
```

https://github.com/systemd/systemd/issues/36174 was supposed to be fixed in systemd 258, but even with the new `--variables=yes` option, the EFI boot entry is not created.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

**Comment by yuwata** [comment]
Should be fixed by #39021.

**Comment by nl6720** [comment]
@yuwata, it's not fixed.

Even with systemd 258 (258-2-arch) which backported 01184496a2b518f33c56b5803549f27fa8f226fe, I still get the same message.

```
Failed to determine current boot order: Operation not supported
```

**Comment by yuwata** [comment]
I guess you also need https://github.com/systemd/systemd/pull/39021

**Comment by nl6720** [comment]
Did you mistype? #39021 added only one commit: 01184496a2b518f33c56b5803549f27fa8f226fe.

**Comment by yuwata** [comment]
No, that fixes chroot detection. You said the issue is in the chroot. So I guess the patch also fixes your issue.

**Comment by nl6720** [comment]
It doesn't. The Arch package systemd 258-2 ( systemctl version: `systemd 258 (258-2-arch)`) includes the patch.

Even with a patched systemd both inside and outside the chroot, I still get this issue.

**Comment by nl6720** [comment]
It doesn't look like it's possible to bisect this since bbeeea43625d22d2ab92b26ed93378acbad8ca66 which added `--variables=yes` already is _bad_.

**Comment by nl6720** [comment]
In case it matters, I only tested this in a VirtualBox VM.

**Comment by lfrancke** [comment]
FWIW I also get the same error

```
[root@archiso efi]# bootctl --variables=yes --esp-path=/efi install
Running in a chroot, enabling --graceful.
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/efi/EFI/systemd/systemd-bootx64.efi".
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/efi/EFI/BOOT/BOOTX64.EFI".
Random seed file /efi/loader/random-seed successfully refreshed (32 bytes).
Failed to determine current boot order, skipping: Operation not supported
```

```
[root@archiso /]# pacman -Q | grep systemd
systemd 258-4
systemd-libs 258-4
systemd-sysvcompat 258-4
systemd-ukify 258-4
```

This is on a real physical laptop.
And it does indeed seem as if systemd 258-4 [includes](https://gitlab.archlinux.org/archlinux/packaging/packages/systemd/-/blob/133c5ec9390327f4fa7f94a7605f3bc0ac740baf/PKGBUILD#L97-114) the [PR](https://github.com/systemd/systemd/pull/39021)

**Comment by yuwata** [comment]
Is `/sys/firmware/efi/` mounted on the chroot environment?
Could you also provide the result of `systemd-detect-virt` in the chroot?

**Comment by lfrancke** [comment]
> Is /sys/firmware/efi/ mounted on the chroot environment?

Looks like it

```
[root@archiso efi]# mount | grep sys/firmware
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
[root@archiso /]# cd /sys/firmware/efi/
[root@archiso efi]# ll
total 0
drwxr-xr-x  5 root root    0 Oct  2 17:43 .
drwxr-xr-x  6 root root    0 Oct  2 17:43 ..
-r--r--r--  1 root root 4.0K Oct  2 17:47 config_table
drwxr-xr-x  2 root root    0 Oct  2 17:43 efivars
drwxr-xr-x  3 root root    0 Oct  2 17:47 esrt
-r--r--r--  1 root root 4.0K Oct  2 17:47 fw_platform_size
-r--r--r--  1 root root 4.0K Oct  2 17:47 fw_vendor
-r--r--r--  1 root root 4.0K Oct  2 17:47 runtime
drwxr-xr-x 16 root root    0 Oct  2 17:47 runtime-map
-r--------  1 root root 4.0K Oct  2 17:47 systab
```

```
[root@archiso efi]# systemd-detect-virt
container-other
```

I hope that helps!

**Comment by YHNdnzj** [comment]
This is not an regression. `--variable=yes` apparently never worked properly since introduction. For Arch users I'll reiterate that it's essentially an Arch issue that you needed all those hacks in bootctl in the first place, and `arch-chroot -S` should fix all the nastiness.

**Comment by leebickmtu** [comment]
I can confirm that booting off the newest Arch ISO (2025.10.01) which includes the new `-S` option for `arch-chroot` the EFI boot entry is created successfully. In that mode `--variables=yes` is not needed either.

**Comment by poettering** [comment]
Closing, since this was apparently fixed on the Arch's side.

**Comment by ashmanda-cs** [comment]
Issue is still occurring. Nothing has been fixed. The installer fails to install GRUB completely. Had to manually install GRUB on chroot, and add bootloader entry manually too.

**Comment by C0rn3j** [comment]
> Issue is still occurring. Nothing has been fixed. The installer fails to install GRUB completely. Had to manually install GRUB on chroot, and add bootloader entry manually too.

A bit late now, but the flag was adopted in [archinstall 3.0.12](https://github.com/archlinux/archinstall/releases/tag/3.0.12), which was already out for a couple weeks at the time you commented, so I suppose the issue there was not running latest versions.
