### ISSUE TITLE
Systemd-logind fails

### ISSUE THREAD

**Issue by EntityDeleter** [systemd/systemd#39012]
### systemd version the issue has been seen with

258

### Used distribution

Arch Linux

### Linux kernel version used

6.16.7-zen1-1-zen

### CPU architectures issue was seen on

x86_64

### Component

loginctl, systemd

### Expected behaviour you didn't see

Systemd-logind starts normally.
It allows Hyprland to start normally.

### Unexpected behaviour you saw

Systemd-logind fails due to missing directories in /run after update from 257.9 to 258.
Due to this, Hyprland is unable to start.

### Steps to reproduce the problem

Install systemd 258.
Regenerate initramfs and reboot.
Open journal logs.

Also, if running Hyprland, it fails. 
Simply downgrading systemd to 257.9 solves the issue and errors from systemd-logind without any other action.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Sep 18 19:59:26 arch-laptop bluetoothd[2347]: profiles/audio/bap.c:bap_adapter_probe() BAP requires ISO Socket which is not enabled
Sep 18 19:59:26 arch-laptop bluetoothd[2347]: bap: Operation not supported (95)
Sep 18 19:59:26 arch-laptop bluetoothd[2347]: Failed to set mode: Rejected (0x0b)
Sep 18 19:59:26 arch-laptop bluetoothd[2347]: Failed to set privacy: Rejected (0x0b)
Sep 18 19:59:27 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/seats/seat0' into place: No such file or directory
Sep 18 19:59:28 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/users/968' into place: No such file or directory
Sep 18 19:59:28 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/users/968' into place: No such file or directory
Sep 18 19:59:28 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/seats/seat0' into place: No such file or directory
Sep 18 19:59:28 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/sessions/c1' into place: No such file or directory
Sep 18 19:59:28 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/users/968' into place: No such file or directory
Sep 18 19:59:28 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/seats/seat0' into place: No such file or directory
Sep 18 19:59:28 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/users/968' into place: No such file or directory
Sep 18 19:59:28 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/sessions/c1' into place: No such file or directory
Sep 18 19:59:28 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/users/968' into place: No such file or directory
Sep 18 19:59:28 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/sessions/1' into place: No such file or directory
Sep 18 19:59:28 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/users/968' into place: No such file or directory
Sep 18 19:59:28 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/users/968' into place: No such file or directory
Sep 18 19:59:28 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/sessions/c1' into place: No such file or directory
Sep 18 19:59:28 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/users/968' into place: No such file or directory
Sep 18 19:59:33 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/seats/seat0' into place: No such file or directory
Sep 18 19:59:33 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/users/968' into place: No such file or directory
Sep 18 19:59:33 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/sessions/c1' into place: No such file or directory
Sep 18 19:59:44 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
Sep 18 19:59:44 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
Sep 18 19:59:44 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/seats/seat0' into place: No such file or directory
Sep 18 19:59:44 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/sessions/2' into place: No such file or directory
Sep 18 19:59:44 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
Sep 18 19:59:44 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/seats/seat0' into place: No such file or directory
Sep 18 19:59:44 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
Sep 18 19:59:44 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/sessions/2' into place: No such file or directory
Sep 18 19:59:44 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
Sep 18 19:59:44 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/sessions/3' into place: No such file or directory
Sep 18 19:59:44 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
Sep 18 19:59:45 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
Sep 18 19:59:45 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/sessions/2' into place: No such file or directory
Sep 18 19:59:45 arch-laptop systemd-logind[2358]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
Sep 18 20:00:10 arch-laptop systemd-coredump[3317]: Process 3305 (Hyprland) of user 1000 terminated abnormally without generating a coredump.
```

**Comment by ssmendon** [comment]
Similar issue. I'm able to remote into the machine over SSH, but `sddm` doesn't display anything. Was unable to grab logs from the steps in https://systemd.io/DEBUGGING/ , because my system wouldn't actually boot with the debugging flags enabled. Have not had the time to review and prune logs, so I have nothing to post unfortunately. The errors are similar to the original post.

`[    0.000000] Linux version 6.16.7-arch1-1 (linux@archlinux) (gcc (GCC) 15.2.1 20250813, GNU ld (GNU Binutils) 2.45.0) #1 SMP PREEMPT_DYNAMIC Thu, 11 Sep 2025 17:42:36 +0000`

Downgrading to `systemd=257.9-1` resolves the problem.

**Comment by yuwata** [comment]
Do you use custom .service file for systemd-logind?
The default systemd-logind.service has
```
RuntimeDirectory=systemd/sessions systemd/seats systemd/users systemd/inhibit systemd/shutdown
```
hence the service can update files in the directories.

**Comment by yuwata** [comment]
Please provide `systemctl cat systemd-logind.service` and debugging logs of systemd-logind.

**Comment by farribeiro** [comment]
A silly comment or idea, systemd could have a similar screen to kernel panic with qrcode

**Comment by EntityDeleter** [comment]
Just updates my OS, and seems that a bug fix has been pushed out (from 258-1 to 258-2). After updating, this problem no longer appears. Thank you and I hope I didn't waste anyone's time. This issue can be marked as closed. I will update if this issue appears on my desktop once I update it as well, but the bug fix seems to be working on my laptop. Thank you.

**Comment by variasdesign** [comment]
I'm having the exact same issue as OP, although I'm using linux-hardened. However, updating to 258-2 doesn't fix the issue. The only modification my systemd-logind has is an override to [notify of failed services](https://wiki.archlinux.org/title/Systemd#Notifying_about_failed_services).

**Comment by variasdesign** [comment]
I'm having the exact same issue as @EntityDeleter. I'm using Arch Linux and linux-hardened. However. The problem persists even when updating to 258.2. Attached are systemd-logind logs running on 258.2:
```
sep 22 11:33:09 orion systemd[1]: Starting User Login Management...
sep 22 11:33:09 orion systemd-logind[2481]: New seat seat0.
sep 22 11:33:09 orion systemd-logind[2481]: Failed to move '/run/systemd/seats/seat0' into place: No such file or directory
sep 22 11:33:09 orion systemd-logind[2481]: Watching system buttons on /dev/input/event2 (Power Button)
sep 22 11:33:09 orion systemd-logind[2481]: Watching system buttons on /dev/input/event1 (Power Button)
sep 22 11:33:09 orion systemd-logind[2481]: Watching system buttons on /dev/input/event0 (Sleep Button)
sep 22 11:33:09 orion systemd-logind[2481]: Watching system buttons on /dev/input/event3 (Yubico YubiKey OTP+FIDO+CCID)
sep 22 11:33:09 orion systemd-logind[2481]: Watching system buttons on /dev/input/event5 (Razer Razer Basilisk V3)
sep 22 11:33:09 orion systemd-logind[2481]: Watching system buttons on /dev/input/event7 (Razer Razer Basilisk V3)
sep 22 11:33:09 orion systemd-logind[2481]: Watching system buttons on /dev/input/event8 (Keychron Keychron Q6)
sep 22 11:33:09 orion systemd-logind[2481]: Watching system buttons on /dev/input/event10 (Keychron Keychron Q6 System Control)
sep 22 11:33:09 orion systemd-logind[2481]: Watching system buttons on /dev/input/event11 (Keychron Keychron Q6 Consumer Control)
sep 22 11:33:09 orion systemd-logind[2481]: Watching system buttons on /dev/input/event12 (Keychron Keychron Q6 Keyboard)
sep 22 11:33:09 orion systemd[1]: Started User Login Management.
sep 22 11:33:10 orion systemd-logind[2481]: Failed to move '/run/systemd/inhibit/1' into place: No such file or directory
sep 22 11:33:10 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:10 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:10 orion systemd-logind[2481]: New session '1' of user 'varias' with class 'user' and type 'tty'.
sep 22 11:33:10 orion systemd-logind[2481]: Failed to move '/run/systemd/seats/seat0' into place: No such file or directory
sep 22 11:33:10 orion systemd-logind[2481]: Failed to move '/run/systemd/sessions/1' into place: No such file or directory
sep 22 11:33:10 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:10 orion systemd-logind[2481]: Failed to move '/run/systemd/seats/seat0' into place: No such file or directory
sep 22 11:33:10 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:10 orion systemd-logind[2481]: Watching system buttons on /dev/input/event10 (Keychron Keychron Q6 System Control)
sep 22 11:33:10 orion systemd-logind[2481]: Failed to move '/run/systemd/sessions/1' into place: No such file or directory
sep 22 11:33:10 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:10 orion systemd-logind[2481]: New session '2' of user 'varias' with class 'manager' and type 'unspecified'.
sep 22 11:33:10 orion systemd-logind[2481]: Failed to move '/run/systemd/sessions/2' into place: No such file or directory
sep 22 11:33:10 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:10 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:10 orion systemd-logind[2481]: Failed to move '/run/systemd/sessions/1' into place: No such file or directory
sep 22 11:33:10 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:13 orion systemd-logind[2481]: Session 1 logged out. Waiting for processes to exit.
sep 22 11:33:13 orion systemd-logind[2481]: Failed to move '/run/systemd/sessions/1' into place: No such file or directory
sep 22 11:33:13 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:13 orion systemd-logind[2481]: Removed session 1.
sep 22 11:33:13 orion systemd-logind[2481]: Failed to move '/run/systemd/seats/seat0' into place: No such file or directory
sep 22 11:33:13 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:13 orion systemd-logind[2481]: Failed to move '/run/systemd/seats/seat0' into place: No such file or directory
sep 22 11:33:13 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:13 orion systemd-logind[2481]: Failed to move '/run/systemd/users/966' into place: No such file or directory
sep 22 11:33:13 orion systemd-logind[2481]: Failed to move '/run/systemd/users/966' into place: No such file or directory
sep 22 11:33:13 orion systemd-logind[2481]: New session '3' of user 'greeter' with class 'greeter' and type 'tty'.
sep 22 11:33:13 orion systemd-logind[2481]: Failed to move '/run/systemd/seats/seat0' into place: No such file or directory
sep 22 11:33:13 orion systemd-logind[2481]: Failed to move '/run/systemd/sessions/3' into place: No such file or directory
sep 22 11:33:13 orion systemd-logind[2481]: Failed to move '/run/systemd/users/966' into place: No such file or directory
sep 22 11:33:13 orion systemd-logind[2481]: Failed to move '/run/systemd/seats/seat0' into place: No such file or directory
sep 22 11:33:13 orion systemd-logind[2481]: Watching system buttons on /dev/input/event10 (Keychron Keychron Q6 System Control)
sep 22 11:33:13 orion systemd-logind[2481]: Failed to move '/run/systemd/users/966' into place: No such file or directory
sep 22 11:33:13 orion systemd-logind[2481]: Failed to move '/run/systemd/sessions/3' into place: No such file or directory
sep 22 11:33:13 orion systemd-logind[2481]: Failed to move '/run/systemd/users/966' into place: No such file or directory
sep 22 11:33:13 orion systemd-logind[2481]: Watching system buttons on /dev/input/event10 (Keychron Keychron Q6 System Control)
sep 22 11:33:13 orion systemd-logind[2481]: New session '4' of user 'greeter' with class 'manager-early' and type 'unspecified'.
sep 22 11:33:13 orion systemd-logind[2481]: Failed to move '/run/systemd/sessions/4' into place: No such file or directory
sep 22 11:33:13 orion systemd-logind[2481]: Failed to move '/run/systemd/users/966' into place: No such file or directory
sep 22 11:33:13 orion systemd-logind[2481]: Failed to move '/run/systemd/users/966' into place: No such file or directory
sep 22 11:33:13 orion systemd-logind[2481]: Failed to move '/run/systemd/sessions/3' into place: No such file or directory
sep 22 11:33:13 orion systemd-logind[2481]: Failed to move '/run/systemd/users/966' into place: No such file or directory
sep 22 11:33:23 orion systemd-logind[2481]: Failed to move '/run/systemd/sessions/2' into place: No such file or directory
sep 22 11:33:23 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:23 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:24 orion systemd-logind[2481]: Removed session 2.
sep 22 11:33:24 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:24 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:26 orion systemd-logind[2481]: Session 3 logged out. Waiting for processes to exit.
sep 22 11:33:26 orion systemd-logind[2481]: Failed to move '/run/systemd/sessions/3' into place: No such file or directory
sep 22 11:33:26 orion systemd-logind[2481]: Failed to move '/run/systemd/users/966' into place: No such file or directory
sep 22 11:33:26 orion systemd-logind[2481]: Removed session 3.
sep 22 11:33:26 orion systemd-logind[2481]: Failed to move '/run/systemd/seats/seat0' into place: No such file or directory
sep 22 11:33:26 orion systemd-logind[2481]: Failed to move '/run/systemd/users/966' into place: No such file or directory
sep 22 11:33:26 orion systemd-logind[2481]: Failed to move '/run/systemd/seats/seat0'thing into place: No such file or directory
sep 22 11:33:26 orion systemd-logind[2481]: Failed to move '/run/systemd/users/966' into place: No such file or directory
sep 22 11:33:26 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:26 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:26 orion systemd-logind[2481]: New session '5' of user 'varias' with class 'user' and type 'tty'.
sep 22 11:33:26 orion systemd-logind[2481]: Failed to move '/run/systemd/seats/seat0thing' into place: No such file or directory
sep 22 11:33:26 orion systemd-logind[2481]: Failed to move '/run/systemd/sessions/5' into place: No such file or directory
sep 22 11:33:26 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:26 orion systemd-logind[2481]: Failed to move '/run/systemd/seats/seat0' into place: No such file or directory
sep 22 11:33:26 orion systemd-logind[2481]: Watching system buttons on /dev/input/event10 (Keychron Keychron Q6 System Control)
sep 22 11:33:26 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:26 orion systemd-logind[2481]: Watching system buttons on /dev/input/event10 (Keychron Keychron Q6 System Control)
sep 22 11:33:26 orion systemd-logind[2481]: Failed to move '/run/systemd/sessions/5' into place: No such file or directory
sep 22 11:33:26 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:26 orion systemd-logind[2481]: New session '6' of user 'varias' with class 'manager' and type 'unspecified'.
sep 22 11:33:26 orion systemd-logind[2481]: Failed to move '/run/systemd/sessions/6' into place: No such file or directory
sep 22 11:33:26 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:27 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:27 orion systemd-logind[2481]: Failed to move '/run/systemd/sessions/5' into place: No such file or directory
sep 22 11:33:27 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:33:36 orion systemd-logind[2481]: Failed to move '/run/systemd/sessions/4' into place: No such file or directory
sep 22 11:33:36 orion systemd-logind[2481]: Failed to move '/run/systemd/users/966' into place: No such file or directory
sep 22 11:33:36 orion systemd-logind[2481]: Failed to move '/run/systemd/users/966' into place: No such file or directory
sep 22 11:33:36 orion systemd-logind[2481]: Removed session 4.
sep 22 11:33:36 orion systemd-logind[2481]: Failed to move '/run/systemd/users/966' into place: No such file or directory
sep 22 11:33:36 orion systemd-logind[2481]: Failed to move '/run/systemd/users/966' into place: No such file or directory
sep 22 11:51:57 orion systemd-logind[2481]: Watching system buttons on /dev/input/event2 (Power Button)
sep 22 11:51:57 orion systemd-logind[2481]: Watching system buttons on /dev/input/event1 (Power Button)
sep 22 11:51:57 orion systemd-logind[2481]: Watching system buttons on /dev/input/event0 (Sleep Button)
sep 22 11:51:57 orion systemd-logind[2481]: Watching system buttons on /dev/input/event3 (Yubico YubiKey OTP+FIDO+CCID)
sep 22 11:51:57 orion systemd-logind[2481]: Watching system buttons on /dev/input/event7 (Razer Razer Basilisk V3)
sep 22 11:51:57 orion systemd-logind[2481]: Watching system buttons on /dev/input/event5 (Razer Razer Basilisk V3)
sep 22 11:51:57 orion systemd-logind[2481]: Watching system buttons on /dev/input/event8 (Keychron Keychron Q6)
sep 22 11:51:57 orion systemd-logind[2481]: Watching system buttons on /dev/input/event10 (Keychron Keychron Q6 System Control)
sep 22 11:51:57 orion systemd-logind[2481]: Watching system buttons on /dev/input/event11 (Keychron Keychron Q6 Consumer Control)
sep 22 11:51:57 orion systemd-logind[2481]: Watching system buttons on /dev/input/event12 (Keychron Keychron Q6 Keyboard)
sep 22 11:54:08 orion systemd-logind[2481]: The system will reboot now!
sep 22 11:54:08 orion systemd-logind[2481]: System is rebooting.
sep 22 11:54:08 orion systemd-logind[2481]: Session 5 logged out. Waiting for processes to exit.
sep 22 11:54:08 orion systemd-logind[2481]: Failed to move '/run/systemd/sessions/5' into place: No such file or directory
sep 22 11:54:08 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:54:08 orion systemd-logind[2481]: Removed session 5.
sep 22 11:54:08 orion systemd-logind[2481]: Failed to move '/run/systemd/seats/seat0' into place: No such file or directory
sep 22 11:54:08 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:54:08 orion systemd-logind[2481]: Failed to move '/run/systemd/seats/seat0' into place: No such file or directory
sep 22 11:54:08 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:54:08 orion systemd-logind[2481]: Watching system buttons on /dev/input/event10 (Keychron Keychron Q6 System Control)
sep 22 11:54:09 orion systemd-logind[2481]: Failed to move '/run/systemd/sessions/6' into place: No such file or directory
sep 22 11:54:09 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:54:09 orion systemd-logind[2481]: Removed session 6.
sep 22 11:54:09 orion systemd-logind[2481]: Failed to move '/run/systemd/users/1000' into place: No such file or directory
sep 22 11:54:09 orion systemd[1]: Stopping User Login Management...
sep 22 11:54:09 orion systemd[1]: systemd-logind.service: Deactivated successfully.
sep 22 11:54:09 orion systemd[1]: Stopped User Login Management.
```

**Comment by variasdesign** [comment]
I've tried reproducing the issue with the debug flags `systemd.log_level=debug systemd.log_target=kmsg log_buf_len=1M printk.devkmsg=on` appended to the kernel parameters. However, I'm unable to boot. My /efi is not being mounted and the boot process gets stuck on `A start job is running for Create Static Device Nodes in /dev gracefully`. Please advise.

**Comment by denismilanovic** [comment]
Continues to be an issue with 258-3 on Arch Linux with linux kernel, preventing GDM from starting:
```
➤ journalctl -b -1 | grep -E '(seat|Gdm)'
Sep 24 23:02:00 fw13 systemd-logind[2311]: New seat seat0.                                                                                    
Sep 24 23:02:00 fw13 systemd-logind[2311]: Failed to move '/run/systemd/seats/seat0' into place: No such file or directory
Sep 24 23:02:02 fw13 gdm[2456]: Gdm: Failed to query CanGraphical information for seat seat0
Sep 24 23:02:24 fw13 gdm[2456]: Gdm: Failed to query CanGraphical information for seat seat0                              
Sep 24 23:02:41 fw13 systemd-logind[2311]: Failed to move '/run/systemd/seats/seat0' into place: No such file or directory
Sep 24 23:02:41 fw13 systemd-logind[2311]: Failed to move '/run/systemd/seats/seat0' into place: No such file or directory    
```

Unambigously caused by upgrading from 257.9-1 to any 258.x so far, and resolved by downgrading:
```
➤ grep 2025-09-24 /var/log/pacman.log | grep -E '(upgraded|downgraded)' 
[2025-09-24T23:00:15+1000] [ALPM] upgraded abseil-cpp (20250814.0-1 -> 20250814.1-1)
[2025-09-24T23:00:15+1000] [ALPM] upgraded util-linux-libs (2.41.1-1 -> 2.41.2-1)
[2025-09-24T23:00:15+1000] [ALPM] upgraded systemd-libs (257.9-1 -> 258-3)
[2025-09-24T23:00:15+1000] [ALPM] upgraded harfbuzz (11.5.0-1 -> 11.5.1-1)
[2025-09-24T23:00:15+1000] [ALPM] upgraded glycin (2.0.0-3 -> 2.0.0-4)
[2025-09-24T23:00:15+1000] [ALPM] upgraded gdk-pixbuf2 (2.44.1-3 -> 2.44.2-1)
[2025-09-24T23:00:15+1000] [ALPM] upgraded util-linux (2.41.1-1 -> 2.41.2-1)
[2025-09-24T23:00:16+1000] [ALPM] upgraded systemd (257.9-1 -> 258-3)
[2025-09-24T23:00:16+1000] [ALPM] upgraded js140 (140.3.0-1 -> 140.3.1-1)
[2025-09-24T23:00:16+1000] [ALPM] upgraded harfbuzz-icu (11.5.0-1 -> 11.5.1-1)
[2025-09-24T23:00:16+1000] [ALPM] upgraded gnome-shell (1:49.0-1 -> 1:49.0-2)
[2025-09-24T23:00:17+1000] [ALPM] upgraded linux (6.16.8.arch2-1 -> 6.16.8.arch3-1)
[2025-09-24T23:00:17+1000] [ALPM] upgraded ollama (0.12.0-2 -> 0.12.1-1)
[2025-09-24T23:00:18+1000] [ALPM] upgraded ollama-rocm (0.12.0-2 -> 0.12.1-1)
[2025-09-24T23:00:18+1000] [ALPM] upgraded parallel (20250822-1 -> 20250922-1)
[2025-09-24T23:00:18+1000] [ALPM] upgraded passt (2025_09_11.6cbcccc-1 -> 2025_09_19.623dbf6-1)
[2025-09-24T23:00:18+1000] [ALPM] upgraded systemd-sysvcompat (257.9-1 -> 258-3)
[2025-09-24T23:03:15+1000] [ALPM] downgraded systemd-libs (258-3 -> 257.9-1)
[2025-09-24T23:03:15+1000] [ALPM] downgraded systemd (258-3 -> 257.9-1)
[2025-09-24T23:03:16+1000] [ALPM] downgraded systemd-sysvcompat (258-3 -> 257.9-1)
```

**Comment by poettering** [comment]
mayb strace logind when this happens to see what syscall precisely fails.

what is linux hardenened? does that carry some out of tree patches?

**Comment by denismilanovic** [comment]
I couldn't see any issues other than 'No such file or directory', which made no sense (earlier steps confirm that `/run/systemd` exists)...

FYI @variasdesign if you are running linux-hardened then  perhaps you're also running apparmor, and should be aware of https://github.com/roddhjav/apparmor.d/issues/867.

All working for me now.

**Comment by variasdesign** [comment]
> I couldn't see any issues other than 'No such file or directory', which made no sense (earlier steps confirm that `/run/systemd` exists)...
> 
> FYI [@variasdesign](https://github.com/variasdesign) if you are running linux-hardened then perhaps you're also running apparmor, and should be aware of [roddhjav/apparmor.d#867](https://github.com/roddhjav/apparmor.d/issues/867).
> 
> All working for me now.

Yes, you are correct. Thanks for the heads-up. We can consider the issue fixed.
