### ISSUE TITLE
systemd-resolved: after network reconnection, DNSSEC unsigned zones treated as bogus, stop resolving

### ISSUE THREAD

**Issue by andersk** [systemd/systemd#4175]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

231
### Used distribution

Ubuntu 16.10
### In case of bug report: Expected behaviour you didn't see

systemd-resolved continues resolving after I disconnect and reconnect the network.
### In case of bug report: Unexpected behaviour you saw

On the MIT network (which runs some ancient version of BIND 9), systemd-resolved stops resolving anything that isn’t DNSSEC-signed after I disconnect and reconnect the network. Signed zones continue to resolve.

This happens with either `DNSSEC=yes` or the default `DNSSEC=allow-downgrade`.
### In case of bug report: Steps to reproduce the problem

``` sh-session
$ systemd-resolve github.com
github.com: 192.30.253.113

-- Information acquired via protocol DNS in 15.6ms.
-- Data is authenticated: no
$ # (disconnect and reconnect wifi)
$ systemd-resolve github.com
github.com: resolve call failed: DNSSEC validation failed: no-signature
```

[Full log from `SYSTEMD_LOG_LEVEL=debug /lib/systemd/systemd-resolved`](https://github.com/systemd/systemd/files/478472/debug.txt) across the reconnection.  Here’s the part where `github.com` fails to resolve after the reconnection.

```
Got message type=method_call sender=:1.12138 destination=org.freedesktop.resolve1 object=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=ResolveHostname cookie=2 reply_cookie=0 error=n/a
Looking up RR for github.com IN A.
Looking up RR for github.com IN AAAA.
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus object=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=80 reply_cookie=0 error=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.12117 object=n/a interface=n/a member=n/a cookie=65 reply_cookie=80 error=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus object=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetNameOwner cookie=81 reply_cookie=0 error=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.12117 object=n/a interface=n/a member=n/a cookie=66 reply_cookie=81 error=n/a
Cache miss for github.com IN A
Transaction 7392 for <github.com IN A> scope dns on */*.
Using feature level UDP+EDNS0+DO+LARGE for transaction 7392.
Using DNS server 18.70.0.160 for transaction 7392.
Sending query packet with id 7392.
Processing incoming packet on transaction 7392.
Requesting SOA to validate transaction 7392 (github.com, unsigned non-SOA/NS RRset <github.com IN A 192.30.253.112>).
Cache miss for github.com IN SOA
Transaction 64818 for <github.com IN SOA> scope dns on */*.
Using feature level UDP+EDNS0+DO+LARGE for transaction 64818.
Using DNS server 18.70.0.160 for transaction 64818.
Sending query packet with id 64818.
Processing incoming packet on transaction 64818.
Requesting DS to validate transaction 64818 (github.com, unsigned SOA/NS RRset).
Cache miss for github.com IN DS
Transaction 24924 for <github.com IN DS> scope dns on */*.
Using feature level UDP+EDNS0+DO+LARGE for transaction 24924.
Using DNS server 18.70.0.160 for transaction 24924.
Sending query packet with id 24924.
Processing incoming packet on transaction 24924.
Requesting DNSKEY to validate transaction 24924 (com, RRSIG with key tag: 27452).
Positive cache hit for com IN DNSKEY
Transaction 55432 for <com IN DNSKEY> on scope dns on */* now complete with <success> from cache (authenticated).
Requesting parent SOA to validate transaction 24924 (github.com, unsigned empty DS response).
Positive cache hit for com IN SOA
Transaction 2111 for <com IN SOA> on scope dns on */* now complete with <success> from cache (authenticated).
Validating response from transaction 24924 (github.com IN DS).
Looking at com IN SOA a.gtld-servers.net nstld.verisign-grs.com 1474161818 1800 900 604800 86400: validated
Found verdict for lookup com IN SOA: secure
Found verdict for lookup github.com IN DS: bogus
DNSSEC validation failed for question github.com IN DS: no-signature
Transaction 24924 for <github.com IN DS> on scope dns on */* now complete with <dnssec-failed> from network (unsigned).
Auxiliary DNSSEC RR query failed validation: no-signature
DNSSEC validation failed for question github.com IN SOA: no-signature
Transaction 64818 for <github.com IN SOA> on scope dns on */* now complete with <dnssec-failed> from network (unsigned).
Auxiliary DNSSEC RR query failed validation: no-signature
DNSSEC validation failed for question github.com IN A: no-signature
Transaction 7392 for <github.com IN A> on scope dns on */* now complete with <dnssec-failed> from network (unsigned).
Sent message type=error sender=n/a destination=:1.12138 object=n/a interface=n/a member=n/a cookie=82 reply_cookie=2 error=DNSSEC validation failed: no-signature
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus object=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RemoveMatch cookie=83 reply_cookie=0 error=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.12117 object=n/a interface=n/a member=n/a cookie=67 reply_cookie=83 error=n/a
Freeing transaction 7392.
Freeing transaction 64818.
Freeing transaction 24924.
Freeing transaction 55432.
Freeing transaction 2111.
```

**Comment by poettering** [comment]
Hmm, this appears to be some real bug here. The relevant part from the logs is probably this:

```
Requesting DS to validate transaction 62202 (org, DNSKEY with key tag: 17883).
Requesting DS to validate transaction 62202 (org, DNSKEY with key tag: 48497).
Requesting DS to validate transaction 62202 (org, DNSKEY with key tag: 64353).
Requesting DNSKEY to validate transaction 62202 (org, RRSIG with key tag: 48497).
Potential cyclic dependency, refusing to add transaction 62202 (org IN DNSKEY) as dependency for 62202 (org IN DNSKEY).
```

**Comment by poettering** [comment]
Hmm, I wonder if the problem might be caused by us using 8.8.8.8 as DNS server immediately after reconnecting and then switching over to 18.71.0.151 shortly after.

**Comment by andersk** [comment]
Wait. I thought you [said](https://github.com/systemd/systemd/issues/494#issuecomment-118930936) that “FallbackDNS= is really just the last resort setting, if no other DNS servers are known: if none could be learnt via dhcp or ppp, and none have been configured explicitly in /etc/resolv.conf or in the DNS= setting.” My network configures DNS servers via DHCP—so why are my DNS queries going to Google, even for a short time?

**Comment by poettering** [comment]
@andersk well, there's a race. resolved uses the fallback DNS servers if it has no other config. And that's what happens here: your network management software appears to configure the IP settings first, and only then set up /etc/resolv.conf. At the same time some lookup is attempted via resolved, and in this short time window resolved has no DNS config, but sees a working IP setup otherwise, and thus uses the fallback DNS servers.

**Comment by andersk** [comment]
My network management software is NetworkManager. This report is from the part of the Ubuntu 16.10 development cycle where NetworkManager was configured without `dns=dnsmasq` to let systemd-resolved get more testing, but otherwise there’s nothing unusual about my setup.

How could this race condition be closed? Is NetworkManager supposed to wait for some acknowledgement from systemd-resolved that the new DNS servers have been picked up before configuring the IP settings?

**Comment by poettering** [comment]
@andersk nm git can push the DNS info into resolved directly, and it does it in the right order iiuc so that the race is fixed.

**Comment by sjoerd-ccu** [comment]
I'm hitting something very similar on my VPN as well:
  $ systemd-resolve ecx1000-0.elements  
ecx1000-0.elements: resolve call failed: DNSSEC validation failed: no-signature

The relevant logs for the query are below (systemd-resolved was restarted after the vpn was setup so it should never have had fallback servers for that link):

> Nov 10 13:23:03 dawn systemd-resolved[26784]: Got message type=method_call sender=:1.1778 destination=org.freedesktop.resolve1 object=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=ResolveHostname cookie=2 reply_cookie=0 error=n/a
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Looking up RR for ecx1000-0.elements IN A.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus object=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=8 reply_cookie=0 error=n/a
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.1776 object=n/a interface=n/a member=n/a cookie=9 reply_cookie=8 error=n/a
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus object=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetNameOwner cookie=9 reply_cookie=0 error=n/a
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.1776 object=n/a interface=n/a member=n/a cookie=10 reply_cookie=9 error=n/a
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Cache miss for ecx1000-0.elements IN A
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Transaction 53283 for <ecx1000-0.elements IN A> scope dns on tap0/_.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Using feature level UDP+EDNS0+DO+LARGE for transaction 53283.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Using DNS server 192.168.103.1 for transaction 53283.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Sending query packet with id 53283.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Processing incoming packet on transaction 53283.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Verified we get a response at feature level UDP+EDNS0+DO from DNS server 192.168.103.1.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Requesting SOA to validate transaction 53283 (ecx1000-0.elements, unsigned non-SOA/NS RRset <ecx1000-0.elements IN A 192.168.103.50>).
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Cache miss for ecx1000-0.elements IN SOA
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Transaction 7868 for <ecx1000-0.elements IN SOA> scope dns on tap0/_.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Using feature level UDP+EDNS0+DO+LARGE for transaction 7868.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Using DNS server 192.168.103.1 for transaction 7868.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Sending query packet with id 7868.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Processing incoming packet on transaction 7868.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Requesting DS to validate transaction 7868 (ecx1000-0.elements, unsigned empty SOA/NS response).
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Cache miss for ecx1000-0.elements IN DS
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Transaction 30531 for <ecx1000-0.elements IN DS> scope dns on tap0/_.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Using feature level UDP+EDNS0+DO+LARGE for transaction 30531.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Using DNS server 192.168.103.1 for transaction 30531.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Sending query packet with id 30531.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Processing incoming packet on transaction 30531.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Requesting parent SOA to validate transaction 30531 (ecx1000-0.elements, unsigned empty DS response).
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Cache miss for elements IN SOA
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Transaction 24800 for <elements IN SOA> scope dns on tap0/_.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Using feature level UDP+EDNS0+DO+LARGE for transaction 24800.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Using DNS server 192.168.103.1 for transaction 24800.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Sending query packet with id 24800.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Processing incoming packet on transaction 24800.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Requesting DNSKEY to validate transaction 24800 (., RRSIG with key tag: 39291).
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Cache miss for . IN DNSKEY
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Transaction 30018 for <. IN DNSKEY> scope dns on tap0/_.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Using feature level UDP+EDNS0+DO+LARGE for transaction 30018.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Using DNS server 192.168.103.1 for transaction 30018.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Sending query packet with id 30018.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Requesting DNSKEY to validate transaction 24800 (., RRSIG with key tag: 39291).
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Requesting DNSKEY to validate transaction 24800 (eg, RRSIG with key tag: 39291).
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Processing incoming packet on transaction 30018.
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Requesting DS to validate transaction 30018 (., DNSKEY with key tag: 19036).
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Requesting DS to validate transaction 30018 (., DNSKEY with key tag: 39291).
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Validating response from transaction 30018 (. IN DNSKEY).
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Looking at . IN DNSKEY 257 3 RSASHA256 AwEAAagAIKlVZrpC6Ia7gEzahOR+9W29euxhJhVVLOyQbSEW0O8
> Nov 10 13:23:03 dawn systemd-resolved[26784]:                             gcCjFFVQUTf6v58fLjwBd0YI0EzrAcQqBGCzh/RStIoO8g0Nfnf
> Nov 10 13:23:03 dawn systemd-resolved[26784]:                             L2MTJRkxoXbfDaUeVPQuYEhg37NZWAJQ9VnMVDxP/VHL496M/QZ
> Nov 10 13:23:03 dawn systemd-resolved[26784]:                             xkjf5/Efucp2gaDX6RS6CXpoY68LsvPVjR0ZSwzz1apAzvN9dlz
> Nov 10 13:23:03 dawn systemd-resolved[26784]:                             EheX7ICJBBtuA6G3LQpzW5hOA2hzCTMjJPJ8LbqF6dsV6DoBQzg
> Nov 10 13:23:03 dawn systemd-resolved[26784]:                             ul0sGIcGOYl7OyQdXfZ57relSQageu+ipAdTTJ25AsRTAoub8ON
> Nov 10 13:23:03 dawn systemd-resolved[26784]:                             GcLmqrAmRLKBP1dfwhYB4N7knNnulqQxA+Uk1ihz0=
> Nov 10 13:23:03 dawn systemd-resolved[26784]:         -- Flags: SEP ZONE_KEY
> Nov 10 13:23:03 dawn systemd-resolved[26784]:         -- Key tag: 19036: validated
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Found verdict for lookup . IN DNSKEY: secure
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Added positive authenticated cache entry for . IN DNSKEY 7200s on */INET/192.168.103.1
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Added positive authenticated cache entry for . IN DNSKEY 7200s on */INET/192.168.103.1
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Transaction 30018 for <. IN DNSKEY> on scope dns on tap0/_ now complete with <success> from network (authenticated).
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Validating response from transaction 24800 (elements IN SOA).
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Looking at . IN NSEC aaa ( NS SOA RRSIG NSEC DNSKEY ): validated
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Found verdict for lookup . IN NSEC: secure
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Looking at eg IN NSEC email ( NS RRSIG NSEC ): validated
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Found verdict for lookup eg IN NSEC: secure
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Looking at . IN SOA a.root-servers.net nstld.verisign-grs.com 2016110901 1800 900 604800 86400: validated
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Found verdict for lookup . IN SOA: secure
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Found verdict for lookup elements IN SOA: bogus
> Nov 10 13:23:03 dawn systemd-resolved[26784]: DNSSEC validation failed for question elements IN SOA: no-signature
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Transaction 24800 for <elements IN SOA> on scope dns on tap0/\* now complete with <dnssec-failed> from network (unsigned).
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Auxiliary DNSSEC RR query failed validation: no-signature
> Nov 10 13:23:03 dawn systemd-resolved[26784]: DNSSEC validation failed for question ecx1000-0.elements IN DS: no-signature
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Transaction 30531 for <ecx1000-0.elements IN DS> on scope dns on tap0/\* now complete with <dnssec-failed> from network (unsigned).
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Auxiliary DNSSEC RR query failed validation: no-signature
> Nov 10 13:23:03 dawn systemd-resolved[26784]: DNSSEC validation failed for question ecx1000-0.elements IN SOA: no-signature
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Transaction 7868 for <ecx1000-0.elements IN SOA> on scope dns on tap0/\* now complete with <dnssec-failed> from network (unsigned).
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Auxiliary DNSSEC RR query failed validation: no-signature
> Nov 10 13:23:03 dawn systemd-resolved[26784]: DNSSEC validation failed for question ecx1000-0.elements IN A: no-signature
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Transaction 53283 for <ecx1000-0.elements IN A> on scope dns on tap0/\* now complete with <dnssec-failed> from network (unsigned).
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Sent message type=error sender=n/a destination=:1.1778 object=n/a interface=n/a member=n/a cookie=10 reply_cookie=2 error=DNSSEC validation failed: no-signature
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus object=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RemoveMatch cookie=11 reply_cookie=0 error=n/a
> Nov 10 13:23:03 dawn systemd-resolved[26784]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.1776 object=n/a interface=n/a member=n/a cookie=11 reply_cookie=11 error=n/a

The resolved status is as follows:

>  Link 5 (tap0)
>       Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
>        LLMNR setting: yes
> MulticastDNS setting: no
>       DNSSEC setting: allow-downgrade
>     DNSSEC supported: yes
>          DNS Servers: 192.168.103.1
>           DNS Domain: ~elements

**Comment by andersk** [comment]
Here is a [debug log](https://github.com/systemd/systemd/files/645467/debug.txt) that shows this still failing on an up-to-date Ubuntu zesty installation, where NetworkManager is configured with `dns=systemd-resolved` (backported from Git). The first failure that I noticed was on the hostname news.ycombinator.com. The log also shows some queries having been resolved via 8.8.8.8, even though you say this should not be happening with `dns=systemd-resolved`.

**Comment by sjoerd-ccu** [comment]
Similar debug log: [systemd-resolve.txt](https://github.com/systemd/systemd/files/766417/systemd-resolve.txt)

This is resolving a domain that only exists on a VPN failing, the VPN itself is using dnsmasq as its nameserver without any special configuration in regards to dnssec

Most relevant parts (or rather the conclusive parts) seem to be:

```
<31>Added positive authenticated cache entry for . IN DNSKEY 7200s on */INET/192.168.103.1
<31>Added positive authenticated cache entry for . IN DNSKEY 7200s on */INET/192.168.103.1
<31>Transaction 50198 for <. IN DNSKEY> on scope dns on tap0/* now complete with <success> from network (authenticated).
<31>Validating response from transaction 57433 (elements IN SOA).
<31>Looking at . IN NSEC aaa ( NS SOA RRSIG NSEC DNSKEY ): validated
<31>Found verdict for lookup . IN NSEC: secure
<31>Looking at eg IN NSEC email ( NS RRSIG NSEC ): validated
<31>Found verdict for lookup eg IN NSEC: secure
<31>Looking at . IN SOA a.root-servers.net nstld.verisign-grs.com 2017020901 1800 900 604800 86400: validated
<31>Found verdict for lookup . IN SOA: secure
<31>Found verdict for lookup elements IN SOA: bogus
<29>DNSSEC validation failed for question elements IN SOA: no-signature
```

**Comment by poettering** [comment]
@sjoerd-ccu which dnssec mode is this? allow-downgrade or strict?

If you are in strict mode, this is expected behaviour, as your TLD "elements" doesn't exist, and resolved has a proof for that.

If you are in allow-downgrade mode however, then this is a different case, as I added a special exception for that case: when a TLD (and only for TLDs we do this) is proven to not exist, we'll permit it anyway.

hence, what's your setup like?

(if you want to use strict mode, but still permit access to this fake TLD, then configure it as NTA — "negative trust anchor" —, either globally or per-interface)

**Comment by poettering** [comment]
@andersk hmm, so it appears that your specific DNS server has problems replying with the necessary NSEC3 data (proof of non-existance). It appears to be broken there: we come to the conclusion that the DNS server does speak DNSSEC, but then it seems to strip NSEC3 data...

if this problem still persists, any chance you can run the following on your DNS server:

```
 dig +dnssec ntp.org DS @18.70.0.160
```

If the NSEC3 really went missing I figure we can add an automatic-downgrade rule if we notice we get a negative response lacking NSEC and NSEC3 from a domain that provides us with a signed SOA.

**Comment by sjoerd-ccu** [comment]
@poettering It's in allow-downgrade mode. Sorry i asumed that information would be in the debug log.

For completeness, this is my laptop connecting to a VPN which has elements as it's internal networks .tdl (Networkmanager via resolved backend).  DNS domains for that interface is set to ~elements.

**Comment by poettering** [comment]
@sjoerd-ccu so, any chance you can retry this with current resolved git with #5347 applied? I am not too keen on spending time on tracking this down if it might already be fixed. Also, we should move your issue to a different github issue, and leave this one for @andersk's issue as the two issues appear quite unrelated to me. Hence, if you could test this again and — if the issue remains — provide the debug output of the failing lookup in a new github issue, that'd be great.

**Comment by sjoerdsimons** [comment]
@poettering My issue fixed in git master, specifically 97c2ea26456f21334ac164f330426dd518067f08 resolves it. Thanks

**Comment by jcrben** [comment]
@poettering still waiting on a response from @andersk per https://github.com/systemd/systemd/issues/4175#issuecomment-279750013? given that it's been over a year perhaps it could be closed

**Comment by jrb** [comment]
I'm still intermittently seeing this pop up on Arch Linux with systemd 239.300-2. Interestingly, it seems to clear up once I fire off a series of requests in rapid succession. For instance, I was just attempting to browse a blog on the unsigned zone `www.redhat.com` about 10 minutes after a network connection change. Firefox immediately displayed a DNS related error, and a `dig redhat.com` from the command line returned a `SERVFAIL`. systemd-resolved logged the following with each dns request:

```
Nov 15 14:23:39 junk systemd-resolved[426]: DNSSEC validation failed for question avatars2.githubusercontent.com IN A: no-signature
Nov 15 14:25:38 junk systemd-resolved[426]: DNSSEC validation failed for question redhat.com IN DS: no-signature
Nov 15 14:25:38 junk systemd-resolved[426]: DNSSEC validation failed for question redhat.com IN SOA: no-signature
Nov 15 14:25:38 junk systemd-resolved[426]: DNSSEC validation failed for question redhat.com IN A: no-signature
```

After running `dig redhat.com` rapidly a half dozen times, it started responding correctly, and systemd-resolved stopped logging validation errors.

**Comment by poettering** [comment]
Let's close this, given the earlier comments.
