### ISSUE TITLE
resolved: non-address lookups fail with unsupported DNSSEC

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#5029]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

232, git master

### Used distribution

Fedora 25, Ubuntu zesty

While writing a test case for PR #4808 I stumbled over an unrelated resolved bug: Our dnsmasq test server does not support DNSSEC, and the test is trying to do an MX lookup which fails due to some buggy fallback.

This is reproducible with our tests when dropping the workaround:
```diff
--- a/test/networkd-test.py
+++ b/test/networkd-test.py
@@ -507,14 +507,6 @@ Domains= ~company ~lab''')
     def test_resolved_etc_hosts(self):
         '''resolved queries to /etc/hosts'''
 
-        # FIXME: -t MX query fails with enabled DNSSEC (even when using
-        # the known negative trust anchor .internal instead of .example)
-        conf = '/run/systemd/resolved.conf.d/test-disable-dnssec.conf'
-        os.makedirs(os.path.dirname(conf), exist_ok=True)
-        with open(conf, 'w') as f:
-            f.write('[Resolve]\nDNSSEC=no')
-        self.addCleanup(os.remove, conf)
-
         # create /etc/hosts bind mount which resolves my.example for IPv4
         hosts = os.path.join(self.workdir, 'hosts')
         with open(hosts, 'w') as f:
```

```
$ test/networkd-test.py -f DnsmasqClientTest.test_resolved_etc_hosts
[...]
ERROR: test_resolved_etc_hosts (__main__.DnsmasqClientTest)
resolved queries to /etc/hosts
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/martin/upstream/systemd/test/networkd-test.py", line 541, in test_resolved_etc_hosts
    out = subprocess.check_output(['systemd-resolve', '--type=MX', 'example'])
  File "/usr/lib64/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['systemd-resolve', '--type=MX', 'example']' returned non-zero exit status 1
```

Under Ubuntu the resolved log shows:
```
systemd-resolved[21055]: Server 192.168.5.1 does not support DNSSEC, downgrading to non-DNSSEC mode
systemd-resolved[21055]: DNSSEC validation failed for question other.intranet IN A: failed-auxiliary
```

Under Fedora (in nspawn) it looks even weirder:
```
Jan 05 18:06:08 systemd systemd-resolved[282]: Switching to DNS server 192.168.5.1 for interface test_eth42.
Jan 05 18:06:08 systemd systemd-resolved[282]: Using degraded feature set (UDP+EDNS0+DO) for DNS server 192.168.5.1.
Jan 05 18:06:12 systemd systemd-resolved[282]: Switching to DNS server 2600::1 for interface test_eth42.
Jan 05 18:06:12 systemd systemd-resolved[282]: Using degraded feature set (UDP+EDNS0+DO) for DNS server 2600::1.
Jan 05 18:06:16 systemd systemd-resolved[282]: Switching to DNS server fe80::ac9b:d5ff:fe97:a7a5%12 for interface test_eth42.
Jan 05 18:06:16 systemd systemd-resolved[282]: Using degraded feature set (UDP+EDNS0+DO) for DNS server fe80::ac9b:d5ff:fe97:a7a5%12.
Jan 05 18:06:21 systemd systemd-resolved[282]: Switching to DNS server 192.168.5.1 for interface test_eth42.
```
and no error messages, but dnsmasq gets spammed until it gives up:
```
Jan  5 18:06:25 dnsmasq[279]: query[SOA] example from fe80::ac9b:d5ff:fe97:a7a5
Jan  5 18:06:25 dnsmasq[279]: forwarded example to fe80::ac9b:d5ff:fe97:a7a5
Jan  5 18:06:25 dnsmasq[279]: query[SOA] example from fe80::ac9b:d5ff:fe97:a7a5
Jan  5 18:06:25 dnsmasq[279]: forwarded example to fe80::ac9b:d5ff:fe97:a7a5
Jan  5 18:06:25 dnsmasq[279]: Maximum number of concurrent DNS queries reached (max: 150)
```

I figure this is because of some different dnsmasq behaviour or  different "real" nameservers in `/etc/resolv.conf`. But it works in both environmens without DNSSEC.

I didn't track this down further yet, but filing this now to avoid forgetting about it.

**Comment by poettering** [comment]
@martinpitt any chance you can get my a verbose log for this? i.e. resolved with SYSTEMD_LOG_LEVEL=debug when these look-ps happen? that would help me tremendously to figure out what is going on here...

**Comment by poettering** [comment]
This might be fixed by #5347. It would be great if this could be verified.

**Comment by martinpitt** [comment]
PR #5347 does not fix it. The logs above are already with `SYSTEMD_LOG_LEVEL=debug`, I'm afraid it won't get any verboserer.

What concerns me is that this doesn't seem to reproduce on my installed Fedora 25, neither with the package (231-12.fc25) nor with resolved from current master. This would point towards a difference in dnsmasq between Fedora and Ubuntu, but then again I did get this regression in a Fedora 25 container as well. I'm afraid this needs some more investigation, I'll report back here now to reproduce it in Fedora.

**Comment by martinpitt** [comment]
This is still an issue with current master. It's fairly easy to reproduce in nspawn on Fedora 25, I just boot a mock chroot (replace `/path/to/systemd-checkout`):
```sh
mock --init
mock -i iproute dnsmasq python3 cryptsetup-libs
mock --quiet --chroot -- sh -ec 'echo root:root | chpasswd; touch /etc/hosts'
sudo systemd-nspawn --boot --directory=$(mock --print-root-path) --bind-ro=/path/to/systemd-checkout:/mnt --private-network
```
Now log in as root:root and run the test:
```
-bash-4.3# /mnt/test/networkd-test.py DnsmasqClientTest.test_resolved_etc_hosts
```
This should succeed. Now drop the workaround from the test (on your host in the checkout dir):
```diff
--- a/test/networkd-test.py
+++ b/test/networkd-test.py
@@ -511,14 +511,6 @@ Domains= ~company ~lab''')
     def test_resolved_etc_hosts(self):
         '''resolved queries to /etc/hosts'''
 
-        # FIXME: -t MX query fails with enabled DNSSEC (even when using
-        # the known negative trust anchor .internal instead of .example)
-        conf = '/run/systemd/resolved.conf.d/test-disable-dnssec.conf'
-        os.makedirs(os.path.dirname(conf), exist_ok=True)
-        with open(conf, 'w') as f:
-            f.write('[Resolve]\nDNSSEC=no')
-        self.addCleanup(os.remove, conf)
-
         # create /etc/hosts bind mount which resolves my.example for IPv4
         hosts = os.path.join(self.workdir, 'hosts')
         with open(hosts, 'w') as f:
```

Now re-run the test in the container, and it will fail like above. So this affects Fedora 25's systemd 231-12.fc25 as well. You can now also run `make -C /mnt install` to install the (previously built) systemd master and reboot, the test will still fail the same way.
