### ISSUE TITLE
-.mount complains about missing file after daemon-reload

### ISSUE THREAD

**Issue by aroig** [systemd/systemd#5375]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> arch linux

### In case of bug report: Expected behaviour you didn't see

> After daemon-reload, The unit `-.mount` reports `loaded` as its LoadState.

### In case of bug report: Unexpected behaviour you saw

> After daemon-reload, The unit `-.mount` has LoadState "error (Reason: No such file or directory)"

### In case of bug report: Steps to reproduce the problem

> After I boot, `-.mount` is fine

    $ systemctl status -- -.mount

    -.mount - Root Mount
       Loaded: loaded
       Active: active (mounted) since Fri 2017-02-17 13:01:54 CET; 2min 23s ago
        Where: /
         What: /dev/sda2
        Tasks: 0 (limit: 4915)
       CGroup: /system.slice/-.mount

> However, if I do a daemon-reload, the root mount unit reports "error: no such file" as LoadState.

    $ systemctl daemon-reload
    $ systemctl status -- -.mount
    -.mount - Root Mount
       Loaded: error (Reason: No such file or directory)
       Active: active (mounted) since Fri 2017-02-17 13:01:54 CET; 3min 46s ago
        Where: /
         What: /dev/sda2
       CGroup: /system.slice/-.mount
    Failed to dump process list, ignoring: Unit -.mount is not loaded properly: No such file or directory.

I have an empty fstab, and let the gpt generator setup the root and boot mounts. I hadn't noticed this before because I kept a root entry in the fstab until recently.

**Comment by poettering** [comment]
Already fixed in ad2706db7cceba69203f3ac2b6ef65d7490c5f29 and related commits.

**Comment by aroig** [comment]
@poettering No, I've just tested, and the bug I reported still happens with current master.

**Comment by keszybz** [comment]
Hm, what does `mkdir /tmp/x; sudo SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/systemd-gpt-auto-generator /tmp/{x,x,x}` say anything? Are there any files in `/tmp/x`?

**Comment by aroig** [comment]
Here it is

    $ mkdir /tmp/x
    $ sudo SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/system-generators/systemd-gpt-auto-generator /tmp/{x,x,x}
    Found container virtualization none.
    /dev/sda2: root device /dev/sda.
    Adding /boot: /dev/sda1 vfat

    $ ls /tmp/x
    boot.automount  boot.mount  local-fs.target.wants/

Nowhere on my system there is a file `-.mount`, I assumed systemd treats it in a special way.

**Comment by aroig** [comment]
@keszybz can you reproduce this problem?

It would be nice to fix this before the 233 release... Having the root mount fail does not inspire much confidence.

Besides, it breaks units that explicitly require a mountpoint by its unit, like a `btrfs-scrub@.service` thing, for instance.

Thanks!

**Comment by keszybz** [comment]
With a working GPT, I have `/run/systemd/generator.late/-.mount`.

If I remove `systemd-gpt-auto-generator` (`ln -s /dev/null /etc/systemd/system-generators/systemd-gpt-auto-generator`), I have the same result as you.

So, couple of questions:
1. how is your root mounted. What do you have in `/proc/cmdline`?
2. why systemd thinks root mount does not have a fragment

Something fishy is going on with the parsing of /proc/self/mountinfo:
```
$ grep ' / / ' /proc/self/mountinfo
... / / ... - ext4 /dev/sda2 ...
```
and yet 
```
$ systemctl status -- -.mount
-.mount - Root Mount
   Loaded: error (Reason: No such file or directory)
...
```

**Comment by keszybz** [comment]
See also #5461.

**Comment by aroig** [comment]
> With a working GPT, I have /run/systemd/generator.late/-.mount

@keszybz So, I was screwing up, sorry.

> 1. how is your root mounted. What do you have in /proc/cmdline

I got a `root=...` entry in there. In that case the gpt-generator just ignores that root mount. I'm not really sure why, but I guess this is intended behaviour. Maybe it should be documented?

If I remove the `root=` in the bootloader config, then all is good.

> 2. why systemd thinks root mount does not have a fragment

It does not have one, because the gpt-generator does not produce one.

Then I think there is no bug left, except maybe for some clarification on the man page, isn't it?

Thanks!

**Comment by poettering** [comment]
I am pretty sure this got fixed by #6459. Closing. Please reopen if this turns out not to fix the issue at hand. Thanks!
