### ISSUE TITLE
"systemctl --user --full is-enabled foo.service" fails with "Failed to get unit file links for foo.service: No such file or directory"

### ISSUE THREAD

**Issue by AlexanderKurtz** [systemd/systemd#5847]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Debian Stretch

### In case of bug report: Expected behaviour you didn't see

> ```systemctl --user --full is-enabled foo.service``` working correctly.

### In case of bug report: Unexpected behaviour you saw

```
alexander@shepard:~$ cat /etc/systemd/user/foo.service 
[Service]
ExecStart=/bin/true

[Install]
WantedBy=default.target
alexander@shepard:~$ systemctl --user daemon-reload
alexander@shepard:~$ file .config/systemd/user/
.config/systemd/user/: directory
alexander@shepard:~$ systemctl --user --full is-enabled foo.service
disabled
Failed to get unit file links for foo.service: No such file or directory
alexander@shepard:~$ echo $?
1
alexander@shepard:~$ 
```

### In case of bug report: Steps to reproduce the problem

> See above.

**Comment by poettering** [comment]
The code in question got quite some updates in 233. Could you please retest this with a more current version before we spend time on tracking this down? There's a good chance this is already fixed.

**Comment by AlexanderKurtz** [comment]
I just tried this in a VM with systemd v233 from Debian Experimental. The error message is indeed gone, but the symlinks are still not displayed correctly:

![screenshot from 2017-05-01 11-58-42](https://cloud.githubusercontent.com/assets/8996356/25577352/a5860cc8-2e65-11e7-868b-0c33b80b8333.png)

I would have expected the last command to show the newly created sysmlink in ```~/.config/systemd/user```. What do you think?

**Comment by AlexanderKurtz** [comment]
Hi!

I just tried this again with systemd v234. The error message is still gone, but the symlinks are still not displayed correctly:

```
alexander@shepard:~$ systemctl --version
systemd 234
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid
alexander@shepard:~$ cat /etc/systemd/user/foo.service 
[Service]
ExecStart=/bin/true

[Install]
WantedBy=default.target
alexander@shepard:~$ systemctl --user daemon-reload
alexander@shepard:~$ file .config/systemd/user/
.config/systemd/user/: directory
alexander@shepard:~$ systemctl --user --full is-enabled foo.service
disabled
alexander@shepard:~$ echo $?
1
alexander@shepard:~$ 
```

**Comment by keszybz** [comment]
Hmm, I don't see any error here:
```
Created symlink /home/bar/.config/systemd/user/default.target.wants/foo.service → /etc/systemd/user/foo.service.
```
Seems fine.
And `is-enabled` doesn't display symlinks. Let's assume this was fixed in v233.

**Comment by AlexanderKurtz** [comment]
Actually, ```is-enabled``` **does** display symlinks for system-wide units when using the ```--full``` option:

```
$ systemctl --full is-enabled ssh
enabled
  /etc/systemd/system/sshd.service
  /etc/systemd/system/multi-user.target.wants/ssh.service
$ 
```

However, for user units this still doesn't work:

```
$ systemctl --user --full is-enabled pulseaudio
enabled
$ 
```
