### ISSUE TITLE
systemd fails to compile with gcc with -O3 and without -flto

### ISSUE THREAD

**Issue by FireBurn** [systemd/systemd#6119]
### Submission type

 - Bug report

### systemd version the issue has been seen with

233

> …

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

Gentoo (gcc 7.1)

> …

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

Compilation error with gcc 7.1

/var/tmp/portage/sys-apps/systemd-233-r1/work/systemd-233/src/shared/install.c: In function ‘unit_file_disable’:
/var/tmp/portage/sys-apps/systemd-233-r1/work/systemd-233/src/shared/install.c:1007:22: error: argument 1 null where non-null expected [-Werror=nonnull]
                 name = basename(path);
                 ~~~~~^~~~~~~~~~~~~~~~
In file included from /var/tmp/portage/sys-apps/systemd-233-r1/work/systemd-233/src/shared/install.c:28:0:
/usr/include/string.h:599:14: note: in a call to function ‘basename’ declared here
 extern char *basename (const char *__filename) __THROW __nonnull ((1));
              ^~~~~~~~

Full log attached




> …

### In case of bug report: Steps to reproduce the problem

Compile systemd with gcc 7.1 (gcc 6.3 works fine

)

> …

**Comment by FireBurn** [comment]
Github didn't accept .log .xz .zip files to be uploaded, renamed to .txt

[build.txt](https://github.com/systemd/systemd/files/1071520/build.txt)

**Comment by poettering** [comment]
hmpf, gcc is clearly wrong here... We explicitly check first that either "name" or "path" are non-null first. And then, if "name" is NULL, we will initialize it from basename(path). This means path must be non-NULL in that case...

I am not sure what we should do in this case. I am a bit puzzled why gcc thinks this should be an error rather than just a warning, and I wonder if there is a way how to turn this off

**Comment by keszybz** [comment]
I'd guess that your gcc needs updating. gcc-7.1.1-2.fc26.x86_64 works fine.

**Comment by poettering** [comment]
@FireBurn which gcc version are you using precisely? 7.1.1?

**Comment by FireBurn** [comment]
GCC 7.1.0, there is no GCC 7.1.1 that I can see on gcc.gnu.org

**Comment by keszybz** [comment]
Yeah, the changelog for the Fedora package is:

Fri May 26 2017 Jakub Jelinek <jakub@redhat.com> 7.1.1-2
- update from the 7 branch
  - PRs ada/80626, ada/80784, documentation/50642, fortran/78659,
        fortran/80121, fortran/80333, fortran/80392, fortran/80484,
        fortran/80741, fortran/80752, go/64238, libgfortran/80333,
        libgfortran/80727, libgfortran/80741, libstdc++/78939, libstdc++/80478,
        libstdc++/80761, libstdc++/80796, middle-end/80539, middle-end/80809,
        middle-end/80853, rtl-optimization/80754, sanitizer/80659,
        sanitizer/80875, target/68163, target/79027, target/79202,
        target/79203, target/80090, target/80510, target/80671, target/80706,
        target/80799, tree-optimization/80453, tree-optimization/80492
- fix s390 indirect_jump reloading (#1450353, PR target/80725)

Wed May 03 2017 Jakub Jelinek <jakub@redhat.com> 7.1.1-1
- update from the 7 branch
  - GCC 7.1 release
  - PRs bootstrap/80531, c++/80534, c/80468, target/68491, target/79430,
        target/80530, tree-optimization/80591

So either the issue is fixed by one the the listed PRs, or you're using different compilation options that somehow confuse gcc or something else is happening. It'd be great if you could reproduce this in a Fedora chroot — gentoo is a bit too complicated ;)

**Comment by FireBurn** [comment]
If you can point me to the source code for GCC 7.1.1 then I'll give it a go, but there's no sign of it on any of the gcc.gnu.org mirrors. Is this a Red Hat only thing I don't remember seeing any patch releases (only major and minor) since 5.1

**Comment by keszybz** [comment]
Yes, as shown in the changelog excerpt above, it contains backports of multiple upstream patches.
The source rpm: https://kojipkgs.fedoraproject.org//packages/gcc/7.1.1/2.fc26/src/gcc-7.1.1-2.fc26.src.rpm.

**Comment by poettering** [comment]
OK, closing this now, let's treat that as bug in gcc, that got fixed in gcc shortly after the release apparently, and downstream distros need to backport that, which Fedora already did apparently.

I hope that makes sense.

**Comment by yurovsky** [comment]
Did anyone find what GCC commit fixes this issue or what patch can be backported? I don't see anything relevant in any of the Fedora logs mentioned (none of the bugzilla IDs point to this issue, etc) so I don't know where it's actually fixed. I would like to backport the fix to my GCC 7.1 toolchain if possible.

**Comment by konstantinblaesi** [comment]
This still happens with gcc 7.2.0 and -O3.
It doesn't happen with -O2.
PR #6657 fixes this for me.

**Comment by MilhouseVH** [comment]
Sorry for the "me too", but confirming the post from @konstantinblaesi - this is still an issue with gcc-7.2.0 and `-O3`, and #6657 fixes it.

**Comment by evverx** [comment]
Now that https://github.com/systemd/systemd/pull/15704 is merged I think this should be reopened. If it's still reproducible with the latest gcc as a last resort we can always add something like
```

if cc.get_id() == 'gcc'
        possible_cc_flags += [
                '-Wno-error=nonnull',
        ]
endif
```

**Comment by evverx** [comment]
Turns out `systemd` still fails to compile with gcc with -O3 with
```
In function 'install_info_add',
    inlined from 'unit_file_disable' at ../src/shared/install.c:2620:21:
../src/shared/install.c:1019:24: warning: argument 1 null where non-null expected [-Wnonnull]
 1019 |                 name = basename(path);
      |                        ^~~~~~~~~~~~~~
In file included from ../src/basic/alloc-util.h:7,
                 from ../src/shared/install.c:12:
../src/shared/install.c: In function 'unit_file_disable':
/usr/include/string.h:487:14: note: in a call to function 'basename' declared here
  487 | extern char *basename (const char *__filename) __THROW __nonnull ((1));
      |              ^~~~~~~~
...
In function 'manager_load_unit_prepare',
    inlined from 'manager_load_unit' at ../src/core/manager.c:2037:13,
    inlined from 'manager_add_job_by_name' at ../src/core/manager.c:1820:13:
../src/core/manager.c:1981:24: warning: argument 1 null where non-null expected [-Wnonnull]
 1981 |                 name = basename(path);
      |                        ^~~~~~~~~~~~~~
In file included from ../src/systemd/sd-id128.h:21,
                 from ../src/systemd/sd-messages.h:20,
                 from ../src/core/manager.c:19:
../src/core/manager.c: In function 'manager_add_job_by_name':
/usr/include/string.h:487:14: note: in a call to function 'basename' declared here
  487 | extern char *basename (const char *__filename) __THROW __nonnull ((1));
      |              ^~~~~~~~
```
I've just opened https://github.com/systemd/systemd/pull/15725. I hope nobody passes -O3 via CFLAGS or -Dc_args.

**Comment by FireBurn** [comment]
I'm building systemd 245 with -O3 here on Gentoo, using GCC 9.3.0 with no issues

**Comment by evverx** [comment]
@FireBurn did you build it with https://github.com/systemd/systemd/commit/7f3a5eb70e476708551445219f7aceb7afc0a4a0?

**Comment by FireBurn** [comment]
I've just added that patch to the ebuild and re-emerged just fine

**Comment by FireBurn** [comment]
The live ebuild from current git compiles just fine for me too

**Comment by evverx** [comment]
That's certainly good news given that I'd prefer not to carry https://github.com/systemd/systemd/pull/15725. That said, I've just tried to compile systemd with `gcc-4.3` on Fedora 31 and it failed there with:
```
[323/1635] Compiling C object 'src/shared/5afaae1@@systemd-shared-245@sta/install.c.o'.
FAILED: src/shared/5afaae1@@systemd-shared-245@sta/install.c.o
cc -Isrc/shared/5afaae1@@systemd-shared-245@sta -Isrc/shared -I../src/shared -Isrc/basic -I../src/basic -Isrc/boot -I../src/boot -Isrc/systemd -I../src/systemd -Isrc/journal -I../src/journal -Isrc/journal-remote -I../src/journal-remote -Isrc/nspawn -I../src/nspawn -Isrc/resolve -I../src/resolve -Isrc/timesync -I../src/timesync -I../src/time-wait-sync -Isrc/login -I../src/login -Isrc/udev -I../src/udev -Isrc/libudev -I../src/libudev -Isrc/core -I../src/core -Isrc/shutdown -I../src/shutdown -I../src/libsystemd/sd-bus -I../src/libsystemd/sd-device -I../src/libsystemd/sd-event -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-network -I../src/libsystemd/sd-resolve -Isrc/libsystemd-network -I../src/libsystemd-network -I. -I../ -I/usr/include/blkid -I/usr/include/libmount -I/usr/include/p11-kit-1 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu99 -O3 -g -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -Wno-maybe-uninitialized -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -ffunction-sections -fdata-sections -Werror=shadow -include config.h -fPIC -pthread -fvisibility=default -MD -MQ 'src/shared/5afaae1@@systemd-shared-245@sta/install.c.o' -MF 'src/shared/5afaae1@@systemd-shared-245@sta/install.c.o.d' -o 'src/shared/5afaae1@@systemd-shared-245@sta/install.c.o' -c ../src/shared/install.c
In function ‘install_info_add’,
    inlined from ‘unit_file_disable’ at ../src/shared/install.c:2620:21:
../src/shared/install.c:1019:24: error: argument 1 null where non-null expected [-Werror=nonnull]
 1019 |                 name = basename(path);
      |                        ^~~~~~~~~~~~~~
In file included from ../src/basic/alloc-util.h:7,
                 from ../src/shared/install.c:12:
../src/shared/install.c: In function ‘unit_file_disable’:
/usr/include/string.h:487:14: note: in a call to function ‘basename’ declared here
  487 | extern char *basename (const char *__filename) __THROW __nonnull ((1));
      |              ^~~~~~~~
cc1: some warnings being treated as errors
[325/1635] Compiling C object 'src/shared/5afaae1@@systemd-shared-245@sta/json.c.o'.
ninja: build stopped: subcommand failed.
make: *** [Makefile:2: all] Error 1
```
```
$ gcc --version
gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[vagrant@hey systemd]$ gcc --version
gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by benjarobin** [comment]
Well the code is wrong here... The compiler is not wrong !

`install_info_add()` is called with `path = NULL`

**Comment by benjarobin** [comment]
Well the compiler is not clever enough, and since the assert does nothing when `NDEBUG` is not defined, this does not help the compiler. Maybe try to replace `assert()` by `assert_se()` ?

**Comment by floppym** [comment]
> the assert does nothing when NDEBUG is not defined

You have that backwards: assert does nothing when `NDEBUG` *is* defined.

**Comment by benjarobin** [comment]
> You have that backwards: assert does nothing when `NDEBUG` _is_ defined.

Yes I meant the opposite.

I cannot reproduce, could you past here the command line used to build `install.c`, mine is:

`cc -Isrc/shared/5afaae1@@systemd-shared-245@sta -Isrc/shared -I../src/shared -Isrc/basic -I../src/basic -Isrc/boot -I../src/boot -Isrc/systemd -I../src/systemd -Isrc/journal -I../src/journal -Isrc/journal-remote -I../src/journal-remote -Isrc/nspawn -I../src/nspawn -Isrc/resolve -I../src/resolve -Isrc/timesync -I../src/timesync -I../src/time-wait-sync -Isrc/login -I../src/login -Isrc/udev -I../src/udev -Isrc/libudev -I../src/libudev -Isrc/core -I../src/core -Isrc/shutdown -I../src/shutdown -I../src/libsystemd/sd-bus -I../src/libsystemd/sd-device -I../src/libsystemd/sd-event -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-network -I../src/libsystemd/sd-resolve -Isrc/libsystemd-network -I../src/libsystemd-network -I. -I.. -I/usr/include/blkid -I/usr/include/libmount -I/usr/include/p11-kit-1 -flto -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=gnu99 -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -Wno-maybe-uninitialized -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -ffunction-sections -fdata-sections -Werror=shadow -include config.h -march=x86-64 -mtune=generic -O3 -DNDEBUG=1 -fno-plt -fPIC -pthread -fvisibility=default -MD -MQ 'src/shared/5afaae1@@systemd-shared-245@sta/install.c.o' -MF 'src/shared/5afaae1@@systemd-shared-245@sta/install.c.o.d' -o 'src/shared/5afaae1@@systemd-shared-245@sta/install.c.o' -c ../src/shared/install.c`

**Comment by evverx** [comment]
@benjarobin I wonder what version of gcc and what distribution you're using?

The command line seems to have been kind of hidden in my comment in the sense that you'd have to scroll right to get to the end. Here's what it looks like:

```cc -Isrc/shared/5afaae1@@systemd-shared-245@sta -Isrc/shared -I../src/shared -Isrc/basic -I../src/basic -Isrc/boot -I../src/boot -Isrc/systemd -I../src/systemd -Isrc/journal -I../src/journal -Isrc/journal-remote -I../src/journal-remote -Isrc/nspawn -I../src/nspawn -Isrc/resolve -I../src/resolve -Isrc/timesync -I../src/timesync -I../src/time-wait-sync -Isrc/login -I../src/login -Isrc/udev -I../src/udev -Isrc/libudev -I../src/libudev -Isrc/core -I../src/core -Isrc/shutdown -I../src/shutdown -I../src/libsystemd/sd-bus -I../src/libsystemd/sd-device -I../src/libsystemd/sd-event -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-network -I../src/libsystemd/sd-resolve -Isrc/libsystemd-network -I../src/libsystemd-network -I. -I../ -I/usr/include/blkid -I/usr/include/libmount -I/usr/include/p11-kit-1 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu99 -O3 -g -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -Wno-maybe-uninitialized -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -ffunction-sections -fdata-sections -Werror=shadow -include config.h -fPIC -pthread -fvisibility=default -MD -MQ 'src/shared/5afaae1@@systemd-shared-245@sta/install.c.o' -MF 'src/shared/5afaae1@@systemd-shared-245@sta/install.c.o.d' -o 'src/shared/5afaae1@@systemd-shared-245@sta/install.c.o' -c ../src/shared/install.c```

It's also reproducible on Debian Testing with gcc-9.3.0: https://travis-ci.org/github/systemd/systemd/jobs/683778366#L2353

**Comment by benjarobin** [comment]
Oh, sorry I did not that the command was already there... I can reproduce with your command. I am using the same version as you, gcc 9.3.0

**Comment by benjarobin** [comment]
Ok, I found why, I am building with `-flto`

**Comment by evverx** [comment]
> Ok, I found why, I am building with -flto

Thank you! Looks like we're getting somewhere :-) Up until this point I thought `meson` added `-flto` automatically when either `--optimization` or `--buildtype=release` was used. Can confirm with `-flto` the issue goes away.

> This code with this workaround build without any error:

It was decided not to go down that road in https://github.com/systemd/systemd/pull/6657 and I generally agree with @poettering.

**Comment by evverx** [comment]
On the other hand, it appears at the time everybody thought that it was just a gcc glitch that could be fixed in a matter of days by just applying a patch of some kind fixing this. As far as I can see, it has never been fixed and is still reproducible with gcc-10 so it seems to be reasonable to reconsider that decision. Anyway, what @benjarobin suggested looks better than https://github.com/systemd/systemd/pull/15725 to me (and more importantly works when -O3 is passed via CFLAGS or c_args). @benjarobin could you open a PR to kick off a new round of review?

**Comment by benjarobin** [comment]
@keszybz Do you think that we can close this issue now?

**Comment by evverx** [comment]
Interestingly, now that gcc-10 can get past that point `systemd` fails to compile with -O3 without -flto with
```
[437/1622] Compiling C object 'src/core/2ac6ece@@core@sta/path.c.o'
FAILED: src/core/2ac6ece@@core@sta/path.c.o
cc -Isrc/core/2ac6ece@@core@sta -Isrc/core -I../src/core -Isrc/basic -I../src/basic -Isrc/boot -I../src/boot -Isrc/home -I../src/home -Isrc/shared -I../src/shared -Isrc/systemd -I../src/systemd -Isrc/journal -I../src/journal -Isrc/journal-remote -I../src/journal-remote -Isrc/nspawn -I../src/nspawn -Isrc/resolve -I../src/resolve -Isrc/timesync -I../src/timesync -I../src/time-wait-sync -Isrc/login -I../src/login -Isrc/udev -I../src/udev -Isrc/libudev -I../src/libudev -Isrc/shutdown -I../src/shutdown -I../src/libsystemd/sd-bus -I../src/libsystemd/sd-device -I../src/libsystemd/sd-event -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-network -I../src/libsystemd/sd-resolve -Isrc/libsystemd-network -I../src/libsystemd-network -I. -I.. -I/usr/include/libmount -I/usr/include/blkid -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu99 -O3 -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -Wno-maybe-uninitialized -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -ffunction-sections -fdata-sections -Werror=shadow -include config.h -fPIC -pthread -MD -MQ 'src/core/2ac6ece@@core@sta/path.c.o' -MF 'src/core/2ac6ece@@core@sta/path.c.o.d' -o 'src/core/2ac6ece@@core@sta/path.c.o' -c ../src/core/path.c
../src/core/path.c: In function ‘path_serialize’:
../src/core/path.c:616:24: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
  616 |                 (void) serialize_item_format(f, "path-spec", "%s %i %s",
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  617 |                                              path_type_to_string(s->type),
      |                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  618 |                                              s->previous_exists,
      |                                              ~~~~~~~~~~~~~~~~~~~
  619 |                                              s->path);
      |                                              ~~~~~~~~
In function ‘path_spec_dump’,
    inlined from ‘path_dump’ at ../src/core/path.c:392:17:
../src/core/path.c:226:9: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
  226 |         fprintf(f,
      |         ^~~~~~~~~~
  227 |                 "%s%s: %s\n",
      |                 ~~~~~~~~~~~~~
  228 |                 prefix,
      |                 ~~~~~~~
  229 |                 path_type_to_string(s->type),
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  230 |                 s->path);
      |                 ~~~~~~~~
cc1: some warnings being treated as errors
```
Other than that a couple of the new [zero-length-bounds](https://gcc.gnu.org/onlinedocs/gcc-10.1.0/gcc/Warning-Options.html#index-Wzero-length-bounds) warnings popped up:
```
[304/1622] Compiling C object 'src/shared/5afaae1@@systemd-shared-245@sta/ethtool-util.c.o'
../src/shared/ethtool-util.c: In function ‘ethtool_get_permanent_macaddr’:
../src/shared/ethtool-util.c:260:60: warning: array subscript 5 is outside the bounds of an interior zero-length array ‘__u8[0]’ {aka ‘unsigned char[]’} [-Wzero-length-bounds]
  260 |                 ret->ether_addr_octet[i] = epaddr.addr.data[i];
      |                                            ~~~~~~~~~~~~~~~~^~~
In file included from ../src/shared/ethtool-util.c:5:
../src/shared/linux/ethtool.h:704:7: note: while referencing ‘data’
  704 |  __u8 data[0];
      |       ^~~~
../src/shared/ethtool-util.c: In function ‘ethtool_set_features’:
../src/shared/ethtool-util.c:488:31: warning: array subscript 0 is outside the bounds of an interior zero-length array ‘__u32[0]’ {aka ‘unsigned int[]’} [-Wzero-length-bounds]
  488 |         len = buffer.info.data[0];
      |               ~~~~~~~~~~~~~~~~^~~
In file included from ../src/shared/ethtool-util.c:5:
../src/shared/linux/ethtool.h:631:8: note: while referencing ‘data’
  631 |  __u32 data[0];
      |        ^~~~
```
```
$ gcc --version
gcc (GCC) 10.0.1 20200430 (Red Hat 10.0.1-0.14)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
I'd wait for gcc-10 to settle a bit before opening an issue though.

**Comment by keszybz** [comment]
→ https://github.com/systemd/systemd/pull/15762
