### ISSUE TITLE
resource-controll does not work in user instance, even on cgroup v2

### ISSUE THREAD

**Issue by LukeShu** [systemd/systemd#6895]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> systemd 234 (+11 commits from systemd-stable repo)

### Used distribution

> Parabola GNU/Linux-libre (like Arch Linux)

### In case of bug report: Expected behaviour you didn't see

 Let `./malloc` ([source code here](https://lukeshu.com/dump/malloc.c.txt)) be a program that keeps malloc(3)ing more memory 1M at a time, writing a few bytes in that memory to force page allocation, and printing to stderr how much it has.
```
$ systemd-run --user --unit=malloc.service --property=MemoryMax=100M ./malloc
Running as unit: malloc.service
$ 
```
I expect it to get killed once it tries to allocate anything more than `100M=100*1024*1024=104857600` bytes; seeing in the journal
```
...
Sep 14 22:45:29 malloc[31295]: have        103,809,024 B
Sep 14 22:45:29 malloc[31295]: have        104,857,600 B
Sep 14 22:45:29 systemd[1]: malloc.service: Main process exited, code=killed, status=9/KILL
Sep 14 22:45:29 systemd[1]: malloc.service: Unit entered failed state.
Sep 14 22:45:29 systemd[1]: malloc.service: Failed with result 'signal'.
```

### In case of bug report: Unexpected behaviour you saw

It used up the entire system memory before the OOM killer fixed that:
```
...
Sep 14 23:18:18 malloc[24274]: have      2,343,567,360 B
Sep 14 23:18:18 malloc[24274]: have      2,344,615,936 B
Sep 14 23:18:18 malloc[24274]: have      2,345,664,512 B
Sep 14 23:18:18 malloc[24274]: have      2,346,713,088 B
Sep 14 23:18:31 systemd[388]: malloc.service: Main process exited, code=killed, status=9/KILL
Sep 14 23:18:31 systemd[388]: malloc.service: Unit entered failed state.
Sep 14 23:18:31 systemd[388]: malloc.service: Failed with result 'signal'.
```
(the journal actually stopped updating during the low-memory situation; htop told me that it did fill the entire ~3.6G I had free, not just the 2.3G that it logged to the journal)
 
### In case of bug report: Steps to reproduce the problem

 First of all, to easily observe this, disable any swap space, it doesn't count toward `MemoryMax`, and `MemorySwapMax` can't be set with `bus_append_unit_property_assignment()`; so disabling swap will make demonstrating this easier.

Using the `malloc.c` program I linked above, and the `systemd-run` commands given above, you should be able to verify this on a unified-hierarchy using system without any extra steps.

Additionally, you may verify the discrepency between system-instance and user-instance behavior by exchanging `systemd-run --user` for `sudo systemd-run`; in which case you will get the "expected" behavior above.

I believe that the cause of this is the controllers being disabled in `cgroup.subtree_control` for the user instance:
```
$ cat /sys/fs/cgroup/user.slice/user-$UID.slice/user@$UID.service/cgroup.controllers 
io memory pids
$ cat /sys/fs/cgroup/user.slice/user-$UID.slice/user@$UID.service/cgroup.subtree_control 
$ 
```
However, I haven't determined cause of *that*.  Without digging in to the source, I suspect that it's because it tries to enable them at the wrong point during setup, and enabling them fails because it would violate the "No Internal Process Constraint".

I believe this is a regression of issue #3744 .

**Comment by keszybz** [comment]
This is a duplicate of #6216, fixed in 40853aa53f.

**Comment by LukeShu** [comment]
Fantastic! I'm sorry for wasting your time.

**Comment by keszybz** [comment]
It's fine ;) I think we fixed it after you opened the issue.

**Comment by ChALkeR** [comment]
This still doesn't seem to work with "hybrid" hierarchy, on Arch Linux.
Is that a bug or a limitation of the hybrid hierarchy?

**Comment by keszybz** [comment]
Yes, it's a limitation of the hybrid hierarchy. From the man page:
> Note that controller delegation to less privileged code is only safe on the
           unified control group hierarchy. Accordingly, access to the specified
           controllers will not be granted to unprivileged services on the legacy
           hierarchy, even when requested.

**Comment by ChALkeR** [comment]
@keszybz Thanks a lot! I missed that part =). Sorry for bothering.
