### ISSUE TITLE
systemd-resolved: search domains aren't updated

### ISSUE THREAD

**Issue by flipreverse** [systemd/systemd#7305]
### Submission type
 - Bug report
### systemd version the issue has been seen with
> systemd 234
> +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP >+GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid

### Used distribution
> Ubuntu 17.10

### In case of bug report: Expected behaviour you didn't see
> systemd-resolved should update its list of search domains every time the connection status changes, e.g., after disconnection from a VPN. For example, it should discard the old search domain used by the VPN network.
> Moreover, if I connect my notebook to our university network, it uses the local search domain. After suspending it, resuming it at home and connect to my local wifi, it should not use the universities search domain anymore. It should only use my local one.

### In case of bug report: Unexpected behaviour you saw
> After disconnecting the VPN oder resuming my notebook at home, systemd-resolve still uses the old search domain.

### In case of bug report: Steps to reproduce the problem

> Connect to a VPN network which uses its own search domain, disconnect from the network and then try to resolve a hostname from the remote network.
> FYI, the following commands fixes the problem:
> systemctl stop systemd-resolved
> rm /run/systemd/resolve/stub-resolv.conf
> systemctl start systemd-resolved

**Comment by poettering** [comment]
This should be fixed by #7014. Closing

**Comment by mrvanes** [comment]
I'm still experiencing this problem on systemd 234-2ubuntu12.1, for what release is the fix planned?

**Comment by bl33pbl0p** [comment]
@mrvanes >=v236

You could request the maintainers of the systemd package in your distribution to backport this for you, it's a small patch.
