### ISSUE TITLE
systemd-sysctl.service: Failed to start Apply Kernel Variables

### ISSUE THREAD

**Issue by BadderBlackBart** [systemd/systemd#7838]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 236

### Used distribution

> Archlinux on Cubox i4 pro (armv7)

### In case of bug report: Unexpected behaviour you saw

> * systemd-sysctl.service - Apply Kernel Variables
   Loaded: loaded (/usr/lib/systemd/system/systemd-sysctl.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2018-01-08 22:06:15 CET; 1 day 23h ago
Docs: man:systemd-sysctl.service(8)
           man:sysctl.d(5)
 Main PID: 177 (code=exited, status=1/FAILURE)
systemd-sysctl[177]: Couldn't write '1' to 'kernel/core_uses_pid': Input/output error
systemd-sysctl[177]: Couldn't write '1' to 'net/ipv4/conf/all/rp_filter': Input/output error
systemd-sysctl[177]: Couldn't write '0' to 'net/ipv4/conf/all/accept_source_route': Input/output error
systemd-sysctl[177]: Couldn't write '1' to 'net/ipv4/conf/all/promote_secondaries': Input/output error
systemd-sysctl[177]: Couldn't write 'fq_codel' to 'net/core/default_qdisc': Input/output error
systemd-sysctl[177]: Couldn't write '1' to 'fs/protected_hardlinks': Input/output error
systemd-sysctl[177]: Couldn't write '1' to 'fs/protected_symlinks': Input/output error
systemd[1]: systemd-sysctl.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: systemd-sysctl.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Apply Kernel Variables.

same issue on archlinuxarm forum: https://archlinuxarm.org/forum/viewtopic.php?f=45&t=12364

**Comment by evverx** [comment]
The issue seems to be a duplicate of https://github.com/systemd/systemd/issues/7744.

**Comment by BadderBlackBart** [comment]
I say that tread too, but is was closed. Does is it mean the problem is fixed and I just have to wait a while?

**Comment by evverx** [comment]
I think the issue has been fixed, but It would be great to get https://github.com/systemd/systemd/commit/521251d2757295b6e9df4b51c7cb33929fbd65c4 backported to check whether it really fixes this issue or not.

**Comment by poettering** [comment]
Yeah, this looks exactly like #7744 which got fixed in git. Let's close this as duplicate. 

Please ping your distro and ask them to backport this fix.

**Comment by BadderBlackBart** [comment]
I notified the archlinux maintainers. I think they backported the fix as pacman had a systemd update. The issue is still present however.

**Comment by floppym** [comment]
Can you run the following command and post the output somewhere? We would mainly be looking for `open` or `write` syscalls that are returning errors.
```
strace /usr/lib/systemd/systemd-sysctl
```

**Comment by BadderBlackBart** [comment]
strace output: https://paste.ofcode.org/ksmppa8pu9GgbfDNpK3GWJ

**Comment by floppym** [comment]
The kernel is returning `EACCESS`, which means you probably did not run this as **root**. Please try again.

**Comment by BadderBlackBart** [comment]
new try: https://paste.ofcode.org/36yjds2b2YXyGSGHJjNN5bV

**Comment by floppym** [comment]
It looks like your installed version of systemd does not include 521251d2757295b6e9df4b51c7cb33929fbd65c4. The writes are being split across 2 syscalls, which was fixed by the referenced commit.

**Comment by BadderBlackBart** [comment]
I can confirm that version 236.80-1 fixed the issue for me.
