### ISSUE TITLE
logind: version >= 222 breaks second login with GDM and LXDM

### ISSUE THREAD

**Issue by City-busz** [systemd/systemd#792]
After I updated systemd to version 222, I'm unable to login second time with GDM and LXDM. I have to kill leftover processes (e.g. ssh-agent) from the first login manually before I'm able to login again.

In the log files I can see the following message:

```
[gdm-password][1309]: pam_systemd(gdm-password:session): Cannot create session: Already occupied by a session
```

This message is added by this commit to systemd: https://github.com/systemd/systemd/commit/b80120c4cba7d134b5437a58437a23fdf7ab2084

Package versions:
- systemd 223-1
- gdm 3.16.2-1
- lxdm 0.5.1-1

Distribution: Arch Linux

**Comment by zonque** [comment]
This is fixed in v223. Any chance you can update to a newer version?

**Comment by City-busz** [comment]
I'm already using systemd 223, and still not working for me.

**Comment by mauritiusdadd** [comment]
I can confirm this still happens in v223, and the issue seems to be independent from the DE/WM and display manager used. See also https://bbs.archlinux.org/viewtopic.php?pid=1549154 and https://bbs.archlinux.org/viewtopic.php?id=200069

**Comment by dvdhrm** [comment]
Fixed by: 10189fd6be0

Thanks for the reports!

**Comment by City-busz** [comment]
I confirm that https://github.com/systemd/systemd/commit/10189fd6be0f547d75bc857860f3ecbbdbc447a6 fixes the problem. Thanks!
